/* Source generated by crazyvoids source generating tool **/
#include "libc_setjmp.h"

void _longjmp() { for(;;){} }
void _setjmp() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}