/* Source generated by crazyvoids source generating tool **/
#include "libkernel_cpumode.h"

void sceKernelGetCpumode() { for(;;){} }
void sceKernelSetFsstParam() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}