/* Source generated by crazyvoids source generating tool **/
#include "libkernel_psmkit.h"

void access() { for(;;){} }
void chdir() { for(;;){} }
void dup() { for(;;){} }
void dup2() { for(;;){} }
void ioctl() { for(;;){} }
void lstat() { for(;;){} }
void pipe() { for(;;){} }
void poll() { for(;;){} }
void pthread_cond_setname_np() { for(;;){} }
void pthread_get_user_context_np() { for(;;){} }
void pthread_kill() { for(;;){} }
void pthread_mutex_setname_np() { for(;;){} }
void pthread_resume_user_context_np() { for(;;){} }
void pthread_suspend_user_context_np() { for(;;){} }
void sceKernelDebugRaiseException() { for(;;){} }
void sceKernelDebugRaiseExceptionWithContext() { for(;;){} }
void sceKernelGetFsSandboxRandomWord() { for(;;){} }
void sceKernelGetModuleInfoFromAddr() { for(;;){} }
void sceKernelJitCreateAliasOfSharedMemory() { for(;;){} }
void sceKernelJitCreateSharedMemory() { for(;;){} }
void sceKernelJitMapSharedMemory() { for(;;){} }
void sceKernelOpenSema() { for(;;){} }
void sceKernelSetProcessProperty() { for(;;){} }
void sem_setname() { for(;;){} }
void sigaction() { for(;;){} }
void sigaddset() { for(;;){} }
void sigaltstack() { for(;;){} }
void sigdelset() { for(;;){} }
void sigemptyset() { for(;;){} }
void sigfillset() { for(;;){} }
void sigismember() { for(;;){} }
void signal() { for(;;){} }
void sigprocmask() { for(;;){} }
void sigsuspend() { for(;;){} }
void socketpair() { for(;;){} }
void sysconf() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}