/* Source generated by crazyvoids source generating tool **/
#include "libkernel_jvm.h"

void dup2() { for(;;){} }
void getrlimit() { for(;;){} }
void ioctl() { for(;;){} }
void kill() { for(;;){} }
void poll() { for(;;){} }
void pthread_kill() { for(;;){} }
void sceKernelGetExecutableModuleHandle() { for(;;){} }
void sceKernelJitCreateAliasOfSharedMemory() { for(;;){} }
void sceKernelJitCreateSharedMemory() { for(;;){} }
void sceKernelJitGetSharedMemoryInfo() { for(;;){} }
void sceKernelJitMapSharedMemory() { for(;;){} }
void setrlimit() { for(;;){} }
void sigaction() { for(;;){} }
void sigaddset() { for(;;){} }
void sigdelset() { for(;;){} }
void sigemptyset() { for(;;){} }
void sigfillset() { for(;;){} }
void sigismember() { for(;;){} }
void sigprocmask() { for(;;){} }
void sigsuspend() { for(;;){} }
void socketpair() { for(;;){} }
void sysconf() { for(;;){} }
void sysctl() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}