/* Source generated by crazyvoids source generating tool **/
#include "libkernel_sysc_se.h"

void sysc_e00() { for(;;){} }
void sysc_s00() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}