/* Source generated by crazyvoids source generating tool **/
#include "libkernel_qadisc.h"

void ioctl() { for(;;){} }
void sceKernelGetSocPowerConsumption() { for(;;){} }
void sceKernelIccGetCountTime() { for(;;){} }
void sceKernelIccGetErrLog() { for(;;){} }
void sceKernelIccGetHwInfo() { for(;;){} }
void sceKernelIccGetSysEventLog() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}