/* Source generated by crazyvoids source generating tool **/
#include "libkernel_pre250mmap.h"

void sceKernelBatchMap() { for(;;){} }
void sceKernelMapDirectMemory() { for(;;){} }
void sceKernelMapNamedDirectMemory() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}