/* Source generated by crazyvoids source generating tool **/
#include "libkernel_exception.h"

void sceKernelAddGpuExceptionEvent() { for(;;){} }
void sceKernelBacktraceSelf() { for(;;){} }
void sceKernelDeleteGpuExceptionEvent() { for(;;){} }
void sceKernelInstallExceptionHandler() { for(;;){} }
void sceKernelRemoveExceptionHandler() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}