/* Source generated by crazyvoids source generating tool **/
#include "libkernel_unity.h"

void sceKernelInstallExceptionHandler() { for(;;){} }
void sceKernelRaiseException() { for(;;){} }
void sceKernelRemoveExceptionHandler() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}