/* Source generated by crazyvoids source generating tool **/
#include "libkernel_ps2emu.h"

void sceKernelJitCreateAliasOfSharedMemory() { for(;;){} }
void sceKernelJitCreateSharedMemory() { for(;;){} }
void sceKernelJitGetSharedMemoryInfo() { for(;;){} }
void sceKernelJitMapSharedMemory() { for(;;){} }
void socketpair() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}