/* Source generated by crazyvoids source generating tool **/
#include "libkernel_module_info.h"

void sceKernelGetModuleInfo2() { for(;;){} }
void sceKernelGetModuleList2() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}