/* Source generated by crazyvoids source generating tool **/
#include "libkernel_module_load_check.h"

void sceKernelIsModuleLoaded() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}