/* Source generated by crazyvoids source generating tool **/
#include "libkernel_avlfmem.h"

void sceKernelAvailableFlexibleMemorySize() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}