/* Source generated by crazyvoids source generating tool **/
#include "libkernel_dmem_aliasing2_for_dev.h"

void sceKernelEnableDmemAliasing() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}