/* Source generated by crazyvoids source generating tool **/
#include "libSceVdecCore.h"

void sceVdecCoreCreateDecoder() { for(;;){} }
void sceVdecCoreDeleteDecoder() { for(;;){} }
void sceVdecCoreFinalizeComputeResource() { for(;;){} }
void sceVdecCoreFlushDecodeOutput() { for(;;){} }
void sceVdecCoreGetDecodeOutput() { for(;;){} }
void sceVdecCoreInitializeComputeResource() { for(;;){} }
void sceVdecCoreMapMemoryBlock() { for(;;){} }
void sceVdecCoreQueryComputeResourceInfo() { for(;;){} }
void sceVdecCoreQueryFrameBufferInfo() { for(;;){} }
void sceVdecCoreQueryInstanceSize() { for(;;){} }
void sceVdecCoreResetDecoder() { for(;;){} }
void sceVdecCoreSetDecodeInput() { for(;;){} }
void sceVdecCoreSetDecodeOutputSw() { for(;;){} }
void sceVdecCoreSyncDecode() { for(;;){} }
void sceVdecCoreSyncDecodeOutputSw() { for(;;){} }
void sceVdecCoreSyncDecodeWptr() { for(;;){} }
void sceVdecCoreTrySyncDecode() { for(;;){} }
void sceVdecCoreTrySyncDecodeOutputSw() { for(;;){} }
void sceVdecCoreTrySyncDecodeWptr() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}