/* Source generated by crazyvoids source generating tool **/
#include "libSceAbstractTwitter.h"

void _ZN15AbstractStorage10TwitterAPI11SendContentEPKvl() { for(;;){} }
void _ZN15AbstractStorage10TwitterAPI6FinishERiRSbIcSt11char_traitsIcENS_8StlAllocIcEEE() { for(;;){} }
void _ZN15AbstractStorage10TwitterAPIC1Ev() { for(;;){} }
void _ZN15AbstractStorage10TwitterAPID1Ev() { for(;;){} }
void _ZN15AbstractStorage13TwitterFolder10NewContentERKSbIcSt11char_traitsIcENS_8StlAllocIcEEEPSt10shared_ptrINS_7ContentEE() { for(;;){} }
void _ZN15AbstractStorage13TwitterFolder12RemoveFolderERKSbIcSt11char_traitsIcENS_8StlAllocIcEEEb() { for(;;){} }
void _ZN15AbstractStorage13TwitterFolder13RemoveContentERKSbIcSt11char_traitsIcENS_8StlAllocIcEEE() { for(;;){} }
void _ZN15AbstractStorage13TwitterFolder4OpenENS_8ItemTypeE() { for(;;){} }
void _ZN15AbstractStorage13TwitterFolder5CloseEv() { for(;;){} }
void _ZN15AbstractStorage13TwitterFolder6RemoveEb() { for(;;){} }
void _ZN15AbstractStorage13TwitterFolder8NextItemEPSt10shared_ptrINS_4ItemEE() { for(;;){} }
void _ZN15AbstractStorage13TwitterFolder9NewFolderERKSbIcSt11char_traitsIcENS_8StlAllocIcEEEPSt10shared_ptrINS_6FolderEE() { for(;;){} }
void _ZN15AbstractStorage13TwitterFolderC1ERKSbIcSt11char_traitsIcENS_8StlAllocIcEEEb() { for(;;){} }
void _ZN15AbstractStorage13TwitterFolderC2ERKSbIcSt11char_traitsIcENS_8StlAllocIcEEEb() { for(;;){} }
void _ZN15AbstractStorage13TwitterFolderD0Ev() { for(;;){} }
void _ZN15AbstractStorage13TwitterFolderD1Ev() { for(;;){} }
void _ZN15AbstractStorage13TwitterFolderD2Ev() { for(;;){} }
void _ZN15AbstractStorage14TwitterContent11SetMetadataEPN23sceMetadataReaderWriter8MetadataE() { for(;;){} }
void _ZN15AbstractStorage14TwitterContent12readExternalESt10shared_ptrINS_7ContentEE() { for(;;){} }
void _ZN15AbstractStorage14TwitterContent13ParseMetadataEPN23sceMetadataReaderWriter8MetadataES3_() { for(;;){} }
void _ZN15AbstractStorage14TwitterContent13writeExternalESt10shared_ptrINS_7ContentEE() { for(;;){} }
void _ZN15AbstractStorage14TwitterContent4OpenEit() { for(;;){} }
void _ZN15AbstractStorage14TwitterContent4ReadEPvlPl() { for(;;){} }
void _ZN15AbstractStorage14TwitterContent5CloseEv() { for(;;){} }
void _ZN15AbstractStorage14TwitterContent5FlushEv() { for(;;){} }
void _ZN15AbstractStorage14TwitterContent5WriteEPKvlPl() { for(;;){} }
void _ZN15AbstractStorage14TwitterContent6RemoveEv() { for(;;){} }
void _ZN15AbstractStorage14TwitterContent6RenameERKSbIcSt11char_traitsIcENS_8StlAllocIcEEE() { for(;;){} }
void _ZN15AbstractStorage14TwitterContent8SeekByteEliPl() { for(;;){} }
void _ZN15AbstractStorage14TwitterContent8SeekTimeElPl() { for(;;){} }
void _ZN15AbstractStorage14TwitterContentC1ERKSbIcSt11char_traitsIcENS_8StlAllocIcEEEb() { for(;;){} }
void _ZN15AbstractStorage14TwitterContentC2ERKSbIcSt11char_traitsIcENS_8StlAllocIcEEEb() { for(;;){} }
void _ZN15AbstractStorage14TwitterContentD0Ev() { for(;;){} }
void _ZN15AbstractStorage14TwitterContentD1Ev() { for(;;){} }
void _ZN15AbstractStorage14TwitterContentD2Ev() { for(;;){} }
void _ZN15AbstractStorage14TwitterService13SearchStorageEv() { for(;;){} }
void _ZN15AbstractStorage14TwitterService23create_storage_instanceERKSbIcSt11char_traitsIcENS_8StlAllocIcEEE() { for(;;){} }
void _ZN15AbstractStorage14TwitterService4StopEv() { for(;;){} }
void _ZN15AbstractStorage14TwitterService5StartEv() { for(;;){} }
void _ZN15AbstractStorage14TwitterServiceC1Ev() { for(;;){} }
void _ZN15AbstractStorage14TwitterServiceC2Ev() { for(;;){} }
void _ZN15AbstractStorage14TwitterServiceD0Ev() { for(;;){} }
void _ZN15AbstractStorage14TwitterServiceD1Ev() { for(;;){} }
void _ZN15AbstractStorage14TwitterServiceD2Ev() { for(;;){} }
void _ZN15AbstractStorage14TwitterStorage10GetContentERKSbIcSt11char_traitsIcENS_8StlAllocIcEEEPSt10shared_ptrINS_7ContentEE() { for(;;){} }
void _ZN15AbstractStorage14TwitterStorage11DeserializeESt10shared_ptrINS_7ContentEEPS1_INS_4ItemEE() { for(;;){} }
void _ZN15AbstractStorage14TwitterStorage13GetRootFolderEPSt10shared_ptrINS_6FolderEE() { for(;;){} }
void _ZN15AbstractStorage14TwitterStorage14GetStorageSizeEPlS1_S1_() { for(;;){} }
void _ZN15AbstractStorage14TwitterStorage15CreateRecursiveERKSbIcSt11char_traitsIcENS_8StlAllocIcEEENS_8ItemTypeEPSt10shared_ptrINS_4ItemEE() { for(;;){} }
void _ZN15AbstractStorage14TwitterStorage15RemoveRecursiveERKSbIcSt11char_traitsIcENS_8StlAllocIcEEE() { for(;;){} }
void _ZN15AbstractStorage14TwitterStorage7GetItemERKSbIcSt11char_traitsIcENS_8StlAllocIcEEEPSt10shared_ptrINS_4ItemEE() { for(;;){} }
void _ZN15AbstractStorage14TwitterStorage7IsExistERKSbIcSt11char_traitsIcENS_8StlAllocIcEEE() { for(;;){} }
void _ZN15AbstractStorage14TwitterStorage9GetForderERKSbIcSt11char_traitsIcENS_8StlAllocIcEEEPSt10shared_ptrINS_6FolderEE() { for(;;){} }
void _ZN15AbstractStorage14TwitterStorage9SerializeESt10shared_ptrINS_7ContentEES1_INS_4ItemEE() { for(;;){} }
void _ZN15AbstractStorage14TwitterStorageC1ERKSbIcSt11char_traitsIcENS_8StlAllocIcEEE() { for(;;){} }
void _ZN15AbstractStorage14TwitterStorageC2ERKSbIcSt11char_traitsIcENS_8StlAllocIcEEE() { for(;;){} }
void _ZN15AbstractStorage14TwitterStorageD0Ev() { for(;;){} }
void _ZN15AbstractStorage14TwitterStorageD1Ev() { for(;;){} }
void _ZN15AbstractStorage14TwitterStorageD2Ev() { for(;;){} }
void _ZNK15AbstractStorage13TwitterFolder10GetServiceEv() { for(;;){} }
void _ZNK15AbstractStorage13TwitterFolder13GetCapabilityEv() { for(;;){} }
void _ZNK15AbstractStorage13TwitterFolder7GetStatEPNS_4StatE() { for(;;){} }
void _ZNK15AbstractStorage14TwitterContent10GetServiceEv() { for(;;){} }
void _ZNK15AbstractStorage14TwitterContent13GetCapabilityEv() { for(;;){} }
void _ZNK15AbstractStorage14TwitterContent7GetStatEPNS_4StatE() { for(;;){} }
void _ZNK15AbstractStorage14TwitterService14GetServiceTypeEv() { for(;;){} }
void _ZNK15AbstractStorage14TwitterStorage10GetServiceEv() { for(;;){} }
void _ZNK15AbstractStorage14TwitterStorage13GetCapabilityEv() { for(;;){} }
void _ZNK15AbstractStorage14TwitterStorage7GetStatEPNS_4StatE() { for(;;){} }
void _ZTVN15AbstractStorage13TwitterFolderE() { for(;;){} }
void _ZTVN15AbstractStorage14TwitterContentE() { for(;;){} }
void _ZTVN15AbstractStorage14TwitterServiceE() { for(;;){} }
void _ZTVN15AbstractStorage14TwitterStorageE() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}