/* Source generated by crazyvoids source generating tool **/
#include "libSceSystemServiceActivateHevcSoft.h"

void sceSystemServiceActivateHevcSoft() { for(;;){} }
void sceSystemServiceActivateHevcSoftAbort() { for(;;){} }
void sceSystemServiceActivateHevcSoftGetStatus() { for(;;){} }
void sceSystemServiceActivateHevcSoftInit() { for(;;){} }
void sceSystemServiceActivateHevcSoftIsActivated() { for(;;){} }
void sceSystemServiceActivateHevcSoftStart() { for(;;){} }
void sceSystemServiceActivateHevcSoftTerm() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}