/* Source generated by crazyvoids source generating tool **/
#include "libScePngDec_jvm.h"

void scePngDecDecodeWithInputControl() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}