/* Source generated by crazyvoids source generating tool **/
#include "libSceDepth.h"

void _sceDepthCalcHeteroAdjustParam() { for(;;){} }
void _sceDepthHeadCandidateTrackerGetInformation() { for(;;){} }
void _sceDepthHeadCandidateTrackerSetInformation() { for(;;){} }
void _sceDepthSetCameraFactoryCalibrationData() { for(;;){} }
void _sceDepthSetHeteroAdjustParam() { for(;;){} }
void _sceDepthSetHeteroMode() { for(;;){} }
void sceDepthCalculateRectificationInformation() { for(;;){} }
void sceDepthDisableHeteroMode() { for(;;){} }
void sceDepthEnableExtendedMode() { for(;;){} }
void sceDepthEnableHeteroMode() { for(;;){} }
void sceDepthEnableHeteroModeAndGenerateInformation() { for(;;){} }
void sceDepthGetCalibrationData() { for(;;){} }
void sceDepthGetImage() { for(;;){} }
void sceDepthGetRectificationInformation() { for(;;){} }
void sceDepthGetSrParameter() { for(;;){} }
void sceDepthHandCandidateTrackerGetResult() { for(;;){} }
void sceDepthHasCalibrationData() { for(;;){} }
void sceDepthHeadCandidateDetectorGetResults() { for(;;){} }
void sceDepthHeadCandidateTrackerGetResult() { for(;;){} }
void sceDepthHeadCandidateTrackerSetValidationInformation() { for(;;){} }
void sceDepthInitialize() { for(;;){} }
void sceDepthLoadCalibrationData() { for(;;){} }
void sceDepthQueryMemory() { for(;;){} }
void sceDepthSaveInternalBuffers() { for(;;){} }
void sceDepthSetCalibrationData() { for(;;){} }
void sceDepthSetCommands() { for(;;){} }
void sceDepthSetPostFilterParameter() { for(;;){} }
void sceDepthSetPreFilterParameter() { for(;;){} }
void sceDepthSetRectificationInformation() { for(;;){} }
void sceDepthSetRoi() { for(;;){} }
void sceDepthSetRoiset() { for(;;){} }
void sceDepthSetSrParameter() { for(;;){} }
void sceDepthSetSrTnrParameter() { for(;;){} }
void sceDepthSubmit() { for(;;){} }
void sceDepthTerminate() { for(;;){} }
void sceDepthUpdate() { for(;;){} }
void sceDepthValidateCurrentCalibrationData() { for(;;){} }
void sceDepthWaitAndExecutePostProcess() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}