/* Source generated by crazyvoids source generating tool **/
#include "libSceAbstractDailymotion.h"

void _ZN15AbstractStorage14DailymotionAPI7SuspendEv() { for(;;){} }
void _ZN15AbstractStorage14DailymotionAPI8initHttpEv() { for(;;){} }
void _ZN15AbstractStorage14DailymotionAPI8termHttpEv() { for(;;){} }
void _ZN15AbstractStorage14DailymotionAPIC1Ev() { for(;;){} }
void _ZN15AbstractStorage14DailymotionAPIC2Ev() { for(;;){} }
void _ZN15AbstractStorage14DailymotionAPID1Ev() { for(;;){} }
void _ZN15AbstractStorage14DailymotionAPID2Ev() { for(;;){} }
void _ZN15AbstractStorage17DailymotionFolder10NewContentERKSbIcSt11char_traitsIcENS_8StlAllocIcEEEPSt10shared_ptrINS_7ContentEE() { for(;;){} }
void _ZN15AbstractStorage17DailymotionFolder12RemoveFolderERKSbIcSt11char_traitsIcENS_8StlAllocIcEEEb() { for(;;){} }
void _ZN15AbstractStorage17DailymotionFolder13RemoveContentERKSbIcSt11char_traitsIcENS_8StlAllocIcEEE() { for(;;){} }
void _ZN15AbstractStorage17DailymotionFolder4OpenENS_8ItemTypeE() { for(;;){} }
void _ZN15AbstractStorage17DailymotionFolder5CloseEv() { for(;;){} }
void _ZN15AbstractStorage17DailymotionFolder6RemoveEb() { for(;;){} }
void _ZN15AbstractStorage17DailymotionFolder9NewFolderERKSbIcSt11char_traitsIcENS_8StlAllocIcEEEPSt10shared_ptrINS_6FolderEE() { for(;;){} }
void _ZN15AbstractStorage17DailymotionFolderC1ERKSbIcSt11char_traitsIcENS_8StlAllocIcEEEb() { for(;;){} }
void _ZN15AbstractStorage17DailymotionFolderC2ERKSbIcSt11char_traitsIcENS_8StlAllocIcEEEb() { for(;;){} }
void _ZN15AbstractStorage17DailymotionFolderD0Ev() { for(;;){} }
void _ZN15AbstractStorage17DailymotionFolderD1Ev() { for(;;){} }
void _ZN15AbstractStorage17DailymotionFolderD2Ev() { for(;;){} }
void _ZN15AbstractStorage18DailymotionContent11SetMetadataEPN23sceMetadataReaderWriter8MetadataE() { for(;;){} }
void _ZN15AbstractStorage18DailymotionContent12readExternalESt10shared_ptrINS_7ContentEE() { for(;;){} }
void _ZN15AbstractStorage18DailymotionContent13ParseMetadataEPN23sceMetadataReaderWriter8MetadataES3_() { for(;;){} }
void _ZN15AbstractStorage18DailymotionContent13writeExternalESt10shared_ptrINS_7ContentEE() { for(;;){} }
void _ZN15AbstractStorage18DailymotionContent4OpenEit() { for(;;){} }
void _ZN15AbstractStorage18DailymotionContent4ReadEPvlPl() { for(;;){} }
void _ZN15AbstractStorage18DailymotionContent5CloseEv() { for(;;){} }
void _ZN15AbstractStorage18DailymotionContent5FlushEv() { for(;;){} }
void _ZN15AbstractStorage18DailymotionContent5WriteEPKvlPl() { for(;;){} }
void _ZN15AbstractStorage18DailymotionContent6RemoveEv() { for(;;){} }
void _ZN15AbstractStorage18DailymotionContent6RenameERKSbIcSt11char_traitsIcENS_8StlAllocIcEEE() { for(;;){} }
void _ZN15AbstractStorage18DailymotionContent8SeekByteEliPl() { for(;;){} }
void _ZN15AbstractStorage18DailymotionContent8SeekTimeElPl() { for(;;){} }
void _ZN15AbstractStorage18DailymotionContentC1ERKSbIcSt11char_traitsIcENS_8StlAllocIcEEEb() { for(;;){} }
void _ZN15AbstractStorage18DailymotionContentC2ERKSbIcSt11char_traitsIcENS_8StlAllocIcEEEb() { for(;;){} }
void _ZN15AbstractStorage18DailymotionContentD0Ev() { for(;;){} }
void _ZN15AbstractStorage18DailymotionContentD1Ev() { for(;;){} }
void _ZN15AbstractStorage18DailymotionContentD2Ev() { for(;;){} }
void _ZN15AbstractStorage18DailymotionService13SearchStorageEv() { for(;;){} }
void _ZN15AbstractStorage18DailymotionService23create_storage_instanceERKSbIcSt11char_traitsIcENS_8StlAllocIcEEE() { for(;;){} }
void _ZN15AbstractStorage18DailymotionService4StopEv() { for(;;){} }
void _ZN15AbstractStorage18DailymotionService5StartEv() { for(;;){} }
void _ZN15AbstractStorage18DailymotionServiceC1Ev() { for(;;){} }
void _ZN15AbstractStorage18DailymotionServiceC2Ev() { for(;;){} }
void _ZN15AbstractStorage18DailymotionServiceD0Ev() { for(;;){} }
void _ZN15AbstractStorage18DailymotionServiceD1Ev() { for(;;){} }
void _ZN15AbstractStorage18DailymotionServiceD2Ev() { for(;;){} }
void _ZN15AbstractStorage18DailymotionStorage10GetContentERKSbIcSt11char_traitsIcENS_8StlAllocIcEEEPSt10shared_ptrINS_7ContentEE() { for(;;){} }
void _ZN15AbstractStorage18DailymotionStorage11DeserializeESt10shared_ptrINS_7ContentEEPS1_INS_4ItemEE() { for(;;){} }
void _ZN15AbstractStorage18DailymotionStorage13GetRootFolderEPSt10shared_ptrINS_6FolderEE() { for(;;){} }
void _ZN15AbstractStorage18DailymotionStorage14GetStorageSizeEPlS1_S1_() { for(;;){} }
void _ZN15AbstractStorage18DailymotionStorage15CreateRecursiveERKSbIcSt11char_traitsIcENS_8StlAllocIcEEENS_8ItemTypeEPSt10shared_ptrINS_4ItemEE() { for(;;){} }
void _ZN15AbstractStorage18DailymotionStorage15RemoveRecursiveERKSbIcSt11char_traitsIcENS_8StlAllocIcEEE() { for(;;){} }
void _ZN15AbstractStorage18DailymotionStorage7GetItemERKSbIcSt11char_traitsIcENS_8StlAllocIcEEEPSt10shared_ptrINS_4ItemEE() { for(;;){} }
void _ZN15AbstractStorage18DailymotionStorage7IsExistERKSbIcSt11char_traitsIcENS_8StlAllocIcEEE() { for(;;){} }
void _ZN15AbstractStorage18DailymotionStorage9GetForderERKSbIcSt11char_traitsIcENS_8StlAllocIcEEEPSt10shared_ptrINS_6FolderEE() { for(;;){} }
void _ZN15AbstractStorage18DailymotionStorage9SerializeESt10shared_ptrINS_7ContentEES1_INS_4ItemEE() { for(;;){} }
void _ZN15AbstractStorage18DailymotionStorageC1ERKSbIcSt11char_traitsIcENS_8StlAllocIcEEE() { for(;;){} }
void _ZN15AbstractStorage18DailymotionStorageC2ERKSbIcSt11char_traitsIcENS_8StlAllocIcEEE() { for(;;){} }
void _ZN15AbstractStorage18DailymotionStorageD0Ev() { for(;;){} }
void _ZN15AbstractStorage18DailymotionStorageD1Ev() { for(;;){} }
void _ZN15AbstractStorage18DailymotionStorageD2Ev() { for(;;){} }
void _ZNK15AbstractStorage17DailymotionFolder10GetServiceEv() { for(;;){} }
void _ZNK15AbstractStorage17DailymotionFolder13GetCapabilityEv() { for(;;){} }
void _ZNK15AbstractStorage17DailymotionFolder7GetStatEPNS_4StatE() { for(;;){} }
void _ZNK15AbstractStorage18DailymotionContent10GetServiceEv() { for(;;){} }
void _ZNK15AbstractStorage18DailymotionContent13GetCapabilityEv() { for(;;){} }
void _ZNK15AbstractStorage18DailymotionContent7GetStatEPNS_4StatE() { for(;;){} }
void _ZNK15AbstractStorage18DailymotionService14GetServiceTypeEv() { for(;;){} }
void _ZNK15AbstractStorage18DailymotionStorage10GetServiceEv() { for(;;){} }
void _ZNK15AbstractStorage18DailymotionStorage13GetCapabilityEv() { for(;;){} }
void _ZNK15AbstractStorage18DailymotionStorage7GetStatEPNS_4StatE() { for(;;){} }
void _ZTVN15AbstractStorage17DailymotionFolderE() { for(;;){} }
void _ZTVN15AbstractStorage18DailymotionContentE() { for(;;){} }
void _ZTVN15AbstractStorage18DailymotionServiceE() { for(;;){} }
void _ZTVN15AbstractStorage18DailymotionStorageE() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}