/* Source generated by crazyvoids source generating tool **/
#include "libSceOpenPsId.h"

void sceKernelGetOpenPsId() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}