/* Source generated by crazyvoids source generating tool **/
#include "libsceHmdReprojectionMultilayer.h"

void sceHmdReprojectionStartMultilayer() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}