/* Source generated by crazyvoids source generating tool **/
#include "libSceSystemServiceClosedCaption.h"

void sceSystemServiceShowClosedCaptionAdvancedSettings() { for(;;){} }
void sceSystemServiceShowClosedCaptionSettings() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}