/* Source generated by crazyvoids source generating tool **/
#include "libSceNpParty.h"

void sceNpPartyCheckCallback() { for(;;){} }
void sceNpPartyCreate() { for(;;){} }
void sceNpPartyCreateA() { for(;;){} }
void sceNpPartyGetId() { for(;;){} }
void sceNpPartyGetMemberInfo() { for(;;){} }
void sceNpPartyGetMemberInfoA() { for(;;){} }
void sceNpPartyGetMembers() { for(;;){} }
void sceNpPartyGetMembersA() { for(;;){} }
void sceNpPartyGetMemberSessionInfo() { for(;;){} }
void sceNpPartyGetMemberVoiceInfo() { for(;;){} }
void sceNpPartyGetState() { for(;;){} }
void sceNpPartyGetStateAsUser() { for(;;){} }
void sceNpPartyGetStateAsUserA() { for(;;){} }
void sceNpPartyGetVoiceChatPriority() { for(;;){} }
void sceNpPartyInitialize() { for(;;){} }
void sceNpPartyJoin() { for(;;){} }
void sceNpPartyLeave() { for(;;){} }
void sceNpPartyRegisterHandler() { for(;;){} }
void sceNpPartyRegisterHandlerA() { for(;;){} }
void sceNpPartyRegisterPrivateHandler() { for(;;){} }
void sceNpPartySendBinaryMessage() { for(;;){} }
void sceNpPartySetVoiceChatPriority() { for(;;){} }
void sceNpPartyShowInvitationList() { for(;;){} }
void sceNpPartyShowInvitationListA() { for(;;){} }
void sceNpPartyTerminate() { for(;;){} }
void sceNpPartyUnregisterPrivateHandler() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}