/* Source generated by crazyvoids source generating tool **/
#include "libSceAudioOutSparkControl.h"

void sceAudioOutSparkControlSetEqCoef() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}