/* Source generated by crazyvoids source generating tool **/
#include "libSceDbgVideoOut.h"

void sceDbgVideoOutAddOutputModeVr60Privilege() { for(;;){} }
void sceDbgVideoOutAddProcessAttribute() { for(;;){} }
void sceDbgVideoOutRemoveProcessAttribute() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}