/* Source generated by crazyvoids source generating tool **/
#include "libSceFreeType.h"

void autofit_module_class() { for(;;){} }
void pshinter_module_class() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}