/* Source generated by crazyvoids source generating tool **/
#include "libSceSocialScreenDialog.h"

void sceSocialScreenDialogClose() { for(;;){} }
void sceSocialScreenDialogGetResult() { for(;;){} }
void sceSocialScreenDialogGetStatus() { for(;;){} }
void sceSocialScreenDialogInitialize() { for(;;){} }
void sceSocialScreenDialogOpen() { for(;;){} }
void sceSocialScreenDialogTerminate() { for(;;){} }
void sceSocialScreenDialogUpdateStatus() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}