/* Source generated by crazyvoids source generating tool **/
#include "libSceBeisobmf.h"

void isobmf_box_getchildbox() { for(;;){} }
void isobmf_box_getdiskoffset() { for(;;){} }
void isobmf_box_getflags32b() { for(;;){} }
void isobmf_box_getmember_length() { for(;;){} }
void isobmf_box_getmember_ptr() { for(;;){} }
void isobmf_box_getmember_type() { for(;;){} }
void isobmf_box_getnextbox() { for(;;){} }
void isobmf_box_getstate() { for(;;){} }
void isobmf_box_gettype() { for(;;){} }
void isobmf_decoder_clear() { for(;;){} }
void isobmf_decoder_create() { for(;;){} }
void isobmf_decoder_decode() { for(;;){} }
void isobmf_decoder_destroy() { for(;;){} }
void isobmf_decoder_get_decoder_tree() { for(;;){} }
void isobmf_decoder_getquerydata() { for(;;){} }
void isobmf_decoder_next_disk_offset() { for(;;){} }
void isobmf_decoder_query() { for(;;){} }
void isobmf_memmanager_set() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}