/* Source generated by crazyvoids source generating tool **/
#include "libSceCustomMusicService.h"

void sceCustomMusicServiceInitialize() { for(;;){} }
void sceCustomMusicServiceSendRequest() { for(;;){} }
void sceCustomMusicServiceTerminate() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}