/* Source generated by crazyvoids source generating tool **/
#include "libSceSystemServiceTelemetry.h"

void sceSystemServiceTelemetrySetData() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}