/* Source generated by crazyvoids source generating tool **/
#include "libSceNpFriendListDialogCompat.h"

void sceNpFriendListDialogGetResult() { for(;;){} }
void sceNpFriendListDialogOpen() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}