/* Source generated by crazyvoids source generating tool **/
#include "libSceSystemServiceWebBrowser.h"

void sceSystemServiceLaunchWebBrowser() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}