/* Source generated by crazyvoids source generating tool **/
#include "libSceGnmDriverResourceRegistration.h"

void sceGnmFindResources() { for(;;){} }
void sceGnmGetResourceRegistrationBuffers() { for(;;){} }
void sceGnmRegisterOwnerForSystem() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}