/* Source generated by crazyvoids source generating tool **/
#include "libSceHmdSetupDialog.h"

void sceHmdSetupDialogClose() { for(;;){} }
void sceHmdSetupDialogGetResult() { for(;;){} }
void sceHmdSetupDialogGetStatus() { for(;;){} }
void sceHmdSetupDialogInitialize() { for(;;){} }
void sceHmdSetupDialogOpen() { for(;;){} }
void sceHmdSetupDialogTerminate() { for(;;){} }
void sceHmdSetupDialogUpdateStatus() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}