/* Source generated by crazyvoids source generating tool **/
#include "libSceAudioOutDeviceService.h"

void sceAudioOutDeviceIdOpen() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}