/* Source generated by crazyvoids source generating tool **/
#include "libSceM4aacEnc.h"

void sceM4aacEncClearContext() { for(;;){} }
void sceM4aacEncCreateEncoder() { for(;;){} }
void sceM4aacEncDeleteEncoder() { for(;;){} }
void sceM4aacEncEncode() { for(;;){} }
void sceM4aacEncEncodeWithPriority() { for(;;){} }
void sceM4aacEncFlush() { for(;;){} }
void sceM4aacEncFlushWithPriority() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}