/* Source generated by crazyvoids source generating tool **/
#include "libSceImeDialog.h"

void sceImeDialogAbort() { for(;;){} }
void sceImeDialogForceClose() { for(;;){} }
void sceImeDialogForTestFunction() { for(;;){} }
void sceImeDialogGetCurrentStarState() { for(;;){} }
void sceImeDialogGetPanelPositionAndForm() { for(;;){} }
void sceImeDialogGetPanelSize() { for(;;){} }
void sceImeDialogGetPanelSizeExtended() { for(;;){} }
void sceImeDialogGetResult() { for(;;){} }
void sceImeDialogGetStatus() { for(;;){} }
void sceImeDialogInit() { for(;;){} }
void sceImeDialogInitInternal() { for(;;){} }
void sceImeDialogInitInternal2() { for(;;){} }
void sceImeDialogInitInternal3() { for(;;){} }
void sceImeDialogSetPanelPosition() { for(;;){} }
void sceImeDialogTerm() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}