/* Source generated by crazyvoids source generating tool **/
#include "libSceSystemServiceVoiceRecognition.h"

void sceSystemServiceDisableVoiceRecognition() { for(;;){} }
void sceSystemServiceReenableVoiceRecognition() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}