/* Source generated by crazyvoids source generating tool **/
#include "libSceAppContentIro.h"

void sceAppContentAddcontEnqueueDownloadByEntitlemetId() { for(;;){} }
void sceAppContentAddcontMountByEntitlemetId() { for(;;){} }
void sceAppContentGetAddcontInfoByEntitlementId() { for(;;){} }
void sceAppContentGetAddcontInfoListByIroTag() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}