/* Source generated by crazyvoids source generating tool **/
#include "libSceNpTrophy.h"

void sceNpTrophyAbortHandle() { for(;;){} }
void sceNpTrophyCaptureScreenshot() { for(;;){} }
void sceNpTrophyConfigGetTrophyDetails() { for(;;){} }
void sceNpTrophyConfigGetTrophyFlagArray() { for(;;){} }
void sceNpTrophyConfigGetTrophyGroupArray() { for(;;){} }
void sceNpTrophyConfigGetTrophyGroupDetails() { for(;;){} }
void sceNpTrophyConfigGetTrophySetInfo() { for(;;){} }
void sceNpTrophyConfigGetTrophySetInfoInGroup() { for(;;){} }
void sceNpTrophyConfigGetTrophySetVersion() { for(;;){} }
void sceNpTrophyConfigGetTrophyTitleDetails() { for(;;){} }
void sceNpTrophyConfigHasGroupFeature() { for(;;){} }
void sceNpTrophyCreateContext() { for(;;){} }
void sceNpTrophyCreateHandle() { for(;;){} }
void sceNpTrophyDestroyContext() { for(;;){} }
void sceNpTrophyDestroyHandle() { for(;;){} }
void sceNpTrophyGetGameIcon() { for(;;){} }
void sceNpTrophyGetGameInfo() { for(;;){} }
void sceNpTrophyGetGroupIcon() { for(;;){} }
void sceNpTrophyGetGroupInfo() { for(;;){} }
void sceNpTrophyGetTrophyIcon() { for(;;){} }
void sceNpTrophyGetTrophyInfo() { for(;;){} }
void sceNpTrophyGetTrophyUnlockState() { for(;;){} }
void sceNpTrophyGroupArrayGetNum() { for(;;){} }
void sceNpTrophyIntAbortHandle() { for(;;){} }
void sceNpTrophyIntCheckNetSyncTitles() { for(;;){} }
void sceNpTrophyIntCreateHandle() { for(;;){} }
void sceNpTrophyIntDestroyHandle() { for(;;){} }
void sceNpTrophyIntGetLocalTrophySummary() { for(;;){} }
void sceNpTrophyIntGetProgress() { for(;;){} }
void sceNpTrophyIntGetRunningTitle() { for(;;){} }
void sceNpTrophyIntGetRunningTitles() { for(;;){} }
void sceNpTrophyIntGetTrpIconByUri() { for(;;){} }
void sceNpTrophyIntNetSyncTitle() { for(;;){} }
void sceNpTrophyIntNetSyncTitles() { for(;;){} }
void sceNpTrophyNumInfoGetTotal() { for(;;){} }
void sceNpTrophyRegisterContext() { for(;;){} }
void sceNpTrophySetInfoGetTrophyFlagArray() { for(;;){} }
void sceNpTrophySetInfoGetTrophyNum() { for(;;){} }
void sceNpTrophyShowTrophyList() { for(;;){} }
void sceNpTrophySystemAbortHandle() { for(;;){} }
void sceNpTrophySystemBuildGroupIconUri() { for(;;){} }
void sceNpTrophySystemBuildNetTrophyIconUri() { for(;;){} }
void sceNpTrophySystemBuildTitleIconUri() { for(;;){} }
void sceNpTrophySystemBuildTrophyIconUri() { for(;;){} }
void sceNpTrophySystemCheckNetSyncTitles() { for(;;){} }
void sceNpTrophySystemCheckRecoveryRequired() { for(;;){} }
void sceNpTrophySystemCloseStorage() { for(;;){} }
void sceNpTrophySystemCreateContext() { for(;;){} }
void sceNpTrophySystemCreateHandle() { for(;;){} }
void sceNpTrophySystemDbgCtl() { for(;;){} }
void sceNpTrophySystemDebugLockTrophy() { for(;;){} }
void sceNpTrophySystemDebugUnlockTrophy() { for(;;){} }
void sceNpTrophySystemDestroyContext() { for(;;){} }
void sceNpTrophySystemDestroyHandle() { for(;;){} }
void sceNpTrophySystemDestroyTrophyConfig() { for(;;){} }
void sceNpTrophySystemGetDbgParam() { for(;;){} }
void sceNpTrophySystemGetDbgParamInt() { for(;;){} }
void sceNpTrophySystemGetGroupIcon() { for(;;){} }
void sceNpTrophySystemGetLocalTrophySummary() { for(;;){} }
void sceNpTrophySystemGetNextTitleFileEntryStatus() { for(;;){} }
void sceNpTrophySystemGetProgress() { for(;;){} }
void sceNpTrophySystemGetTitleFileStatus() { for(;;){} }
void sceNpTrophySystemGetTitleIcon() { for(;;){} }
void sceNpTrophySystemGetTitleSyncStatus() { for(;;){} }
void sceNpTrophySystemGetTrophyConfig() { for(;;){} }
void sceNpTrophySystemGetTrophyData() { for(;;){} }
void sceNpTrophySystemGetTrophyGroupData() { for(;;){} }
void sceNpTrophySystemGetTrophyIcon() { for(;;){} }
void sceNpTrophySystemGetTrophyTitleData() { for(;;){} }
void sceNpTrophySystemGetTrophyTitleIds() { for(;;){} }
void sceNpTrophySystemGetUserFileInfo() { for(;;){} }
void sceNpTrophySystemGetUserFileStatus() { for(;;){} }
void sceNpTrophySystemIsServerAvailable() { for(;;){} }
void sceNpTrophySystemNetSyncTitle() { for(;;){} }
void sceNpTrophySystemNetSyncTitles() { for(;;){} }
void sceNpTrophySystemOpenStorage() { for(;;){} }
void sceNpTrophySystemPerformRecovery() { for(;;){} }
void sceNpTrophySystemRemoveAll() { for(;;){} }
void sceNpTrophySystemRemoveTitleData() { for(;;){} }
void sceNpTrophySystemRemoveUserData() { for(;;){} }
void sceNpTrophySystemSetDbgParam() { for(;;){} }
void sceNpTrophySystemSetDbgParamInt() { for(;;){} }
void sceNpTrophyUnlockTrophy() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}