/* Source generated by crazyvoids source generating tool **/
#include "libSceUsbStorageDialog.h"

void sceUsbStorageDialogClose() { for(;;){} }
void sceUsbStorageDialogGetResult() { for(;;){} }
void sceUsbStorageDialogGetStatus() { for(;;){} }
void sceUsbStorageDialogInitialize() { for(;;){} }
void sceUsbStorageDialogOpen() { for(;;){} }
void sceUsbStorageDialogTerminate() { for(;;){} }
void sceUsbStorageDialogUpdateStatus() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}