/* Source generated by crazyvoids source generating tool **/
#include "libSceCoredump_debug.h"

void sceCoredumpDebugForceCoredumpOnAppClose() { for(;;){} }
void sceCoredumpDebugTriggerCoredump() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}