/* Source generated by crazyvoids source generating tool **/
#include "libScePadTracker.h"

void scePadTrackerCalibrate() { for(;;){} }
void scePadTrackerGetWorkingMemorySize() { for(;;){} }
void scePadTrackerInit() { for(;;){} }
void scePadTrackerReadState() { for(;;){} }
void scePadTrackerTerm() { for(;;){} }
void scePadTrackerUpdate() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}