/* Source generated by crazyvoids source generating tool **/
#include "libSceNpUtilityCompat.h"

void sceNpLookupCreateTitleCtx() { for(;;){} }
void sceNpLookupNpId() { for(;;){} }
void sceNpWordFilterCreateTitleCtx() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}