/* Source generated by crazyvoids source generating tool **/
#include "libSceJson.h"

void _ZN3sce4Json11Initializer10initializeEPKNS0_13InitParameterE() { for(;;){} }
void _ZN3sce4Json11Initializer9terminateEv() { for(;;){} }
void _ZN3sce4Json11InitializerC1Ev() { for(;;){} }
void _ZN3sce4Json11InitializerC2Ev() { for(;;){} }
void _ZN3sce4Json11InitializerD1Ev() { for(;;){} }
void _ZN3sce4Json11InitializerD2Ev() { for(;;){} }
void _ZN3sce4Json11s_initparamE() { for(;;){} }
void _ZN3sce4Json4FreeEPv() { for(;;){} }
void _ZN3sce4Json5Value10referArrayEv() { for(;;){} }
void _ZN3sce4Json5Value10referValueEm() { for(;;){} }
void _ZN3sce4Json5Value10referValueERKSbIcSt11char_traitsIcENS0_8StlAllocIcEEE() { for(;;){} }
void _ZN3sce4Json5Value10s_nullboolE() { for(;;){} }
void _ZN3sce4Json5Value10s_nullrealE() { for(;;){} }
void _ZN3sce4Json5Value11referObjectEv() { for(;;){} }
void _ZN3sce4Json5Value11referStringEv() { for(;;){} }
void _ZN3sce4Json5Value11s_nullarrayE() { for(;;){} }
void _ZN3sce4Json5Value12referBooleanEv() { for(;;){} }
void _ZN3sce4Json5Value12referIntegerEv() { for(;;){} }
void _ZN3sce4Json5Value12s_nullobjectE() { for(;;){} }
void _ZN3sce4Json5Value12s_nullstringE() { for(;;){} }
void _ZN3sce4Json5Value13referUIntegerEv() { for(;;){} }
void _ZN3sce4Json5Value13s_nullintegerE() { for(;;){} }
void _ZN3sce4Json5Value14s_nulluintegerE() { for(;;){} }
void _ZN3sce4Json5Value18serialize_internalERSbIcSt11char_traitsIcENS0_8StlAllocIcEEEPFiS7_PvES8_PS1_() { for(;;){} }
void _ZN3sce4Json5Value21setNullAccessCallBackEPFRKS1_NS0_9ValueTypeEPS2_PvES6_() { for(;;){} }
void _ZN3sce4Json5Value3setEb() { for(;;){} }
void _ZN3sce4Json5Value3setEd() { for(;;){} }
void _ZN3sce4Json5Value3setEl() { for(;;){} }
void _ZN3sce4Json5Value3setEm() { for(;;){} }
void _ZN3sce4Json5Value3setENS0_9ValueTypeE() { for(;;){} }
void _ZN3sce4Json5Value3setERKS1_() { for(;;){} }
void _ZN3sce4Json5Value3setERKSbIcSt11char_traitsIcENS0_8StlAllocIcEEE() { for(;;){} }
void _ZN3sce4Json5Value3setERKSt3mapISbIcSt11char_traitsIcENS0_8StlAllocIcEEES1_St4lessIS7_ENS5_ISt4pairIS7_S1_EEEE() { for(;;){} }
void _ZN3sce4Json5Value3setERKSt4listIS1_NS0_8StlAllocIS1_EEE() { for(;;){} }
void _ZN3sce4Json5Value4swapERS1_() { for(;;){} }
void _ZN3sce4Json5Value5clearEv() { for(;;){} }
void _ZN3sce4Json5Value9referRealEv() { for(;;){} }
void _ZN3sce4Json5Value9serializeERSbIcSt11char_traitsIcENS0_8StlAllocIcEEE() { for(;;){} }
void _ZN3sce4Json5Value9serializeERSbIcSt11char_traitsIcENS0_8StlAllocIcEEEPFiS7_PvES8_() { for(;;){} }
void _ZN3sce4Json5Value9setParentEPKS1_() { for(;;){} }
void _ZN3sce4Json5ValueaSERKS1_() { for(;;){} }
void _ZN3sce4Json5ValueC1Eb() { for(;;){} }
void _ZN3sce4Json5ValueC1Ed() { for(;;){} }
void _ZN3sce4Json5ValueC1El() { for(;;){} }
void _ZN3sce4Json5ValueC1Em() { for(;;){} }
void _ZN3sce4Json5ValueC1ENS0_9ValueTypeE() { for(;;){} }
void _ZN3sce4Json5ValueC1ERKS1_() { for(;;){} }
void _ZN3sce4Json5ValueC1ERKSbIcSt11char_traitsIcENS0_8StlAllocIcEEE() { for(;;){} }
void _ZN3sce4Json5ValueC1ERKSt3mapISbIcSt11char_traitsIcENS0_8StlAllocIcEEES1_St4lessIS7_ENS5_ISt4pairIS7_S1_EEEE() { for(;;){} }
void _ZN3sce4Json5ValueC1ERKSt4listIS1_NS0_8StlAllocIS1_EEE() { for(;;){} }
void _ZN3sce4Json5ValueC1Ev() { for(;;){} }
void _ZN3sce4Json5ValueC2Eb() { for(;;){} }
void _ZN3sce4Json5ValueC2Ed() { for(;;){} }
void _ZN3sce4Json5ValueC2El() { for(;;){} }
void _ZN3sce4Json5ValueC2Em() { for(;;){} }
void _ZN3sce4Json5ValueC2ENS0_9ValueTypeE() { for(;;){} }
void _ZN3sce4Json5ValueC2ERKS1_() { for(;;){} }
void _ZN3sce4Json5ValueC2ERKSbIcSt11char_traitsIcENS0_8StlAllocIcEEE() { for(;;){} }
void _ZN3sce4Json5ValueC2ERKSt3mapISbIcSt11char_traitsIcENS0_8StlAllocIcEEES1_St4lessIS7_ENS5_ISt4pairIS7_S1_EEEE() { for(;;){} }
void _ZN3sce4Json5ValueC2ERKSt4listIS1_NS0_8StlAllocIS1_EEE() { for(;;){} }
void _ZN3sce4Json5ValueC2Ev() { for(;;){} }
void _ZN3sce4Json5ValueD1Ev() { for(;;){} }
void _ZN3sce4Json5ValueD2Ev() { for(;;){} }
void _ZN3sce4Json6MallocEm() { for(;;){} }
void _ZN3sce4Json6Parser10parseArrayERNS0_5ValueERNS0_11InputStreamEPS2_() { for(;;){} }
void _ZN3sce4Json6Parser10parseValueERNS0_5ValueERNS0_11InputStreamEPS2_() { for(;;){} }
void _ZN3sce4Json6Parser11parseNumberERNS0_5ValueERNS0_11InputStreamEPS2_() { for(;;){} }
void _ZN3sce4Json6Parser11parseObjectERNS0_5ValueERNS0_11InputStreamEPS2_() { for(;;){} }
void _ZN3sce4Json6Parser11parseStringERNS0_5ValueERNS0_11InputStreamEPS2_() { for(;;){} }
void _ZN3sce4Json6Parser11parseStringERSbIcSt11char_traitsIcENS0_8StlAllocIcEEERNS0_11InputStreamE() { for(;;){} }
void _ZN3sce4Json6Parser12parseQuadHexERNS0_11InputStreamE() { for(;;){} }
void _ZN3sce4Json6Parser14parseCodePointERSbIcSt11char_traitsIcENS0_8StlAllocIcEEERNS0_11InputStreamE() { for(;;){} }
void _ZN3sce4Json6Parser5parseERNS0_5ValueEPFiRcPvES5_() { for(;;){} }
void _ZN3sce4Json6Parser5parseERNS0_5ValueEPKc() { for(;;){} }
void _ZN3sce4Json6Parser5parseERNS0_5ValueEPKcm() { for(;;){} }
void _ZN3sce4Json9RootParamC1Ev() { for(;;){} }
void _ZN3sce4Json9RootParamC2Ev() { for(;;){} }
void _ZN3sce4Json9RootParamD1Ev() { for(;;){} }
void _ZN3sce4Json9RootParamD2Ev() { for(;;){} }
void _ZNK3sce4Json5Value10getBooleanEv() { for(;;){} }
void _ZNK3sce4Json5Value10getIntegerEv() { for(;;){} }
void _ZNK3sce4Json5Value11getUIntegerEv() { for(;;){} }
void _ZNK3sce4Json5Value5countEv() { for(;;){} }
void _ZNK3sce4Json5Value7getRealEv() { for(;;){} }
void _ZNK3sce4Json5Value7getRootEv() { for(;;){} }
void _ZNK3sce4Json5Value7getTypeEv() { for(;;){} }
void _ZNK3sce4Json5Value8getArrayEv() { for(;;){} }
void _ZNK3sce4Json5Value8getValueEm() { for(;;){} }
void _ZNK3sce4Json5Value8getValueERKSbIcSt11char_traitsIcENS0_8StlAllocIcEEE() { for(;;){} }
void _ZNK3sce4Json5Value8toStringERSbIcSt11char_traitsIcENS0_8StlAllocIcEEE() { for(;;){} }
void _ZNK3sce4Json5Value9getObjectEv() { for(;;){} }
void _ZNK3sce4Json5Value9getStringEv() { for(;;){} }
void _ZNK3sce4Json5ValuecvbEv() { for(;;){} }
void _ZNK3sce4Json5ValueixEm() { for(;;){} }
void _ZNK3sce4Json5ValueixEPKc() { for(;;){} }
void _ZNK3sce4Json5ValueixERKSbIcSt11char_traitsIcENS0_8StlAllocIcEEE() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}