/* Source generated by crazyvoids source generating tool **/
#include "libSceVideoOutExtra.h"

void sceVideoOutAdjustColor2_() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}