/* Source generated by crazyvoids source generating tool **/
#include "libSceJpegDec_jvm.h"

void sceJpegDecDecodeWithInputControl() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}