/* Source generated by crazyvoids source generating tool **/
#include "libScePlayGo.h"

void scePlayGoClose() { for(;;){} }
void scePlayGoGetChunkId() { for(;;){} }
void scePlayGoGetEta() { for(;;){} }
void scePlayGoGetInstallSpeed() { for(;;){} }
void scePlayGoGetLanguageMask() { for(;;){} }
void scePlayGoGetLocus() { for(;;){} }
void scePlayGoGetProgress() { for(;;){} }
void scePlayGoGetToDoList() { for(;;){} }
void scePlayGoInitialize() { for(;;){} }
void scePlayGoOpen() { for(;;){} }
void scePlayGoPrefetch() { for(;;){} }
void scePlayGoSetInstallSpeed() { for(;;){} }
void scePlayGoSetLanguageMask() { for(;;){} }
void scePlayGoSetToDoList() { for(;;){} }
void scePlayGoTerminate() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}