/* Source generated by crazyvoids source generating tool **/
#include "libSceConvertKeycode.h"

void sceConvertKeycodeGetCharacter() { for(;;){} }
void sceConvertKeycodeGetVirtualKeycode() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}