/* Source generated by crazyvoids source generating tool **/
#include "libSceAudiodecCpuDdp.h"

void audiodeccpuinternal_core_ops_ddp() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}