/* Source generated by crazyvoids source generating tool **/
#include "libSceSaveData.h"

void sceSaveDataAbort() { for(;;){} }
void sceSaveDataBackup() { for(;;){} }
void sceSaveDataBindPsnAccount() { for(;;){} }
void sceSaveDataBindPsnAccountForSystemBackup() { for(;;){} }
void sceSaveDataChangeDatabase() { for(;;){} }
void sceSaveDataChangeInternal() { for(;;){} }
void sceSaveDataCheckBackupData() { for(;;){} }
void sceSaveDataCheckBackupDataInternal() { for(;;){} }
void sceSaveDataCheckCloudData() { for(;;){} }
void sceSaveDataCheckIpmiIfSize() { for(;;){} }
void sceSaveDataCheckSaveDataBroken() { for(;;){} }
void sceSaveDataCheckSaveDataVersion() { for(;;){} }
void sceSaveDataCheckSaveDataVersionLatest() { for(;;){} }
void sceSaveDataClearProgress() { for(;;){} }
void sceSaveDataCopy5() { for(;;){} }
void sceSaveDataCreateUploadData() { for(;;){} }
void sceSaveDataDebug() { for(;;){} }
void sceSaveDataDebugCleanMount() { for(;;){} }
void sceSaveDataDebugCompiledSdkVersion() { for(;;){} }
void sceSaveDataDebugCreateSaveDataRoot() { for(;;){} }
void sceSaveDataDebugGetThreadId() { for(;;){} }
void sceSaveDataDebugRemoveSaveDataRoot() { for(;;){} }
void sceSaveDataDebugTarget() { for(;;){} }
void sceSaveDataDelete() { for(;;){} }
void sceSaveDataDelete5() { for(;;){} }
void sceSaveDataDeleteAllUser() { for(;;){} }
void sceSaveDataDeleteCloudData() { for(;;){} }
void sceSaveDataDeleteUser() { for(;;){} }
void sceSaveDataDirNameSearch() { for(;;){} }
void sceSaveDataDirNameSearchInternal() { for(;;){} }
void sceSaveDataDownload() { for(;;){} }
void sceSaveDataGetAllSize() { for(;;){} }
void sceSaveDataGetAppLaunchedUser() { for(;;){} }
void sceSaveDataGetAutoUploadRequestInfo() { for(;;){} }
void sceSaveDataGetAutoUploadSetting() { for(;;){} }
void sceSaveDataGetBoundPsnAccountCount() { for(;;){} }
void sceSaveDataGetClientThreadPriority() { for(;;){} }
void sceSaveDataGetCloudQuotaInfo() { for(;;){} }
void sceSaveDataGetDataBaseFilePath() { for(;;){} }
void sceSaveDataGetEventInfo() { for(;;){} }
void sceSaveDataGetEventResult() { for(;;){} }
void sceSaveDataGetFormat() { for(;;){} }
void sceSaveDataGetMountedSaveDataCount() { for(;;){} }
void sceSaveDataGetMountInfo() { for(;;){} }
void sceSaveDataGetParam() { for(;;){} }
void sceSaveDataGetProgress() { for(;;){} }
void sceSaveDataGetSaveDataCount() { for(;;){} }
void sceSaveDataGetSaveDataMemory() { for(;;){} }
void sceSaveDataGetSaveDataMemory2() { for(;;){} }
void sceSaveDataGetSaveDataRootDir() { for(;;){} }
void sceSaveDataGetSaveDataRootPath() { for(;;){} }
void sceSaveDataGetSaveDataRootUsbPath() { for(;;){} }
void sceSaveDataGetSavePoint() { for(;;){} }
void sceSaveDataGetUpdatedDataCount() { for(;;){} }
void sceSaveDataInitialize() { for(;;){} }
void sceSaveDataInitialize2() { for(;;){} }
void sceSaveDataInitialize3() { for(;;){} }
void sceSaveDataInitializeForCdlg() { for(;;){} }
void sceSaveDataIsDeletingUsbDb() { for(;;){} }
void sceSaveDataIsMounted() { for(;;){} }
void sceSaveDataLoadIcon() { for(;;){} }
void sceSaveDataMount() { for(;;){} }
void sceSaveDataMount2() { for(;;){} }
void sceSaveDataMount5() { for(;;){} }
void sceSaveDataMountInternal() { for(;;){} }
void sceSaveDataMountSys() { for(;;){} }
void sceSaveDataPromote5() { for(;;){} }
void sceSaveDataRebuildDatabase() { for(;;){} }
void sceSaveDataRegisterEventCallback() { for(;;){} }
void sceSaveDataRestoreBackupData() { for(;;){} }
void sceSaveDataRestoreLoadSaveDataMemory() { for(;;){} }
void sceSaveDataSaveIcon() { for(;;){} }
void sceSaveDataSetAutoUploadSetting() { for(;;){} }
void sceSaveDataSetEventInfo() { for(;;){} }
void sceSaveDataSetParam() { for(;;){} }
void sceSaveDataSetSaveDataLibraryUser() { for(;;){} }
void sceSaveDataSetSaveDataMemory() { for(;;){} }
void sceSaveDataSetSaveDataMemory2() { for(;;){} }
void sceSaveDataSetupSaveDataMemory() { for(;;){} }
void sceSaveDataSetupSaveDataMemory2() { for(;;){} }
void sceSaveDataShutdownStart() { for(;;){} }
void sceSaveDataSyncCloudList() { for(;;){} }
void sceSaveDataSyncSaveDataMemory() { for(;;){} }
void sceSaveDataTerminate() { for(;;){} }
void sceSaveDataTransferringMount() { for(;;){} }
void sceSaveDataUmount() { for(;;){} }
void sceSaveDataUmountSys() { for(;;){} }
void sceSaveDataUmountWithBackup() { for(;;){} }
void sceSaveDataUnregisterEventCallback() { for(;;){} }
void sceSaveDataUpload() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}