/* Source generated by crazyvoids source generating tool **/
#include "libSceNgs2.h"

void sceNgs2CalcWaveformBlock() { for(;;){} }
void sceNgs2CustomRackGetModuleInfo() { for(;;){} }
void sceNgs2FftInit() { for(;;){} }
void sceNgs2FftProcess() { for(;;){} }
void sceNgs2FftQuerySize() { for(;;){} }
void sceNgs2GeomApply() { for(;;){} }
void sceNgs2GeomCalcListener() { for(;;){} }
void sceNgs2GeomResetListenerParam() { for(;;){} }
void sceNgs2GeomResetSourceParam() { for(;;){} }
void sceNgs2GetWaveformFrameInfo() { for(;;){} }
void sceNgs2PanGetVolumeMatrix() { for(;;){} }
void sceNgs2PanInit() { for(;;){} }
void sceNgs2ParseWaveformData() { for(;;){} }
void sceNgs2ParseWaveformFile() { for(;;){} }
void sceNgs2ParseWaveformUser() { for(;;){} }
void sceNgs2RackCreate() { for(;;){} }
void sceNgs2RackCreateWithAllocator() { for(;;){} }
void sceNgs2RackDestroy() { for(;;){} }
void sceNgs2RackGetInfo() { for(;;){} }
void sceNgs2RackGetUserData() { for(;;){} }
void sceNgs2RackGetVoiceHandle() { for(;;){} }
void sceNgs2RackLock() { for(;;){} }
void sceNgs2RackQueryBufferSize() { for(;;){} }
void sceNgs2RackSetUserData() { for(;;){} }
void sceNgs2RackUnlock() { for(;;){} }
void sceNgs2ReportRegisterHandler() { for(;;){} }
void sceNgs2ReportUnregisterHandler() { for(;;){} }
void sceNgs2SystemCreate() { for(;;){} }
void sceNgs2SystemCreateWithAllocator() { for(;;){} }
void sceNgs2SystemDestroy() { for(;;){} }
void sceNgs2SystemEnumHandles() { for(;;){} }
void sceNgs2SystemEnumRackHandles() { for(;;){} }
void sceNgs2SystemGetInfo() { for(;;){} }
void sceNgs2SystemGetUserData() { for(;;){} }
void sceNgs2SystemLock() { for(;;){} }
void sceNgs2SystemQueryBufferSize() { for(;;){} }
void sceNgs2SystemRender() { for(;;){} }
void sceNgs2SystemSetGrainSamples() { for(;;){} }
void sceNgs2SystemSetSampleRate() { for(;;){} }
void sceNgs2SystemSetUserData() { for(;;){} }
void sceNgs2SystemUnlock() { for(;;){} }
void sceNgs2VoiceControl() { for(;;){} }
void sceNgs2VoiceGetMatrixInfo() { for(;;){} }
void sceNgs2VoiceGetOwner() { for(;;){} }
void sceNgs2VoiceGetPortInfo() { for(;;){} }
void sceNgs2VoiceGetState() { for(;;){} }
void sceNgs2VoiceGetStateFlags() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}