/* Source generated by crazyvoids source generating tool **/
#include "libSceRemoteplay.h"

void sceRemoteplayApprove() { for(;;){} }
void sceRemoteplayClearAllRegistData() { for(;;){} }
void sceRemoteplayClearConnectHistory() { for(;;){} }
void sceRemoteplayConfirmDeviceRegist() { for(;;){} }
void sceRemoteplayDisconnect() { for(;;){} }
void sceRemoteplayGeneratePinCode() { for(;;){} }
void sceRemoteplayGetApMode() { for(;;){} }
void sceRemoteplayGetConnectHistory() { for(;;){} }
void sceRemoteplayGetConnectionStatus() { for(;;){} }
void sceRemoteplayGetConnectUserId() { for(;;){} }
void sceRemoteplayGetMbusDeviceInfo() { for(;;){} }
void sceRemoteplayGetRemoteplayStatus() { for(;;){} }
void sceRemoteplayGetRpMode() { for(;;){} }
void sceRemoteplayImeClose() { for(;;){} }
void sceRemoteplayImeFilterResult() { for(;;){} }
void sceRemoteplayImeGetEvent() { for(;;){} }
void sceRemoteplayImeNotify() { for(;;){} }
void sceRemoteplayImeNotifyEventResult() { for(;;){} }
void sceRemoteplayImeOpen() { for(;;){} }
void sceRemoteplayImeSetCaret() { for(;;){} }
void sceRemoteplayImeSetText() { for(;;){} }
void sceRemoteplayInitialize() { for(;;){} }
void sceRemoteplayIsRemoteOskReady() { for(;;){} }
void sceRemoteplayIsRemotePlaying() { for(;;){} }
void sceRemoteplayNotifyMbusDeviceRegistComplete() { for(;;){} }
void sceRemoteplayNotifyNpPushWakeup() { for(;;){} }
void sceRemoteplayNotifyPinCodeError() { for(;;){} }
void sceRemoteplayNotifyUserDelete() { for(;;){} }
void sceRemoteplayPrintAllRegistData() { for(;;){} }
void sceRemoteplayProhibit() { for(;;){} }
void sceRemoteplayProhibitStreaming() { for(;;){} }
void sceRemoteplaySetApMode() { for(;;){} }
void sceRemoteplaySetLogLevel() { for(;;){} }
void sceRemoteplaySetProhibition() { for(;;){} }
void sceRemoteplaySetProhibitionForVsh() { for(;;){} }
void sceRemoteplaySetRpMode() { for(;;){} }
void sceRemoteplayTerminate() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}