/* Source generated by crazyvoids source generating tool **/
#include "libScePsmKitSystem.h"

void _Z5dummyv() { for(;;){} }
void scePsmKitFontConfigGetFont() { for(;;){} }
void scePsmKitFontConfigGetFontPath() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}