/* Source generated by crazyvoids source generating tool **/
#include "libSceAudioDeviceControl.h"

void sceAudioDeviceControlGet() { for(;;){} }
void sceAudioDeviceControlSet() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}