/* Source generated by crazyvoids source generating tool **/
#include "libSceMsgDialog.h"

void sceMsgDialogClose() { for(;;){} }
void sceMsgDialogGetResult() { for(;;){} }
void sceMsgDialogGetStatus() { for(;;){} }
void sceMsgDialogInitialize() { for(;;){} }
void sceMsgDialogOpen() { for(;;){} }
void sceMsgDialogProgressBarInc() { for(;;){} }
void sceMsgDialogProgressBarSetMsg() { for(;;){} }
void sceMsgDialogProgressBarSetValue() { for(;;){} }
void sceMsgDialogTerminate() { for(;;){} }
void sceMsgDialogUpdateStatus() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}