/* Source generated by crazyvoids source generating tool **/
#include "libSceSysUtil.h"

void sceSysUtilSendAddressingSystemNotification() { for(;;){} }
void sceSysUtilSendAddressingSystemNotificationWithDeviceId() { for(;;){} }
void sceSysUtilSendAddressingSystemNotificationWithUserId() { for(;;){} }
void sceSysUtilSendAddressingSystemNotificationWithUserName() { for(;;){} }
void sceSysUtilSendNotificationRequest() { for(;;){} }
void sceSysUtilSendNpDebugNotificationRequest() { for(;;){} }
void sceSysUtilSendSystemNotification() { for(;;){} }
void sceSysUtilSendSystemNotification2() { for(;;){} }
void sceSysUtilSendSystemNotificationParamInit() { for(;;){} }
void sceSysUtilSendSystemNotificationWithAppId() { for(;;){} }
void sceSysUtilSendSystemNotificationWithAppInfo() { for(;;){} }
void sceSysUtilSendSystemNotificationWithAppName() { for(;;){} }
void sceSysUtilSendSystemNotificationWithAppNameRelatedToUser() { for(;;){} }
void sceSysUtilSendSystemNotificationWithDeviceId() { for(;;){} }
void sceSysUtilSendSystemNotificationWithDeviceIdRelatedToUser() { for(;;){} }
void sceSysUtilSendSystemNotificationWithErrorCode() { for(;;){} }
void sceSysUtilSendSystemNotificationWithParams() { for(;;){} }
void sceSysUtilSendSystemNotificationWithText() { for(;;){} }
void sceSysUtilSendSystemNotificationWithTextRelatedToUser() { for(;;){} }
void sceSysUtilSendSystemNotificationWithUserId() { for(;;){} }
void sceSysUtilSendSystemNotificationWithUserName() { for(;;){} }
void sceSysUtilSendSystemNotificationWithUserNameInfo() { for(;;){} }
void sceSysUtilSendTrcCheckNotificationRequest() { for(;;){} }
void sceSysUtilSendWebDebugNotificationRequest() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}