/* Source generated by crazyvoids source generating tool **/
#include "libSceUsbStorageAux.h"

void sceUsbStorageGetdentsClose() { for(;;){} }
void sceUsbStorageGetdentsOpen() { for(;;){} }
void sceUsbStorageGetdentsRead() { for(;;){} }
void sceUsbStorageRegisterCallbackForMapUnavailable() { for(;;){} }
void sceUsbStorageRequestMapWSB() { for(;;){} }
void sceUsbStorageUnregisterCallbackForMapUnavailable() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}