/* Source generated by crazyvoids source generating tool **/
#include "libSceWebBrowserDialog.h"

void sceWebBrowserDialogClose() { for(;;){} }
void sceWebBrowserDialogGetEvent() { for(;;){} }
void sceWebBrowserDialogGetResult() { for(;;){} }
void sceWebBrowserDialogGetStatus() { for(;;){} }
void sceWebBrowserDialogInitialize() { for(;;){} }
void sceWebBrowserDialogNavigate() { for(;;){} }
void sceWebBrowserDialogOpen() { for(;;){} }
void sceWebBrowserDialogOpenForPredeterminedContent() { for(;;){} }
void sceWebBrowserDialogResetCookie() { for(;;){} }
void sceWebBrowserDialogSetCookie() { for(;;){} }
void sceWebBrowserDialogSetZoom() { for(;;){} }
void sceWebBrowserDialogTerminate() { for(;;){} }
void sceWebBrowserDialogUpdateStatus() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}