/* Source generated by crazyvoids source generating tool **/
#include "libSceNpPartyCompat.h"

void sceNpPartyCreate() { for(;;){} }
void sceNpPartyGetMemberInfo() { for(;;){} }
void sceNpPartyGetMembers() { for(;;){} }
void sceNpPartyGetStateAsUser() { for(;;){} }
void sceNpPartyRegisterHandler() { for(;;){} }
void sceNpPartyShowInvitationList() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}