/* Source generated by crazyvoids source generating tool **/
#include "libSceSystemServiceUdsApp.h"

void sceSystemServiceLaunchUdsApp() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}