/* Source generated by crazyvoids source generating tool **/
#include "libSceContentDelete.h"

void sceContentDeleteById() { for(;;){} }
void sceContentDeleteByPath() { for(;;){} }
void sceContentDeleteInitialize() { for(;;){} }
void sceContentDeleteTerminate() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}