/* Source generated by crazyvoids source generating tool **/
#include "libSceMbusDebug.h"

void sceMbusDebugAcquireControl() { for(;;){} }
void sceMbusDebugAcquireControlWithState() { for(;;){} }
void sceMbusDebugAcquireControlWithState2() { for(;;){} }
void sceMbusDebugAcquireControlWithStateFlag() { for(;;){} }
void sceMbusDebugAddProcess() { for(;;){} }
void sceMbusDebugCheckProcessResume() { for(;;){} }
void sceMbusDebugDisableBgmForShellUi() { for(;;){} }
void sceMbusDebugGetApplicationStartupInfo() { for(;;){} }
void sceMbusDebugGetControlStatus() { for(;;){} }
void sceMbusDebugGetDeviceInfo() { for(;;){} }
void sceMbusDebugGetInternalInfo() { for(;;){} }
void sceMbusDebugGetPriorityInfo() { for(;;){} }
void sceMbusDebugReenableBgmForShellUi() { for(;;){} }
void sceMbusDebugReleaseControl() { for(;;){} }
void sceMbusDebugRemoveCameraAppModuleFocus() { for(;;){} }
void sceMbusDebugResumeApplication() { for(;;){} }
void sceMbusDebugSetApplicationFocusByAppId() { for(;;){} }
void sceMbusDebugSetCameraAppModuleFocus() { for(;;){} }
void sceMbusDebugSetControllerFocusByAppId() { for(;;){} }
void sceMbusDebugSetOtherProcessExcludedAction() { for(;;){} }
void sceMbusDebugSetPriority() { for(;;){} }
void sceMbusDebugStartApplication() { for(;;){} }
void sceMbusDebugStartApplication2() { for(;;){} }
void sceMbusDebugStartApplicationNull() { for(;;){} }
void sceMbusDebugSuspendApplication() { for(;;){} }
void sceMbusDebugTerminateApplication() { for(;;){} }
void sceMbusDebugTerminateProcess() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}