/* Source generated by crazyvoids source generating tool **/
#include "libSceJitBridge.h"

void _ZN19JITSharedDataMemory15shared_mallinfoEv() { for(;;){} }
void _ZN19JITSharedDataMemory9sbrk_infoE() { for(;;){} }
void _ZN19JITSharedTextMemory15shared_mallinfoEv() { for(;;){} }
void _ZN19JITSharedTextMemory9sbrk_infoE() { for(;;){} }
void _ZN9JITBridge12ringDoorbellEiNS_8DoorbellE() { for(;;){} }
void _ZN9JITBridge12waitDoorbellEi() { for(;;){} }
void _ZN9JITBridge14shutdownFromVMEPS_b() { for(;;){} }
void _ZN9JITBridge16initializeFromVMEPKcPPcPKNS_11RestartDataE() { for(;;){} }
void _ZN9JITBridge20shutdownFromCompilerEPS_b() { for(;;){} }
void _ZN9JITBridge22initializeFromCompilerEPKcPPcPKNS_11RestartDataE() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}