/* Source generated by crazyvoids source generating tool **/
#include "libSceScm.h"

void sceSblACMgrCheckPlatformDLL() { for(;;){} }
void sceSblACMgrIsPlatformDLL() { for(;;){} }
void sceSblRcMgrIsAllowLimitedUiInspector() { for(;;){} }
void sceSblRcMgrIsIntdevForPSM() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}