/* Source generated by crazyvoids source generating tool **/
#include "libSceCompanionUtil.h"

void sceCompanionUtilGetEvent() { for(;;){} }
void sceCompanionUtilGetRemoteOskEvent() { for(;;){} }
void sceCompanionUtilInitialize() { for(;;){} }
void sceCompanionUtilOptParamInitialize() { for(;;){} }
void sceCompanionUtilTerminate() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}