/* Source generated by crazyvoids source generating tool **/
#include "libSceBemp2sys.h"

void bemp2sys_logprintf_getlevel() { for(;;){} }
void bemp2sys_logprintf_setfunc() { for(;;){} }
void bemp2sys_logprintf_setlevel() { for(;;){} }
void bemp2sys_memmanager_set() { for(;;){} }
void bemp2sys_psdecoder_create() { for(;;){} }
void bemp2sys_psdecoder_destroy() { for(;;){} }
void bemp2sys_psdecoder_init() { for(;;){} }
void bemp2sys_psdecoder_readpacket() { for(;;){} }
void bemp2sys_psdecoder_release() { for(;;){} }
void bemp2sys_psdecoder_sendmessage() { for(;;){} }
void bemp2sys_tsdecoder_create() { for(;;){} }
void bemp2sys_tsdecoder_destroy() { for(;;){} }
void bemp2sys_tsdecoder_init() { for(;;){} }
void bemp2sys_tsdecoder_readpacket() { for(;;){} }
void bemp2sys_tsdecoder_release() { for(;;){} }
void bemp2sys_tsdecoder_sendmessage() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}