/* Source generated by crazyvoids source generating tool **/
#include "libScePsm.h"

void __dso_handle() { for(;;){} }
void _ZN3sce3pss4core14IntHandleTable13NextIntHandleEv() { for(;;){} }
void _ZN3sce3pss4core14IntHandleTable5mutexE() { for(;;){} }
void _ZN3sce3pss4core9PsmObjectC1Ev() { for(;;){} }
void _ZN3sce3pss4core9PsmObjectC2Ev() { for(;;){} }
void _ZN3sce3pss4core9PsmObjectD0Ev() { for(;;){} }
void _ZN3sce3pss4core9PsmObjectD1Ev() { for(;;){} }
void _ZN3sce3pss4core9PsmObjectD2Ev() { for(;;){} }
void _ZN3sce3pss4core9threading4Cond4WaitEi() { for(;;){} }
void _ZN3sce3pss4core9threading4Cond6NotifyEv() { for(;;){} }
void _ZN3sce3pss4core9threading4CondC1ERNS2_5MutexEPKci() { for(;;){} }
void _ZN3sce3pss4core9threading4CondC2ERNS2_5MutexEPKci() { for(;;){} }
void _ZN3sce3pss4core9threading4CondD1Ev() { for(;;){} }
void _ZN3sce3pss4core9threading4CondD2Ev() { for(;;){} }
void _ZN3sce3pss5orbis9framework12PsmFramework3RunEv() { for(;;){} }
void _ZN3sce3pss5orbis9framework12PsmFramework8FinalizeEv() { for(;;){} }
void ScePsmMonoArrayAddrWithSize() { for(;;){} }
void ScePsmMonoArrayLength() { for(;;){} }
void ScePsmMonoDomainGet() { for(;;){} }
void ScePsmMonoFree() { for(;;){} }
void ScePsmMonoGcWbarrierGenericStore() { for(;;){} }
void ScePsmMonoStringChars() { for(;;){} }
void ScePsmMonoStringFromUtf16() { for(;;){} }
void ScePsmMonoStringLength() { for(;;){} }
void ScePsmMonoStringNew() { for(;;){} }
void ScePsmMonoStringNewWrapper() { for(;;){} }
void ScePsmMonoStringToUtf8() { for(;;){} }
void scePsmRegisterInternalCall() { for(;;){} }
void scePsmRegisterPInvokeCallTable() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}