/* Source generated by crazyvoids source generating tool **/
#include "libSceSystemStateMgr.h"

void sceSystemStateMgrCancelShutdownTimer() { for(;;){} }
void sceSystemStateMgrEnterMediaPlaybackMode() { for(;;){} }
void sceSystemStateMgrEnterStandby() { for(;;){} }
void sceSystemStateMgrExtendShutdownTimer() { for(;;){} }
void sceSystemStateMgrExtendShutdownTimerForPostAutoUpdateProcess() { for(;;){} }
void sceSystemStateMgrGetCurrentState() { for(;;){} }
void sceSystemStateMgrGetTriggerCode() { for(;;){} }
void sceSystemStateMgrIsBdDriveReady() { for(;;){} }
void sceSystemStateMgrIsGpuPerformanceNormal() { for(;;){} }
void sceSystemStateMgrIsShellUIShutdownInProgress() { for(;;){} }
void sceSystemStateMgrIsStandbyModeEnabled() { for(;;){} }
void sceSystemStateMgrLeaveMediaPlaybackMode() { for(;;){} }
void sceSystemStateMgrNotifySystemSuspendResumeProgress() { for(;;){} }
void sceSystemStateMgrReboot() { for(;;){} }
void sceSystemStateMgrSendCecOneTouchPlayCommand() { for(;;){} }
void sceSystemStateMgrStartRebootTimer() { for(;;){} }
void sceSystemStateMgrStartShutdownTimer() { for(;;){} }
void sceSystemStateMgrStartStadbyTimer() { for(;;){} }
void sceSystemStateMgrStartVshAutoUpdateTimer() { for(;;){} }
void sceSystemStateMgrTickMusicPlayback() { for(;;){} }
void sceSystemStateMgrTickPartyChat() { for(;;){} }
void sceSystemStateMgrTurnOff() { for(;;){} }
void sceSystemStateMgrVshAutoUpdate() { for(;;){} }
void sceSystemStateMgrWaitVshAutoUpdateVerifyDone() { for(;;){} }
void sceSystemStateMgrWakeUp() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}