/* Source generated by crazyvoids source generating tool **/
#include "libSceSrcUtl.h"

void sceSrcUtilityFinalize() { for(;;){} }
void sceSrcUtilityFlush() { for(;;){} }
void sceSrcUtilityGetDelaySamples() { for(;;){} }
void sceSrcUtilityGetHandleSize() { for(;;){} }
void sceSrcUtilityGetPriority() { for(;;){} }
void sceSrcUtilityInitialize() { for(;;){} }
void sceSrcUtilityResample() { for(;;){} }
void sceSrcUtilitySetPriority() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}