/* Source generated by crazyvoids source generating tool **/
#include "libSceNpScoreCompat.h"

void sceNpScoreCreateNpTitleCtx() { for(;;){} }
void sceNpScoreGetFriendsRanking() { for(;;){} }
void sceNpScoreGetFriendsRankingAsync() { for(;;){} }
void sceNpScoreGetGameData() { for(;;){} }
void sceNpScoreGetGameDataAsync() { for(;;){} }
void sceNpScoreGetRankingByNpId() { for(;;){} }
void sceNpScoreGetRankingByNpIdAsync() { for(;;){} }
void sceNpScoreGetRankingByNpIdPcId() { for(;;){} }
void sceNpScoreGetRankingByNpIdPcIdAsync() { for(;;){} }
void sceNpScoreGetRankingByRange() { for(;;){} }
void sceNpScoreGetRankingByRangeAsync() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}