/* Source generated by crazyvoids source generating tool **/
#include "libSceLncUtil.h"

void sceLncUtilAcquireCpuBudgetOfExtraAudioDevices() { for(;;){} }
void sceLncUtilAcquireCpuBudgetOfImeForBigApp() { for(;;){} }
void sceLncUtilAcquireCpuBudgetOfInGameStore() { for(;;){} }
void sceLncUtilActivateCdlg() { for(;;){} }
void sceLncUtilAddLocalProcess() { for(;;){} }
void sceLncUtilBlockAppSuspend() { for(;;){} }
void sceLncUtilBlockingGetEventForDaemon() { for(;;){} }
void sceLncUtilContinueApp() { for(;;){} }
void sceLncUtilCrashSyscore() { for(;;){} }
void sceLncUtilDeactivateCdlg() { for(;;){} }
void sceLncUtilDeclareReadyForSuspend() { for(;;){} }
void sceLncUtilDisableSuspendNotification() { for(;;){} }
void sceLncUtilEnableSuspendNotification() { for(;;){} }
void sceLncUtilFinishSpecialResume() { for(;;){} }
void sceLncUtilForceKillApp() { for(;;){} }
void sceLncUtilForceKillLocalProcess() { for(;;){} }
void sceLncUtilGetApp0DirPath() { for(;;){} }
void sceLncUtilGetAppCategory() { for(;;){} }
void sceLncUtilGetAppFocusedAppStatus() { for(;;){} }
void sceLncUtilGetAppId() { for(;;){} }
void sceLncUtilGetAppIdOfBigApp() { for(;;){} }
void sceLncUtilGetAppIdOfMiniApp() { for(;;){} }
void sceLncUtilGetAppLaunchedUser() { for(;;){} }
void sceLncUtilGetAppStatus() { for(;;){} }
void sceLncUtilGetAppStatusListForShellUIReboot() { for(;;){} }
void sceLncUtilGetAppTitleId() { for(;;){} }
void sceLncUtilGetAppType() { for(;;){} }
void sceLncUtilGetCdlgExec() { for(;;){} }
void sceLncUtilGetCoredumpState() { for(;;){} }
void sceLncUtilGetDbgExecutablePath() { for(;;){} }
void sceLncUtilGetEventForDaemon() { for(;;){} }
void sceLncUtilGetEventForShellUI() { for(;;){} }
void sceLncUtilGetLocalProcessStatusList() { for(;;){} }
void sceLncUtilGetParentSocket() { for(;;){} }
void sceLncUtilGetResultKillApp() { for(;;){} }
void sceLncUtilGetResultLaunchAppByTitleId() { for(;;){} }
void sceLncUtilInitialize() { for(;;){} }
void sceLncUtilIsActiveCdlg() { for(;;){} }
void sceLncUtilIsAppSuspended() { for(;;){} }
void sceLncUtilIsCpuBudgetOfExtraAudioDevicesAvailable() { for(;;){} }
void sceLncUtilIsPs2Emu() { for(;;){} }
void sceLncUtilIsShellUiFgAndGameBgCpuMode() { for(;;){} }
void sceLncUtilKickCoredumpOnlyProcMem() { for(;;){} }
void sceLncUtilKillApp() { for(;;){} }
void sceLncUtilKillAppWithReason() { for(;;){} }
void sceLncUtilKillLocalProcess() { for(;;){} }
void sceLncUtilLaunchApp() { for(;;){} }
void sceLncUtilLoadExec() { for(;;){} }
void sceLncUtilNotifyCoredumpRequestEnd() { for(;;){} }
void sceLncUtilNotifyCoredumpRequestProgress() { for(;;){} }
void sceLncUtilNotifyVshReady() { for(;;){} }
void sceLncUtilRaiseException() { for(;;){} }
void sceLncUtilRaiseExceptionLocalProcess() { for(;;){} }
void sceLncUtilRegisterCdlgSharedMemoryName() { for(;;){} }
void sceLncUtilRegisterDaemon() { for(;;){} }
void sceLncUtilRegisterShellUI() { for(;;){} }
void sceLncUtilReleaseCpuBudgetOfExtraAudioDevices() { for(;;){} }
void sceLncUtilReleaseCpuBudgetOfImeForBigApp() { for(;;){} }
void sceLncUtilReleaseCpuBudgetOfInGameStore() { for(;;){} }
void sceLncUtilResumeApp() { for(;;){} }
void sceLncUtilResumeLocalProcess() { for(;;){} }
void sceLncUtilSetAppFocus() { for(;;){} }
void sceLncUtilSetCdlgExec() { for(;;){} }
void sceLncUtilSetControllerFocus() { for(;;){} }
void sceLncUtilSetControllerFocusPermission() { for(;;){} }
void sceLncUtilStartKillApp() { for(;;){} }
void sceLncUtilStartLaunchAppByTitleId() { for(;;){} }
void sceLncUtilSuspendApp() { for(;;){} }
void sceLncUtilSuspendBackgroundApp() { for(;;){} }
void sceLncUtilSuspendLocalProcess() { for(;;){} }
void sceLncUtilSystemSuspend() { for(;;){} }
void sceLncUtilTerminate() { for(;;){} }
void sceLncUtilTryBlockAppSuspend() { for(;;){} }
void sceLncUtilUnblockAppSuspend() { for(;;){} }
void sceLncUtilUnregisterCdlgSharedMemoryName() { for(;;){} }
void sceLncUtilUnregisterDaemon() { for(;;){} }
void sceLncUtilUnregisterShellUI() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}