/* Source generated by crazyvoids source generating tool **/
#include "libsceNpEulaDialog.h"

void sceNpEulaDialogCheckVersion() { for(;;){} }
void sceNpEulaDialogCheckVersionAbort() { for(;;){} }
void sceNpEulaDialogClose() { for(;;){} }
void sceNpEulaDialogGetResult() { for(;;){} }
void sceNpEulaDialogGetStatus() { for(;;){} }
void sceNpEulaDialogInitialize() { for(;;){} }
void sceNpEulaDialogOpen() { for(;;){} }
void sceNpEulaDialogTerminate() { for(;;){} }
void sceNpEulaDialogUpdateStatus() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}