/* Source generated by crazyvoids source generating tool **/
#include "libSceCommonDialog.h"

void sceCommonDialogInitialize() { for(;;){} }
void sceCommonDialogIsUsed() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}