/* Source generated by crazyvoids source generating tool **/
#include "libSceIpmiDbg.h"

void sceIpmiMgrGetIpcBlockerPid() { for(;;){} }
void sceIpmiMgrGetIpcBlockerPidByAppId() { for(;;){} }
void sceIpmiMgrPauseDump() { for(;;){} }
void sceIpmiMgrRaiseExceptionToPid() { for(;;){} }
void sceIpmiMgrStartDump() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}