/* Source generated by crazyvoids source generating tool **/
#include "libSceErrorDialog.h"

void sceErrorDialogClose() { for(;;){} }
void sceErrorDialogGetStatus() { for(;;){} }
void sceErrorDialogInitialize() { for(;;){} }
void sceErrorDialogOpen() { for(;;){} }
void sceErrorDialogOpenDetail() { for(;;){} }
void sceErrorDialogOpenWithReport() { for(;;){} }
void sceErrorDialogTerminate() { for(;;){} }
void sceErrorDialogUpdateStatus() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}