/* Source generated by crazyvoids source generating tool **/
#include "libSceDeviceService.h"

void sceDeviceServiceGetEventState() { for(;;){} }
void sceDeviceServiceGetGeneration() { for(;;){} }
void sceDeviceServiceInitialize() { for(;;){} }
void sceDeviceServiceQueryDeviceInfo_() { for(;;){} }
void sceDeviceServiceTerminate() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}