/* Source generated by crazyvoids source generating tool **/
#include "libScePs2EmuMenuDialog.h"

void scePs2EmuMenuDialogClose() { for(;;){} }
void scePs2EmuMenuDialogGetResult() { for(;;){} }
void scePs2EmuMenuDialogGetStatus() { for(;;){} }
void scePs2EmuMenuDialogInitialize() { for(;;){} }
void scePs2EmuMenuDialogOpen() { for(;;){} }
void scePs2EmuMenuDialogTerminate() { for(;;){} }
void scePs2EmuMenuDialogUpdateStatus() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}