/* Source generated by crazyvoids source generating tool **/
#include "libScePngEnc.h"

void scePngEncCreate() { for(;;){} }
void scePngEncDelete() { for(;;){} }
void scePngEncEncode() { for(;;){} }
void scePngEncQueryMemorySize() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}