/* Source generated by crazyvoids source generating tool **/
#include "libSceVideoCoreInterface.h"

void sceVideoCoreInterfaceAddVblankEvent() { for(;;){} }
void sceVideoCoreInterfaceCloseCanvas() { for(;;){} }
void sceVideoCoreInterfaceCloseVideoOut() { for(;;){} }
void sceVideoCoreInterfaceCreateCanvasContext() { for(;;){} }
void sceVideoCoreInterfaceCreateFrameBufferContext() { for(;;){} }
void sceVideoCoreInterfaceDestroyCanvasContext() { for(;;){} }
void sceVideoCoreInterfaceDestroyFrameBufferContext() { for(;;){} }
void sceVideoCoreInterfaceFinishRendering() { for(;;){} }
void sceVideoCoreInterfaceFlushVideoOutBuffer() { for(;;){} }
void sceVideoCoreInterfaceGetCanvasVideoBufferAddress() { for(;;){} }
void sceVideoCoreInterfaceGetCanvasVideoBufferSize() { for(;;){} }
void sceVideoCoreInterfaceGetRenderFrameBuffer() { for(;;){} }
void sceVideoCoreInterfaceInitializeInterface() { for(;;){} }
void sceVideoCoreInterfaceLoadModule() { for(;;){} }
void sceVideoCoreInterfaceMainLoop() { for(;;){} }
void sceVideoCoreInterfaceOpenCanvas() { for(;;){} }
void sceVideoCoreInterfaceOpenVideoOut() { for(;;){} }
void sceVideoCoreInterfaceSetCanvasId() { for(;;){} }
void sceVideoCoreInterfaceSetFunctionTable() { for(;;){} }
void sceVideoCoreInterfaceSetFunctionTableExt() { for(;;){} }
void sceVideoCoreInterfaceSetVideoOutBufferInfo() { for(;;){} }
void sceVideoCoreInterfaceSubmitCanvases() { for(;;){} }
void sceVideoCoreInterfaceUnloadModule() { for(;;){} }
void sceVideoCoreInterfaceWaitCanvasFlip() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}