/* Source generated by crazyvoids source generating tool **/
#include "libSceSysCore.h"

void _sceApplicationGetAppId() { for(;;){} }
void sceApplicationAddProcess2() { for(;;){} }
void sceApplicationBeginSclkChange() { for(;;){} }
void sceApplicationBlockingKill2() { for(;;){} }
void sceApplicationBlockingKill3() { for(;;){} }
void sceApplicationContinue() { for(;;){} }
void sceApplicationCrashSyscore() { for(;;){} }
void sceApplicationCrashSystemProcess() { for(;;){} }
void sceApplicationDebugSpawnCommonDialog() { for(;;){} }
void sceApplicationDebugSpawnDaemon() { for(;;){} }
void sceApplicationEndSclkChange() { for(;;){} }
void sceApplicationExitSpawn() { for(;;){} }
void sceApplicationExitSpawn2() { for(;;){} }
void sceApplicationFinalize() { for(;;){} }
void sceApplicationGetAppInfoByAppId() { for(;;){} }
void sceApplicationGetAppPackageInfoForCoredump() { for(;;){} }
void sceApplicationGetCanvasHandle() { for(;;){} }
void sceApplicationGetCanvasHandleByApplicationLocalPid() { for(;;){} }
void sceApplicationGetCanvasHandleByPid() { for(;;){} }
void sceApplicationGetCompiledSdkVersionByAppId() { for(;;){} }
void sceApplicationGetCoredumpDirAndFileName() { for(;;){} }
void sceApplicationGetCoredumpState() { for(;;){} }
void sceApplicationGetCpuUsage() { for(;;){} }
void sceApplicationGetCpuUsage2() { for(;;){} }
void sceApplicationGetDbgExecutablePath() { for(;;){} }
void sceApplicationGetMode() { for(;;){} }
void sceApplicationGetProcs() { for(;;){} }
void sceApplicationGetShellCoreAppId() { for(;;){} }
void sceApplicationGetStateForDebugger() { for(;;){} }
void sceApplicationInitialize() { for(;;){} }
void sceApplicationInitializeForShellCore() { for(;;){} }
void sceApplicationIsCrashReportBeingProcessed() { for(;;){} }
void sceApplicationIsPrimaryProcess() { for(;;){} }
void sceApplicationIsResumable() { for(;;){} }
void sceApplicationIsSuspendable() { for(;;){} }
void sceApplicationKickCoredump() { for(;;){} }
void sceApplicationKickCoredump2() { for(;;){} }
void sceApplicationKill() { for(;;){} }
void sceApplicationLocalProcessKill() { for(;;){} }
void sceApplicationLocalProcessKill2() { for(;;){} }
void sceApplicationLocalProcessResume() { for(;;){} }
void sceApplicationLocalProcessSuspend() { for(;;){} }
void sceApplicationNotifyCoredumpRequestEnd() { for(;;){} }
void sceApplicationNotifyCoredumpRequestProgress() { for(;;){} }
void sceApplicationNotifyPhase() { for(;;){} }
void sceApplicationNotifyVshMainOnStandby() { for(;;){} }
void sceApplicationNotifyVshReady() { for(;;){} }
void sceApplicationRaiseException() { for(;;){} }
void sceApplicationRaiseExceptionToLocalPid() { for(;;){} }
void sceApplicationRaiseExceptionToPid() { for(;;){} }
void sceApplicationRequestToChangeRenderingMode() { for(;;){} }
void sceApplicationResume() { for(;;){} }
void sceApplicationSendDebugSpawnResult2() { for(;;){} }
void sceApplicationSendResultOfDebuggerKillRequest() { for(;;){} }
void sceApplicationSendResultOfDebuggerResumeRequest() { for(;;){} }
void sceApplicationSendResultOfDebuggerSuspendRequest() { for(;;){} }
void sceApplicationSendResultOfDebuggerTitleIdLaunchRequest() { for(;;){} }
void sceApplicationSetApplicationFocus() { for(;;){} }
void sceApplicationSetCanvasHandle() { for(;;){} }
void sceApplicationSetControllerFocus() { for(;;){} }
void sceApplicationSetControllerFocusPermissionToSubProcess() { for(;;){} }
void sceApplicationSetMemoryPstate() { for(;;){} }
void sceApplicationSignalShellCoreHeartBeat() { for(;;){} }
void sceApplicationSpawnCommonDialog() { for(;;){} }
void sceApplicationSpawnDaemon() { for(;;){} }
void sceApplicationSuspend() { for(;;){} }
void sceApplicationSuspendSystemForDebugger() { for(;;){} }
void sceApplicationSwitchToBaseMode() { for(;;){} }
void sceApplicationSwitchToNeoMode() { for(;;){} }
void sceApplicationSwitchToNeoMode2() { for(;;){} }
void sceApplicationSystemReboot() { for(;;){} }
void sceApplicationSystemShutdown2() { for(;;){} }
void sceApplicationSystemSuspend() { for(;;){} }
void sceApplictionGetStateForDebugger() { for(;;){} }
void sceSysCoreGetEventCount() { for(;;){} }
void sceSysCoreReceiveEvent() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}