/* Source generated by crazyvoids source generating tool **/
#include "libSceVdecwrap.h"

void sceVdecwrapCreateDecoder() { for(;;){} }
void sceVdecwrapDeleteDecoder() { for(;;){} }
void sceVdecwrapFlushDecodeOutput() { for(;;){} }
void sceVdecwrapGetDecodeOutput() { for(;;){} }
void sceVdecwrapMapDirectMemory() { for(;;){} }
void sceVdecwrapQueryDecoderMemoryInfo() { for(;;){} }
void sceVdecwrapQueryFrameBufferInfo() { for(;;){} }
void sceVdecwrapResetDecoder() { for(;;){} }
void sceVdecwrapSetDecodeInput() { for(;;){} }
void sceVdecwrapSyncDecode() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}