/* Source generated by crazyvoids source generating tool **/
#include "libSceAutoMounterClient.h"

void sceAutoMounterClientGetUsbDeviceInfo() { for(;;){} }
void sceAutoMounterClientGetUsbDeviceList() { for(;;){} }
void sceAutoMounterClientInit() { for(;;){} }
void sceAutoMounterClientRegisterCallback() { for(;;){} }
void sceAutoMounterClientTerm() { for(;;){} }
void sceAutoMounterClientUnregisterCallback() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}