/* Source generated by crazyvoids source generating tool **/
#include "libSceMove.h"

void sceMoveClose() { for(;;){} }
void sceMoveGetBluetoothAddress() { for(;;){} }
void sceMoveGetCalibrationInfo() { for(;;){} }
void sceMoveGetDeviceId() { for(;;){} }
void sceMoveGetDeviceInfo() { for(;;){} }
void sceMoveGetExtensionPortInfo() { for(;;){} }
void sceMoveInit() { for(;;){} }
void sceMoveIsReproductionModel() { for(;;){} }
void sceMoveIsValidHandle() { for(;;){} }
void sceMoveOpen() { for(;;){} }
void sceMoveReadStateLatest() { for(;;){} }
void sceMoveReadStateRecent() { for(;;){} }
void sceMoveReadStateRecentForTracker() { for(;;){} }
void sceMoveResetLightSphere() { for(;;){} }
void sceMoveSetCalibrationMode() { for(;;){} }
void sceMoveSetExtensionPortOutput() { for(;;){} }
void sceMoveSetLightSphere() { for(;;){} }
void sceMoveSetLightSphereForTracker() { for(;;){} }
void sceMoveSetVibration() { for(;;){} }
void sceMoveTerm() { for(;;){} }
void sceMoveWriteCalibrationInfo() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}