#pragma once

// Params should go here....

// code goes here
// example ABI_SYSV int test(int input);
void sceRegMgrBackupNeedMem();
void sceRegMgrBackupPullData();
void sceRegMgrBackupPushData();
void sceRegMgrCheckError();
void sceRegMgrCntlDeleteReg();
void sceRegMgrCntlGetFileName();
void sceRegMgrCntlGetFilesCount();
void sceRegMgrCntlStart();
void sceRegMgrCntlStopHdd();
void sceRegMgrCntSetInitReinst();
void sceRegMgrDrvDataCheckGet();
void sceRegMgrDrvDataClose();
void sceRegMgrDrvDataOpen();
void sceRegMgrDrvGetEntCnt();
void sceRegMgrDrvGetUpdateCnt();
void sceRegMgrEvtGetCnt();
void sceRegMgrEvtGetRegId();
void sceRegMgrGetBin();
void sceRegMgrGetBinInitVal();
void sceRegMgrGetInt();
void sceRegMgrGetIntInitVal();
void sceRegMgrGetStr();
void sceRegMgrGetStrInitVal();
void sceRegMgrGetVersion();
void sceRegMgrIsChange();
void sceRegMgrIsInitOK();
void sceRegMgrLogPull();
void sceRegMgrLogStart();
void sceRegMgrNonSysCheckError();
void sceRegMgrNonSysGetBin();
void sceRegMgrNonSysGetInt();
void sceRegMgrNonSysGetStr();
void sceRegMgrNonSysSetBin();
void sceRegMgrNonSysSetInt();
void sceRegMgrNonSysSetStr();
void sceRegMgrPrintInfo();
void sceRegMgrRecoverRegNvs();
void sceRegMgrResetVal();
void sceRegMgrSetBin();
void sceRegMgrSetInitLevel();
void sceRegMgrSetInt();
void sceRegMgrSetStr();
void sceRegMgrSrvCnvRegionInt();
void sceRegMgrSrvCnvRegionStr();
void sceRegMgrSrvGetMachineType();
void sceRegMgrSrvGetQAFforReg();
void sceRegMgrSrvGetRealMachineType();
void sceRegMgrSrvGetRegion();
void sceRegMgrSrvGetRegionStr();
void sceRegMgrToolDataCheckGet();
void sceRegMgrToolGetEntryCnt();
void sceRegMgrToolGetInfo();
void sceRegMgrToolGetUpdateCnt();
