/* Source generated by crazyvoids source generating tool **/
#include "libSceAppMessaging.h"

void sceAppMessagingClearEventFlag() { for(;;){} }
void sceAppMessagingReceiveMsg() { for(;;){} }
void sceAppMessagingSendMsg() { for(;;){} }
void sceAppMessagingSendMsgToShellCore() { for(;;){} }
void sceAppMessagingSendMsgToShellUI() { for(;;){} }
void sceAppMessagingSetEventFlag() { for(;;){} }
void sceAppMessagingTryGetEventFlag() { for(;;){} }
void sceAppMessagingTryReceiveMsg() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}