/* Source generated by crazyvoids source generating tool **/
#include "libSceVideoOutAniso.h"

void sceVideoOutAddBufferAnisoPrivilege() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}