/* Source generated by crazyvoids source generating tool **/
#include "libSceLoginService.h"

void sceLoginServiceInitialize() { for(;;){} }
void sceLoginServiceRequestDevices() { for(;;){} }
void sceLoginServiceTerminate() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}