/* Source generated by crazyvoids source generating tool **/
#include "libSceHidControl.h"

void sceHidControlConnectHandle() { for(;;){} }
void sceHidControlConnectPort() { for(;;){} }
void sceHidControlDisconnectDevice() { for(;;){} }
void sceHidControlDisconnectHandle() { for(;;){} }
void sceHidControlDisconnectPort() { for(;;){} }
void sceHidControlGetAuthInformation() { for(;;){} }
void sceHidControlGetBatteryState() { for(;;){} }
void sceHidControlGetDeviceId() { for(;;){} }
void sceHidControlGetDeviceInfo() { for(;;){} }
void sceHidControlGetDeviceName() { for(;;){} }
void sceHidControlGetJediExtensionUnitInfo() { for(;;){} }
void sceHidControlGetJediState() { for(;;){} }
void sceHidControlGetSparkState() { for(;;){} }
void sceHidControlInit() { for(;;){} }
void sceHidControlSetApplicationFocus() { for(;;){} }
void sceHidControlSetHandleState() { for(;;){} }
void sceHidControlSetJediAudioOutPath() { for(;;){} }
void sceHidControlSetJediVolumeGain() { for(;;){} }
void sceHidControlSetProcessFocus() { for(;;){} }
void sceHidControlSetRevokeList() { for(;;){} }
void sceHidControlSetUserColor() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}