/* Source generated by crazyvoids source generating tool **/
#include "libSceAbstractFacebook.h"

void _ZN15AbstractStorage14FacebookFolder10NewContentERKSbIcSt11char_traitsIcENS_8StlAllocIcEEEPSt10shared_ptrINS_7ContentEE() { for(;;){} }
void _ZN15AbstractStorage14FacebookFolder11SetMetadataEPN23sceMetadataReaderWriter8MetadataE() { for(;;){} }
void _ZN15AbstractStorage14FacebookFolder12create_albumEv() { for(;;){} }
void _ZN15AbstractStorage14FacebookFolder12readExternalESt10shared_ptrINS_7ContentEE() { for(;;){} }
void _ZN15AbstractStorage14FacebookFolder12RemoveFolderERKSbIcSt11char_traitsIcENS_8StlAllocIcEEEb() { for(;;){} }
void _ZN15AbstractStorage14FacebookFolder13ParseMetadataEPN23sceMetadataReaderWriter8MetadataES3_() { for(;;){} }
void _ZN15AbstractStorage14FacebookFolder13RemoveContentERKSbIcSt11char_traitsIcENS_8StlAllocIcEEE() { for(;;){} }
void _ZN15AbstractStorage14FacebookFolder13writeExternalESt10shared_ptrINS_7ContentEE() { for(;;){} }
void _ZN15AbstractStorage14FacebookFolder4OpenENS_8ItemTypeE() { for(;;){} }
void _ZN15AbstractStorage14FacebookFolder5CloseEv() { for(;;){} }
void _ZN15AbstractStorage14FacebookFolder6RemoveEb() { for(;;){} }
void _ZN15AbstractStorage14FacebookFolder8NextItemEPSt10shared_ptrINS_4ItemEE() { for(;;){} }
void _ZN15AbstractStorage14FacebookFolder9NewFolderERKSbIcSt11char_traitsIcENS_8StlAllocIcEEEPSt10shared_ptrINS_6FolderEE() { for(;;){} }
void _ZN15AbstractStorage14FacebookFolderC1ERKSbIcSt11char_traitsIcENS_8StlAllocIcEEEb() { for(;;){} }
void _ZN15AbstractStorage14FacebookFolderC2ERKSbIcSt11char_traitsIcENS_8StlAllocIcEEEb() { for(;;){} }
void _ZN15AbstractStorage14FacebookFolderD0Ev() { for(;;){} }
void _ZN15AbstractStorage14FacebookFolderD1Ev() { for(;;){} }
void _ZN15AbstractStorage14FacebookFolderD2Ev() { for(;;){} }
void _ZN15AbstractStorage15FacebookContent11SetMetadataEPN23sceMetadataReaderWriter8MetadataE() { for(;;){} }
void _ZN15AbstractStorage15FacebookContent12readExternalESt10shared_ptrINS_7ContentEE() { for(;;){} }
void _ZN15AbstractStorage15FacebookContent13ParseMetadataEPN23sceMetadataReaderWriter8MetadataES3_() { for(;;){} }
void _ZN15AbstractStorage15FacebookContent13writeExternalESt10shared_ptrINS_7ContentEE() { for(;;){} }
void _ZN15AbstractStorage15FacebookContent4OpenEit() { for(;;){} }
void _ZN15AbstractStorage15FacebookContent4ReadEPvlPl() { for(;;){} }
void _ZN15AbstractStorage15FacebookContent5CloseEv() { for(;;){} }
void _ZN15AbstractStorage15FacebookContent5FlushEv() { for(;;){} }
void _ZN15AbstractStorage15FacebookContent5WriteEPKvlPl() { for(;;){} }
void _ZN15AbstractStorage15FacebookContent6RemoveEv() { for(;;){} }
void _ZN15AbstractStorage15FacebookContent6RenameERKSbIcSt11char_traitsIcENS_8StlAllocIcEEE() { for(;;){} }
void _ZN15AbstractStorage15FacebookContent8SeekByteEliPl() { for(;;){} }
void _ZN15AbstractStorage15FacebookContent8SeekTimeElPl() { for(;;){} }
void _ZN15AbstractStorage15FacebookContentC1ERKSbIcSt11char_traitsIcENS_8StlAllocIcEEEbb() { for(;;){} }
void _ZN15AbstractStorage15FacebookContentC2ERKSbIcSt11char_traitsIcENS_8StlAllocIcEEEbb() { for(;;){} }
void _ZN15AbstractStorage15FacebookContentD0Ev() { for(;;){} }
void _ZN15AbstractStorage15FacebookContentD1Ev() { for(;;){} }
void _ZN15AbstractStorage15FacebookContentD2Ev() { for(;;){} }
void _ZN15AbstractStorage15FacebookService13SearchStorageEv() { for(;;){} }
void _ZN15AbstractStorage15FacebookService23create_storage_instanceERKSbIcSt11char_traitsIcENS_8StlAllocIcEEE() { for(;;){} }
void _ZN15AbstractStorage15FacebookService4StopEv() { for(;;){} }
void _ZN15AbstractStorage15FacebookService5StartEv() { for(;;){} }
void _ZN15AbstractStorage15FacebookServiceC1Ev() { for(;;){} }
void _ZN15AbstractStorage15FacebookServiceC2Ev() { for(;;){} }
void _ZN15AbstractStorage15FacebookServiceD0Ev() { for(;;){} }
void _ZN15AbstractStorage15FacebookServiceD1Ev() { for(;;){} }
void _ZN15AbstractStorage15FacebookServiceD2Ev() { for(;;){} }
void _ZN15AbstractStorage15FacebookStorage11DeserializeESt10shared_ptrINS_7ContentEEPS1_INS_4ItemEE() { for(;;){} }
void _ZN15AbstractStorage15FacebookStorage11SetMetadataEPN23sceMetadataReaderWriter8MetadataE() { for(;;){} }
void _ZN15AbstractStorage15FacebookStorage13GetRootFolderEPSt10shared_ptrINS_6FolderEE() { for(;;){} }
void _ZN15AbstractStorage15FacebookStorage14GetStorageSizeEPlS1_S1_() { for(;;){} }
void _ZN15AbstractStorage15FacebookStorage15CreateRecursiveERKSbIcSt11char_traitsIcENS_8StlAllocIcEEENS_8ItemTypeEPSt10shared_ptrINS_4ItemEE() { for(;;){} }
void _ZN15AbstractStorage15FacebookStorage15RemoveRecursiveERKSbIcSt11char_traitsIcENS_8StlAllocIcEEE() { for(;;){} }
void _ZN15AbstractStorage15FacebookStorage7GetItemERKSbIcSt11char_traitsIcENS_8StlAllocIcEEEPSt10shared_ptrINS_4ItemEE() { for(;;){} }
void _ZN15AbstractStorage15FacebookStorage7IsExistERKSbIcSt11char_traitsIcENS_8StlAllocIcEEE() { for(;;){} }
void _ZN15AbstractStorage15FacebookStorage9SerializeESt10shared_ptrINS_7ContentEES1_INS_4ItemEE() { for(;;){} }
void _ZN15AbstractStorage15FacebookStorageC1ERKSbIcSt11char_traitsIcENS_8StlAllocIcEEE() { for(;;){} }
void _ZN15AbstractStorage15FacebookStorageC2ERKSbIcSt11char_traitsIcENS_8StlAllocIcEEE() { for(;;){} }
void _ZN15AbstractStorage15FacebookStorageD0Ev() { for(;;){} }
void _ZN15AbstractStorage15FacebookStorageD1Ev() { for(;;){} }
void _ZN15AbstractStorage15FacebookStorageD2Ev() { for(;;){} }
void _ZNK15AbstractStorage14FacebookFolder10GetServiceEv() { for(;;){} }
void _ZNK15AbstractStorage14FacebookFolder13GetCapabilityEv() { for(;;){} }
void _ZNK15AbstractStorage14FacebookFolder7GetStatEPNS_4StatE() { for(;;){} }
void _ZNK15AbstractStorage15FacebookContent10GetServiceEv() { for(;;){} }
void _ZNK15AbstractStorage15FacebookContent13GetCapabilityEv() { for(;;){} }
void _ZNK15AbstractStorage15FacebookContent7GetStatEPNS_4StatE() { for(;;){} }
void _ZNK15AbstractStorage15FacebookService14GetServiceTypeEv() { for(;;){} }
void _ZNK15AbstractStorage15FacebookStorage10GetServiceEv() { for(;;){} }
void _ZNK15AbstractStorage15FacebookStorage13GetCapabilityEv() { for(;;){} }
void _ZNK15AbstractStorage15FacebookStorage7GetStatEPNS_4StatE() { for(;;){} }
void _ZNKSt15_Ref_count_base12_Get_deleterERKSt9type_info() { for(;;){} }
void _ZNSbIcSt11char_traitsIcEN15AbstractStorage8StlAllocIcEEE6assignERKS4_mm() { for(;;){} }
void _ZNSt10_Ref_countIN15AbstractStorage14FacebookFolderEE12_Delete_thisEv() { for(;;){} }
void _ZNSt10_Ref_countIN15AbstractStorage14FacebookFolderEE8_DestroyEv() { for(;;){} }
void _ZNSt10_Ref_countIN15AbstractStorage14FacebookFolderEED0Ev() { for(;;){} }
void _ZNSt10_Ref_countIN15AbstractStorage14FacebookFolderEED1Ev() { for(;;){} }
void _ZNSt10_Ref_countIN15AbstractStorage15FacebookContentEE12_Delete_thisEv() { for(;;){} }
void _ZNSt10_Ref_countIN15AbstractStorage15FacebookContentEE8_DestroyEv() { for(;;){} }
void _ZNSt10_Ref_countIN15AbstractStorage15FacebookContentEED0Ev() { for(;;){} }
void _ZNSt10_Ref_countIN15AbstractStorage15FacebookContentEED1Ev() { for(;;){} }
void _ZNSt6vectorIN15AbstractStorage19FacebookFolderEntryESaIS1_EE11_ReallocateEm() { for(;;){} }
void _ZNSt6vectorIN15AbstractStorage19FacebookFolderEntryESaIS1_EE9push_backEOS1_() { for(;;){} }
void _ZTVN15AbstractStorage14FacebookFolderE() { for(;;){} }
void _ZTVN15AbstractStorage15FacebookContentE() { for(;;){} }
void _ZTVN15AbstractStorage15FacebookServiceE() { for(;;){} }
void _ZTVN15AbstractStorage15FacebookStorageE() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}