/* Source generated by crazyvoids source generating tool **/
#include "libSceNpTusCompat.h"

void sceNpTssCreateNpTitleCtx() { for(;;){} }
void sceNpTusAddAndGetVariable() { for(;;){} }
void sceNpTusAddAndGetVariableAsync() { for(;;){} }
void sceNpTusAddAndGetVariableVUser() { for(;;){} }
void sceNpTusAddAndGetVariableVUserAsync() { for(;;){} }
void sceNpTusCreateNpTitleCtx() { for(;;){} }
void sceNpTusDeleteMultiSlotData() { for(;;){} }
void sceNpTusDeleteMultiSlotDataAsync() { for(;;){} }
void sceNpTusDeleteMultiSlotVariable() { for(;;){} }
void sceNpTusDeleteMultiSlotVariableAsync() { for(;;){} }
void sceNpTusGetData() { for(;;){} }
void sceNpTusGetDataAsync() { for(;;){} }
void sceNpTusGetDataVUser() { for(;;){} }
void sceNpTusGetDataVUserAsync() { for(;;){} }
void sceNpTusGetFriendsDataStatus() { for(;;){} }
void sceNpTusGetFriendsDataStatusAsync() { for(;;){} }
void sceNpTusGetFriendsVariable() { for(;;){} }
void sceNpTusGetFriendsVariableAsync() { for(;;){} }
void sceNpTusGetMultiSlotDataStatus() { for(;;){} }
void sceNpTusGetMultiSlotDataStatusAsync() { for(;;){} }
void sceNpTusGetMultiSlotDataStatusVUser() { for(;;){} }
void sceNpTusGetMultiSlotDataStatusVUserAsync() { for(;;){} }
void sceNpTusGetMultiSlotVariable() { for(;;){} }
void sceNpTusGetMultiSlotVariableAsync() { for(;;){} }
void sceNpTusGetMultiSlotVariableVUser() { for(;;){} }
void sceNpTusGetMultiSlotVariableVUserAsync() { for(;;){} }
void sceNpTusGetMultiUserDataStatus() { for(;;){} }
void sceNpTusGetMultiUserDataStatusAsync() { for(;;){} }
void sceNpTusGetMultiUserDataStatusVUser() { for(;;){} }
void sceNpTusGetMultiUserDataStatusVUserAsync() { for(;;){} }
void sceNpTusGetMultiUserVariable() { for(;;){} }
void sceNpTusGetMultiUserVariableAsync() { for(;;){} }
void sceNpTusGetMultiUserVariableVUser() { for(;;){} }
void sceNpTusGetMultiUserVariableVUserAsync() { for(;;){} }
void sceNpTusSetData() { for(;;){} }
void sceNpTusSetDataAsync() { for(;;){} }
void sceNpTusSetDataVUser() { for(;;){} }
void sceNpTusSetDataVUserAsync() { for(;;){} }
void sceNpTusSetMultiSlotVariable() { for(;;){} }
void sceNpTusSetMultiSlotVariableAsync() { for(;;){} }
void sceNpTusTryAndSetVariable() { for(;;){} }
void sceNpTusTryAndSetVariableAsync() { for(;;){} }
void sceNpTusTryAndSetVariableVUser() { for(;;){} }
void sceNpTusTryAndSetVariableVUserAsync() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}