/* Source generated by crazyvoids source generating tool **/
#include "libSceNpUniversalDataSystem.h"

void sceNpUniversalDataSystemAbortHandle() { for(;;){} }
void sceNpUniversalDataSystemCreateContext() { for(;;){} }
void sceNpUniversalDataSystemCreateHandle() { for(;;){} }
void sceNpUniversalDataSystemDestroyContext() { for(;;){} }
void sceNpUniversalDataSystemDestroyHandle() { for(;;){} }
void sceNpUniversalDataSystemIntAbortHandle() { for(;;){} }
void sceNpUniversalDataSystemIntCreateContext() { for(;;){} }
void sceNpUniversalDataSystemIntCreateHandle() { for(;;){} }
void sceNpUniversalDataSystemIntDeleteAllRecord() { for(;;){} }
void sceNpUniversalDataSystemIntDestroyContext() { for(;;){} }
void sceNpUniversalDataSystemIntDestroyHandle() { for(;;){} }
void sceNpUniversalDataSystemIntPostRecord() { for(;;){} }
void sceNpUniversalDataSystemPostRecord() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}