/* Source generated by crazyvoids source generating tool **/
#include "libSceNpSnsFacebookDialog.h"

void sceNpSnsFacebookDialogClose() { for(;;){} }
void sceNpSnsFacebookDialogGetResult() { for(;;){} }
void sceNpSnsFacebookDialogGetStatus() { for(;;){} }
void sceNpSnsFacebookDialogInitialize() { for(;;){} }
void sceNpSnsFacebookDialogOpen() { for(;;){} }
void sceNpSnsFacebookDialogTerminate() { for(;;){} }
void sceNpSnsFacebookDialogUpdateStatus() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}