/* Source generated by crazyvoids source generating tool **/
#include "libSceVideoNativeExtEssential.h"

void sceVideoNativeExtEssential_CreateDecInstance() { for(;;){} }
void sceVideoNativeExtEssential_DestroyDecInstance() { for(;;){} }
void sceVideoNativeExtEssential_Finalize() { for(;;){} }
void sceVideoNativeExtEssential_Initialize() { for(;;){} }
void sceVideoNativeExtEssential_IsInit() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}