/* Source generated by crazyvoids source generating tool **/
#include "libSceScreenShot.h"

void _Z5dummyv() { for(;;){} }
void sceScreenShotCapture() { for(;;){} }
void sceScreenShotDisable() { for(;;){} }
void sceScreenShotDisableNotification() { for(;;){} }
void sceScreenShotEnable() { for(;;){} }
void sceScreenShotEnableNotification() { for(;;){} }
void sceScreenShotGetAppInfo() { for(;;){} }
void sceScreenShotGetDrcParam() { for(;;){} }
void sceScreenShotIsDisabled() { for(;;){} }
void sceScreenShotIsVshScreenCaptureDisabled() { for(;;){} }
void sceScreenShotSetOverlayImage() { for(;;){} }
void sceScreenShotSetOverlayImageWithOrigin() { for(;;){} }
void sceScreenShotSetParam() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}