/* Source generated by crazyvoids source generating tool **/
#include "libSceShareFactoryUtil.h"

void sceShareFactoryUtilBackToGameFromShareFactory() { for(;;){} }
void sceShareFactoryUtilGetLaunchStatus() { for(;;){} }
void sceShareFactoryUtilGetLaunchStatusOfShareFactory() { for(;;){} }
void sceShareFactoryUtilInitialize() { for(;;){} }
void sceShareFactoryUtilLaunchShareFactory() { for(;;){} }
void sceShareFactoryUtilTerminate() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}