/* Source generated by crazyvoids source generating tool **/
#include "libSceNpSignaling.h"

void sceNpSignalingActivateConnection() { for(;;){} }
void sceNpSignalingActivateConnectionA() { for(;;){} }
void sceNpSignalingCancelPeerNetInfo() { for(;;){} }
void sceNpSignalingCreateContext() { for(;;){} }
void sceNpSignalingCreateContextA() { for(;;){} }
void sceNpSignalingDeactivateConnection() { for(;;){} }
void sceNpSignalingDeleteContext() { for(;;){} }
void sceNpSignalingGetConnectionFromNpId() { for(;;){} }
void sceNpSignalingGetConnectionFromPeerAddress() { for(;;){} }
void sceNpSignalingGetConnectionFromPeerAddressA() { for(;;){} }
void sceNpSignalingGetConnectionInfo() { for(;;){} }
void sceNpSignalingGetConnectionInfoA() { for(;;){} }
void sceNpSignalingGetConnectionStatistics() { for(;;){} }
void sceNpSignalingGetConnectionStatus() { for(;;){} }
void sceNpSignalingGetContextOption() { for(;;){} }
void sceNpSignalingGetLocalNetInfo() { for(;;){} }
void sceNpSignalingGetMemoryInfo() { for(;;){} }
void sceNpSignalingGetPeerNetInfo() { for(;;){} }
void sceNpSignalingGetPeerNetInfoA() { for(;;){} }
void sceNpSignalingGetPeerNetInfoResult() { for(;;){} }
void sceNpSignalingInitialize() { for(;;){} }
void sceNpSignalingSetContextOption() { for(;;){} }
void sceNpSignalingTerminate() { for(;;){} }
void sceNpSignalingTerminateConnection() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}