/* Source generated by crazyvoids source generating tool **/
#include "libSceGnmDebugReset.h"

void sceGnmDebugReset() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}