/* Source generated by crazyvoids source generating tool **/
#include "libSceNpProfileDialog.h"

void sceNpProfileDialogClose() { for(;;){} }
void sceNpProfileDialogGetResult() { for(;;){} }
void sceNpProfileDialogGetStatus() { for(;;){} }
void sceNpProfileDialogInitialize() { for(;;){} }
void sceNpProfileDialogOpen() { for(;;){} }
void sceNpProfileDialogOpenA() { for(;;){} }
void sceNpProfileDialogTerminate() { for(;;){} }
void sceNpProfileDialogUpdateStatus() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}