/* Source generated by crazyvoids source generating tool **/
#include "libSceCoredump.h"

void sceCoredumpAttachMemoryRegion() { for(;;){} }
void sceCoredumpAttachMemoryRegionAsUserFile() { for(;;){} }
void sceCoredumpAttachUserFile() { for(;;){} }
void sceCoredumpConfigDumpMode() { for(;;){} }
void sceCoredumpDebugTextOut() { for(;;){} }
void sceCoredumpGetStopInfoCpu() { for(;;){} }
void sceCoredumpGetStopInfoGpu() { for(;;){} }
void sceCoredumpGetThreadContextInfo() { for(;;){} }
void sceCoredumpInternalGetThreadContextInfo() { for(;;){} }
void sceCoredumpRegisterCoredumpHandler() { for(;;){} }
void sceCoredumpSetUserDataType() { for(;;){} }
void sceCoredumpUnregisterCoredumpHandler() { for(;;){} }
void sceCoredumpWriteUserData() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}