/* Source generated by crazyvoids source generating tool **/
#include "libSceScreenShotDrc.h"

void sceScreenShotSetDrcParam() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}