/* Source generated by crazyvoids source generating tool **/
#include "libSceNetCtl.h"

void sceNetCtlCheckCallback() { for(;;){} }
void sceNetCtlCheckCallbackForLibIpcInt() { for(;;){} }
void sceNetCtlClearEventForLibIpcInt() { for(;;){} }
void sceNetCtlClearEventIpcInt() { for(;;){} }
void sceNetCtlConnectConfIpcInt() { for(;;){} }
void sceNetCtlConnectIpcInt() { for(;;){} }
void sceNetCtlConnectWithRetryIpcInt() { for(;;){} }
void sceNetCtlDisableBandwidthManagementIpcInt() { for(;;){} }
void sceNetCtlDisconnectIpcInt() { for(;;){} }
void sceNetCtlEnableBandwidthManagementIpcInt() { for(;;){} }
void sceNetCtlGetBandwidthInfoIpcInt() { for(;;){} }
void sceNetCtlGetEtherLinkMode() { for(;;){} }
void sceNetCtlGetIfStat() { for(;;){} }
void sceNetCtlGetInfo() { for(;;){} }
void sceNetCtlGetInfoIpcInt() { for(;;){} }
void sceNetCtlGetNatInfo() { for(;;){} }
void sceNetCtlGetNatInfoIpcInt() { for(;;){} }
void sceNetCtlGetNetEvConfigInfoIpcInt() { for(;;){} }
void sceNetCtlGetResult() { for(;;){} }
void sceNetCtlGetResultIpcInt() { for(;;){} }
void sceNetCtlGetScanInfoBssidForSsidListScanIpcInt() { for(;;){} }
void sceNetCtlGetScanInfoBssidIpcInt() { for(;;){} }
void sceNetCtlGetScanInfoByBssidIpcInt() { for(;;){} }
void sceNetCtlGetScanInfoForSsidListScanIpcInt() { for(;;){} }
void sceNetCtlGetScanInfoForSsidScanIpcInt() { for(;;){} }
void sceNetCtlGetState() { for(;;){} }
void sceNetCtlGetState2IpcInt() { for(;;){} }
void sceNetCtlGetStateIpcInt() { for(;;){} }
void sceNetCtlGetWifiType() { for(;;){} }
void sceNetCtlInit() { for(;;){} }
void sceNetCtlIsBandwidthManagementEnabledIpcInt() { for(;;){} }
void sceNetCtlRegisterCallback() { for(;;){} }
void sceNetCtlRegisterCallbackForLibIpcInt() { for(;;){} }
void sceNetCtlRegisterCallbackIpcInt() { for(;;){} }
void sceNetCtlScanIpcInt() { for(;;){} }
void sceNetCtlSetErrorNotificationEnabledIpcInt() { for(;;){} }
void sceNetCtlSetStunWithPaddingFlagIpcInt() { for(;;){} }
void sceNetCtlTerm() { for(;;){} }
void sceNetCtlUnregisterCallback() { for(;;){} }
void sceNetCtlUnregisterCallbackForLibIpcInt() { for(;;){} }
void sceNetCtlUnregisterCallbackIpcInt() { for(;;){} }
void sceNetCtlUnsetStunWithPaddingFlagIpcInt() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}