/* Source generated by crazyvoids source generating tool **/
#include "libSceMetadataReaderWriter.h"

void _ZN23sceMetadataReaderWriter10initializeEv() { for(;;){} }
void _ZN23sceMetadataReaderWriter11getMimeTypeERKSsRSt6vectorIjSaIjEE() { for(;;){} }
void _ZN23sceMetadataReaderWriter12readMetadataERKSsRKNS_8MetadataEjRS2_() { for(;;){} }
void _ZN23sceMetadataReaderWriter13writeMetadataERKSsRKNS_8MetadataEj() { for(;;){} }
void _ZN23sceMetadataReaderWriter13writeMetadataERKSsRKNS_8MetadataEjPS2_() { for(;;){} }
void _ZN23sceMetadataReaderWriter15ParserInterfaceC1ERKS0_() { for(;;){} }
void _ZN23sceMetadataReaderWriter15ParserInterfaceC2ERKS0_() { for(;;){} }
void _ZN23sceMetadataReaderWriter16extractThumbnailERKSsjRNS_9ThumbnailE() { for(;;){} }
void _ZN23sceMetadataReaderWriter17getParserInfoListERSt6vectorINS_10ParserInfoESaIS1_EE() { for(;;){} }
void _ZN23sceMetadataReaderWriter18registerParserInfoERKSt6vectorINS_10ParserInfoESaIS1_EE() { for(;;){} }
void _ZN23sceMetadataReaderWriter20unregisterParserInfoEv() { for(;;){} }
void _ZN23sceMetadataReaderWriter23registerParserInterfaceEjRKNS_15ParserInterfaceE() { for(;;){} }
void _ZN23sceMetadataReaderWriter5ValueaSERS0_() { for(;;){} }
void _ZN23sceMetadataReaderWriter8finalizeEv() { for(;;){} }
void _ZN23sceMetadataReaderWriter8Metadata11deleteFieldERKSs() { for(;;){} }
void _ZN23sceMetadataReaderWriter8Metadata11DeserializeERN3sce4Json5ValueERS0_() { for(;;){} }
void _ZN23sceMetadataReaderWriter8Metadata15iterateAllFieldEPFiRKSsRKNS_5ValueEbE() { for(;;){} }
void _ZN23sceMetadataReaderWriter8Metadata8getFieldEiRSsRNS_5ValueERb() { for(;;){} }
void _ZN23sceMetadataReaderWriter8Metadata8setFieldERKSs() { for(;;){} }
void _ZN23sceMetadataReaderWriter8Metadata8setFieldERKSsRKNS_5ValueE() { for(;;){} }
void _ZN23sceMetadataReaderWriter8Metadata9SerializeERS0_RN3sce4Json5ValueE() { for(;;){} }
void _ZN23sceMetadataReaderWriter8MetadataaSERKS0_() { for(;;){} }
void _ZN23sceMetadataReaderWriter8MetadataC1EPFPvmEPFvS1_E() { for(;;){} }
void _ZN23sceMetadataReaderWriter8MetadataC1ERKS0_() { for(;;){} }
void _ZN23sceMetadataReaderWriter8MetadataC1ERKS0_PFPvmEPFvS3_E() { for(;;){} }
void _ZN23sceMetadataReaderWriter8MetadataC1Ev() { for(;;){} }
void _ZN23sceMetadataReaderWriter8MetadataC2EPFPvmEPFvS1_E() { for(;;){} }
void _ZN23sceMetadataReaderWriter8MetadataC2ERKS0_() { for(;;){} }
void _ZN23sceMetadataReaderWriter8MetadataC2ERKS0_PFPvmEPFvS3_E() { for(;;){} }
void _ZN23sceMetadataReaderWriter8MetadataC2Ev() { for(;;){} }
void _ZN23sceMetadataReaderWriter8MetadataD0Ev() { for(;;){} }
void _ZN23sceMetadataReaderWriter8MetadataD1Ev() { for(;;){} }
void _ZN23sceMetadataReaderWriter8MetadataD2Ev() { for(;;){} }
void _ZNK23sceMetadataReaderWriter8Metadata13getFieldCountEv() { for(;;){} }
void _ZNK23sceMetadataReaderWriter8Metadata8getFieldEiRSsRNS_5ValueE() { for(;;){} }
void _ZNK23sceMetadataReaderWriter8Metadata8getValueERKSsRNS_5ValueE() { for(;;){} }
void _ZNK23sceMetadataReaderWriter8Metadata9dumpValueEv() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}