#pragma once

// Params should go here....

// code goes here
// example ABI_SYSV int test(int input);
void _ZN23sceMetadataReaderWriter10initializeEv();
void _ZN23sceMetadataReaderWriter11getMimeTypeERKSsRSt6vectorIjSaIjEE();
void _ZN23sceMetadataReaderWriter12readMetadataERKSsRKNS_8MetadataEjRS2_();
void _ZN23sceMetadataReaderWriter13writeMetadataERKSsRKNS_8MetadataEj();
void _ZN23sceMetadataReaderWriter13writeMetadataERKSsRKNS_8MetadataEjPS2_();
void _ZN23sceMetadataReaderWriter15ParserInterfaceC1ERKS0_();
void _ZN23sceMetadataReaderWriter15ParserInterfaceC2ERKS0_();
void _ZN23sceMetadataReaderWriter16extractThumbnailERKSsjRNS_9ThumbnailE();
void _ZN23sceMetadataReaderWriter17getParserInfoListERSt6vectorINS_10ParserInfoESaIS1_EE();
void _ZN23sceMetadataReaderWriter18registerParserInfoERKSt6vectorINS_10ParserInfoESaIS1_EE();
void _ZN23sceMetadataReaderWriter20unregisterParserInfoEv();
void _ZN23sceMetadataReaderWriter23registerParserInterfaceEjRKNS_15ParserInterfaceE();
void _ZN23sceMetadataReaderWriter5ValueaSERS0_();
void _ZN23sceMetadataReaderWriter8finalizeEv();
void _ZN23sceMetadataReaderWriter8Metadata11deleteFieldERKSs();
void _ZN23sceMetadataReaderWriter8Metadata11DeserializeERN3sce4Json5ValueERS0_();
void _ZN23sceMetadataReaderWriter8Metadata15iterateAllFieldEPFiRKSsRKNS_5ValueEbE();
void _ZN23sceMetadataReaderWriter8Metadata8getFieldEiRSsRNS_5ValueERb();
void _ZN23sceMetadataReaderWriter8Metadata8setFieldERKSs();
void _ZN23sceMetadataReaderWriter8Metadata8setFieldERKSsRKNS_5ValueE();
void _ZN23sceMetadataReaderWriter8Metadata9SerializeERS0_RN3sce4Json5ValueE();
void _ZN23sceMetadataReaderWriter8MetadataaSERKS0_();
void _ZN23sceMetadataReaderWriter8MetadataC1EPFPvmEPFvS1_E();
void _ZN23sceMetadataReaderWriter8MetadataC1ERKS0_();
void _ZN23sceMetadataReaderWriter8MetadataC1ERKS0_PFPvmEPFvS3_E();
void _ZN23sceMetadataReaderWriter8MetadataC1Ev();
void _ZN23sceMetadataReaderWriter8MetadataC2EPFPvmEPFvS1_E();
void _ZN23sceMetadataReaderWriter8MetadataC2ERKS0_();
void _ZN23sceMetadataReaderWriter8MetadataC2ERKS0_PFPvmEPFvS3_E();
void _ZN23sceMetadataReaderWriter8MetadataC2Ev();
void _ZN23sceMetadataReaderWriter8MetadataD0Ev();
void _ZN23sceMetadataReaderWriter8MetadataD1Ev();
void _ZN23sceMetadataReaderWriter8MetadataD2Ev();
void _ZNK23sceMetadataReaderWriter8Metadata13getFieldCountEv();
void _ZNK23sceMetadataReaderWriter8Metadata8getFieldEiRSsRNS_5ValueE();
void _ZNK23sceMetadataReaderWriter8Metadata8getValueERKSsRNS_5ValueE();
void _ZNK23sceMetadataReaderWriter8Metadata9dumpValueEv();
