/* Source generated by crazyvoids source generating tool **/
#include "libSceSystemService.h"

void sceSystemServiceAcquireFb0() { for(;;){} }
void sceSystemServiceAddLocalProcess() { for(;;){} }
void sceSystemServiceAddLocalProcessForPsmKit() { for(;;){} }
void sceSystemServiceChangeAcpClock() { for(;;){} }
void sceSystemServiceChangeCpuClock() { for(;;){} }
void sceSystemServiceChangeGpuClock() { for(;;){} }
void sceSystemServiceChangeMemoryClock() { for(;;){} }
void sceSystemServiceChangeMemoryClockToBaseMode() { for(;;){} }
void sceSystemServiceChangeMemoryClockToDefault() { for(;;){} }
void sceSystemServiceChangeMemoryClockToMultiMediaMode() { for(;;){} }
void sceSystemServiceChangeNumberOfGpuCu() { for(;;){} }
void sceSystemServiceChangeSamuClock() { for(;;){} }
void sceSystemServiceChangeUvdClock() { for(;;){} }
void sceSystemServiceChangeVceClock() { for(;;){} }
void sceSystemServiceDisableMusicPlayer() { for(;;){} }
void sceSystemServiceDisablePersonalEyeToEyeDistanceSetting() { for(;;){} }
void sceSystemServiceDisableSuspendConfirmationDialog() { for(;;){} }
void sceSystemServiceEnablePersonalEyeToEyeDistanceSetting() { for(;;){} }
void sceSystemServiceEnableSuspendConfirmationDialog() { for(;;){} }
void sceSystemServiceGetAppFocusedAppStatus() { for(;;){} }
void sceSystemServiceGetAppIdOfBigApp() { for(;;){} }
void sceSystemServiceGetAppIdOfMiniApp() { for(;;){} }
void sceSystemServiceGetAppStatus() { for(;;){} }
void sceSystemServiceGetAppType() { for(;;){} }
void sceSystemServiceGetDisplaySafeAreaInfo() { for(;;){} }
void sceSystemServiceGetEventForDaemon() { for(;;){} }
void sceSystemServiceGetGpuLoadEmulationMode() { for(;;){} }
void sceSystemServiceGetLocalProcessStatusList() { for(;;){} }
void sceSystemServiceGetParentSocket() { for(;;){} }
void sceSystemServiceGetParentSocketForPsmKit() { for(;;){} }
void sceSystemServiceGetPSButtonEvent() { for(;;){} }
void sceSystemServiceGetRenderingMode() { for(;;){} }
void sceSystemServiceGetStatus() { for(;;){} }
void sceSystemServiceGetTitleWorkaroundInfo() { for(;;){} }
void sceSystemServiceGetVersionNumberOfCameraCalibrationData() { for(;;){} }
void sceSystemServiceHideSplashScreen() { for(;;){} }
void sceSystemServiceIsAppSuspended() { for(;;){} }
void sceSystemServiceIsBgmPlaying() { for(;;){} }
void sceSystemServiceIsEyeToEyeDistanceAdjusted() { for(;;){} }
void sceSystemServiceIsScreenSaverOn() { for(;;){} }
void sceSystemServiceIsShellUiFgAndGameBgCpuMode() { for(;;){} }
void sceSystemServiceKillApp() { for(;;){} }
void sceSystemServiceKillLocalProcess() { for(;;){} }
void sceSystemServiceKillLocalProcessForPsmKit() { for(;;){} }
void sceSystemServiceLaunchApp() { for(;;){} }
void sceSystemServiceLaunchEventDetails() { for(;;){} }
void sceSystemServiceLaunchTournamentsTeamProfile() { for(;;){} }
void sceSystemServiceLaunchWebBrowser() { for(;;){} }
void sceSystemServiceLoadExec() { for(;;){} }
void sceSystemServiceNavigateToAnotherApp() { for(;;){} }
void sceSystemServiceNavigateToGoBack() { for(;;){} }
void sceSystemServiceNavigateToGoBackWithValue() { for(;;){} }
void sceSystemServiceNavigateToGoHome() { for(;;){} }
void sceSystemServiceParamGetInt() { for(;;){} }
void sceSystemServiceParamGetString() { for(;;){} }
void sceSystemServicePowerTick() { for(;;){} }
void sceSystemServiceRaiseExceptionLocalProcess() { for(;;){} }
void sceSystemServiceReceiveEvent() { for(;;){} }
void sceSystemServiceReenableMusicPlayer() { for(;;){} }
void sceSystemServiceRegisterDaemon() { for(;;){} }
void sceSystemServiceReleaseFb0() { for(;;){} }
void sceSystemServiceReportAbnormalTermination() { for(;;){} }
void sceSystemServiceRequestCameraCalibration() { for(;;){} }
void sceSystemServiceRequestToChangeRenderingMode() { for(;;){} }
void sceSystemServiceResumeLocalProcess() { for(;;){} }
void sceSystemServiceSetControllerFocusPermission() { for(;;){} }
void sceSystemServiceSetGpuLoadEmulationMode() { for(;;){} }
void sceSystemServiceSetOutOfVrPlayAreaFlag() { for(;;){} }
void sceSystemServiceSetOutOfVrPlayZoneWarning() { for(;;){} }
void sceSystemServiceShowControllerSettings() { for(;;){} }
void sceSystemServiceShowDisplaySafeAreaSettings() { for(;;){} }
void sceSystemServiceShowEyeToEyeDistanceSetting() { for(;;){} }
void sceSystemServiceSuspendBackgroundApp() { for(;;){} }
void sceSystemServiceSuspendLocalProcess() { for(;;){} }
void sceSystemServiceTickVideoPlayback() { for(;;){} }
void sceSystemServiceTurnOffScreenSaver() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}