/* Source generated by crazyvoids source generating tool **/
#include "libSceAudioOut.h"

void sceAudioOutA3dControl() { for(;;){} }
void sceAudioOutA3dExit() { for(;;){} }
void sceAudioOutA3dInit() { for(;;){} }
void sceAudioOutAttachToApplicationByPid() { for(;;){} }
void sceAudioOutChangeAppModuleState() { for(;;){} }
void sceAudioOutClose() { for(;;){} }
void sceAudioOutDetachFromApplicationByPid() { for(;;){} }
void sceAudioOutExConfigureOutputMode() { for(;;){} }
void sceAudioOutExGetSystemInfo() { for(;;){} }
void sceAudioOutExPtClose() { for(;;){} }
void sceAudioOutExPtGetLastOutputTime() { for(;;){} }
void sceAudioOutExPtOpen() { for(;;){} }
void sceAudioOutExSystemInfoIsSupportedAudioOutExMode() { for(;;){} }
void sceAudioOutGetFocusEnablePid() { for(;;){} }
void sceAudioOutGetHandleStatusInfo() { for(;;){} }
void sceAudioOutGetInfo() { for(;;){} }
void sceAudioOutGetInfoOpenNum() { for(;;){} }
void sceAudioOutGetLastOutputTime() { for(;;){} }
void sceAudioOutGetPortState() { for(;;){} }
void sceAudioOutGetSimulatedHandleStatusInfo() { for(;;){} }
void sceAudioOutGetSimulatedHandleStatusInfo2() { for(;;){} }
void sceAudioOutGetSparkVss() { for(;;){} }
void sceAudioOutGetSystemState() { for(;;){} }
void sceAudioOutInit() { for(;;){} }
void sceAudioOutInitIpmiGetSession() { for(;;){} }
void sceAudioOutMasteringGetState() { for(;;){} }
void sceAudioOutMasteringInit() { for(;;){} }
void sceAudioOutMasteringSetParam() { for(;;){} }
void sceAudioOutMasteringTerm() { for(;;){} }
void sceAudioOutMbusInit() { for(;;){} }
void sceAudioOutOpen() { for(;;){} }
void sceAudioOutOpenEx() { for(;;){} }
void sceAudioOutOutput() { for(;;){} }
void sceAudioOutOutputs() { for(;;){} }
void sceAudioOutPtClose() { for(;;){} }
void sceAudioOutPtGetLastOutputTime() { for(;;){} }
void sceAudioOutPtOpen() { for(;;){} }
void sceAudioOutSetConnections() { for(;;){} }
void sceAudioOutSetConnectionsForUser() { for(;;){} }
void sceAudioOutSetDevConnection() { for(;;){} }
void sceAudioOutSetHeadphoneOutMode() { for(;;){} }
void sceAudioOutSetJediJackVolume() { for(;;){} }
void sceAudioOutSetJediSpkVolume() { for(;;){} }
void sceAudioOutSetMainOutput() { for(;;){} }
void sceAudioOutSetMixLevelPadSpk() { for(;;){} }
void sceAudioOutSetMorpheusParam() { for(;;){} }
void sceAudioOutSetMorpheusWorkingMode() { for(;;){} }
void sceAudioOutSetPortConnections() { for(;;){} }
void sceAudioOutSetPortStatuses() { for(;;){} }
void sceAudioOutSetRecMode() { for(;;){} }
void sceAudioOutSetSparkParam() { for(;;){} }
void sceAudioOutSetUsbVolume() { for(;;){} }
void sceAudioOutSetVolume() { for(;;){} }
void sceAudioOutSetVolumeDown() { for(;;){} }
void sceAudioOutStartAuxBroadcast() { for(;;){} }
void sceAudioOutStartSharePlay() { for(;;){} }
void sceAudioOutStopAuxBroadcast() { for(;;){} }
void sceAudioOutStopSharePlay() { for(;;){} }
void sceAudioOutSuspendResume() { for(;;){} }
void sceAudioOutSysConfigureOutputMode() { for(;;){} }
void sceAudioOutSysGetHdmiMonitorInfo() { for(;;){} }
void sceAudioOutSysGetSystemInfo() { for(;;){} }
void sceAudioOutSysHdmiMonitorInfoIsSupportedAudioOutMode() { for(;;){} }
void sceAudioOutSystemControlGet() { for(;;){} }
void sceAudioOutSystemControlSet() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}