/* Source generated by crazyvoids source generating tool **/
#include "libScePlayReady.h"

void sceBufferAlloc() { for(;;){} }
void sceBufferDup() { for(;;){} }
void sceBufferFree() { for(;;){} }
void sceBufferInit() { for(;;){} }
void sceBufferRealloc() { for(;;){} }
void scePlayReadyApiInitializeInitParams() { for(;;){} }
void scePlayReadyApiIsStarted() { for(;;){} }
void scePlayReadyApiStart() { for(;;){} }
void scePlayReadyApiStop() { for(;;){} }
void scePlayReadyApiVersion() { for(;;){} }
void scePlayReadyApiVersionString() { for(;;){} }
void scePlayReadyBufferFree() { for(;;){} }
void scePlayReadyBufferInit() { for(;;){} }
void scePlayReadyBufferMalloc() { for(;;){} }
void scePlayReadyBufferRealloc() { for(;;){} }
void scePlayReadyContentGetProperty() { for(;;){} }
void scePlayReadyContentSetProperty() { for(;;){} }
void scePlayReadyDomainCertEnumFini() { for(;;){} }
void scePlayReadyDomainCertEnumInit() { for(;;){} }
void scePlayReadyDomainCertEnumNext() { for(;;){} }
void scePlayReadyDomainCertFind() { for(;;){} }
void scePlayReadyDomainJoinGenerateChallenge() { for(;;){} }
void scePlayReadyDomainJoinProcessResponse() { for(;;){} }
void scePlayReadyDomainLeaveGenerateChallenge() { for(;;){} }
void scePlayReadyDomainLeaveProcessResponse() { for(;;){} }
void scePlayReadyEnvelopeClose() { for(;;){} }
void scePlayReadyEnvelopeGetSize() { for(;;){} }
void scePlayReadyEnvelopeInitializeRead() { for(;;){} }
void scePlayReadyEnvelopeOpen() { for(;;){} }
void scePlayReadyEnvelopeRead() { for(;;){} }
void scePlayReadyEnvelopeSeek() { for(;;){} }
void scePlayReadyFinalize() { for(;;){} }
void scePlayReadyFreeDecryptContext() { for(;;){} }
void scePlayReadyInitialize() { for(;;){} }
void scePlayReadyInitializeInitParams() { for(;;){} }
void scePlayReadyLicenseAcqGenerateAck() { for(;;){} }
void scePlayReadyLicenseAcqGenerateChallenge() { for(;;){} }
void scePlayReadyLicenseAcqGetAdditionalResponseData() { for(;;){} }
void scePlayReadyLicenseAcqProcessAckResponse() { for(;;){} }
void scePlayReadyLicenseAcqProcessResponse() { for(;;){} }
void scePlayReadyMemAlloc() { for(;;){} }
void scePlayReadyMemFree() { for(;;){} }
void scePlayReadyMemGetStats() { for(;;){} }
void scePlayReadyMemRealloc() { for(;;){} }
void scePlayReadyNewDecryptContext() { for(;;){} }
void scePlayReadyReaderBind() { for(;;){} }
void scePlayReadyReaderCommit() { for(;;){} }
void scePlayReadyReaderDecrypt() { for(;;){} }
void scePlayReadyReset() { for(;;){} }
void scePlayReadyStoreCleanup() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}