/* Source generated by crazyvoids source generating tool **/
#include "libSceClSysCallWrapper.h"

void sceClAudiodecCreateDecoder() { for(;;){} }
void sceClAudiodecDecode() { for(;;){} }
void sceClAudiodecDeleteDecoder() { for(;;){} }
void sceClAudiodecInitLibrary() { for(;;){} }
void sceClAudiodecTermLibrary() { for(;;){} }
void sceClHttpAbortRequest() { for(;;){} }
void sceClHttpAddRequestHeader() { for(;;){} }
void sceClHttpCreateConnectionWithURL() { for(;;){} }
void sceClHttpCreateEpoll() { for(;;){} }
void sceClHttpCreateRequestWithURL() { for(;;){} }
void sceClHttpCreateTemplate() { for(;;){} }
void sceClHttpDeleteConnection() { for(;;){} }
void sceClHttpDeleteRequest() { for(;;){} }
void sceClHttpDeleteTemplate() { for(;;){} }
void sceClHttpDestroyEpoll() { for(;;){} }
void sceClHttpGetMemoryPoolStats() { for(;;){} }
void sceClHttpInit() { for(;;){} }
void sceClHttpReadData() { for(;;){} }
void sceClHttpSendRequest() { for(;;){} }
void sceClHttpSetAutoRedirect() { for(;;){} }
void sceClHttpSetEpoll() { for(;;){} }
void sceClHttpSetNonblock() { for(;;){} }
void sceClHttpSetRedirectCallback() { for(;;){} }
void sceClHttpsSetSslCallback() { for(;;){} }
void sceClHttpTerm() { for(;;){} }
void sceClHttpUnsetEpoll() { for(;;){} }
void sceClHttpWaitRequest() { for(;;){} }
void sceClKernelCreateEventFlag() { for(;;){} }
void sceClKernelDeleteEventFlag() { for(;;){} }
void sceClKernelMapNamedFlexibleMemory() { for(;;){} }
void sceClKernelMunmap() { for(;;){} }
void sceClKernelNanosleep() { for(;;){} }
void sceClKernelReleaseFlexibleMemory() { for(;;){} }
void sceClKernelSetEventFlag() { for(;;){} }
void sceClKernelUsleep() { for(;;){} }
void sceClKernelWaitEventFlag() { for(;;){} }
void sceClNetInit() { for(;;){} }
void sceClNetPoolCreate() { for(;;){} }
void sceClNetPoolDestroy() { for(;;){} }
void sceClNetTerm() { for(;;){} }
void sceClPthreadAttrDestroy() { for(;;){} }
void sceClPthreadAttrInit() { for(;;){} }
void sceClPthreadAttrSetdetachstate() { for(;;){} }
void sceClPthreadAttrSetinheritsched() { for(;;){} }
void sceClPthreadAttrSetschedparam() { for(;;){} }
void sceClPthreadAttrSetstacksize() { for(;;){} }
void sceClPthreadCondattrDestroy() { for(;;){} }
void sceClPthreadCondattrInit() { for(;;){} }
void sceClPthreadCondDestroy() { for(;;){} }
void sceClPthreadCondInit() { for(;;){} }
void sceClPthreadCondSignal() { for(;;){} }
void sceClPthreadCondWait() { for(;;){} }
void sceClPthreadCreate() { for(;;){} }
void sceClPthreadDetach() { for(;;){} }
void sceClPthreadExit() { for(;;){} }
void sceClPthreadJoin() { for(;;){} }
void sceClPthreadMutexattrDestroy() { for(;;){} }
void sceClPthreadMutexattrInit() { for(;;){} }
void sceClPthreadMutexattrSetprioceiling() { for(;;){} }
void sceClPthreadMutexattrSetprotocol() { for(;;){} }
void sceClPthreadMutexattrSettype() { for(;;){} }
void sceClPthreadMutexDestroy() { for(;;){} }
void sceClPthreadMutexInit() { for(;;){} }
void sceClPthreadMutexLock() { for(;;){} }
void sceClPthreadMutexUnlock() { for(;;){} }
void sceClPthreadSetprio() { for(;;){} }
void sceClSendSystemNotification() { for(;;){} }
void sceClSslGetSerialNumber() { for(;;){} }
void sceClSslInit() { for(;;){} }
void sceClSslTerm() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}