/* Source generated by crazyvoids source generating tool **/
#include "libSceSystemServiceVideoServiceWebApp.h"

void sceSystemServiceLoadExecVideoServiceWebApp() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}