/* Source generated by crazyvoids source generating tool **/
#include "libSceGnmDriverCompat.h"

void sceGnmDrawInitToDefaultContextStateInternalCommand() { for(;;){} }
void sceGnmDrawInitToDefaultContextStateInternalSize() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}