/* Source generated by crazyvoids source generating tool **/
#include "libSceSystemServiceActivateMpeg2.h"

void sceSystemServiceActivateMpeg2Abort() { for(;;){} }
void sceSystemServiceActivateMpeg2GetStatus() { for(;;){} }
void sceSystemServiceActivateMpeg2Init() { for(;;){} }
void sceSystemServiceActivateMpeg2IsActivated() { for(;;){} }
void sceSystemServiceActivateMpeg2Start() { for(;;){} }
void sceSystemServiceActivateMpeg2Term() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}