/* Source generated by crazyvoids source generating tool **/
#include "libSceGameLiveStreaming.h"

void sceGameLiveStreamingApplySocialFeedbackMessageFilter() { for(;;){} }
void sceGameLiveStreamingCheckCallback() { for(;;){} }
void sceGameLiveStreamingClearPresetSocialFeedbackCommands() { for(;;){} }
void sceGameLiveStreamingClearSocialFeedbackMessages() { for(;;){} }
void sceGameLiveStreamingClearSpoilerTag() { for(;;){} }
void sceGameLiveStreamingEnableLiveStreaming() { for(;;){} }
void sceGameLiveStreamingEnableSocialFeedback() { for(;;){} }
void sceGameLiveStreamingGetCurrentBroadcastScreenLayout() { for(;;){} }
void sceGameLiveStreamingGetCurrentStatus() { for(;;){} }
void sceGameLiveStreamingGetCurrentStatus2() { for(;;){} }
void sceGameLiveStreamingGetProgramInfo() { for(;;){} }
void sceGameLiveStreamingGetSocialFeedbackMessages() { for(;;){} }
void sceGameLiveStreamingGetSocialFeedbackMessagesCount() { for(;;){} }
void sceGameLiveStreamingInitialize() { for(;;){} }
void sceGameLiveStreamingLaunchLiveViewer() { for(;;){} }
void sceGameLiveStreamingLaunchLiveViewerA() { for(;;){} }
void sceGameLiveStreamingPermitLiveStreaming() { for(;;){} }
void sceGameLiveStreamingPermitServerSideRecording() { for(;;){} }
void sceGameLiveStreamingPostSocialMessage() { for(;;){} }
void sceGameLiveStreamingRegisterCallback() { for(;;){} }
void sceGameLiveStreamingScreenCloseSeparateMode() { for(;;){} }
void sceGameLiveStreamingScreenConfigureSeparateMode() { for(;;){} }
void sceGameLiveStreamingScreenInitialize() { for(;;){} }
void sceGameLiveStreamingScreenInitializeSeparateModeParameter() { for(;;){} }
void sceGameLiveStreamingScreenOpenSeparateMode() { for(;;){} }
void sceGameLiveStreamingScreenSetMode() { for(;;){} }
void sceGameLiveStreamingScreenTerminate() { for(;;){} }
void sceGameLiveStreamingSetCameraFrameSetting() { for(;;){} }
void sceGameLiveStreamingSetDefaultServiceProviderPermission() { for(;;){} }
void sceGameLiveStreamingSetGuardAreas() { for(;;){} }
void sceGameLiveStreamingSetInvitationSessionId() { for(;;){} }
void sceGameLiveStreamingSetLinkCommentPreset() { for(;;){} }
void sceGameLiveStreamingSetMaxBitrate() { for(;;){} }
void sceGameLiveStreamingSetMetadata() { for(;;){} }
void sceGameLiveStreamingSetPresetSocialFeedbackCommands() { for(;;){} }
void sceGameLiveStreamingSetPresetSocialFeedbackCommandsDescription() { for(;;){} }
void sceGameLiveStreamingSetServiceProviderPermission() { for(;;){} }
void sceGameLiveStreamingSetSpoilerTag() { for(;;){} }
void sceGameLiveStreamingSetStandbyScreenResource() { for(;;){} }
void sceGameLiveStreamingStartGenerateStandbyScreenResource() { for(;;){} }
void sceGameLiveStreamingStartSocialFeedbackMessageFiltering() { for(;;){} }
void sceGameLiveStreamingStopGenerateStandbyScreenResource() { for(;;){} }
void sceGameLiveStreamingStopSocialFeedbackMessageFiltering() { for(;;){} }
void sceGameLiveStreamingTerminate() { for(;;){} }
void sceGameLiveStreamingUnregisterCallback() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}