/* Source generated by crazyvoids source generating tool **/
#include "libSceBackupRestoreUtil.h"

void sceBackupRestoreUtilBackupData() { for(;;){} }
void sceBackupRestoreUtilCancelBackupData() { for(;;){} }
void sceBackupRestoreUtilCancelGetRequiredSize() { for(;;){} }
void sceBackupRestoreUtilCancelGetTitles() { for(;;){} }
void sceBackupRestoreUtilCancelRestoreData() { for(;;){} }
void sceBackupRestoreUtilDeleteBackupData() { for(;;){} }
void sceBackupRestoreUtilGetBackupDataInfo() { for(;;){} }
void sceBackupRestoreUtilGetBackupParam() { for(;;){} }
void sceBackupRestoreUtilGetBackupProgress() { for(;;){} }
void sceBackupRestoreUtilGetRequiredSize() { for(;;){} }
void sceBackupRestoreUtilGetRestoreProgress() { for(;;){} }
void sceBackupRestoreUtilGetTitles() { for(;;){} }
void sceBackupRestoreUtilInitialize() { for(;;){} }
void sceBackupRestoreUtilPrepareBackup() { for(;;){} }
void sceBackupRestoreUtilRestoreData() { for(;;){} }
void sceBackupRestoreUtilTerminate() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}