/* Source generated by crazyvoids source generating tool **/
#include "libSceAvPlayerStreaming.h"

void MvpHttpAbort() { for(;;){} }
void MvpHttpDeInit() { for(;;){} }
void MvpHttpGet() { for(;;){} }
void MvpHttpGetLastError() { for(;;){} }
void MvpHttpHead() { for(;;){} }
void MvpHttpHeadCleanup() { for(;;){} }
void MvpHttpInit() { for(;;){} }
void MvpHttpPost() { for(;;){} }
void MvpHttpSetCert() { for(;;){} }
void MvpHttpSetRecvTimeout() { for(;;){} }
void MvpHttpSetRedirectCb() { for(;;){} }
void sceTsCloseFile() { for(;;){} }
void sceTsDisableRepresentation() { for(;;){} }
void sceTsEnableRepresentation() { for(;;){} }
void sceTsEnableStream() { for(;;){} }
void sceTsGetAvailableBW() { for(;;){} }
void sceTsGetLiveStatus() { for(;;){} }
void sceTsGetNextAuInfo() { for(;;){} }
void sceTsGetNextUnitData() { for(;;){} }
void sceTsGetRepresentationCount() { for(;;){} }
void sceTsGetRepresentationInfo() { for(;;){} }
void sceTsGetSeekWindow() { for(;;){} }
void sceTsGetStreamInfo() { for(;;){} }
void sceTsGetUrlEncryptionType() { for(;;){} }
void sceTsJumpPTS() { for(;;){} }
void sceTsOpenFile() { for(;;){} }
void sceTsOpenFileEx() { for(;;){} }
void sceTsReleaseBuffer() { for(;;){} }
void sceTsRepresentationIsEnabled() { for(;;){} }
void sceTsSetAvailableBW() { for(;;){} }
void sceTsSetStartingBW() { for(;;){} }
void sceTsStartFileStreaming() { for(;;){} }
void sceTsStopFileStreaming() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}