/* Source generated by crazyvoids source generating tool **/
#include "libSceNpAuthCompat.h"

void sceNpAuthGetAuthorizationCode() { for(;;){} }
void sceNpAuthGetIdToken() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}