/* Source generated by crazyvoids source generating tool **/
#include "libSceUpdateService.h"

void sceUpsrvGetCompletedTaskId() { for(;;){} }
void sceUpsrvGetRebootFlag() { for(;;){} }
void sceUpsrvGetSystemExUpdateTaskState() { for(;;){} }
void sceUpsrvInitialize() { for(;;){} }
void sceUpsrvPostErrorLog() { for(;;){} }
void sceUpsrvResumePausedTask() { for(;;){} }
void sceUpsrvSwitchSystemExBank() { for(;;){} }
void sceUpsrvSwitchSystemExBankWithoutVerify() { for(;;){} }
void sceUpsrvTerminate() { for(;;){} }
void sceUpsrvUpdateCancelBDUpdate() { for(;;){} }
void sceUpsrvUpdateCheckCancel() { for(;;){} }
void sceUpsrvUpdateCheckCreateHandler() { for(;;){} }
void sceUpsrvUpdateCheckDestroyHandler() { for(;;){} }
void sceUpsrvUpdateCheckDoCheckSystem() { for(;;){} }
void sceUpsrvUpdateCheckDoCheckSystemBeta() { for(;;){} }
void sceUpsrvUpdateCheckDoCheckSystemForDevKit() { for(;;){} }
void sceUpsrvUpdateCheckDoCheckSystemForSettings() { for(;;){} }
void sceUpsrvUpdateCheckDoCheckSystemVersionDown() { for(;;){} }
void sceUpsrvUpdateCheckDoCheckSystemWithPupInfo() { for(;;){} }
void sceUpsrvUpdateCheckGetUpdatelistURL() { for(;;){} }
void sceUpsrvUpdateCreateUpdateTask() { for(;;){} }
void sceUpsrvUpdateDestroyUpdateTask() { for(;;){} }
void sceUpsrvUpdateDoCheckBootUpdate() { for(;;){} }
void sceUpsrvUpdateDoUpdate() { for(;;){} }
void sceUpsrvUpdateDoUpdateBeta() { for(;;){} }
void sceUpsrvUpdateDoUpdateSystemEx() { for(;;){} }
void sceUpsrvUpdateDoUpdateWithHandler() { for(;;){} }
void sceUpsrvUpdateDoUpdateWithPupInfo() { for(;;){} }
void sceUpsrvUpdateDoUpdateWithPupPath() { for(;;){} }
void sceUpsrvUpdateGetBetaAgreementUrl() { for(;;){} }
void sceUpsrvUpdateGetBetaAgreementUrlForUpdate() { for(;;){} }
void sceUpsrvUpdateGetBetaFeatureListUrlForUpdate() { for(;;){} }
void sceUpsrvUpdateGetDownloadProgress() { for(;;){} }
void sceUpsrvUpdateGetEulaDisplay() { for(;;){} }
void sceUpsrvUpdateGetEulaStr() { for(;;){} }
void sceUpsrvUpdateGetEulaStrLen() { for(;;){} }
void sceUpsrvUpdateGetFeatureListUrl() { for(;;){} }
void sceUpsrvUpdateGetFeatureListUrlForSystemExUpdate() { for(;;){} }
void sceUpsrvUpdateGetFeatureListUrlForUpdate() { for(;;){} }
void sceUpsrvUpdateGetImageWritingProgress() { for(;;){} }
void sceUpsrvUpdateGetObfuscatedString() { for(;;){} }
void sceUpsrvUpdateGetUpdateTaskInfo() { for(;;){} }
void sceUpsrvUpdateGetUpdateTaskMgrInfo() { for(;;){} }
void sceUpsrvUpdateSetEulaAccept() { for(;;){} }
void sceUpsrvUpdateSetUpdateMode() { for(;;){} }
void sceUpsrvUpdateStartUpdateTask() { for(;;){} }
void sceUpsrvVerifySystemExBank() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}