/* Source generated by crazyvoids source generating tool **/
#include "libSceCompanionHttpd.h"

void sceCompanionHttpdAddHeader() { for(;;){} }
void sceCompanionHttpdGet2ndScreenStatus() { for(;;){} }
void sceCompanionHttpdGetEvent() { for(;;){} }
void sceCompanionHttpdGetUserId() { for(;;){} }
void sceCompanionHttpdInitialize() { for(;;){} }
void sceCompanionHttpdInitialize2() { for(;;){} }
void sceCompanionHttpdOptParamInitialize() { for(;;){} }
void sceCompanionHttpdRegisterRequestBodyReceptionCallback() { for(;;){} }
void sceCompanionHttpdRegisterRequestCallback() { for(;;){} }
void sceCompanionHttpdRegisterRequestCallback2() { for(;;){} }
void sceCompanionHttpdSetBody() { for(;;){} }
void sceCompanionHttpdSetStatus() { for(;;){} }
void sceCompanionHttpdStart() { for(;;){} }
void sceCompanionHttpdStop() { for(;;){} }
void sceCompanionHttpdTerminate() { for(;;){} }
void sceCompanionHttpdUnregisterRequestBodyReceptionCallback() { for(;;){} }
void sceCompanionHttpdUnregisterRequestCallback() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}