/* Source generated by crazyvoids source generating tool **/
#include "libSceFontFt.h"

void sceFontFtSupportBdf() { for(;;){} }
void sceFontFtSupportCid() { for(;;){} }
void sceFontFtSupportFontFormats() { for(;;){} }
void sceFontFtSupportOpenType() { for(;;){} }
void sceFontFtSupportOpenTypeOtf() { for(;;){} }
void sceFontFtSupportOpenTypeTtf() { for(;;){} }
void sceFontFtSupportPcf() { for(;;){} }
void sceFontFtSupportPfr() { for(;;){} }
void sceFontFtSupportSystemFonts() { for(;;){} }
void sceFontFtSupportTrueType() { for(;;){} }
void sceFontFtSupportTrueTypeGx() { for(;;){} }
void sceFontFtSupportType1() { for(;;){} }
void sceFontFtSupportType42() { for(;;){} }
void sceFontFtSupportWinFonts() { for(;;){} }
void sceFontSelectLibraryFt() { for(;;){} }
void sceFontSelectRendererFt() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}