/* Source generated by crazyvoids source generating tool **/
#include "libSceNetCtlV6.h"

void sceNetCtlGetInfoV6() { for(;;){} }
void sceNetCtlGetResultV6() { for(;;){} }
void sceNetCtlGetStateV6() { for(;;){} }
void sceNetCtlRegisterCallbackV6() { for(;;){} }
void sceNetCtlUnregisterCallbackV6() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}