/* Source generated by crazyvoids source generating tool **/
#include "libSceSystemServicePartyVoice.h"

void sceSystemServiceDisablePartyVoice() { for(;;){} }
void sceSystemServiceReenablePartyVoice() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}