/* Source generated by crazyvoids source generating tool **/
#include "libSceContentSearch.h"

void sceContentSearchCloseMetadata() { for(;;){} }
void sceContentSearchGetApplicationLastUpdateId() { for(;;){} }
void sceContentSearchGetContentLastUpdateId() { for(;;){} }
void sceContentSearchGetMetadataFieldInfo() { for(;;){} }
void sceContentSearchGetMetadataValue() { for(;;){} }
void sceContentSearchGetMyApplicationIndex() { for(;;){} }
void sceContentSearchGetNumOfApplication() { for(;;){} }
void sceContentSearchGetNumOfContent() { for(;;){} }
void sceContentSearchGetTotalContentSize() { for(;;){} }
void sceContentSearchInit() { for(;;){} }
void sceContentSearchOpenMetadata() { for(;;){} }
void sceContentSearchOpenMetadataByContentId() { for(;;){} }
void sceContentSearchSearchApplication() { for(;;){} }
void sceContentSearchSearchContent() { for(;;){} }
void sceContentSearchTerm() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}