/* Source generated by crazyvoids source generating tool **/
#include "libSceDataTransfer.h"

void sceDataTransferHostAbort() { for(;;){} }
void sceDataTransferHostLaunch() { for(;;){} }
void sceDataTransferHostNotifyEasySignInReady() { for(;;){} }
void sceDataTransferInitialize() { for(;;){} }
void sceDataTransferTargetAbortBindSavedata() { for(;;){} }
void sceDataTransferTargetAbortDeactivate() { for(;;){} }
void sceDataTransferTargetAbortEth0() { for(;;){} }
void sceDataTransferTargetAbortGetDeviceInfo() { for(;;){} }
void sceDataTransferTargetAbortGetDeviceInfoApplication() { for(;;){} }
void sceDataTransferTargetAbortGetTitles() { for(;;){} }
void sceDataTransferTargetAbortGetUsers() { for(;;){} }
void sceDataTransferTargetAbortLaunch() { for(;;){} }
void sceDataTransferTargetAbortPrepareTransfer() { for(;;){} }
void sceDataTransferTargetAbortPwrReq() { for(;;){} }
void sceDataTransferTargetAbortReboot() { for(;;){} }
void sceDataTransferTargetAbortSendSsoNew2Old() { for(;;){} }
void sceDataTransferTargetAbortSendSsoOld2New() { for(;;){} }
void sceDataTransferTargetAbortTransfer() { for(;;){} }
void sceDataTransferTargetAbortTransferSpeed() { for(;;){} }
void sceDataTransferTargetEventIsAuthReady() { for(;;){} }
void sceDataTransferTargetEventIsIPv6Ready() { for(;;){} }
void sceDataTransferTargetEventIsPwrReqReady() { for(;;){} }
void sceDataTransferTargetGetFailedUsers() { for(;;){} }
void sceDataTransferTargetGetRebootData() { for(;;){} }
void sceDataTransferTargetGetTransferProgress() { for(;;){} }
void sceDataTransferTargetRequestAbortSearch() { for(;;){} }
void sceDataTransferTargetRequestActivate() { for(;;){} }
void sceDataTransferTargetRequestAuth() { for(;;){} }
void sceDataTransferTargetRequestBindSavedata() { for(;;){} }
void sceDataTransferTargetRequestComplete() { for(;;){} }
void sceDataTransferTargetRequestCreateRebootData() { for(;;){} }
void sceDataTransferTargetRequestDeactivate() { for(;;){} }
void sceDataTransferTargetRequestGetDeviceInfo() { for(;;){} }
void sceDataTransferTargetRequestGetDeviceInfoApplication() { for(;;){} }
void sceDataTransferTargetRequestGetTitles() { for(;;){} }
void sceDataTransferTargetRequestGetUsers() { for(;;){} }
void sceDataTransferTargetRequestLaunch() { for(;;){} }
void sceDataTransferTargetRequestPrepareTransfer() { for(;;){} }
void sceDataTransferTargetRequestPrepareTransferProgress() { for(;;){} }
void sceDataTransferTargetRequestPwrReq() { for(;;){} }
void sceDataTransferTargetRequestReboot() { for(;;){} }
void sceDataTransferTargetRequestSearch() { for(;;){} }
void sceDataTransferTargetRequestSendSsoNew2Old() { for(;;){} }
void sceDataTransferTargetRequestSendSsoOld2New() { for(;;){} }
void sceDataTransferTargetRequestStartTransfer() { for(;;){} }
void sceDataTransferTargetRequestTransferSpeed() { for(;;){} }
void sceDataTransferTerminate() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}