/* Source generated by crazyvoids source generating tool **/
#include "libSceJpegEnc.h"

void sceJpegEncCreate() { for(;;){} }
void sceJpegEncDelete() { for(;;){} }
void sceJpegEncEncode() { for(;;){} }
void sceJpegEncQueryMemorySize() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}