/* Source generated by crazyvoids source generating tool **/
#include "libSceNpUtility.h"

void sceNpAppInfoIntAbortRequest() { for(;;){} }
void sceNpAppInfoIntCheckAvailability() { for(;;){} }
void sceNpAppInfoIntCheckAvailabilityA() { for(;;){} }
void sceNpAppInfoIntCheckAvailabilityAll() { for(;;){} }
void sceNpAppInfoIntCheckAvailabilityAllA() { for(;;){} }
void sceNpAppInfoIntCheckServiceAvailability() { for(;;){} }
void sceNpAppInfoIntCheckServiceAvailabilityA() { for(;;){} }
void sceNpAppInfoIntCheckServiceAvailabilityAll() { for(;;){} }
void sceNpAppInfoIntCheckServiceAvailabilityAllA() { for(;;){} }
void sceNpAppInfoIntCreateRequest() { for(;;){} }
void sceNpAppInfoIntDestroyRequest() { for(;;){} }
void sceNpAppInfoIntFinalize() { for(;;){} }
void sceNpAppInfoIntInitialize() { for(;;){} }
void sceNpAppLaunchLinkIntAbortRequest() { for(;;){} }
void sceNpAppLaunchLinkIntCreateRequest() { for(;;){} }
void sceNpAppLaunchLinkIntDestroyRequest() { for(;;){} }
void sceNpAppLaunchLinkIntFinalize() { for(;;){} }
void sceNpAppLaunchLinkIntGetCompatibleTitleIdList() { for(;;){} }
void sceNpAppLaunchLinkIntGetCompatibleTitleIdNum() { for(;;){} }
void sceNpAppLaunchLinkIntInitialize() { for(;;){} }
void sceNpBandwidthTestAbort() { for(;;){} }
void sceNpBandwidthTestDownloadOnlyInitStart() { for(;;){} }
void sceNpBandwidthTestGetStatus() { for(;;){} }
void sceNpBandwidthTestInitStart() { for(;;){} }
void sceNpBandwidthTestShutdown() { for(;;){} }
void sceNpBandwidthTestShutdownInt() { for(;;){} }
void sceNpBandwidthTestUploadOnlyInitStart() { for(;;){} }
void sceNpLookupAbortRequest() { for(;;){} }
void sceNpLookupCreateAsyncRequest() { for(;;){} }
void sceNpLookupCreateRequest() { for(;;){} }
void sceNpLookupCreateTitleCtx() { for(;;){} }
void sceNpLookupCreateTitleCtxA() { for(;;){} }
void sceNpLookupDeleteRequest() { for(;;){} }
void sceNpLookupDeleteTitleCtx() { for(;;){} }
void sceNpLookupNetAbortRequest() { for(;;){} }
void sceNpLookupNetCensorComment() { for(;;){} }
void sceNpLookupNetConvertJidToNpId() { for(;;){} }
void sceNpLookupNetConvertNpIdToJid() { for(;;){} }
void sceNpLookupNetCreateRequest() { for(;;){} }
void sceNpLookupNetCreateTitleCtx() { for(;;){} }
void sceNpLookupNetDeleteRequest() { for(;;){} }
void sceNpLookupNetDeleteTitleCtx() { for(;;){} }
void sceNpLookupNetInit() { for(;;){} }
void sceNpLookupNetInitWithFunctionPointer() { for(;;){} }
void sceNpLookupNetInitWithMemoryPool() { for(;;){} }
void sceNpLookupNetIsInit() { for(;;){} }
void sceNpLookupNetNpId() { for(;;){} }
void sceNpLookupNetSanitizeComment() { for(;;){} }
void sceNpLookupNetSetTimeout() { for(;;){} }
void sceNpLookupNetTerm() { for(;;){} }
void sceNpLookupNpId() { for(;;){} }
void sceNpLookupPollAsync() { for(;;){} }
void sceNpLookupSetTimeout() { for(;;){} }
void sceNpLookupWaitAsync() { for(;;){} }
void sceNpServiceChecker2IntAbortRequest() { for(;;){} }
void sceNpServiceChecker2IntCreateRequest() { for(;;){} }
void sceNpServiceChecker2IntDestroyRequest() { for(;;){} }
void sceNpServiceChecker2IntFinalize() { for(;;){} }
void sceNpServiceChecker2IntGetServiceAvailability() { for(;;){} }
void sceNpServiceChecker2IntGetServiceAvailabilityA() { for(;;){} }
void sceNpServiceChecker2IntInitialize() { for(;;){} }
void sceNpServiceChecker2IntIsSetServiceType() { for(;;){} }
void sceNpServiceCheckerIntAbortRequest() { for(;;){} }
void sceNpServiceCheckerIntCreateRequest() { for(;;){} }
void sceNpServiceCheckerIntDestroyRequest() { for(;;){} }
void sceNpServiceCheckerIntFinalize() { for(;;){} }
void sceNpServiceCheckerIntGetAvailability() { for(;;){} }
void sceNpServiceCheckerIntGetAvailabilityList() { for(;;){} }
void sceNpServiceCheckerIntInitialize() { for(;;){} }
void sceNpServiceCheckerIntIsCached() { for(;;){} }
void sceNpTitleMetadataIntAbortRequest() { for(;;){} }
void sceNpTitleMetadataIntCreateRequest() { for(;;){} }
void sceNpTitleMetadataIntDeleteRequest() { for(;;){} }
void sceNpTitleMetadataIntGetInfo() { for(;;){} }
void sceNpTitleMetadataIntGetNpTitleId() { for(;;){} }
void sceNpUtilityInit() { for(;;){} }
void sceNpUtilityTerm() { for(;;){} }
void sceNpWordFilterAbortRequest() { for(;;){} }
void sceNpWordFilterCensorComment() { for(;;){} }
void sceNpWordFilterCreateAsyncRequest() { for(;;){} }
void sceNpWordFilterCreateRequest() { for(;;){} }
void sceNpWordFilterCreateTitleCtx() { for(;;){} }
void sceNpWordFilterCreateTitleCtxA() { for(;;){} }
void sceNpWordFilterDeleteRequest() { for(;;){} }
void sceNpWordFilterDeleteTitleCtx() { for(;;){} }
void sceNpWordFilterPollAsync() { for(;;){} }
void sceNpWordFilterSanitizeComment() { for(;;){} }
void sceNpWordFilterSetTimeout() { for(;;){} }
void sceNpWordFilterWaitAsync() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}