/* Source generated by crazyvoids source generating tool **/
#include "libSceImeBackend.h"

void sceImeBackendAllConfirm() { for(;;){} }
void sceImeBackendAllDeleteConvertString() { for(;;){} }
void sceImeBackendBackspaceCharacter() { for(;;){} }
void sceImeBackendClose() { for(;;){} }
void sceImeBackendConvertBackward() { for(;;){} }
void sceImeBackendConvertCancel() { for(;;){} }
void sceImeBackendConvertForward() { for(;;){} }
void sceImeBackendDeleteCharacter() { for(;;){} }
void sceImeBackendEnterCharacter() { for(;;){} }
void sceImeBackendForTestFunction() { for(;;){} }
void sceImeBackendGetCandidateList() { for(;;){} }
void sceImeBackendGetCandidateListSize() { for(;;){} }
void sceImeBackendGetCandidateSelect() { for(;;){} }
void sceImeBackendGetCaretIndex() { for(;;){} }
void sceImeBackendGetConfirmString() { for(;;){} }
void sceImeBackendGetConvertMode() { for(;;){} }
void sceImeBackendGetConvertString() { for(;;){} }
void sceImeBackendGetStatus() { for(;;){} }
void sceImeBackendGetString() { for(;;){} }
void sceImeBackendModeCaretNext() { for(;;){} }
void sceImeBackendModeCaretPrevious() { for(;;){} }
void sceImeBackendOpen() { for(;;){} }
void sceImeBackendParamInit() { for(;;){} }
void sceImeBackendPartConfirm() { for(;;){} }
void sceImeBackendReset() { for(;;){} }
void sceImeBackendSetConvertMode() { for(;;){} }
void sceImeBackendTemporalConfirm() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}