/* Source generated by crazyvoids source generating tool **/
#include "libSceComposite.h"

void sceCompositorAllocateIndex() { for(;;){} }
void sceCompositorCheckCrash() { for(;;){} }
void sceCompositorCommandGpuPerfBegin() { for(;;){} }
void sceCompositorCommandGpuPerfEnd() { for(;;){} }
void sceCompositorCreateIndirectRenderTarget() { for(;;){} }
void sceCompositorDeleteIndirectRenderTarget() { for(;;){} }
void sceCompositorFlush() { for(;;){} }
void sceCompositorFlushWithRepeat() { for(;;){} }
void sceCompositorGetAnotherProcessSystemAddress() { for(;;){} }
void sceCompositorGetAnotherProcessSystemSize() { for(;;){} }
void sceCompositorGetAnotherProcessVideoAddress() { for(;;){} }
void sceCompositorGetAnotherProcessVideoSize() { for(;;){} }
void sceCompositorGetCanvasHandle() { for(;;){} }
void sceCompositorGetClientList() { for(;;){} }
void sceCompositorGetDmemOffset() { for(;;){} }
void sceCompositorGetDummyAddress() { for(;;){} }
void sceCompositorGetDummySize() { for(;;){} }
void sceCompositorGetRemainedCommandNum() { for(;;){} }
void sceCompositorGetRenderTargetResolution() { for(;;){} }
void sceCompositorGetSystemAddress() { for(;;){} }
void sceCompositorGetSystemSize() { for(;;){} }
void sceCompositorGetVideoAddress() { for(;;){} }
void sceCompositorGetVideoSize() { for(;;){} }
void sceCompositorHandleProcessEvents() { for(;;){} }
void sceCompositorInit() { for(;;){} }
void sceCompositorInitWithProcessOrder() { for(;;){} }
void sceCompositorInsertThreadTraceMarker() { for(;;){} }
void sceCompositorIsDebugCaptureEnabled() { for(;;){} }
void sceCompositorIsReady4K() { for(;;){} }
void sceCompositorLockCommandBuffer() { for(;;){} }
void sceCompositorMakeCanvasHandle() { for(;;){} }
void sceCompositorMapAnotherProcess() { for(;;){} }
void sceCompositorQuit() { for(;;){} }
void sceCompositorReleaseCommandBuffer() { for(;;){} }
void sceCompositorReleaseIndex() { for(;;){} }
void sceCompositorReleaseLocalStall() { for(;;){} }
void sceCompositorReserveCommandBuffer() { for(;;){} }
void sceCompositorResetZoomCommand() { for(;;){} }
void sceCompositorSetCompositeCanvasCommandInC() { for(;;){} }
void sceCompositorSetCursorImageAddress() { for(;;){} }
void sceCompositorSetDebugPositionCommand() { for(;;){} }
void sceCompositorSetEndOfFrameCommand() { for(;;){} }
void sceCompositorSetEventCommand() { for(;;){} }
void sceCompositorSetFlipCommand() { for(;;){} }
void sceCompositorSetGameSufaceControlCommand() { for(;;){} }
void sceCompositorSetGnmContextCommand() { for(;;){} }
void sceCompositorSetIndirectCanvasCommand() { for(;;){} }
void sceCompositorSetIndirectCompositionCommand() { for(;;){} }
void sceCompositorSetIndirectRenderTargetConfigCommand() { for(;;){} }
void sceCompositorSetInvisibleCanvasCommand() { for(;;){} }
void sceCompositorSetKeepDisplayBufferCommand() { for(;;){} }
void sceCompositorSetLocalStallCommand() { for(;;){} }
void sceCompositorSetMemoryCommand() { for(;;){} }
void sceCompositorSetMorpheusState() { for(;;){} }
void sceCompositorSetPatchCommand() { for(;;){} }
void sceCompositorSetPostEventCommand() { for(;;){} }
void sceCompositorSetRepeatCommand() { for(;;){} }
void sceCompositorSetResolutionCommand() { for(;;){} }
void sceCompositorSetSeparateContextCommand() { for(;;){} }
void sceCompositorSetSystemConfigWithMask() { for(;;){} }
void sceCompositorSetZoomCommand() { for(;;){} }
void sceCompositorSystemConfig() { for(;;){} }
void sceCompositorWaitEndOfRendering() { for(;;){} }
void sceCompositorWaitEvent() { for(;;){} }
void sceCompositorWaitPostEvent() { for(;;){} }
void sceCompsoitorGetGpuClock() { for(;;){} }
void sceCompsoitorGetRenderingTime() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}