/* Source generated by crazyvoids source generating tool **/
#include "libSceNpGriefReport.h"

void sceNpGriefReportCdAbortRequest() { for(;;){} }
void sceNpGriefReportCdBaseDataInit() { for(;;){} }
void sceNpGriefReportCdCreateRequest() { for(;;){} }
void sceNpGriefReportCdDeleteRequest() { for(;;){} }
void sceNpGriefReportCdInit() { for(;;){} }
void sceNpGriefReportCdPost() { for(;;){} }
void sceNpGriefReportCdTerm() { for(;;){} }
void sceNpGriefReportReadGroupMessageFile() { for(;;){} }
void sceNpGriefReportReadLfpsCommentFile() { for(;;){} }
void sceNpGriefReportReadReportItem() { for(;;){} }
void sceNpGriefReportReadTextChatFile() { for(;;){} }
void sceNpGriefReportWriteActivityAttachFile() { for(;;){} }
void sceNpGriefReportWriteGroupMessageFile() { for(;;){} }
void sceNpGriefReportWriteJsonFile() { for(;;){} }
void sceNpGriefReportWriteReportItem() { for(;;){} }
void sceNpGriefReportWriteReportItem2() { for(;;){} }
void sceNpGriefReportWriteTemporaryFile() { for(;;){} }
void sceNpGriefReportWriteTextChatFile() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}