/* Source generated by crazyvoids source generating tool **/
#include "libSceVideodec2.h"

void sceVideodec2AllocateComputeQueue() { for(;;){} }
void sceVideodec2CreateDecoder() { for(;;){} }
void sceVideodec2CreateHevcDecoder() { for(;;){} }
void sceVideodec2Decode() { for(;;){} }
void sceVideodec2DeleteDecoder() { for(;;){} }
void sceVideodec2Flush() { for(;;){} }
void sceVideodec2GetAvcPictureInfo() { for(;;){} }
void sceVideodec2GetHevcPictureInfo() { for(;;){} }
void sceVideodec2GetPictureInfo() { for(;;){} }
void sceVideodec2MapDirectMemory() { for(;;){} }
void sceVideodec2QueryComputeMemoryInfo() { for(;;){} }
void sceVideodec2QueryDecoderMemoryInfo() { for(;;){} }
void sceVideodec2QueryHevcDecoderMemoryInfo() { for(;;){} }
void sceVideodec2ReleaseComputeQueue() { for(;;){} }
void sceVideodec2Reset() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}