/* Source generated by crazyvoids source generating tool **/
#include "libSceLoginDialog.h"

void sceLoginDialogClose() { for(;;){} }
void sceLoginDialogGetResult() { for(;;){} }
void sceLoginDialogGetStatus() { for(;;){} }
void sceLoginDialogInitialize() { for(;;){} }
void sceLoginDialogOpen() { for(;;){} }
void sceLoginDialogTerminate() { for(;;){} }
void sceLoginDialogUpdateStatus() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}