/* Source generated by crazyvoids source generating tool **/
#include "libSceIpmi.h"

void _ZN4IPMI4impl10ClientImpl10disconnectEv() { for(;;){} }
void _ZN4IPMI4impl10ClientImpl10initializeEPKNS_6Client6ConfigEPv() { for(;;){} }
void _ZN4IPMI4impl10ClientImpl11getUserDataEv() { for(;;){} }
void _ZN4IPMI4impl10ClientImpl12tryGetResultEjjPiPNS_10BufferInfoEj() { for(;;){} }
void _ZN4IPMI4impl10ClientImpl12tryGetResultEjPiPvPmm() { for(;;){} }
void _ZN4IPMI4impl10ClientImpl13pollEventFlagEjmjPm() { for(;;){} }
void _ZN4IPMI4impl10ClientImpl13waitEventFlagEjmjPmPj() { for(;;){} }
void _ZN4IPMI4impl10ClientImpl16invokeSyncMethodEjPKNS_8DataInfoEjPiPNS_10BufferInfoEj() { for(;;){} }
void _ZN4IPMI4impl10ClientImpl16invokeSyncMethodEjPKvmPiPvPmm() { for(;;){} }
void _ZN4IPMI4impl10ClientImpl17invokeAsyncMethodEjPKNS_8DataInfoEjPjPKNS_6Client12EventNotifeeE() { for(;;){} }
void _ZN4IPMI4impl10ClientImpl17invokeAsyncMethodEjPKvmPjPKNS_6Client12EventNotifeeE() { for(;;){} }
void _ZN4IPMI4impl10ClientImpl19terminateConnectionEv() { for(;;){} }
void _ZN4IPMI4impl10ClientImpl6getMsgEjPvPmmPj() { for(;;){} }
void _ZN4IPMI4impl10ClientImpl7connectEPKvmPi() { for(;;){} }
void _ZN4IPMI4impl10ClientImpl7destroyEv() { for(;;){} }
void _ZN4IPMI4impl10ClientImpl9tryGetMsgEjPvPmm() { for(;;){} }
void _ZN4IPMI4impl10ClientImplC1Ev() { for(;;){} }
void _ZN4IPMI4impl10ClientImplC2Ev() { for(;;){} }
void _ZN4IPMI4impl10ClientImplD0Ev() { for(;;){} }
void _ZN4IPMI4impl10ClientImplD1Ev() { for(;;){} }
void _ZN4IPMI4impl10ClientImplD2Ev() { for(;;){} }
void _ZN4IPMI4impl10ServerImpl11getUserDataEv() { for(;;){} }
void _ZN4IPMI4impl10ServerImpl11tryDispatchEPvm() { for(;;){} }
void _ZN4IPMI4impl10ServerImpl13createSessionEPPNS_7SessionEPvS5_() { for(;;){} }
void _ZN4IPMI4impl10ServerImpl13runDispatcherEPvm() { for(;;){} }
void _ZN4IPMI4impl10ServerImpl18shutdownDispatcherEv() { for(;;){} }
void _ZN4IPMI4impl10ServerImpl7destroyEv() { for(;;){} }
void _ZN4IPMI4impl10ServerImplC1Ev() { for(;;){} }
void _ZN4IPMI4impl10ServerImplC2Ev() { for(;;){} }
void _ZN4IPMI4impl10ServerImplD0Ev() { for(;;){} }
void _ZN4IPMI4impl10ServerImplD1Ev() { for(;;){} }
void _ZN4IPMI4impl10ServerImplD2Ev() { for(;;){} }
void _ZN4IPMI4impl11SessionImpl10trySendMsgEjPKvm() { for(;;){} }
void _ZN4IPMI4impl11SessionImpl11getUserDataEv() { for(;;){} }
void _ZN4IPMI4impl11SessionImpl11tryDispatchEPvm() { for(;;){} }
void _ZN4IPMI4impl11SessionImpl12getClientPidEv() { for(;;){} }
void _ZN4IPMI4impl11SessionImpl12setEventFlagEjm() { for(;;){} }
void _ZN4IPMI4impl11SessionImpl13emptyMsgQueueEj() { for(;;){} }
void _ZN4IPMI4impl11SessionImpl26respondToSyncMethodRequestEiPKNS_10BufferInfoEj() { for(;;){} }
void _ZN4IPMI4impl11SessionImpl26respondToSyncMethodRequestEiPKvm() { for(;;){} }
void _ZN4IPMI4impl11SessionImpl27respondToAsyncMethodRequestEjiPKvm() { for(;;){} }
void _ZN4IPMI4impl11SessionImpl27respondToAsyncMethodRequestEjjiPKNS_8DataInfoEj() { for(;;){} }
void _ZN4IPMI4impl11SessionImpl6getMsgEjPvPmmPj() { for(;;){} }
void _ZN4IPMI4impl11SessionImpl7destroyEv() { for(;;){} }
void _ZN4IPMI4impl11SessionImpl7sendMsgEjPKvmPj() { for(;;){} }
void _ZN4IPMI4impl11SessionImpl9getServerEv() { for(;;){} }
void _ZN4IPMI4impl11SessionImpl9tryGetMsgEjPvPmm() { for(;;){} }
void _ZN4IPMI4impl11SessionImplC1Ev() { for(;;){} }
void _ZN4IPMI4impl11SessionImplC2Ev() { for(;;){} }
void _ZN4IPMI4impl11SessionImplD0Ev() { for(;;){} }
void _ZN4IPMI4impl11SessionImplD1Ev() { for(;;){} }
void _ZN4IPMI4impl11SessionImplD2Ev() { for(;;){} }
void _ZN4IPMI6Client6Config14MsgQueueConfig20estimateMsgQueueSizeEmj() { for(;;){} }
void _ZN4IPMI6Client6Config14MsgQueueConfigC1Ev() { for(;;){} }
void _ZN4IPMI6Client6Config14MsgQueueConfigC2Ev() { for(;;){} }
void _ZN4IPMI6Client6Config24estimateClientMemorySizeEv() { for(;;){} }
void _ZN4IPMI6Client6Config26SyncMethodInvocationConfigC1Ev() { for(;;){} }
void _ZN4IPMI6Client6Config26SyncMethodInvocationConfigC2Ev() { for(;;){} }
void _ZN4IPMI6Client6Config27AsyncMethodInvocationConfigC1Ev() { for(;;){} }
void _ZN4IPMI6Client6Config27AsyncMethodInvocationConfigC2Ev() { for(;;){} }
void _ZN4IPMI6Client6ConfigC1Ev() { for(;;){} }
void _ZN4IPMI6Client6ConfigC2Ev() { for(;;){} }
void _ZN4IPMI6Client6createEPPS0_PKNS0_6ConfigEPvS6_() { for(;;){} }
void _ZN4IPMI6ClientC2Ev() { for(;;){} }
void _ZN4IPMI6ClientD0Ev() { for(;;){} }
void _ZN4IPMI6ClientD1Ev() { for(;;){} }
void _ZN4IPMI6ClientD2Ev() { for(;;){} }
void _ZN4IPMI6Server12EventHandler15onSessionKilledEPNS_7SessionE() { for(;;){} }
void _ZN4IPMI6Server12EventHandler20onSyncMethodDispatchEPNS_7SessionEjPKNS_8DataInfoEjPNS_10BufferInfoEj() { for(;;){} }
void _ZN4IPMI6Server12EventHandler21onAsyncMethodDispatchEPNS_7SessionEjjPKNS_8DataInfoEj() { for(;;){} }
void _ZN4IPMI6Server12EventHandlerD0Ev() { for(;;){} }
void _ZN4IPMI6Server12EventHandlerD1Ev() { for(;;){} }
void _ZN4IPMI6Server12EventHandlerD2Ev() { for(;;){} }
void _ZN4IPMI6Server6ConfigC1Ev() { for(;;){} }
void _ZN4IPMI6Server6ConfigC2Ev() { for(;;){} }
void _ZN4IPMI6Server6createEPPS0_PKNS0_6ConfigEPvS6_() { for(;;){} }
void _ZN4IPMI6ServerC2Ev() { for(;;){} }
void _ZN4IPMI6ServerD0Ev() { for(;;){} }
void _ZN4IPMI6ServerD1Ev() { for(;;){} }
void _ZN4IPMI6ServerD2Ev() { for(;;){} }
void _ZN4IPMI7Session6Config25estimateSessionMemorySizeEv() { for(;;){} }
void _ZN4IPMI7SessionC2Ev() { for(;;){} }
void _ZN4IPMI7SessionD0Ev() { for(;;){} }
void _ZN4IPMI7SessionD1Ev() { for(;;){} }
void _ZN4IPMI7SessionD2Ev() { for(;;){} }
void _ZNK4IPMI6Server6Config29estimateTempWorkingMemorySizeEv() { for(;;){} }
void _ZTVN4IPMI6Server12EventHandlerE() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}