/* Source generated by crazyvoids source generating tool **/
#include "libSceGameUpdate.h"

void sceGameUpdateAbortRequest() { for(;;){} }
void sceGameUpdateCheck() { for(;;){} }
void sceGameUpdateCreateRequest() { for(;;){} }
void sceGameUpdateDeleteRequest() { for(;;){} }
void sceGameUpdateInitialize() { for(;;){} }
void sceGameUpdateTerminate() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}