/* Source generated by crazyvoids source generating tool **/
#include "libSceNetCtlForNpToolkit.h"

void sceNetCtlCheckCallbackForNpToolkit() { for(;;){} }
void sceNetCtlClearEventForNpToolkit() { for(;;){} }
void sceNetCtlRegisterCallbackForNpToolkit() { for(;;){} }
void sceNetCtlUnregisterCallbackForNpToolkit() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}