/* Source generated by crazyvoids source generating tool **/
#include "libSceSystemServiceWebApp.h"

void sceSystemServiceLaunchWebApp() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}