/* Source generated by crazyvoids source generating tool **/
#include "libSceAudiodec.h"

void sceAudiodecClearContext() { for(;;){} }
void sceAudiodecCreateDecoder() { for(;;){} }
void sceAudiodecDecode() { for(;;){} }
void sceAudiodecDecode2() { for(;;){} }
void sceAudiodecDecode2WithPriority() { for(;;){} }
void sceAudiodecDecodeWithPriority() { for(;;){} }
void sceAudiodecDeleteDecoder() { for(;;){} }
void sceAudiodecInitLibrary() { for(;;){} }
void sceAudiodecTermLibrary() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}