/* Source generated by crazyvoids source generating tool **/
#include "libSceVrTrackerDeviceRejection.h"

void sceVrTrackerSetDeviceRejection() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}