/* Source generated by crazyvoids source generating tool **/
#include "libSceMoveTracker.h"

void sceMoveTrackerCalibrateReset() { for(;;){} }
void sceMoveTrackerCalibrateYaw() { for(;;){} }
void sceMoveTrackerCameraUpdate() { for(;;){} }
void sceMoveTrackerCaptureInit() { for(;;){} }
void sceMoveTrackerCaptureTerm() { for(;;){} }
void sceMoveTrackerControllersUpdate() { for(;;){} }
void sceMoveTrackerGetState() { for(;;){} }
void sceMoveTrackerGetVersion() { for(;;){} }
void sceMoveTrackerGetWorkingMemorySize() { for(;;){} }
void sceMoveTrackerInit() { for(;;){} }
void sceMoveTrackerPlayGetImages() { for(;;){} }
void sceMoveTrackerPlayGetStates() { for(;;){} }
void sceMoveTrackerPlayStart() { for(;;){} }
void sceMoveTrackerPlayStep() { for(;;){} }
void sceMoveTrackerRecordSave() { for(;;){} }
void sceMoveTrackerRecordStart() { for(;;){} }
void sceMoveTrackerRecordStop() { for(;;){} }
void sceMoveTrackerTerm() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}