/* Source generated by crazyvoids source generating tool **/
#include "libSceGameCustomDataDialogCompat.h"

void sceGameCustomDataDialogGetResult() { for(;;){} }
void sceGameCustomDataDialogOpen() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}