/* Source generated by crazyvoids source generating tool **/
#include "libSceNetBwe.h"

void sceNetBweCheckCallbackIpcInt() { for(;;){} }
void sceNetBweClearEventIpcInt() { for(;;){} }
void sceNetBweFinishInternetConnectionTestIpcInt() { for(;;){} }
void sceNetBweGetInfoIpcInt() { for(;;){} }
void sceNetBweRegisterCallbackIpcInt() { for(;;){} }
void sceNetBweSetInternetConnectionTestResultIpcInt() { for(;;){} }
void sceNetBweStartInternetConnectionTestBandwidthTestIpcInt() { for(;;){} }
void sceNetBweStartInternetConnectionTestIpcInt() { for(;;){} }
void sceNetBweUnregisterCallbackIpcInt() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}