/* Source generated by crazyvoids source generating tool **/
#include "libSceVdecsw.h"

void sceVdecswAllocateComputeQueue() { for(;;){} }
void sceVdecswCreateDecoder() { for(;;){} }
void sceVdecswDeleteDecoder() { for(;;){} }
void sceVdecswFinalizeDecodeSequence() { for(;;){} }
void sceVdecswGetAvcPictureInfo() { for(;;){} }
void sceVdecswGetHevcPictureInfo() { for(;;){} }
void sceVdecswGetPictureInfo() { for(;;){} }
void sceVdecswQueryComputeMemoryInfo() { for(;;){} }
void sceVdecswQueryDecoderMemoryInfo() { for(;;){} }
void sceVdecswReleaseComputeQueue() { for(;;){} }
void sceVdecswResetDecoder() { for(;;){} }
void sceVdecswSetDecodeInput() { for(;;){} }
void sceVdecswSetDecodeOutput() { for(;;){} }
void sceVdecswSyncDecodeInput() { for(;;){} }
void sceVdecswSyncDecodeOutput() { for(;;){} }
void sceVdecswTrySyncDecodeInput() { for(;;){} }
void sceVdecswTrySyncDecodeOutput() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}