/* Source generated by crazyvoids source generating tool **/
#include "libSceMusicCoreServerClientJsEx.h"

void sceMusicCoreServerCheckCoreStatus() { for(;;){} }
void sceMusicCoreServerRegistEventCallback() { for(;;){} }
void sceMusicCoreServerTriggerEvent() { for(;;){} }
void sceMusicCoreServerTriggerEventSync() { for(;;){} }
void sceMusicCoreServerTryLoadCore() { for(;;){} }
void sceMusicCoreServerUnregistEventCallback() { for(;;){} }
void sceMusicCoreServerUpdateSpWakeupAuthorityList() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}