/* Source generated by crazyvoids source generating tool **/
#include "libSceAudioIn.h"

void sceAudioInChangeAppModuleState() { for(;;){} }
void sceAudioInClose() { for(;;){} }
void sceAudioInCountPorts() { for(;;){} }
void sceAudioInDeviceHqOpen() { for(;;){} }
void sceAudioInDeviceIdHqOpen() { for(;;){} }
void sceAudioInDeviceIdOpen() { for(;;){} }
void sceAudioInDeviceOpen() { for(;;){} }
void sceAudioInDeviceOpenEx() { for(;;){} }
void sceAudioInExtClose() { for(;;){} }
void sceAudioInExtCtrl() { for(;;){} }
void sceAudioInExtInput() { for(;;){} }
void sceAudioInExtOpen() { for(;;){} }
void sceAudioInGetGain() { for(;;){} }
void sceAudioInGetHandleStatusInfo() { for(;;){} }
void sceAudioInGetRerouteCount() { for(;;){} }
void sceAudioInGetSilentState() { for(;;){} }
void sceAudioInHqOpen() { for(;;){} }
void sceAudioInHqOpenEx() { for(;;){} }
void sceAudioInInit() { for(;;){} }
void sceAudioInInput() { for(;;){} }
void sceAudioInInputs() { for(;;){} }
void sceAudioInIsSharedDevice() { for(;;){} }
void sceAudioInOpen() { for(;;){} }
void sceAudioInOpenEx() { for(;;){} }
void sceAudioInSetCompressorPreGain() { for(;;){} }
void sceAudioInSetConnections() { for(;;){} }
void sceAudioInSetConnectionsForUser() { for(;;){} }
void sceAudioInSetDevConnection() { for(;;){} }
void sceAudioInSetFocusForUser() { for(;;){} }
void sceAudioInSetMode() { for(;;){} }
void sceAudioInSetMode2() { for(;;){} }
void sceAudioInSetPortConnections() { for(;;){} }
void sceAudioInSetPortStatuses() { for(;;){} }
void sceAudioInSetSparkParam() { for(;;){} }
void sceAudioInSetSparkSideTone() { for(;;){} }
void sceAudioInSetUsbGain() { for(;;){} }
void sceAudioInSetUserMute() { for(;;){} }
void sceAudioInVmicCreate() { for(;;){} }
void sceAudioInVmicDestroy() { for(;;){} }
void sceAudioInVmicWrite() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}