/* Source generated by crazyvoids source generating tool **/
#include "libSceAvSetting.h"

void sceAvSettingAddCallbacks() { for(;;){} }
void sceAvSettingAddCallbacksForLnc() { for(;;){} }
void sceAvSettingAddCallbacksForSocialScreen() { for(;;){} }
void sceAvSettingCallbackFuncsInit() { for(;;){} }
void sceAvSettingCallbackFuncsInit_() { for(;;){} }
void sceAvSettingCallbackFuncsInitForLnc() { for(;;){} }
void sceAvSettingCallbackFuncsInitForLnc_() { for(;;){} }
void sceAvSettingChangeOutputMode() { for(;;){} }
void sceAvSettingChangeOutputMode2() { for(;;){} }
void sceAvSettingChangeOutputMode3() { for(;;){} }
void sceAvSettingChangeOutputModeForDiag() { for(;;){} }
void sceAvSettingChangeProcessAttribute() { for(;;){} }
void sceAvSettingCheckCallback() { for(;;){} }
void sceAvSettingControlHdcpEncryption() { for(;;){} }
void sceAvSettingDriverChangeConnectionStatus() { for(;;){} }
void sceAvSettingDriverUpdateStatus() { for(;;){} }
void sceAvSettingEnterAudioMuteForShutdown() { for(;;){} }
void sceAvSettingGetCurrentDeviceInfo_() { for(;;){} }
void sceAvSettingGetCurrentHdmiDeviceId() { for(;;){} }
void sceAvSettingGetCurrentOutputMode_() { for(;;){} }
void sceAvSettingGetCurrentOutputMode2_() { for(;;){} }
void sceAvSettingGetDetailedHdcpStatus() { for(;;){} }
void sceAvSettingGetDeviceInfo() { for(;;){} }
void sceAvSettingGetHdcpStatus() { for(;;){} }
void sceAvSettingGetHdmiConnectDisconnectNum() { for(;;){} }
void sceAvSettingGetHdmiKsvList() { for(;;){} }
void sceAvSettingGetHdmiMonitorInfo() { for(;;){} }
void sceAvSettingGetHdmiRawEdid() { for(;;){} }
void sceAvSettingGetMorpheusPuStatus() { for(;;){} }
void sceAvSettingGetNativeHdmiMonitorInfo() { for(;;){} }
void sceAvSettingGetRawHdmiMonitorInfo() { for(;;){} }
void sceAvSettingInit() { for(;;){} }
void sceAvSettingIsSupportedAudioOutModeByHdmiMonitorInfo() { for(;;){} }
void sceAvSettingIsSupportedHdcpVersionByHdmiMonitorInfo() { for(;;){} }
void sceAvSettingIsSupportedVideoOutModeByHdmiMonitorInfo() { for(;;){} }
void sceAvSettingIsSuspendedProcessOutputModeAvailable() { for(;;){} }
void sceAvSettingIsSuspendedProcessOutputModeAvailable2() { for(;;){} }
void sceAvSettingIsVrSupportedByHdmiMonitorInfo2() { for(;;){} }
void sceAvSettingNotifyAudioOutMode() { for(;;){} }
void sceAvSettingNotifyResponseForSocialScreen() { for(;;){} }
void sceAvSettingNotifyUmdEvent() { for(;;){} }
void sceAvSettingNotifyVideoOutMode() { for(;;){} }
void sceAvSettingRemoveCallbacks() { for(;;){} }
void sceAvSettingRemoveProcessOutputMode() { for(;;){} }
void sceAvSettingSet2dVrMode() { for(;;){} }
void sceAvSettingSetAudioOutModeAny_() { for(;;){} }
void sceAvSettingSetAudioOutModeInvalid_() { for(;;){} }
void sceAvSettingSetAvOutputMode() { for(;;){} }
void sceAvSettingSetDispclk() { for(;;){} }
void sceAvSettingSetDisplayBlackLevel() { for(;;){} }
void sceAvSettingSetHdcpMode() { for(;;){} }
void sceAvSettingSetHdcpStatus() { for(;;){} }
void sceAvSettingSetHdmiGamutMetadata_() { for(;;){} }
void sceAvSettingSetVideoOutModeAny_() { for(;;){} }
void sceAvSettingSetVideoOutModeInvalid_() { for(;;){} }
void sceAvSettingSetVideoOutputColorEffect() { for(;;){} }
void sceAvSettingSetVideoOutSource() { for(;;){} }
void sceAvSettingSimulateProcessOutputModeArbitration_() { for(;;){} }
void sceAvSettingTerm() { for(;;){} }
void sceAvSettingWaitCallback() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}