/* Source generated by crazyvoids source generating tool **/
#include "libSceWebBrowserInjectedBundle.h"

void WKBundleInitialize() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}