/* Source generated by crazyvoids source generating tool **/
#include "libSceSigninDialog.h"

void sceSigninDialogClose() { for(;;){} }
void sceSigninDialogGetResult() { for(;;){} }
void sceSigninDialogGetStatus() { for(;;){} }
void sceSigninDialogInitialize() { for(;;){} }
void sceSigninDialogOpen() { for(;;){} }
void sceSigninDialogTerminate() { for(;;){} }
void sceSigninDialogUpdateStatus() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}