/* Source generated by crazyvoids source generating tool **/
#include "libSceNetCtlApDialog.h"

void sceNetCtlApDialogClose() { for(;;){} }
void sceNetCtlApDialogGetResult() { for(;;){} }
void sceNetCtlApDialogGetStatus() { for(;;){} }
void sceNetCtlApDialogInitialize() { for(;;){} }
void sceNetCtlApDialogOpen() { for(;;){} }
void sceNetCtlApDialogTerminate() { for(;;){} }
void sceNetCtlApDialogUpdateStatus() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}