/* Source generated by crazyvoids source generating tool **/
#include "libSceContentBinder.h"

void sceContentBinderEnd() { for(;;){} }
void sceContentBinderGetNumOfDifference() { for(;;){} }
void sceContentBinderInitialize() { for(;;){} }
void sceContentBinderIsUpdated() { for(;;){} }
void sceContentBinderReset() { for(;;){} }
void sceContentBinderSearchDifference() { for(;;){} }
void sceContentBinderStart() { for(;;){} }
void sceContentBinderTerminate() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}