/* Source generated by crazyvoids source generating tool **/
#include "libSceNetDebug.h"

void sceNetEmulationGet() { for(;;){} }
void sceNetEmulationSet() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}