/* Source generated by crazyvoids source generating tool **/
#include "libSceSystemServicePs2Emu.h"

void sceSystemServiceAddLocalProcessForPs2Emu() { for(;;){} }
void sceSystemServiceGetParentSocketForPs2Emu() { for(;;){} }
void sceSystemServiceKillLocalProcessForPs2Emu() { for(;;){} }
void sceSystemServiceShowImposeMenuForPs2Emu() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}