/* Source generated by crazyvoids source generating tool **/
#include "libSceAbstractStorage.h"

void _ZN15AbstractStorage12Serializable12readExternalESt10shared_ptrINS_7ContentEE() { for(;;){} }
void _ZN15AbstractStorage12Serializable13writeExternalESt10shared_ptrINS_7ContentEE() { for(;;){} }
void _ZN15AbstractStorage12SerializableC1Ev() { for(;;){} }
void _ZN15AbstractStorage12SerializableC2Ev() { for(;;){} }
void _ZN15AbstractStorage12SerializableD1Ev() { for(;;){} }
void _ZN15AbstractStorage12SerializableD2Ev() { for(;;){} }
void _ZN15AbstractStorage14MemfileContent12readExternalESt10shared_ptrINS_7ContentEE() { for(;;){} }
void _ZN15AbstractStorage14MemfileContent13writeExternalESt10shared_ptrINS_7ContentEE() { for(;;){} }
void _ZN15AbstractStorage14MemfileContent4OpenEit() { for(;;){} }
void _ZN15AbstractStorage14MemfileContent4ReadEPvlPl() { for(;;){} }
void _ZN15AbstractStorage14MemfileContent5CloseEv() { for(;;){} }
void _ZN15AbstractStorage14MemfileContent5FlushEv() { for(;;){} }
void _ZN15AbstractStorage14MemfileContent5WriteEPKvlPl() { for(;;){} }
void _ZN15AbstractStorage14MemfileContent6RemoveEv() { for(;;){} }
void _ZN15AbstractStorage14MemfileContent8SeekByteEliPl() { for(;;){} }
void _ZN15AbstractStorage14MemfileContent8SeekTimeElPl() { for(;;){} }
void _ZN15AbstractStorage14MemfileContentD0Ev() { for(;;){} }
void _ZN15AbstractStorage14MemfileContentD1Ev() { for(;;){} }
void _ZN15AbstractStorage14MemfileContentD2Ev() { for(;;){} }
void _ZN15AbstractStorage14StorageManager10GetStorageERKSbIcSt11char_traitsIcENS_8StlAllocIcEEEPSt10shared_ptrINS_7StorageEE() { for(;;){} }
void _ZN15AbstractStorage14StorageManager10InitializeEv() { for(;;){} }
void _ZN15AbstractStorage14StorageManager10m_instanceE() { for(;;){} }
void _ZN15AbstractStorage14StorageManager11GetInstanceERNS_12MemAllocatorEPv() { for(;;){} }
void _ZN15AbstractStorage14StorageManager11GetInstanceEv() { for(;;){} }
void _ZN15AbstractStorage14StorageManager12NotifyCreateERKSbIcSt11char_traitsIcENS_8StlAllocIcEEEb() { for(;;){} }
void _ZN15AbstractStorage14StorageManager12NotifyRemoveERKSbIcSt11char_traitsIcENS_8StlAllocIcEEEb() { for(;;){} }
void _ZN15AbstractStorage14StorageManager15ReleaseInstanceEv() { for(;;){} }
void _ZN15AbstractStorage14StorageManager16get_storage_nameERKSbIcSt11char_traitsIcENS_8StlAllocIcEEE() { for(;;){} }
void _ZN15AbstractStorage14StorageManager16NotifyWriteCloseERKSbIcSt11char_traitsIcENS_8StlAllocIcEEE() { for(;;){} }
void _ZN15AbstractStorage14StorageManager16RegisterListenerEPNS_17ItemEventListenerE() { for(;;){} }
void _ZN15AbstractStorage14StorageManager16RegisterListenerEPNS_20StorageEventListenerE() { for(;;){} }
void _ZN15AbstractStorage14StorageManager17NotifySetMetadataERKSbIcSt11char_traitsIcENS_8StlAllocIcEEE() { for(;;){} }
void _ZN15AbstractStorage14StorageManager18GetStorageNameListEPSt6vectorISbIcSt11char_traitsIcENS_8StlAllocIcEEESaIS6_EE() { for(;;){} }
void _ZN15AbstractStorage14StorageManager18UnregisterListenerEPKNS_17ItemEventListenerE() { for(;;){} }
void _ZN15AbstractStorage14StorageManager18UnregisterListenerEPKNS_20StorageEventListenerE() { for(;;){} }
void _ZN15AbstractStorage14StorageManager20get_service_instanceENS_11ServiceTypeE() { for(;;){} }
void _ZN15AbstractStorage14StorageManager21NotifyStorageAttachedERKSbIcSt11char_traitsIcENS_8StlAllocIcEEENS_11ServiceTypeE() { for(;;){} }
void _ZN15AbstractStorage14StorageManager21NotifyStorageDetachedERKSbIcSt11char_traitsIcENS_8StlAllocIcEEE() { for(;;){} }
void _ZN15AbstractStorage14StorageManager4FreeEPv() { for(;;){} }
void _ZN15AbstractStorage14StorageManager4LoadENS_11ServiceTypeE() { for(;;){} }
void _ZN15AbstractStorage14StorageManager6MallocEm() { for(;;){} }
void _ZN15AbstractStorage14StorageManager6UnloadENS_11ServiceTypeE() { for(;;){} }
void _ZN15AbstractStorage14StorageManager6UpdateENS_11ServiceTypeE() { for(;;){} }
void _ZN15AbstractStorage14StorageManager9TerminateEv() { for(;;){} }
void _ZN15AbstractStorage14StorageManagerC1Ev() { for(;;){} }
void _ZN15AbstractStorage14StorageManagerC2Ev() { for(;;){} }
void _ZN15AbstractStorage14StorageManagerD1Ev() { for(;;){} }
void _ZN15AbstractStorage14StorageManagerD2Ev() { for(;;){} }
void _ZN15AbstractStorage15HttpTransaction15ReceiveResponseERSbIcSt11char_traitsIcENS_8StlAllocIcEEERiS6_() { for(;;){} }
void _ZN15AbstractStorage15HttpTransaction15SendHttpRequestERKSbIcSt11char_traitsIcENS_8StlAllocIcEEEiRKSt3mapIS5_S5_St4lessIS5_ESaISt4pairIS6_S5_EEEmb() { for(;;){} }
void _ZN15AbstractStorage15HttpTransaction4InitEv() { for(;;){} }
void _ZN15AbstractStorage15HttpTransaction4TermEv() { for(;;){} }
void _ZN15AbstractStorage15HttpTransaction8SendDataEPKvm() { for(;;){} }
void _ZN15AbstractStorage15HttpTransactionC1Ev() { for(;;){} }
void _ZN15AbstractStorage15HttpTransactionC2Ev() { for(;;){} }
void _ZN15AbstractStorage15HttpTransactionD1Ev() { for(;;){} }
void _ZN15AbstractStorage15HttpTransactionD2Ev() { for(;;){} }
void _ZN15AbstractStorage4Item11GetPathNameEv() { for(;;){} }
void _ZN15AbstractStorage4Item11SetMetadataEPN23sceMetadataReaderWriter8MetadataE() { for(;;){} }
void _ZN15AbstractStorage4Item13ParseMetadataEPN23sceMetadataReaderWriter8MetadataES3_() { for(;;){} }
void _ZN15AbstractStorage4Item14GetStorageNameEv() { for(;;){} }
void _ZN15AbstractStorage4Item6RenameERKSbIcSt11char_traitsIcENS_8StlAllocIcEEE() { for(;;){} }
void _ZN15AbstractStorage4Item7GetNameERKSbIcSt11char_traitsIcENS_8StlAllocIcEEE() { for(;;){} }
void _ZN15AbstractStorage4Item7GetNameEv() { for(;;){} }
void _ZN15AbstractStorage4Item8set_metaERN23sceMetadataReaderWriter8MetadataERKSbIcSt11char_traitsIcENS_8StlAllocIcEEEm() { for(;;){} }
void _ZN15AbstractStorage4Item8set_metaERN23sceMetadataReaderWriter8MetadataERKSbIcSt11char_traitsIcENS_8StlAllocIcEEESA_() { for(;;){} }
void _ZN15AbstractStorage4ItemC2ERKSbIcSt11char_traitsIcENS_8StlAllocIcEEE() { for(;;){} }
void _ZN15AbstractStorage4ItemD0Ev() { for(;;){} }
void _ZN15AbstractStorage4ItemD1Ev() { for(;;){} }
void _ZN15AbstractStorage4ItemD2Ev() { for(;;){} }
void _ZN15AbstractStorage4ItemdlEPv() { for(;;){} }
void _ZN15AbstractStorage4ItemnwEm() { for(;;){} }
void _ZN15AbstractStorage6FolderC2ERKSbIcSt11char_traitsIcENS_8StlAllocIcEEE() { for(;;){} }
void _ZN15AbstractStorage6FolderD0Ev() { for(;;){} }
void _ZN15AbstractStorage6FolderD1Ev() { for(;;){} }
void _ZN15AbstractStorage6FolderD2Ev() { for(;;){} }
void _ZN15AbstractStorage7AbsFreeEPv() { for(;;){} }
void _ZN15AbstractStorage7Content12GetExtensionERKSbIcSt11char_traitsIcENS_8StlAllocIcEEE() { for(;;){} }
void _ZN15AbstractStorage7Content12GetMimeTypesEv() { for(;;){} }
void _ZN15AbstractStorage7Content6RenameERKSbIcSt11char_traitsIcENS_8StlAllocIcEEE() { for(;;){} }
void _ZN15AbstractStorage7ContentC2ERKSbIcSt11char_traitsIcENS_8StlAllocIcEEE() { for(;;){} }
void _ZN15AbstractStorage7ContentD0Ev() { for(;;){} }
void _ZN15AbstractStorage7ContentD1Ev() { for(;;){} }
void _ZN15AbstractStorage7ContentD2Ev() { for(;;){} }
void _ZN15AbstractStorage7Service11NextStorageERSbIcSt11char_traitsIcENS_8StlAllocIcEEE() { for(;;){} }
void _ZN15AbstractStorage7Service13CreateStorageERKSbIcSt11char_traitsIcENS_8StlAllocIcEEEPSt10shared_ptrINS_7StorageEE() { for(;;){} }
void _ZN15AbstractStorage7Service18clear_storage_listEv() { for(;;){} }
void _ZN15AbstractStorage7Service4LoadENS_11ServiceTypeE() { for(;;){} }
void _ZN15AbstractStorage7Service4StopEv() { for(;;){} }
void _ZN15AbstractStorage7Service5StartEv() { for(;;){} }
void _ZN15AbstractStorage7Service6UnLoadEPS0_() { for(;;){} }
void _ZN15AbstractStorage7ServiceC2Ev() { for(;;){} }
void _ZN15AbstractStorage7ServiceD0Ev() { for(;;){} }
void _ZN15AbstractStorage7ServiceD1Ev() { for(;;){} }
void _ZN15AbstractStorage7ServiceD2Ev() { for(;;){} }
void _ZN15AbstractStorage7StorageC2ERKSbIcSt11char_traitsIcENS_8StlAllocIcEEE() { for(;;){} }
void _ZN15AbstractStorage7StorageD0Ev() { for(;;){} }
void _ZN15AbstractStorage7StorageD1Ev() { for(;;){} }
void _ZN15AbstractStorage7StorageD2Ev() { for(;;){} }
void _ZN15AbstractStorage9AbsMallocEm() { for(;;){} }
void _ZNK15AbstractStorage14MemfileContent10GetServiceEv() { for(;;){} }
void _ZNK15AbstractStorage14MemfileContent13GetCapabilityEv() { for(;;){} }
void _ZNK15AbstractStorage14MemfileContent7GetStatEPNS_4StatE() { for(;;){} }
void _ZNK15AbstractStorage4Item12GetThumbnailEPSt10shared_ptrINS_7ContentEE() { for(;;){} }
void _ZNK15AbstractStorage4Item15CreateThumbnailEPvPSt10shared_ptrINS_7ContentEE() { for(;;){} }
void _ZNK15AbstractStorage6Folder7GetTypeEv() { for(;;){} }
void _ZNK15AbstractStorage7Content7GetTypeEv() { for(;;){} }
void _ZNK15AbstractStorage7Storage7GetTypeEv() { for(;;){} }
void _ZTVN15AbstractStorage12SerializableE() { for(;;){} }
void _ZTVN15AbstractStorage14MemfileContentE() { for(;;){} }
void _ZTVN15AbstractStorage4ItemE() { for(;;){} }
void _ZTVN15AbstractStorage6FolderE() { for(;;){} }
void _ZTVN15AbstractStorage7ContentE() { for(;;){} }
void _ZTVN15AbstractStorage7ServiceE() { for(;;){} }
void _ZTVN15AbstractStorage7StorageE() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}