/* Source generated by crazyvoids source generating tool **/
#include "libSceShareUtility.h"

void sceShareUtilityAdvanceFromFileWithContentIdList() { for(;;){} }
void sceShareUtilityAdvanceFromFileWithTitleIdList() { for(;;){} }
void sceShareUtilityAdvanceGetServiceInfo() { for(;;){} }
void sceShareUtilityAdvanceInitialize() { for(;;){} }
void sceShareUtilityAdvanceQueryServiceInfoA() { for(;;){} }
void sceShareUtilityAdvanceSetUploadContentData() { for(;;){} }
void sceShareUtilityAdvanceTerminate() { for(;;){} }
void sceShareUtilityAdvanceValidateContents() { for(;;){} }
void sceShareUtilityAdvanceWakeUpShareMenu() { for(;;){} }
void sceShareUtilityAdvanceWakeUpShareMenuBroadcast() { for(;;){} }
void sceShareUtilityAdvanceWakeUpShareMenuDefault() { for(;;){} }
void sceShareUtilityAdvanceWakeUpShareMenuForShareContent() { for(;;){} }
void sceShareUtilityInitialize() { for(;;){} }
void sceShareUtilityInitializeEx2() { for(;;){} }
void sceShareUtilityOpenShareMenu() { for(;;){} }
void sceShareUtilityOpenShareMenuBroadcast() { for(;;){} }
void sceShareUtilityOpenShareMenuDefault() { for(;;){} }
void sceShareUtilityOpenShareMenuForShareContent() { for(;;){} }
void sceShareUtilityTerminate() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}