/* Source generated by crazyvoids source generating tool **/
#include "libSceSystemServiceTournamentMlg.h"

void sceSystemServiceLaunchTournamentList() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}