/* Source generated by crazyvoids source generating tool **/
#include "libSceVrServiceDialog.h"

void sceVrServiceDialogClose() { for(;;){} }
void sceVrServiceDialogGetResult() { for(;;){} }
void sceVrServiceDialogGetStatus() { for(;;){} }
void sceVrServiceDialogInitialize() { for(;;){} }
void sceVrServiceDialogOpen() { for(;;){} }
void sceVrServiceDialogTerminate() { for(;;){} }
void sceVrServiceDialogUpdateStatus() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}