/* Source generated by crazyvoids source generating tool **/
#include "libSceSaveDataDialog.h"

void sceSaveDataDialogClose() { for(;;){} }
void sceSaveDataDialogGetResult() { for(;;){} }
void sceSaveDataDialogGetStatus() { for(;;){} }
void sceSaveDataDialogInitialize() { for(;;){} }
void sceSaveDataDialogIsReadyToDisplay() { for(;;){} }
void sceSaveDataDialogOpen() { for(;;){} }
void sceSaveDataDialogProgressBarInc() { for(;;){} }
void sceSaveDataDialogProgressBarSetValue() { for(;;){} }
void sceSaveDataDialogTerminate() { for(;;){} }
void sceSaveDataDialogUpdateStatus() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}