/* Source generated by crazyvoids source generating tool **/
#include "libSceOpusCeltDec.h"

void sceOpusCeltDecCreate() { for(;;){} }
void sceOpusCeltDecCtl() { for(;;){} }
void sceOpusCeltDecDecode() { for(;;){} }
void sceOpusCeltDecDecodeFloat() { for(;;){} }
void sceOpusCeltDecDecodeFloatWithPriority() { for(;;){} }
void sceOpusCeltDecDecodeWithPriority() { for(;;){} }
void sceOpusCeltDecDestroy() { for(;;){} }
void sceOpusCeltDecGetSize() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}