/* Source generated by crazyvoids source generating tool **/
#include "libSceAjm.h"

void sceAjmBatchCancel() { for(;;){} }
void sceAjmBatchErrorDump() { for(;;){} }
void sceAjmBatchJobControlBufferRa() { for(;;){} }
void sceAjmBatchJobInlineBuffer() { for(;;){} }
void sceAjmBatchJobRunBufferRa() { for(;;){} }
void sceAjmBatchJobRunSplitBufferRa() { for(;;){} }
void sceAjmBatchStartBuffer() { for(;;){} }
void sceAjmBatchWait() { for(;;){} }
void sceAjmDecAt9ParseConfigData() { for(;;){} }
void sceAjmDecMp3ParseFrame() { for(;;){} }
void sceAjmFinalize() { for(;;){} }
void sceAjmInitialize() { for(;;){} }
void sceAjmInstanceCodecType() { for(;;){} }
void sceAjmInstanceCreate() { for(;;){} }
void sceAjmInstanceDestroy() { for(;;){} }
void sceAjmInstanceExtend() { for(;;){} }
void sceAjmInstanceSwitch() { for(;;){} }
void sceAjmMemoryRegister() { for(;;){} }
void sceAjmMemoryUnregister() { for(;;){} }
void sceAjmModuleRegister() { for(;;){} }
void sceAjmModuleUnregister() { for(;;){} }
void sceAjmStrError() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}