/* Source generated by crazyvoids source generating tool **/
#include "libSceSystemServiceStore.h"

void sceSystemServiceLaunchStore() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}