/* Source generated by crazyvoids source generating tool **/
#include "libScePad.h"

void scePadClose() { for(;;){} }
void scePadConnectPort() { for(;;){} }
void scePadDeviceClassGetExtendedInformation() { for(;;){} }
void scePadDeviceClassParseData() { for(;;){} }
void scePadDeviceOpen() { for(;;){} }
void scePadDisableVibration() { for(;;){} }
void scePadDisconnectDevice() { for(;;){} }
void scePadDisconnectPort() { for(;;){} }
void scePadEnableAutoDetect() { for(;;){} }
void scePadEnableExtensionPort() { for(;;){} }
void scePadEnableSpecificDeviceClass() { for(;;){} }
void scePadEnableUsbConnection() { for(;;){} }
void scePadGetBluetoothAddress() { for(;;){} }
void scePadGetCapability() { for(;;){} }
void scePadGetControllerInformation() { for(;;){} }
void scePadGetDataInternal() { for(;;){} }
void scePadGetDeviceId() { for(;;){} }
void scePadGetDeviceInfo() { for(;;){} }
void scePadGetExtControllerInformation() { for(;;){} }
void scePadGetExtensionUnitInfo() { for(;;){} }
void scePadGetFeatureReport() { for(;;){} }
void scePadGetHandle() { for(;;){} }
void scePadGetIdleCount() { for(;;){} }
void scePadGetInfo() { for(;;){} }
void scePadGetInfoByPortType() { for(;;){} }
void scePadGetLicenseControllerInformation() { for(;;){} }
void scePadGetMotionSensorPosition() { for(;;){} }
void scePadGetMotionTimerUnit() { for(;;){} }
void scePadGetSphereRadius() { for(;;){} }
void scePadGetVersionInfo() { for(;;){} }
void scePadInit() { for(;;){} }
void scePadIsBlasterConnected() { for(;;){} }
void scePadIsDS4Connected() { for(;;){} }
void scePadIsLightBarBaseBrightnessControllable() { for(;;){} }
void scePadIsMoveConnected() { for(;;){} }
void scePadIsMoveReproductionModel() { for(;;){} }
void scePadIsValidHandle() { for(;;){} }
void scePadMbusInit() { for(;;){} }
void scePadMbusTerm() { for(;;){} }
void scePadOpen() { for(;;){} }
void scePadOpenExt() { for(;;){} }
void scePadOpenExt2() { for(;;){} }
void scePadOutputReport() { for(;;){} }
void scePadRead() { for(;;){} }
void scePadReadBlasterForTracker() { for(;;){} }
void scePadReadExt() { for(;;){} }
void scePadReadForTracker() { for(;;){} }
void scePadReadHistory() { for(;;){} }
void scePadReadState() { for(;;){} }
void scePadReadStateExt() { for(;;){} }
void scePadResetLightBar() { for(;;){} }
void scePadResetLightBarAll() { for(;;){} }
void scePadResetLightBarAllByPortType() { for(;;){} }
void scePadResetOrientation() { for(;;){} }
void scePadResetOrientationForTracker() { for(;;){} }
void scePadSetAngularVelocityDeadbandState() { for(;;){} }
void scePadSetAutoPowerOffCount() { for(;;){} }
void scePadSetButtonRemappingInfo() { for(;;){} }
void scePadSetConnection() { for(;;){} }
void scePadSetExtensionReport() { for(;;){} }
void scePadSetFeatureReport() { for(;;){} }
void scePadSetForceIntercepted() { for(;;){} }
void scePadSetLightBar() { for(;;){} }
void scePadSetLightBarBaseBrightness() { for(;;){} }
void scePadSetLightBarBlinking() { for(;;){} }
void scePadSetLightBarForTracker() { for(;;){} }
void scePadSetLoginUserNumber() { for(;;){} }
void scePadSetMotionSensorState() { for(;;){} }
void scePadSetProcessFocus() { for(;;){} }
void scePadSetProcessPrivilege() { for(;;){} }
void scePadSetProcessPrivilegeOfButtonRemapping() { for(;;){} }
void scePadSetTiltCorrectionState() { for(;;){} }
void scePadSetUserColor() { for(;;){} }
void scePadSetVibration() { for(;;){} }
void scePadSetVibrationForce() { for(;;){} }
void scePadSetVrTrackingMode() { for(;;){} }
void scePadShareOutputData() { for(;;){} }
void scePadStartRecording() { for(;;){} }
void scePadStopRecording() { for(;;){} }
void scePadSwitchConnection() { for(;;){} }
void scePadVertualDeviceAddDevice() { for(;;){} }
void scePadVirtualDeviceAddDevice() { for(;;){} }
void scePadVirtualDeviceDeleteDevice() { for(;;){} }
void scePadVirtualDeviceGetRemoteSetting() { for(;;){} }
void scePadVirtualDeviceInsertData() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}