/* Source generated by crazyvoids source generating tool **/
#include "libSceNpAuth.h"

void sceNpAuthAbortRequest() { for(;;){} }
void sceNpAuthCreateAsyncRequest() { for(;;){} }
void sceNpAuthCreateRequest() { for(;;){} }
void sceNpAuthDeleteRequest() { for(;;){} }
void sceNpAuthGetAuthorizationCode() { for(;;){} }
void sceNpAuthGetAuthorizationCodeA() { for(;;){} }
void sceNpAuthGetIdToken() { for(;;){} }
void sceNpAuthGetIdTokenA() { for(;;){} }
void sceNpAuthPollAsync() { for(;;){} }
void sceNpAuthSetTimeout() { for(;;){} }
void sceNpAuthWaitAsync() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}