/* Source generated by crazyvoids source generating tool **/
#include "libSceAbstractYoutube.h"

void _ZN15AbstractStorage10YoutubeAPI11SendContentEPKvl() { for(;;){} }
void _ZN15AbstractStorage10YoutubeAPI14SetAccessTokenERKSbIcSt11char_traitsIcENS_8StlAllocIcEEE() { for(;;){} }
void _ZN15AbstractStorage10YoutubeAPI17GetUploadLocationERKSbIcSt11char_traitsIcENS_8StlAllocIcEEEmS7_RS5_() { for(;;){} }
void _ZN15AbstractStorage10YoutubeAPI5StartERKSbIcSt11char_traitsIcENS_8StlAllocIcEEE() { for(;;){} }
void _ZN15AbstractStorage10YoutubeAPI6ResumeERSbIcSt11char_traitsIcENS_8StlAllocIcEEERlm() { for(;;){} }
void _ZN15AbstractStorage10YoutubeAPI7SuspendEv() { for(;;){} }
void _ZN15AbstractStorage10YoutubeAPI8initHttpEv() { for(;;){} }
void _ZN15AbstractStorage10YoutubeAPI8termHttpEv() { for(;;){} }
void _ZN15AbstractStorage10YoutubeAPIC1Ev() { for(;;){} }
void _ZN15AbstractStorage10YoutubeAPIC2Ev() { for(;;){} }
void _ZN15AbstractStorage10YoutubeAPID1Ev() { for(;;){} }
void _ZN15AbstractStorage10YoutubeAPID2Ev() { for(;;){} }
void _ZN15AbstractStorage13YoutubeFolder10NewContentERKSbIcSt11char_traitsIcENS_8StlAllocIcEEEPSt10shared_ptrINS_7ContentEE() { for(;;){} }
void _ZN15AbstractStorage13YoutubeFolder12RemoveFolderERKSbIcSt11char_traitsIcENS_8StlAllocIcEEEb() { for(;;){} }
void _ZN15AbstractStorage13YoutubeFolder13RemoveContentERKSbIcSt11char_traitsIcENS_8StlAllocIcEEE() { for(;;){} }
void _ZN15AbstractStorage13YoutubeFolder4OpenENS_8ItemTypeE() { for(;;){} }
void _ZN15AbstractStorage13YoutubeFolder5CloseEv() { for(;;){} }
void _ZN15AbstractStorage13YoutubeFolder6RemoveEb() { for(;;){} }
void _ZN15AbstractStorage13YoutubeFolder9NewFolderERKSbIcSt11char_traitsIcENS_8StlAllocIcEEEPSt10shared_ptrINS_6FolderEE() { for(;;){} }
void _ZN15AbstractStorage13YoutubeFolderC1ERKSbIcSt11char_traitsIcENS_8StlAllocIcEEEb() { for(;;){} }
void _ZN15AbstractStorage13YoutubeFolderC2ERKSbIcSt11char_traitsIcENS_8StlAllocIcEEEb() { for(;;){} }
void _ZN15AbstractStorage13YoutubeFolderD0Ev() { for(;;){} }
void _ZN15AbstractStorage13YoutubeFolderD1Ev() { for(;;){} }
void _ZN15AbstractStorage13YoutubeFolderD2Ev() { for(;;){} }
void _ZN15AbstractStorage14YoutubeContent11SetMetadataEPN23sceMetadataReaderWriter8MetadataE() { for(;;){} }
void _ZN15AbstractStorage14YoutubeContent12readExternalESt10shared_ptrINS_7ContentEE() { for(;;){} }
void _ZN15AbstractStorage14YoutubeContent13ParseMetadataEPN23sceMetadataReaderWriter8MetadataES3_() { for(;;){} }
void _ZN15AbstractStorage14YoutubeContent13writeExternalESt10shared_ptrINS_7ContentEE() { for(;;){} }
void _ZN15AbstractStorage14YoutubeContent4OpenEit() { for(;;){} }
void _ZN15AbstractStorage14YoutubeContent4ReadEPvlPl() { for(;;){} }
void _ZN15AbstractStorage14YoutubeContent5CloseEv() { for(;;){} }
void _ZN15AbstractStorage14YoutubeContent5FlushEv() { for(;;){} }
void _ZN15AbstractStorage14YoutubeContent5WriteEPKvlPl() { for(;;){} }
void _ZN15AbstractStorage14YoutubeContent6RemoveEv() { for(;;){} }
void _ZN15AbstractStorage14YoutubeContent6RenameERKSbIcSt11char_traitsIcENS_8StlAllocIcEEE() { for(;;){} }
void _ZN15AbstractStorage14YoutubeContent8SeekByteEliPl() { for(;;){} }
void _ZN15AbstractStorage14YoutubeContent8SeekTimeElPl() { for(;;){} }
void _ZN15AbstractStorage14YoutubeContentC1ERKSbIcSt11char_traitsIcENS_8StlAllocIcEEEb() { for(;;){} }
void _ZN15AbstractStorage14YoutubeContentC2ERKSbIcSt11char_traitsIcENS_8StlAllocIcEEEb() { for(;;){} }
void _ZN15AbstractStorage14YoutubeContentD0Ev() { for(;;){} }
void _ZN15AbstractStorage14YoutubeContentD1Ev() { for(;;){} }
void _ZN15AbstractStorage14YoutubeContentD2Ev() { for(;;){} }
void _ZN15AbstractStorage14YoutubeService13SearchStorageEv() { for(;;){} }
void _ZN15AbstractStorage14YoutubeService23create_storage_instanceERKSbIcSt11char_traitsIcENS_8StlAllocIcEEE() { for(;;){} }
void _ZN15AbstractStorage14YoutubeService4StopEv() { for(;;){} }
void _ZN15AbstractStorage14YoutubeService5StartEv() { for(;;){} }
void _ZN15AbstractStorage14YoutubeServiceC1Ev() { for(;;){} }
void _ZN15AbstractStorage14YoutubeServiceC2Ev() { for(;;){} }
void _ZN15AbstractStorage14YoutubeServiceD0Ev() { for(;;){} }
void _ZN15AbstractStorage14YoutubeServiceD1Ev() { for(;;){} }
void _ZN15AbstractStorage14YoutubeServiceD2Ev() { for(;;){} }
void _ZN15AbstractStorage14YoutubeStorage10GetContentERKSbIcSt11char_traitsIcENS_8StlAllocIcEEEPSt10shared_ptrINS_7ContentEE() { for(;;){} }
void _ZN15AbstractStorage14YoutubeStorage11DeserializeESt10shared_ptrINS_7ContentEEPS1_INS_4ItemEE() { for(;;){} }
void _ZN15AbstractStorage14YoutubeStorage13GetRootFolderEPSt10shared_ptrINS_6FolderEE() { for(;;){} }
void _ZN15AbstractStorage14YoutubeStorage14GetStorageSizeEPlS1_S1_() { for(;;){} }
void _ZN15AbstractStorage14YoutubeStorage15CreateRecursiveERKSbIcSt11char_traitsIcENS_8StlAllocIcEEENS_8ItemTypeEPSt10shared_ptrINS_4ItemEE() { for(;;){} }
void _ZN15AbstractStorage14YoutubeStorage15RemoveRecursiveERKSbIcSt11char_traitsIcENS_8StlAllocIcEEE() { for(;;){} }
void _ZN15AbstractStorage14YoutubeStorage7GetItemERKSbIcSt11char_traitsIcENS_8StlAllocIcEEEPSt10shared_ptrINS_4ItemEE() { for(;;){} }
void _ZN15AbstractStorage14YoutubeStorage7IsExistERKSbIcSt11char_traitsIcENS_8StlAllocIcEEE() { for(;;){} }
void _ZN15AbstractStorage14YoutubeStorage9GetForderERKSbIcSt11char_traitsIcENS_8StlAllocIcEEEPSt10shared_ptrINS_6FolderEE() { for(;;){} }
void _ZN15AbstractStorage14YoutubeStorage9SerializeESt10shared_ptrINS_7ContentEES1_INS_4ItemEE() { for(;;){} }
void _ZN15AbstractStorage14YoutubeStorageC1ERKSbIcSt11char_traitsIcENS_8StlAllocIcEEE() { for(;;){} }
void _ZN15AbstractStorage14YoutubeStorageC2ERKSbIcSt11char_traitsIcENS_8StlAllocIcEEE() { for(;;){} }
void _ZN15AbstractStorage14YoutubeStorageD0Ev() { for(;;){} }
void _ZN15AbstractStorage14YoutubeStorageD1Ev() { for(;;){} }
void _ZN15AbstractStorage14YoutubeStorageD2Ev() { for(;;){} }
void _ZNK15AbstractStorage13YoutubeFolder10GetServiceEv() { for(;;){} }
void _ZNK15AbstractStorage13YoutubeFolder13GetCapabilityEv() { for(;;){} }
void _ZNK15AbstractStorage13YoutubeFolder7GetStatEPNS_4StatE() { for(;;){} }
void _ZNK15AbstractStorage14YoutubeContent10GetServiceEv() { for(;;){} }
void _ZNK15AbstractStorage14YoutubeContent13GetCapabilityEv() { for(;;){} }
void _ZNK15AbstractStorage14YoutubeContent7GetStatEPNS_4StatE() { for(;;){} }
void _ZNK15AbstractStorage14YoutubeService14GetServiceTypeEv() { for(;;){} }
void _ZNK15AbstractStorage14YoutubeStorage10GetServiceEv() { for(;;){} }
void _ZNK15AbstractStorage14YoutubeStorage13GetCapabilityEv() { for(;;){} }
void _ZNK15AbstractStorage14YoutubeStorage7GetStatEPNS_4StatE() { for(;;){} }
void _ZTVN15AbstractStorage13YoutubeFolderE() { for(;;){} }
void _ZTVN15AbstractStorage14YoutubeContentE() { for(;;){} }
void _ZTVN15AbstractStorage14YoutubeServiceE() { for(;;){} }
void _ZTVN15AbstractStorage14YoutubeStorageE() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}