/* Source generated by crazyvoids source generating tool **/
#include "libSceSystemServiceSuspend.h"

void sceSystemServiceDeclareReadyForSuspend() { for(;;){} }
void sceSystemServiceDisableSuspendNotification() { for(;;){} }
void sceSystemServiceEnableSuspendNotification() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}