/* Source generated by crazyvoids source generating tool **/
#include "libSceProfileCacheExternal.h"

void sceProfileCacheGetAvatar() { for(;;){} }
void sceProfileCacheGetProfilePicture() { for(;;){} }
void sceProfileCacheGetTrueName() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}