/* Source generated by crazyvoids source generating tool **/
#include "libSceDbgAudioOut.h"

void sceAudioOutSetSystemDebugState() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}