/* Source generated by crazyvoids source generating tool **/
#include "libSceNetCtlAp.h"

void sceNetCtlApCheckCallback() { for(;;){} }
void sceNetCtlApClearEvent() { for(;;){} }
void sceNetCtlApGetConnectInfo() { for(;;){} }
void sceNetCtlApGetInfo() { for(;;){} }
void sceNetCtlApGetResult() { for(;;){} }
void sceNetCtlApGetState() { for(;;){} }
void sceNetCtlApInit() { for(;;){} }
void sceNetCtlApRegisterCallback() { for(;;){} }
void sceNetCtlApStop() { for(;;){} }
void sceNetCtlApTerm() { for(;;){} }
void sceNetCtlApUnregisterCallback() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}