/* Source generated by crazyvoids source generating tool **/
#include "libSceTextToSpeech.h"

void sceTextToSpeechCancelImpl() { for(;;){} }
void sceTextToSpeechCloseImpl() { for(;;){} }
void sceTextToSpeechGetStatusImpl() { for(;;){} }
void sceTextToSpeechInitImpl() { for(;;){} }
void sceTextToSpeechOpenImpl() { for(;;){} }
void sceTextToSpeechPauseImpl() { for(;;){} }
void sceTextToSpeechResumeImpl() { for(;;){} }
void sceTextToSpeechSpeakContinuousImpl() { for(;;){} }
void sceTextToSpeechSpeakImpl() { for(;;){} }
void sceTextToSpeechTermImpl() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}