/* Source generated by crazyvoids source generating tool **/
#include "libSceCustomMusicCore.h"

void sceCustomMusicCoreBgmClose() { for(;;){} }
void sceCustomMusicCoreBgmOpen() { for(;;){} }
void sceCustomMusicCoreBgmOpen2() { for(;;){} }
void sceCustomMusicCoreBgmOutput() { for(;;){} }
void sceCustomMusicCoreBgmSetAudioVolume() { for(;;){} }
void sceCustomMusicCoreBgmStart() { for(;;){} }
void sceCustomMusicCoreBgmStop() { for(;;){} }
void sceCustomMusicCoreGetBgmAuthorityStatus() { for(;;){} }
void sceCustomMusicCoreGetHdcpStatus() { for(;;){} }
void sceCustomMusicCoreGetSystemAudioVolume() { for(;;){} }
void sceCustomMusicCorePostEvent() { for(;;){} }
void sceCustomMusicCoreSendEvent() { for(;;){} }
void sceCustomMusicCoreSendMulticastEvent() { for(;;){} }
void sceCustomMusicCoreSendSpMessage() { for(;;){} }
void sceCustomMusicCoreSetSystemAudioVolume() { for(;;){} }
void sceCustomMusicCoreStartOperation() { for(;;){} }
void sceCustomMusicCoreStartOperation2() { for(;;){} }
void sceCustomMusicCoreStopOperation() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}