/* Source generated by crazyvoids source generating tool **/
#include "libSceNpWebApi.h"

void sceNpWebApiAbortHandle() { for(;;){} }
void sceNpWebApiAbortRequest() { for(;;){} }
void sceNpWebApiAddHttpRequestHeader() { for(;;){} }
void sceNpWebApiAddMultipartPart() { for(;;){} }
void sceNpWebApiCheckTimeout() { for(;;){} }
void sceNpWebApiClearAllUnusedConnection() { for(;;){} }
void sceNpWebApiClearUnusedConnection() { for(;;){} }
void sceNpWebApiCreateContext() { for(;;){} }
void sceNpWebApiCreateContextA() { for(;;){} }
void sceNpWebApiCreateExtdPushEventFilter() { for(;;){} }
void sceNpWebApiCreateHandle() { for(;;){} }
void sceNpWebApiCreateMultipartRequest() { for(;;){} }
void sceNpWebApiCreatePushEventFilter() { for(;;){} }
void sceNpWebApiCreateRequest() { for(;;){} }
void sceNpWebApiCreateServicePushEventFilter() { for(;;){} }
void sceNpWebApiDeleteContext() { for(;;){} }
void sceNpWebApiDeleteExtdPushEventFilter() { for(;;){} }
void sceNpWebApiDeleteHandle() { for(;;){} }
void sceNpWebApiDeletePushEventFilter() { for(;;){} }
void sceNpWebApiDeleteRequest() { for(;;){} }
void sceNpWebApiDeleteServicePushEventFilter() { for(;;){} }
void sceNpWebApiGetConnectionStats() { for(;;){} }
void sceNpWebApiGetErrorCode() { for(;;){} }
void sceNpWebApiGetHttpResponseHeaderValue() { for(;;){} }
void sceNpWebApiGetHttpResponseHeaderValueLength() { for(;;){} }
void sceNpWebApiGetHttpStatusCode() { for(;;){} }
void sceNpWebApiGetMemoryPoolStats() { for(;;){} }
void sceNpWebApiInitialize() { for(;;){} }
void sceNpWebApiInitializeForPresence() { for(;;){} }
void sceNpWebApiIntCreateCtxIndExtdPushEventFilter() { for(;;){} }
void sceNpWebApiIntCreateRequest() { for(;;){} }
void sceNpWebApiIntCreateServicePushEventFilter() { for(;;){} }
void sceNpWebApiIntInitialize() { for(;;){} }
void sceNpWebApiIntRegisterServicePushEventCallback() { for(;;){} }
void sceNpWebApiIntRegisterServicePushEventCallbackA() { for(;;){} }
void sceNpWebApiReadData() { for(;;){} }
void sceNpWebApiRegisterExtdPushEventCallback() { for(;;){} }
void sceNpWebApiRegisterExtdPushEventCallbackA() { for(;;){} }
void sceNpWebApiRegisterNotificationCallback() { for(;;){} }
void sceNpWebApiRegisterPushEventCallback() { for(;;){} }
void sceNpWebApiRegisterServicePushEventCallback() { for(;;){} }
void sceNpWebApiSendMultipartRequest() { for(;;){} }
void sceNpWebApiSendMultipartRequest2() { for(;;){} }
void sceNpWebApiSendRequest() { for(;;){} }
void sceNpWebApiSendRequest2() { for(;;){} }
void sceNpWebApiSetHandleTimeout() { for(;;){} }
void sceNpWebApiSetMaxConnection() { for(;;){} }
void sceNpWebApiSetMultipartContentType() { for(;;){} }
void sceNpWebApiSetRequestTimeout() { for(;;){} }
void sceNpWebApiTerminate() { for(;;){} }
void sceNpWebApiUnregisterExtdPushEventCallback() { for(;;){} }
void sceNpWebApiUnregisterNotificationCallback() { for(;;){} }
void sceNpWebApiUnregisterPushEventCallback() { for(;;){} }
void sceNpWebApiUnregisterServicePushEventCallback() { for(;;){} }
void sceNpWebApiUtilityParseNpId() { for(;;){} }
void sceNpWebApiVshInitialize() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}