/* Source generated by crazyvoids source generating tool **/
#include "libSceNpCommerce.h"

void sceNpCommerceDialogClose() { for(;;){} }
void sceNpCommerceDialogGetResult() { for(;;){} }
void sceNpCommerceDialogGetStatus() { for(;;){} }
void sceNpCommerceDialogInitialize() { for(;;){} }
void sceNpCommerceDialogInitializeInternal() { for(;;){} }
void sceNpCommerceDialogOpen() { for(;;){} }
void sceNpCommerceDialogTerminate() { for(;;){} }
void sceNpCommerceDialogUpdateStatus() { for(;;){} }
void sceNpCommerceHidePsStoreIcon() { for(;;){} }
void sceNpCommerceSetPsStoreIconLayout() { for(;;){} }
void sceNpCommerceShowPsStoreIcon() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}