/* Source generated by crazyvoids source generating tool **/
#include "libSceMusicCoreServerClient.h"

void sceMusicCoreServerForceKillCurrentCore() { for(;;){} }
void sceMusicCoreServerGetCoreInfo() { for(;;){} }
void sceMusicCoreServerGetEvent() { for(;;){} }
void sceMusicCoreServerGetPlayStartCondition() { for(;;){} }
void sceMusicCoreServerGetPlayStatus() { for(;;){} }
void sceMusicCoreServerGetSpTrackInfo() { for(;;){} }
void sceMusicCoreServerGetSpWakeupAuthorityList() { for(;;){} }
void sceMusicCoreServerGetStatusOfTracks() { for(;;){} }
void sceMusicCoreServerGetTitleId() { for(;;){} }
void sceMusicCoreServerGetTrackInfo() { for(;;){} }
void sceMusicCoreServerInitialize() { for(;;){} }
void sceMusicCoreServerKillCurrentCore() { for(;;){} }
void sceMusicCoreServerLaunchSpCore() { for(;;){} }
void sceMusicCoreServerLaunchUsbMusicCore() { for(;;){} }
void sceMusicCoreServerPlayControl() { for(;;){} }
void sceMusicCoreServerPlaySpUri() { for(;;){} }
void sceMusicCoreServerSetAudioVolume() { for(;;){} }
void sceMusicCoreServerSetRepeatMode() { for(;;){} }
void sceMusicCoreServerSetShuffle() { for(;;){} }
void sceMusicCoreServerSetSpWakeupAuthorityList() { for(;;){} }
void sceMusicCoreServerSetTrackList() { for(;;){} }
void sceMusicCoreServerTerminate() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}