/* Source generated by crazyvoids source generating tool **/
#include "libSceNpFriendListDialog.h"

void sceNpFriendListDialogClose() { for(;;){} }
void sceNpFriendListDialogGetResult() { for(;;){} }
void sceNpFriendListDialogGetResultA() { for(;;){} }
void sceNpFriendListDialogGetStatus() { for(;;){} }
void sceNpFriendListDialogInitialize() { for(;;){} }
void sceNpFriendListDialogOpen() { for(;;){} }
void sceNpFriendListDialogOpenA() { for(;;){} }
void sceNpFriendListDialogTerminate() { for(;;){} }
void sceNpFriendListDialogUpdateStatus() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}