/* Source generated by crazyvoids source generating tool **/
#include "libSceWkFontConfig.h"

void _Z5dummyv() { for(;;){} }
void sceWkFontConfigGetAttr() { for(;;){} }
void sceWkFontConfigGetFont() { for(;;){} }
void sceWkFontConfigGetFontFromFontName() { for(;;){} }
void sceWkFontConfigGetFontName() { for(;;){} }
void sceWkFontConfigGetFontPath() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}