/* Source generated by crazyvoids source generating tool **/
#include "libSceNpSnsYouTubeDialog.h"

void sceNpSnsYouTubeDialogClose() { for(;;){} }
void sceNpSnsYouTubeDialogGetResult() { for(;;){} }
void sceNpSnsYouTubeDialogGetStatus() { for(;;){} }
void sceNpSnsYouTubeDialogInitialize() { for(;;){} }
void sceNpSnsYouTubeDialogOpen() { for(;;){} }
void sceNpSnsYouTubeDialogTerminate() { for(;;){} }
void sceNpSnsYouTubeDialogUpdateStatus() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}