/* Source generated by crazyvoids source generating tool **/
#include "libSceAvSettingDebug.h"

void sceAvSettingDebugAddCallbacks() { for(;;){} }
void sceAvSettingDebugClearDiagCommand() { for(;;){} }
void sceAvSettingDebugSetDiagState() { for(;;){} }
void sceAvSettingDebugSetHdmiMonitorInfo() { for(;;){} }
void sceAvSettingDebugSetProcessAttribute() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}