/* Source generated by crazyvoids source generating tool **/
#include "libSceGnmDebugModuleReset.h"

void sceGnmDebugModuleReset() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}