/* Source generated by crazyvoids source generating tool **/
#include "libSceNpScore.h"

void sceNpScoreAbortRequest() { for(;;){} }
void sceNpScoreCensorComment() { for(;;){} }
void sceNpScoreCensorCommentAsync() { for(;;){} }
void sceNpScoreChangeModeForOtherSaveDataOwners() { for(;;){} }
void sceNpScoreCreateNpTitleCtx() { for(;;){} }
void sceNpScoreCreateNpTitleCtxA() { for(;;){} }
void sceNpScoreCreateRequest() { for(;;){} }
void sceNpScoreCreateTitleCtx() { for(;;){} }
void sceNpScoreDeleteNpTitleCtx() { for(;;){} }
void sceNpScoreDeleteRequest() { for(;;){} }
void sceNpScoreGetBoardInfo() { for(;;){} }
void sceNpScoreGetBoardInfoAsync() { for(;;){} }
void sceNpScoreGetFriendsRanking() { for(;;){} }
void sceNpScoreGetFriendsRankingA() { for(;;){} }
void sceNpScoreGetFriendsRankingAAsync() { for(;;){} }
void sceNpScoreGetFriendsRankingAsync() { for(;;){} }
void sceNpScoreGetFriendsRankingForCrossSave() { for(;;){} }
void sceNpScoreGetFriendsRankingForCrossSaveAsync() { for(;;){} }
void sceNpScoreGetGameData() { for(;;){} }
void sceNpScoreGetGameDataAsync() { for(;;){} }
void sceNpScoreGetGameDataByAccountId() { for(;;){} }
void sceNpScoreGetGameDataByAccountIdAsync() { for(;;){} }
void sceNpScoreGetRankingByAccountId() { for(;;){} }
void sceNpScoreGetRankingByAccountIdAsync() { for(;;){} }
void sceNpScoreGetRankingByAccountIdForCrossSave() { for(;;){} }
void sceNpScoreGetRankingByAccountIdForCrossSaveAsync() { for(;;){} }
void sceNpScoreGetRankingByAccountIdPcId() { for(;;){} }
void sceNpScoreGetRankingByAccountIdPcIdAsync() { for(;;){} }
void sceNpScoreGetRankingByAccountIdPcIdForCrossSave() { for(;;){} }
void sceNpScoreGetRankingByAccountIdPcIdForCrossSaveAsync() { for(;;){} }
void sceNpScoreGetRankingByNpId() { for(;;){} }
void sceNpScoreGetRankingByNpIdAsync() { for(;;){} }
void sceNpScoreGetRankingByNpIdPcId() { for(;;){} }
void sceNpScoreGetRankingByNpIdPcIdAsync() { for(;;){} }
void sceNpScoreGetRankingByRange() { for(;;){} }
void sceNpScoreGetRankingByRangeA() { for(;;){} }
void sceNpScoreGetRankingByRangeAAsync() { for(;;){} }
void sceNpScoreGetRankingByRangeAsync() { for(;;){} }
void sceNpScoreGetRankingByRangeForCrossSave() { for(;;){} }
void sceNpScoreGetRankingByRangeForCrossSaveAsync() { for(;;){} }
void sceNpScorePollAsync() { for(;;){} }
void sceNpScoreRecordGameData() { for(;;){} }
void sceNpScoreRecordGameDataAsync() { for(;;){} }
void sceNpScoreRecordScore() { for(;;){} }
void sceNpScoreRecordScoreAsync() { for(;;){} }
void sceNpScoreSanitizeComment() { for(;;){} }
void sceNpScoreSanitizeCommentAsync() { for(;;){} }
void sceNpScoreSetPlayerCharacterId() { for(;;){} }
void sceNpScoreSetThreadParam() { for(;;){} }
void sceNpScoreSetTimeout() { for(;;){} }
void sceNpScoreWaitAsync() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}