/* Source generated by crazyvoids source generating tool **/
#include "libSceAbstractLocal.h"

void _ZN15AbstractStorage11LocalFolder10NewContentERKSbIcSt11char_traitsIcENS_8StlAllocIcEEEPSt10shared_ptrINS_7ContentEE() { for(;;){} }
void _ZN15AbstractStorage11LocalFolder12readExternalESt10shared_ptrINS_7ContentEE() { for(;;){} }
void _ZN15AbstractStorage11LocalFolder12RemoveFolderERKSbIcSt11char_traitsIcENS_8StlAllocIcEEEb() { for(;;){} }
void _ZN15AbstractStorage11LocalFolder13RemoveContentERKSbIcSt11char_traitsIcENS_8StlAllocIcEEE() { for(;;){} }
void _ZN15AbstractStorage11LocalFolder13writeExternalESt10shared_ptrINS_7ContentEE() { for(;;){} }
void _ZN15AbstractStorage11LocalFolder4OpenENS_8ItemTypeE() { for(;;){} }
void _ZN15AbstractStorage11LocalFolder5CloseEv() { for(;;){} }
void _ZN15AbstractStorage11LocalFolder6RemoveEb() { for(;;){} }
void _ZN15AbstractStorage11LocalFolder8NextItemEPSt10shared_ptrINS_4ItemEE() { for(;;){} }
void _ZN15AbstractStorage11LocalFolder9NewFolderERKSbIcSt11char_traitsIcENS_8StlAllocIcEEEPSt10shared_ptrINS_6FolderEE() { for(;;){} }
void _ZN15AbstractStorage11LocalFolderC1ERKSbIcSt11char_traitsIcENS_8StlAllocIcEEE() { for(;;){} }
void _ZN15AbstractStorage11LocalFolderC2ERKSbIcSt11char_traitsIcENS_8StlAllocIcEEE() { for(;;){} }
void _ZN15AbstractStorage11LocalFolderD0Ev() { for(;;){} }
void _ZN15AbstractStorage11LocalFolderD1Ev() { for(;;){} }
void _ZN15AbstractStorage11LocalFolderD2Ev() { for(;;){} }
void _ZN15AbstractStorage12LocalContent12readExternalESt10shared_ptrINS_7ContentEE() { for(;;){} }
void _ZN15AbstractStorage12LocalContent13ParseMetadataEPN23sceMetadataReaderWriter8MetadataES3_() { for(;;){} }
void _ZN15AbstractStorage12LocalContent13writeExternalESt10shared_ptrINS_7ContentEE() { for(;;){} }
void _ZN15AbstractStorage12LocalContent4OpenEit() { for(;;){} }
void _ZN15AbstractStorage12LocalContent4ReadEPvlPl() { for(;;){} }
void _ZN15AbstractStorage12LocalContent5CloseEv() { for(;;){} }
void _ZN15AbstractStorage12LocalContent5FlushEv() { for(;;){} }
void _ZN15AbstractStorage12LocalContent5WriteEPKvlPl() { for(;;){} }
void _ZN15AbstractStorage12LocalContent6RemoveEv() { for(;;){} }
void _ZN15AbstractStorage12LocalContent6RenameERKSbIcSt11char_traitsIcENS_8StlAllocIcEEE() { for(;;){} }
void _ZN15AbstractStorage12LocalContent8SeekByteEliPl() { for(;;){} }
void _ZN15AbstractStorage12LocalContent8SeekTimeElPl() { for(;;){} }
void _ZN15AbstractStorage12LocalContentC1ERKSbIcSt11char_traitsIcENS_8StlAllocIcEEE() { for(;;){} }
void _ZN15AbstractStorage12LocalContentC2ERKSbIcSt11char_traitsIcENS_8StlAllocIcEEE() { for(;;){} }
void _ZN15AbstractStorage12LocalContentD0Ev() { for(;;){} }
void _ZN15AbstractStorage12LocalContentD1Ev() { for(;;){} }
void _ZN15AbstractStorage12LocalContentD2Ev() { for(;;){} }
void _ZN15AbstractStorage12LocalService13SearchStorageEv() { for(;;){} }
void _ZN15AbstractStorage12LocalService18append_storagelistERKSbIcSt11char_traitsIcENS_8StlAllocIcEEEb() { for(;;){} }
void _ZN15AbstractStorage12LocalService19isSandBoxRandomWordERKSbIcSt11char_traitsIcENS_8StlAllocIcEEE() { for(;;){} }
void _ZN15AbstractStorage12LocalService20GetSandBoxRandomWordEv() { for(;;){} }
void _ZN15AbstractStorage12LocalService23create_storage_instanceERKSbIcSt11char_traitsIcENS_8StlAllocIcEEE() { for(;;){} }
void _ZN15AbstractStorage12LocalService4StopEv() { for(;;){} }
void _ZN15AbstractStorage12LocalService5StartEv() { for(;;){} }
void _ZN15AbstractStorage12LocalServiceC1Ev() { for(;;){} }
void _ZN15AbstractStorage12LocalServiceC2Ev() { for(;;){} }
void _ZN15AbstractStorage12LocalServiceD0Ev() { for(;;){} }
void _ZN15AbstractStorage12LocalServiceD1Ev() { for(;;){} }
void _ZN15AbstractStorage12LocalServiceD2Ev() { for(;;){} }
void _ZN15AbstractStorage12LocalStorage11DeserializeESt10shared_ptrINS_7ContentEEPS1_INS_4ItemEE() { for(;;){} }
void _ZN15AbstractStorage12LocalStorage12readExternalESt10shared_ptrINS_7ContentEE() { for(;;){} }
void _ZN15AbstractStorage12LocalStorage13GetRootFolderEPSt10shared_ptrINS_6FolderEE() { for(;;){} }
void _ZN15AbstractStorage12LocalStorage13writeExternalESt10shared_ptrINS_7ContentEE() { for(;;){} }
void _ZN15AbstractStorage12LocalStorage14GetStorageSizeEPlS1_S1_() { for(;;){} }
void _ZN15AbstractStorage12LocalStorage15CreateRecursiveERKSbIcSt11char_traitsIcENS_8StlAllocIcEEENS_8ItemTypeEPSt10shared_ptrINS_4ItemEE() { for(;;){} }
void _ZN15AbstractStorage12LocalStorage15RemoveRecursiveERKSbIcSt11char_traitsIcENS_8StlAllocIcEEE() { for(;;){} }
void _ZN15AbstractStorage12LocalStorage5ChModERKSbIcSt11char_traitsIcENS_8StlAllocIcEEEt() { for(;;){} }
void _ZN15AbstractStorage12LocalStorage7GetItemERKSbIcSt11char_traitsIcENS_8StlAllocIcEEEPSt10shared_ptrINS_4ItemEE() { for(;;){} }
void _ZN15AbstractStorage12LocalStorage7IsExistERKSbIcSt11char_traitsIcENS_8StlAllocIcEEE() { for(;;){} }
void _ZN15AbstractStorage12LocalStorage9SerializeESt10shared_ptrINS_7ContentEES1_INS_4ItemEE() { for(;;){} }
void _ZN15AbstractStorage12LocalStorageC1ERKSbIcSt11char_traitsIcENS_8StlAllocIcEEE() { for(;;){} }
void _ZN15AbstractStorage12LocalStorageC2ERKSbIcSt11char_traitsIcENS_8StlAllocIcEEE() { for(;;){} }
void _ZN15AbstractStorage12LocalStorageD0Ev() { for(;;){} }
void _ZN15AbstractStorage12LocalStorageD1Ev() { for(;;){} }
void _ZN15AbstractStorage12LocalStorageD2Ev() { for(;;){} }
void _ZNK15AbstractStorage11LocalFolder10GetServiceEv() { for(;;){} }
void _ZNK15AbstractStorage11LocalFolder13GetCapabilityEv() { for(;;){} }
void _ZNK15AbstractStorage11LocalFolder7GetStatEPNS_4StatE() { for(;;){} }
void _ZNK15AbstractStorage12LocalContent10GetServiceEv() { for(;;){} }
void _ZNK15AbstractStorage12LocalContent13GetCapabilityEv() { for(;;){} }
void _ZNK15AbstractStorage12LocalContent7GetStatEPNS_4StatE() { for(;;){} }
void _ZNK15AbstractStorage12LocalService14GetServiceTypeEv() { for(;;){} }
void _ZNK15AbstractStorage12LocalStorage10GetServiceEv() { for(;;){} }
void _ZNK15AbstractStorage12LocalStorage13GetCapabilityEv() { for(;;){} }
void _ZNK15AbstractStorage12LocalStorage7GetStatEPNS_4StatE() { for(;;){} }
void _ZTVN15AbstractStorage11LocalFolderE() { for(;;){} }
void _ZTVN15AbstractStorage12LocalContentE() { for(;;){} }
void _ZTVN15AbstractStorage12LocalServiceE() { for(;;){} }
void _ZTVN15AbstractStorage12LocalStorageE() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}