/* Source generated by crazyvoids source generating tool **/
#include "libSceRazorCpu.h"

void sceRazorCpuBeginLogicalFileAccess() { for(;;){} }
void sceRazorCpuDisableFiberUserMarkers() { for(;;){} }
void sceRazorCpuEndLogicalFileAccess() { for(;;){} }
void sceRazorCpuFiberLogNameChange() { for(;;){} }
void sceRazorCpuFiberSwitch() { for(;;){} }
void sceRazorCpuFlushOccurred() { for(;;){} }
void sceRazorCpuGetDataTagStorageSize() { for(;;){} }
void sceRazorCpuGpuMarkerSync() { for(;;){} }
void sceRazorCpuInitDataTags() { for(;;){} }
void sceRazorCpuInitializeGpuMarkerContext() { for(;;){} }
void sceRazorCpuInitializeInternal() { for(;;){} }
void sceRazorCpuIsCapturing() { for(;;){} }
void sceRazorCpuJobManagerDispatch() { for(;;){} }
void sceRazorCpuJobManagerJob() { for(;;){} }
void sceRazorCpuJobManagerSequence() { for(;;){} }
void sceRazorCpuPlotValue() { for(;;){} }
void sceRazorCpuPopMarker() { for(;;){} }
void sceRazorCpuPushMarker() { for(;;){} }
void sceRazorCpuPushMarkerStatic() { for(;;){} }
void sceRazorCpuResizeTaggedBuffer() { for(;;){} }
void sceRazorCpuSetPopMarkerCallback() { for(;;){} }
void sceRazorCpuSetPushMarkerCallback() { for(;;){} }
void sceRazorCpuSetPushMarkerStaticCallback() { for(;;){} }
void sceRazorCpuShutdownDataTags() { for(;;){} }
void sceRazorCpuStartCaptureInternal() { for(;;){} }
void sceRazorCpuStopCaptureInternal() { for(;;){} }
void sceRazorCpuSync() { for(;;){} }
void sceRazorCpuTagArray() { for(;;){} }
void sceRazorCpuTagBuffer() { for(;;){} }
void sceRazorCpuUnTagBuffer() { for(;;){} }
void sceRazorCpuWriteBookmark() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}