/* Source generated by crazyvoids source generating tool **/
#include "libSceIme.h"

void FinalizeImeModule() { for(;;){} }
void InitializeImeModule() { for(;;){} }
void sceImeClose() { for(;;){} }
void sceImeConfigGet() { for(;;){} }
void sceImeConfigSet() { for(;;){} }
void sceImeConfirmCandidate() { for(;;){} }
void sceImeDicAddWord() { for(;;){} }
void sceImeDicDeleteLearnDics() { for(;;){} }
void sceImeDicDeleteUserDics() { for(;;){} }
void sceImeDicDeleteWord() { for(;;){} }
void sceImeDicGetWords() { for(;;){} }
void sceImeDicReplaceWord() { for(;;){} }
void sceImeDisableController() { for(;;){} }
void sceImeFilterText() { for(;;){} }
void sceImeForTestFunction() { for(;;){} }
void sceImeGetPanelPositionAndForm() { for(;;){} }
void sceImeGetPanelSize() { for(;;){} }
void sceImeKeyboardClose() { for(;;){} }
void sceImeKeyboardGetInfo() { for(;;){} }
void sceImeKeyboardGetResourceId() { for(;;){} }
void sceImeKeyboardOpen() { for(;;){} }
void sceImeKeyboardOpenInternal() { for(;;){} }
void sceImeKeyboardSetMode() { for(;;){} }
void sceImeKeyboardUpdate() { for(;;){} }
void sceImeOpen() { for(;;){} }
void sceImeOpenInternal() { for(;;){} }
void sceImeParamInit() { for(;;){} }
void sceImeSetCandidateIndex() { for(;;){} }
void sceImeSetCaret() { for(;;){} }
void sceImeSetText() { for(;;){} }
void sceImeSetTextGeometry() { for(;;){} }
void sceImeUpdate() { for(;;){} }
void sceImeVshClearPreedit() { for(;;){} }
void sceImeVshClose() { for(;;){} }
void sceImeVshConfirmPreedit() { for(;;){} }
void sceImeVshDisableController() { for(;;){} }
void sceImeVshGetPanelPositionAndForm() { for(;;){} }
void sceImeVshInformConfirmdString() { for(;;){} }
void sceImeVshInformConfirmdString2() { for(;;){} }
void sceImeVshOpen() { for(;;){} }
void sceImeVshSendTextInfo() { for(;;){} }
void sceImeVshSetCaretGeometry() { for(;;){} }
void sceImeVshSetCaretIndexInPreedit() { for(;;){} }
void sceImeVshSetPanelPosition() { for(;;){} }
void sceImeVshSetParam() { for(;;){} }
void sceImeVshSetPreeditGeometry() { for(;;){} }
void sceImeVshSetSelectGeometry() { for(;;){} }
void sceImeVshSetSelectionText() { for(;;){} }
void sceImeVshUpdate() { for(;;){} }
void sceImeVshUpdateContext() { for(;;){} }
void sceImeVshUpdateContext2() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}