/* Source generated by crazyvoids source generating tool **/
#include "libSceVrTracker.h"

void sceVrTrackerCpuProcess() { for(;;){} }
void sceVrTrackerGetPlayAreaWarningInfo() { for(;;){} }
void sceVrTrackerGetResult() { for(;;){} }
void sceVrTrackerGetTime() { for(;;){} }
void sceVrTrackerGpuSubmit() { for(;;){} }
void sceVrTrackerGpuWait() { for(;;){} }
void sceVrTrackerGpuWaitAndCpuProcess() { for(;;){} }
void sceVrTrackerInit() { for(;;){} }
void sceVrTrackerNotifyEndOfCpuProcess() { for(;;){} }
void sceVrTrackerQueryMemory() { for(;;){} }
void sceVrTrackerRecalibrate() { for(;;){} }
void sceVrTrackerRegisterDevice() { for(;;){} }
void sceVrTrackerRegisterDeviceInternal() { for(;;){} }
void sceVrTrackerResetAll() { for(;;){} }
void sceVrTrackerResetOrientationRelative() { for(;;){} }
void sceVrTrackerSaveInternalBuffers() { for(;;){} }
void sceVrTrackerSetDurationUntilStatusNotTracking() { for(;;){} }
void sceVrTrackerSetExtendedMode() { for(;;){} }
void sceVrTrackerSetLEDBrightness() { for(;;){} }
void sceVrTrackerSetRestingMode() { for(;;){} }
void sceVrTrackerTerm() { for(;;){} }
void sceVrTrackerUnregisterDevice() { for(;;){} }
void sceVrTrackerUpdateMotionSensorData() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}