/* Source generated by crazyvoids source generating tool **/
#include "libSceUsbd.h"

void sceUsbdAllocTransfer() { for(;;){} }
void sceUsbdAttachKernelDriver() { for(;;){} }
void sceUsbdBulkTransfer() { for(;;){} }
void sceUsbdCancelTransfer() { for(;;){} }
void sceUsbdCheckConnected() { for(;;){} }
void sceUsbdClaimInterface() { for(;;){} }
void sceUsbdClearHalt() { for(;;){} }
void sceUsbdClose() { for(;;){} }
void sceUsbdControlTransfer() { for(;;){} }
void sceUsbdControlTransferGetData() { for(;;){} }
void sceUsbdControlTransferGetSetup() { for(;;){} }
void sceUsbdDetachKernelDriver() { for(;;){} }
void sceUsbdEventHandlerActive() { for(;;){} }
void sceUsbdEventHandlingOk() { for(;;){} }
void sceUsbdExit() { for(;;){} }
void sceUsbdFillBulkTransfer() { for(;;){} }
void sceUsbdFillControlSetup() { for(;;){} }
void sceUsbdFillControlTransfer() { for(;;){} }
void sceUsbdFillInterruptTransfer() { for(;;){} }
void sceUsbdFillIsoTransfer() { for(;;){} }
void sceUsbdFreeConfigDescriptor() { for(;;){} }
void sceUsbdFreeDeviceList() { for(;;){} }
void sceUsbdFreeTransfer() { for(;;){} }
void sceUsbdGetActiveConfigDescriptor() { for(;;){} }
void sceUsbdGetBusNumber() { for(;;){} }
void sceUsbdGetConfigDescriptor() { for(;;){} }
void sceUsbdGetConfigDescriptorByValue() { for(;;){} }
void sceUsbdGetConfiguration() { for(;;){} }
void sceUsbdGetDescriptor() { for(;;){} }
void sceUsbdGetDevice() { for(;;){} }
void sceUsbdGetDeviceAddress() { for(;;){} }
void sceUsbdGetDeviceDescriptor() { for(;;){} }
void sceUsbdGetDeviceList() { for(;;){} }
void sceUsbdGetDeviceSpeed() { for(;;){} }
void sceUsbdGetIsoPacketBuffer() { for(;;){} }
void sceUsbdGetMaxIsoPacketSize() { for(;;){} }
void sceUsbdGetMaxPacketSize() { for(;;){} }
void sceUsbdGetStringDescriptor() { for(;;){} }
void sceUsbdGetStringDescriptorAscii() { for(;;){} }
void sceUsbdHandleEvents() { for(;;){} }
void sceUsbdHandleEventsLocked() { for(;;){} }
void sceUsbdHandleEventsTimeout() { for(;;){} }
void sceUsbdInit() { for(;;){} }
void sceUsbdInterruptTransfer() { for(;;){} }
void sceUsbdKernelDriverActive() { for(;;){} }
void sceUsbdLockEvents() { for(;;){} }
void sceUsbdLockEventWaiters() { for(;;){} }
void sceUsbdOpen() { for(;;){} }
void sceUsbdOpenDeviceWithVidPid() { for(;;){} }
void sceUsbdRefDevice() { for(;;){} }
void sceUsbdReleaseInterface() { for(;;){} }
void sceUsbdResetDevice() { for(;;){} }
void sceUsbdSetConfiguration() { for(;;){} }
void sceUsbdSetInterfaceAltSetting() { for(;;){} }
void sceUsbdSetIsoPacketLengths() { for(;;){} }
void sceUsbdSubmitTransfer() { for(;;){} }
void sceUsbdTryLockEvents() { for(;;){} }
void sceUsbdUnlockEvents() { for(;;){} }
void sceUsbdUnlockEventWaiters() { for(;;){} }
void sceUsbdUnrefDevice() { for(;;){} }
void sceUsbdWaitForEvent() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}