/* Source generated by crazyvoids source generating tool **/
#include "libSceVideoRecording.h"

void sceVideoRecordingClose() { for(;;){} }
void sceVideoRecordingCopyBGRAtoNV12() { for(;;){} }
void sceVideoRecordingGetInfo() { for(;;){} }
void sceVideoRecordingGetStatus() { for(;;){} }
void sceVideoRecordingInit() { for(;;){} }
void sceVideoRecordingOpen() { for(;;){} }
void sceVideoRecordingOpen2() { for(;;){} }
void sceVideoRecordingQueryHddSize2() { for(;;){} }
void sceVideoRecordingQueryMemSize() { for(;;){} }
void sceVideoRecordingQueryMemSize2() { for(;;){} }
void sceVideoRecordingSetInfo() { for(;;){} }
void sceVideoRecordingStart() { for(;;){} }
void sceVideoRecordingStop() { for(;;){} }
void sceVideoRecordingTerm() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}