/* Source generated by crazyvoids source generating tool **/
#include "libSceDbgKeyboard.h"

void sceDbgKeyboardClose() { for(;;){} }
void sceDbgKeyboardGetKey2Char() { for(;;){} }
void sceDbgKeyboardInit() { for(;;){} }
void sceDbgKeyboardOpen() { for(;;){} }
void sceDbgKeyboardRead() { for(;;){} }
void sceDbgKeyboardReadState() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}