/* Source generated by crazyvoids source generating tool **/
#include "libSceSystemServiceAppLaunchLink.h"

void sceSystemServiceInvokeAppLaunchLink() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}