/* Source generated by crazyvoids source generating tool **/
#include "libSceNpMatching2.h"

void sceNpMatching2AbortContextStart() { for(;;){} }
void sceNpMatching2ContextStart() { for(;;){} }
void sceNpMatching2ContextStop() { for(;;){} }
void sceNpMatching2CreateContext() { for(;;){} }
void sceNpMatching2CreateContextA() { for(;;){} }
void sceNpMatching2CreateContextInternal() { for(;;){} }
void sceNpMatching2CreateJoinRoom() { for(;;){} }
void sceNpMatching2CreateJoinRoomA() { for(;;){} }
void sceNpMatching2DestroyContext() { for(;;){} }
void sceNpMatching2GetLobbyInfoList() { for(;;){} }
void sceNpMatching2GetLobbyMemberDataInternal() { for(;;){} }
void sceNpMatching2GetLobbyMemberDataInternalList() { for(;;){} }
void sceNpMatching2GetMemoryInfo() { for(;;){} }
void sceNpMatching2GetRoomDataExternalList() { for(;;){} }
void sceNpMatching2GetRoomDataInternal() { for(;;){} }
void sceNpMatching2GetRoomJoinedSlotMaskLocal() { for(;;){} }
void sceNpMatching2GetRoomMemberDataExternalList() { for(;;){} }
void sceNpMatching2GetRoomMemberDataInternal() { for(;;){} }
void sceNpMatching2GetRoomMemberIdListLocal() { for(;;){} }
void sceNpMatching2GetRoomPasswordLocal() { for(;;){} }
void sceNpMatching2GetServerId() { for(;;){} }
void sceNpMatching2GetSignalingOptParamLocal() { for(;;){} }
void sceNpMatching2GetSslMemoryInfo() { for(;;){} }
void sceNpMatching2GetUserInfoList() { for(;;){} }
void sceNpMatching2GetUserInfoListA() { for(;;){} }
void sceNpMatching2GetWorldIdArrayForAllServers() { for(;;){} }
void sceNpMatching2GetWorldInfoList() { for(;;){} }
void sceNpMatching2GrantRoomOwner() { for(;;){} }
void sceNpMatching2Initialize() { for(;;){} }
void sceNpMatching2JoinLobby() { for(;;){} }
void sceNpMatching2JoinRoom() { for(;;){} }
void sceNpMatching2JoinRoomA() { for(;;){} }
void sceNpMatching2KickoutRoomMember() { for(;;){} }
void sceNpMatching2LeaveLobby() { for(;;){} }
void sceNpMatching2LeaveRoom() { for(;;){} }
void sceNpMatching2RegisterContextCallback() { for(;;){} }
void sceNpMatching2RegisterLobbyEventCallback() { for(;;){} }
void sceNpMatching2RegisterLobbyMessageCallback() { for(;;){} }
void sceNpMatching2RegisterManualUdpSignalingCallback() { for(;;){} }
void sceNpMatching2RegisterRoomEventCallback() { for(;;){} }
void sceNpMatching2RegisterRoomMessageCallback() { for(;;){} }
void sceNpMatching2RegisterSignalingCallback() { for(;;){} }
void sceNpMatching2SearchRoom() { for(;;){} }
void sceNpMatching2SendLobbyChatMessage() { for(;;){} }
void sceNpMatching2SendRoomChatMessage() { for(;;){} }
void sceNpMatching2SendRoomMessage() { for(;;){} }
void sceNpMatching2SetDefaultRequestOptParam() { for(;;){} }
void sceNpMatching2SetExtraInitParam() { for(;;){} }
void sceNpMatching2SetLobbyMemberDataInternal() { for(;;){} }
void sceNpMatching2SetRoomDataExternal() { for(;;){} }
void sceNpMatching2SetRoomDataInternal() { for(;;){} }
void sceNpMatching2SetRoomDataInternalExt() { for(;;){} }
void sceNpMatching2SetRoomMemberDataInternal() { for(;;){} }
void sceNpMatching2SetSignalingOptParam() { for(;;){} }
void sceNpMatching2SetUserInfo() { for(;;){} }
void sceNpMatching2SignalingAbortConnection() { for(;;){} }
void sceNpMatching2SignalingCancelPeerNetInfo() { for(;;){} }
void sceNpMatching2SignalingEnableManualUdpMode() { for(;;){} }
void sceNpMatching2SignalingEstablishConnection() { for(;;){} }
void sceNpMatching2SignalingGetConnectionInfo() { for(;;){} }
void sceNpMatching2SignalingGetConnectionInfoA() { for(;;){} }
void sceNpMatching2SignalingGetConnectionStatus() { for(;;){} }
void sceNpMatching2SignalingGetLocalNetInfo() { for(;;){} }
void sceNpMatching2SignalingGetPeerNetInfo() { for(;;){} }
void sceNpMatching2SignalingGetPeerNetInfoResult() { for(;;){} }
void sceNpMatching2SignalingGetPingInfo() { for(;;){} }
void sceNpMatching2SignalingGetPort() { for(;;){} }
void sceNpMatching2SignalingSetPort() { for(;;){} }
void sceNpMatching2Terminate() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}