/* Source generated by crazyvoids source generating tool **/
#include "libSceMusicPlayerService.h"

void sceMusicPlayerServiceBeginTransaction() { for(;;){} }
void sceMusicPlayerServiceCreateTrackList() { for(;;){} }
void sceMusicPlayerServiceEndTransaction() { for(;;){} }
void sceMusicPlayerServiceGetAudioVolume() { for(;;){} }
void sceMusicPlayerServiceGetCurrentPlayStatus() { for(;;){} }
void sceMusicPlayerServiceGetPlaybackResults() { for(;;){} }
void sceMusicPlayerServiceGetPlayStatusExtension() { for(;;){} }
void sceMusicPlayerServiceGetTrackInfo() { for(;;){} }
void sceMusicPlayerServiceGetTrackListVersion() { for(;;){} }
void sceMusicPlayerServiceInitialize() { for(;;){} }
void sceMusicPlayerServiceInitialize2() { for(;;){} }
void sceMusicPlayerServiceInitialize3() { for(;;){} }
void sceMusicPlayerServiceInsertTrackEntry() { for(;;){} }
void sceMusicPlayerServiceNextTrack() { for(;;){} }
void sceMusicPlayerServicePause() { for(;;){} }
void sceMusicPlayerServicePlay() { for(;;){} }
void sceMusicPlayerServicePlayStartByTime() { for(;;){} }
void sceMusicPlayerServicePreviousTrack() { for(;;){} }
void sceMusicPlayerServiceReceiveEvent() { for(;;){} }
void sceMusicPlayerServiceRemoveAllData() { for(;;){} }
void sceMusicPlayerServiceRemoveTrackEntry() { for(;;){} }
void sceMusicPlayerServiceRemoveTrackList() { for(;;){} }
void sceMusicPlayerServiceSeek() { for(;;){} }
void sceMusicPlayerServiceSetAudioVolume() { for(;;){} }
void sceMusicPlayerServiceSetRepeatMode() { for(;;){} }
void sceMusicPlayerServiceSetShuffle() { for(;;){} }
void sceMusicPlayerServiceSetTrackList() { for(;;){} }
void sceMusicPlayerServiceSetTrackList2() { for(;;){} }
void sceMusicPlayerServiceSetUsbStorageDeviceInfo() { for(;;){} }
void sceMusicPlayerServiceStop() { for(;;){} }
void sceMusicPlayerServiceTerminate() { for(;;){} }
void sceMusicPlayerServiceUnpause() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}