/* Source generated by crazyvoids source generating tool **/
#include "libSceGameCustomDataDialog.h"

void sceGameCustomDataDialogClose() { for(;;){} }
void sceGameCustomDataDialogGetResult() { for(;;){} }
void sceGameCustomDataDialogGetResultA() { for(;;){} }
void sceGameCustomDataDialogGetStatus() { for(;;){} }
void sceGameCustomDataDialogInitialize() { for(;;){} }
void sceGameCustomDataDialogOpen() { for(;;){} }
void sceGameCustomDataDialogOpenA() { for(;;){} }
void sceGameCustomDataDialogTerminate() { for(;;){} }
void sceGameCustomDataDialogUpdateStatus() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}