/* Source generated by crazyvoids source generating tool **/
#include "libSceAvcap.h"

void sceVshAvcapClose() { for(;;){} }
void sceVshAvcapCreateSyncer() { for(;;){} }
void sceVshAvcapDeleteSyncer() { for(;;){} }
void sceVshAvcapGetInfo() { for(;;){} }
void sceVshAvcapGetStaticInfo() { for(;;){} }
void sceVshAvcapInit() { for(;;){} }
void sceVshAvcapOpenAudio() { for(;;){} }
void sceVshAvcapOpenAudioEx() { for(;;){} }
void sceVshAvcapOpenUserdata() { for(;;){} }
void sceVshAvcapOpenVideo() { for(;;){} }
void sceVshAvcapOpenVideoEx() { for(;;){} }
void sceVshAvcapReadAudio() { for(;;){} }
void sceVshAvcapReadUserdata() { for(;;){} }
void sceVshAvcapReadVideo() { for(;;){} }
void sceVshAvcapSelect() { for(;;){} }
void sceVshAvcapSetInfo() { for(;;){} }
void sceVshAvcapSetStaticInfo() { for(;;){} }
void sceVshAvcapStart() { for(;;){} }
void sceVshAvcapStop() { for(;;){} }
void sceVshAvcapTerm() { for(;;){} }
void sceVshAvcapUpdateSyncer() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}