/* Source generated by crazyvoids source generating tool **/
#include "libSceAppContent.h"

void _Z5dummyv() { for(;;){} }
void sceAppContentAddcontDelete() { for(;;){} }
void sceAppContentAddcontEnqueueDownload() { for(;;){} }
void sceAppContentAddcontMount() { for(;;){} }
void sceAppContentAddcontShrink() { for(;;){} }
void sceAppContentAddcontUnmount() { for(;;){} }
void sceAppContentAppParamGetInt() { for(;;){} }
void sceAppContentAppParamGetString() { for(;;){} }
void sceAppContentDownload0Expand() { for(;;){} }
void sceAppContentDownload0Shrink() { for(;;){} }
void sceAppContentDownload1Expand() { for(;;){} }
void sceAppContentDownloadDataFormat() { for(;;){} }
void sceAppContentDownloadDataGetAvailableSpaceKb() { for(;;){} }
void sceAppContentGetAddcontDownloadProgress() { for(;;){} }
void sceAppContentGetAddcontInfo() { for(;;){} }
void sceAppContentGetAddcontInfoList() { for(;;){} }
void sceAppContentGetEntitlementKey() { for(;;){} }
void sceAppContentGetRegion() { for(;;){} }
void sceAppContentInitialize() { for(;;){} }
void sceAppContentRequestPatchInstall() { for(;;){} }
void sceAppContentSmallSharedDataFormat() { for(;;){} }
void sceAppContentSmallSharedDataGetAvailableSpaceKb() { for(;;){} }
void sceAppContentSmallSharedDataMount() { for(;;){} }
void sceAppContentSmallSharedDataUnmount() { for(;;){} }
void sceAppContentTemporaryDataFormat() { for(;;){} }
void sceAppContentTemporaryDataGetAvailableSpaceKb() { for(;;){} }
void sceAppContentTemporaryDataMount() { for(;;){} }
void sceAppContentTemporaryDataMount2() { for(;;){} }
void sceAppContentTemporaryDataUnmount() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}