/* Source generated by crazyvoids source generating tool **/
#include "libSceNetCtlApIpcInt.h"

void sceNetCtlApAppInitWpaKey() { for(;;){} }
void sceNetCtlApAppInitWpaKeyForQa() { for(;;){} }
void sceNetCtlApAppStartWithRetry() { for(;;){} }
void sceNetCtlApAppStartWithRetryPid() { for(;;){} }
void sceNetCtlApRestart() { for(;;){} }
void sceNetCtlApRpCheckCallback() { for(;;){} }
void sceNetCtlApRpClearEvent() { for(;;){} }
void sceNetCtlApRpGetInfo() { for(;;){} }
void sceNetCtlApRpGetResult() { for(;;){} }
void sceNetCtlApRpGetState() { for(;;){} }
void sceNetCtlApRpRegisterCallback() { for(;;){} }
void sceNetCtlApRpStart() { for(;;){} }
void sceNetCtlApRpStartConf() { for(;;){} }
void sceNetCtlApRpStartWithRetry() { for(;;){} }
void sceNetCtlApRpStop() { for(;;){} }
void sceNetCtlApRpUnregisterCallback() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}