/* Source generated by crazyvoids source generating tool **/
#include "libSceSystemServicePsmKit.h"

void sceSystemServiceAddLocalProcessForPsmKit() { for(;;){} }
void sceSystemServiceGetParentSocketForPsmKit() { for(;;){} }
void sceSystemServiceKillLocalProcessForPsmKit() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}