/* Source generated by crazyvoids source generating tool **/
#include "libSceIduUtil.h"

void sceIduUtilClearAllSchedules() { for(;;){} }
void sceIduUtilDeleteSaveData() { for(;;){} }
void sceIduUtilDisablePriorityDownloads() { for(;;){} }
void sceIduUtilDownloadInstallPkg() { for(;;){} }
void sceIduUtilEnablePriorityDownloads() { for(;;){} }
void sceIduUtilGetAppVersion() { for(;;){} }
void sceIduUtilGetBgftProgress() { for(;;){} }
void sceIduUtilGetCompilationDiscInfo() { for(;;){} }
void sceIduUtilGetCompilationDiscTitleInfo() { for(;;){} }
void sceIduUtilGetDiscInfo() { for(;;){} }
void sceIduUtilGetDiskSpaceStats() { for(;;){} }
void sceIduUtilGetDownloadInstallProgress() { for(;;){} }
void sceIduUtilGetDownloadState() { for(;;){} }
void sceIduUtilGetEnvironment() { for(;;){} }
void sceIduUtilGetInstalledApp() { for(;;){} }
void sceIduUtilGetInstalledAppWithOffset() { for(;;){} }
void sceIduUtilGetMasterVersion() { for(;;){} }
void sceIduUtilGetNumInstalledApps() { for(;;){} }
void sceIduUtilGetNumSchedules() { for(;;){} }
void sceIduUtilGetOpenPsId() { for(;;){} }
void sceIduUtilGetSchedule() { for(;;){} }
void sceIduUtilGetSettingBin() { for(;;){} }
void sceIduUtilGetSettingInt() { for(;;){} }
void sceIduUtilGetSettingStr() { for(;;){} }
void sceIduUtilHideOverlay() { for(;;){} }
void sceIduUtilInitialize() { for(;;){} }
void sceIduUtilIsAppInstalled() { for(;;){} }
void sceIduUtilIsDiscCompilationDisc() { for(;;){} }
void sceIduUtilIsDiscInserted() { for(;;){} }
void sceIduUtilIsInitialised() { for(;;){} }
void sceIduUtilIsRifInstalled() { for(;;){} }
void sceIduUtilIsStaffMode() { for(;;){} }
void sceIduUtilLaunchTitle() { for(;;){} }
void sceIduUtilLaunchTitleV2() { for(;;){} }
void sceIduUtilPauseAllDownloads() { for(;;){} }
void sceIduUtilReboot() { for(;;){} }
void sceIduUtilRegisterFlag() { for(;;){} }
void sceIduUtilRegisterOverlayMsg() { for(;;){} }
void sceIduUtilResumeAllDownloads() { for(;;){} }
void sceIduUtilSetMoveMode() { for(;;){} }
void sceIduUtilSetPupVersion() { for(;;){} }
void sceIduUtilSetSchedule() { for(;;){} }
void sceIduUtilSetSettingBin() { for(;;){} }
void sceIduUtilSetSettingInt() { for(;;){} }
void sceIduUtilSetSettingStr() { for(;;){} }
void sceIduUtilSetSysLanguage() { for(;;){} }
void sceIduUtilShowOverlay() { for(;;){} }
void sceIduUtilTerminate() { for(;;){} }
void sceIduUtilUninstallApp() { for(;;){} }
void sceIduUtilUpdateSelf() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}