/* Source generated by crazyvoids source generating tool **/
#include "libSceJpegDec.h"

void sceJpegDecCreate() { for(;;){} }
void sceJpegDecDecode() { for(;;){} }
void sceJpegDecDecodeWithInputControl() { for(;;){} }
void sceJpegDecDelete() { for(;;){} }
void sceJpegDecParseHeader() { for(;;){} }
void sceJpegDecQueryMemorySize() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}