/* Source generated by crazyvoids source generating tool **/
#include "libSceAudiodecCpu.h"

void sceAudiodecCpuClearContext() { for(;;){} }
void sceAudiodecCpuDecode() { for(;;){} }
void sceAudiodecCpuInitDecoder() { for(;;){} }
void sceAudiodecCpuInternalClearContext() { for(;;){} }
void sceAudiodecCpuInternalDecode() { for(;;){} }
void sceAudiodecCpuInternalInitDecoder() { for(;;){} }
void sceAudiodecCpuInternalQueryMemSize() { for(;;){} }
void sceAudiodecCpuQueryMemSize() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}