/* Source generated by crazyvoids source generating tool **/
#include "libSceVideodec.h"

void sceVideodecCreateDecoder() { for(;;){} }
void sceVideodecDecode() { for(;;){} }
void sceVideodecDeleteDecoder() { for(;;){} }
void sceVideodecFlush() { for(;;){} }
void sceVideodecMapMemory() { for(;;){} }
void sceVideodecQueryResourceInfo() { for(;;){} }
void sceVideodecReset() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}