/* Source generated by crazyvoids source generating tool **/
#include "libSceAudiodecCpuHevag.h"

void audiodeccpuinternal_core_ops_hevag2() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}