/* Source generated by crazyvoids source generating tool **/
#include "libSceRtc.h"

void sceRtcCheckValid() { for(;;){} }
void sceRtcCompareTick() { for(;;){} }
void sceRtcConvertLocalTimeToUtc() { for(;;){} }
void sceRtcConvertUtcToLocalTime() { for(;;){} }
void sceRtcEnd() { for(;;){} }
void sceRtcFormatRFC2822() { for(;;){} }
void sceRtcFormatRFC2822LocalTime() { for(;;){} }
void sceRtcFormatRFC3339() { for(;;){} }
void sceRtcFormatRFC3339LocalTime() { for(;;){} }
void sceRtcGetCurrentAdNetworkTick() { for(;;){} }
void sceRtcGetCurrentClock() { for(;;){} }
void sceRtcGetCurrentClockLocalTime() { for(;;){} }
void sceRtcGetCurrentDebugNetworkTick() { for(;;){} }
void sceRtcGetCurrentNetworkTick() { for(;;){} }
void sceRtcGetCurrentRawNetworkTick() { for(;;){} }
void sceRtcGetCurrentTick() { for(;;){} }
void sceRtcGetDayOfWeek() { for(;;){} }
void sceRtcGetDaysInMonth() { for(;;){} }
void sceRtcGetDosTime() { for(;;){} }
void sceRtcGetTick() { for(;;){} }
void sceRtcGetTickResolution() { for(;;){} }
void sceRtcGetTime_t() { for(;;){} }
void sceRtcGetWin32FileTime() { for(;;){} }
void sceRtcInit() { for(;;){} }
void sceRtcIsLeapYear() { for(;;){} }
void sceRtcParseDateTime() { for(;;){} }
void sceRtcParseRFC3339() { for(;;){} }
void sceRtcSetConf() { for(;;){} }
void sceRtcSetCurrentAdNetworkTick() { for(;;){} }
void sceRtcSetCurrentDebugNetworkTick() { for(;;){} }
void sceRtcSetCurrentNetworkTick() { for(;;){} }
void sceRtcSetCurrentTick() { for(;;){} }
void sceRtcSetDosTime() { for(;;){} }
void sceRtcSetTick() { for(;;){} }
void sceRtcSetTime_t() { for(;;){} }
void sceRtcSetWin32FileTime() { for(;;){} }
void sceRtcTickAddDays() { for(;;){} }
void sceRtcTickAddHours() { for(;;){} }
void sceRtcTickAddMicroseconds() { for(;;){} }
void sceRtcTickAddMinutes() { for(;;){} }
void sceRtcTickAddMonths() { for(;;){} }
void sceRtcTickAddSeconds() { for(;;){} }
void sceRtcTickAddTicks() { for(;;){} }
void sceRtcTickAddWeeks() { for(;;){} }
void sceRtcTickAddYears() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}