/* Source generated by crazyvoids source generating tool **/
#include "libSceGameLiveStreaming_debug.h"

void sceGameLiveStreamingStartDebugBroadcast() { for(;;){} }
void sceGameLiveStreamingStopDebugBroadcast() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}