/* Source generated by crazyvoids source generating tool **/
#include "libSceSysmodule.h"

void sceSysmoduleGetModuleHandleInternal() { for(;;){} }
void sceSysmoduleIsCalledFromSysModule() { for(;;){} }
void sceSysmoduleIsCameraPreloaded() { for(;;){} }
void sceSysmoduleIsLoaded() { for(;;){} }
void sceSysmoduleIsLoadedInternal() { for(;;){} }
void sceSysmoduleLoadModule() { for(;;){} }
void sceSysmoduleLoadModuleByNameInternal() { for(;;){} }
void sceSysmoduleLoadModuleInternal() { for(;;){} }
void sceSysmoduleLoadModuleInternalWithArg() { for(;;){} }
void sceSysmoduleMapLibcForLibkernel() { for(;;){} }
void sceSysmodulePreloadModuleForLibkernel() { for(;;){} }
void sceSysmoduleUnloadModule() { for(;;){} }
void sceSysmoduleUnloadModuleByNameInternal() { for(;;){} }
void sceSysmoduleUnloadModuleInternal() { for(;;){} }
void sceSysmoduleUnloadModuleInternalWithArg() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}