/* Source generated by crazyvoids source generating tool **/
#include "libSceAppContentSc.h"

void sceAppContentGetDownloadedStoreCountry() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}