/* Source generated by crazyvoids source generating tool **/
#include "libSceAvPlayer.h"

void sceAvPlayerAddSource() { for(;;){} }
void sceAvPlayerAddSourceEx() { for(;;){} }
void sceAvPlayerChangeStream() { for(;;){} }
void sceAvPlayerClose() { for(;;){} }
void sceAvPlayerCurrentTime() { for(;;){} }
void sceAvPlayerDisableStream() { for(;;){} }
void sceAvPlayerEnableStream() { for(;;){} }
void sceAvPlayerGetAudioData() { for(;;){} }
void sceAvPlayerGetStreamInfo() { for(;;){} }
void sceAvPlayerGetVideoData() { for(;;){} }
void sceAvPlayerGetVideoDataEx() { for(;;){} }
void sceAvPlayerInit() { for(;;){} }
void sceAvPlayerInitEx() { for(;;){} }
void sceAvPlayerIsActive() { for(;;){} }
void sceAvPlayerJumpToTime() { for(;;){} }
void sceAvPlayerPause() { for(;;){} }
void sceAvPlayerPostInit() { for(;;){} }
void sceAvPlayerPrintf() { for(;;){} }
void sceAvPlayerResume() { for(;;){} }
void sceAvPlayerSetAvSyncMode() { for(;;){} }
void sceAvPlayerSetLogCallback() { for(;;){} }
void sceAvPlayerSetLooping() { for(;;){} }
void sceAvPlayerSetTrickSpeed() { for(;;){} }
void sceAvPlayerStart() { for(;;){} }
void sceAvPlayerStop() { for(;;){} }
void sceAvPlayerStreamCount() { for(;;){} }
void sceAvPlayerVprintf() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}