/* Source generated by crazyvoids source generating tool **/
#include "libSceVoice.h"

void sceVoiceConnectIPortToOPort() { for(;;){} }
void sceVoiceCreatePort() { for(;;){} }
void sceVoiceDeletePort() { for(;;){} }
void sceVoiceDisconnectIPortFromOPort() { for(;;){} }
void sceVoiceEnd() { for(;;){} }
void sceVoiceGetBitRate() { for(;;){} }
void sceVoiceGetMuteFlag() { for(;;){} }
void sceVoiceGetPortAttr() { for(;;){} }
void sceVoiceGetPortInfo() { for(;;){} }
void sceVoiceGetResourceInfo() { for(;;){} }
void sceVoiceGetVolume() { for(;;){} }
void sceVoiceInit() { for(;;){} }
void sceVoicePausePort() { for(;;){} }
void sceVoicePausePortAll() { for(;;){} }
void sceVoiceReadFromOPort() { for(;;){} }
void sceVoiceResetPort() { for(;;){} }
void sceVoiceResumePort() { for(;;){} }
void sceVoiceResumePortAll() { for(;;){} }
void sceVoiceSetBitRate() { for(;;){} }
void sceVoiceSetMuteFlag() { for(;;){} }
void sceVoiceSetMuteFlagAll() { for(;;){} }
void sceVoiceSetThreadsParams() { for(;;){} }
void sceVoiceSetVolume() { for(;;){} }
void sceVoiceStart() { for(;;){} }
void sceVoiceStop() { for(;;){} }
void sceVoiceUpdatePort() { for(;;){} }
void sceVoiceVADAdjustment() { for(;;){} }
void sceVoiceVADSetVersion() { for(;;){} }
void sceVoiceWriteToIPort() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}