/* Source generated by crazyvoids source generating tool **/
#include "libSceNpSignalingCompat.h"

void sceNpSignalingActivateConnection() { for(;;){} }
void sceNpSignalingCreateContext() { for(;;){} }
void sceNpSignalingGetConnectionFromNpId() { for(;;){} }
void sceNpSignalingGetConnectionInfo() { for(;;){} }
void sceNpSignalingGetPeerNetInfo() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}