/* Source generated by crazyvoids source generating tool **/
#include "libSceNpSnsDailymotionDialog.h"

void sceNpSnsDailymotionDialogClose() { for(;;){} }
void sceNpSnsDailymotionDialogGetResult() { for(;;){} }
void sceNpSnsDailymotionDialogGetStatus() { for(;;){} }
void sceNpSnsDailymotionDialogInitialize() { for(;;){} }
void sceNpSnsDailymotionDialogOpen() { for(;;){} }
void sceNpSnsDailymotionDialogTerminate() { for(;;){} }
void sceNpSnsDailymotionDialogUpdateStatus() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}