/* Source generated by crazyvoids source generating tool **/
#include "libSceNpWebApiCompat.h"

void sceNpWebApiCreateContext() { for(;;){} }
void sceNpWebApiCreatePushEventFilter() { for(;;){} }
void sceNpWebApiCreateServicePushEventFilter() { for(;;){} }
void sceNpWebApiDeletePushEventFilter() { for(;;){} }
void sceNpWebApiDeleteServicePushEventFilter() { for(;;){} }
void sceNpWebApiRegisterExtdPushEventCallback() { for(;;){} }
void sceNpWebApiRegisterNotificationCallback() { for(;;){} }
void sceNpWebApiRegisterPushEventCallback() { for(;;){} }
void sceNpWebApiRegisterServicePushEventCallback() { for(;;){} }
void sceNpWebApiUnregisterNotificationCallback() { for(;;){} }
void sceNpWebApiUnregisterPushEventCallback() { for(;;){} }
void sceNpWebApiUnregisterServicePushEventCallback() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}