/* Source generated by crazyvoids source generating tool **/
#include "libSceLibcInternalExt.h"

void sceLibcHeapGetTraceInfo() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}