/* Source generated by crazyvoids source generating tool **/
#include "libSceMbus.h"

void sceMbusAcquireControl() { for(;;){} }
void sceMbusAcquireControlList() { for(;;){} }
void sceMbusAcquireControlWithState() { for(;;){} }
void sceMbusAcquireControlWithState2() { for(;;){} }
void sceMbusAcquireControlWithStateFlag() { for(;;){} }
void sceMbusAddAudioOutHandleAttribute() { for(;;){} }
void sceMbusAddHandle() { for(;;){} }
void sceMbusAddHandleByDeviceId() { for(;;){} }
void sceMbusAddHandleByUserId() { for(;;){} }
void sceMbusAddHandleByVidPid() { for(;;){} }
void sceMbusAddHandleWithModuleId() { for(;;){} }
void sceMbusAttachToApplicationByPid() { for(;;){} }
void sceMbusBindDeviceWithUserId() { for(;;){} }
void sceMbusChangeAppModuleState() { for(;;){} }
void sceMbusCheckDriverCallback() { for(;;){} }
void sceMbusConvertToLocalDeviceId() { for(;;){} }
void sceMbusConvertToLocalDeviceId2() { for(;;){} }
void sceMbusConvertToMbusDeviceId() { for(;;){} }
void sceMbusDetachFromApplicationByPid() { for(;;){} }
void sceMbusDisableBgmForShellUi() { for(;;){} }
void sceMbusDisconnectDevice() { for(;;){} }
void sceMbusDumpAppInfo() { for(;;){} }
void sceMbusDumpDeviceInfo() { for(;;){} }
void sceMbusDumpHandleStatusInfo() { for(;;){} }
void sceMbusDumpHandleStatusInfoAll() { for(;;){} }
void sceMbusDumpModuleStateInfo() { for(;;){} }
void sceMbusDumpModuleStateInfoAll() { for(;;){} }
void sceMbusDumpPlayerInfo() { for(;;){} }
void sceMbusDumpPortHandleInfo() { for(;;){} }
void sceMbusDumpProcMediaInfo() { for(;;){} }
void sceMbusDumpProcMediaInfoAll() { for(;;){} }
void sceMbusDumpUserMediaInfo() { for(;;){} }
void sceMbusEnterAudioOutAutoAttenuation() { for(;;){} }
void sceMbusEventBusStatusChangeSubscribe() { for(;;){} }
void sceMbusEventBusStatusChangeUnsubscribe() { for(;;){} }
void sceMbusEventCallbackFuncsInit_() { for(;;){} }
void sceMbusEventCreate_() { for(;;){} }
void sceMbusEventDestroy() { for(;;){} }
void sceMbusEventReceive() { for(;;){} }
void sceMbusGetControlStatus() { for(;;){} }
void sceMbusGetDeviceDescription() { for(;;){} }
void sceMbusGetDeviceInfo_() { for(;;){} }
void sceMbusGetDeviceInfoByBusId_() { for(;;){} }
void sceMbusGetDeviceInfoByCondition_() { for(;;){} }
void sceMbusGetDeviceInfoByConditionForDeviceService() { for(;;){} }
void sceMbusGetSimulatedHandleStatusInfo() { for(;;){} }
void sceMbusGetSimulatedHandleStatusInfo2() { for(;;){} }
void sceMbusGetSparkState() { for(;;){} }
void sceMbusInit() { for(;;){} }
void sceMbusIsUsingDevice() { for(;;){} }
void sceMbusLeaveAudioOutAutoAttenuation() { for(;;){} }
void sceMbusNotifyDriverEvent() { for(;;){} }
void sceMbusReenableBgmForShellUi() { for(;;){} }
void sceMbusRegisterDriver() { for(;;){} }
void sceMbusReleaseControl() { for(;;){} }
void sceMbusRemoveAudioOutHandleAttribute() { for(;;){} }
void sceMbusRemoveCameraAppModuleFocus() { for(;;){} }
void sceMbusRemoveHandle() { for(;;){} }
void sceMbusRemoveProxy() { for(;;){} }
void sceMbusResolveByDeviceId() { for(;;){} }
void sceMbusResolveByHandle() { for(;;){} }
void sceMbusResolveByPlayerId() { for(;;){} }
void sceMbusResolveByUserId() { for(;;){} }
void sceMbusSetAutoLoginMode() { for(;;){} }
void sceMbusSetCameraAppModuleFocus() { for(;;){} }
void sceMbusSetDeviceFunctionState() { for(;;){} }
void sceMbusSetDuckingSetting() { for(;;){} }
void sceMbusSetProxy() { for(;;){} }
void sceMbusSetRoutingMode() { for(;;){} }
void sceMbusSetScratchData() { for(;;){} }
void sceMbusSetScratchDataUpdatedEventMask() { for(;;){} }
void sceMbusSetTestFlag() { for(;;){} }
void sceMbusSetThreadParam() { for(;;){} }
void sceMbusSetUsbPowerBlackList() { for(;;){} }
void sceMbusStartAudioOutAuxBroadcast() { for(;;){} }
void sceMbusStartAudioOutSharePlay() { for(;;){} }
void sceMbusStopAudioOutAuxBroadcast() { for(;;){} }
void sceMbusStopAudioOutSharePlay() { for(;;){} }
void sceMbusTerm() { for(;;){} }
void sceMbusUnregisterDriver() { for(;;){} }
void sceMbusUserLogin() { for(;;){} }
void sceMbusUserLogout() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}