/* Source generated by crazyvoids source generating tool **/
#include "libSceGameLiveStreamingCompat.h"

void sceGameLiveStreamingGetCurrentStatus() { for(;;){} }
void sceGameLiveStreamingLaunchLiveViewer() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}