/* Source generated by crazyvoids source generating tool **/
#include "libSceNpManagerIsPlusMember.h"

void sceNpIsPlusMember() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}