/* Source generated by crazyvoids source generating tool **/
#include "libSceSystemService_jvm.h"

void sceSystemServiceAddLocalProcessForJvm() { for(;;){} }
void sceSystemServiceGetParentSocketForJvm() { for(;;){} }
void sceSystemServiceKillLocalProcessForJvm() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}