/* Source generated by crazyvoids source generating tool **/
#include "libSceSystemGesture.h"

void sceSystemGestureAppendTouchRecognizer() { for(;;){} }
void sceSystemGestureClose() { for(;;){} }
void sceSystemGestureCreateTouchRecognizer() { for(;;){} }
void sceSystemGestureDebugGetVersion() { for(;;){} }
void sceSystemGestureFinalizePrimitiveTouchRecognizer() { for(;;){} }
void sceSystemGestureGetPrimitiveTouchEventByIndex() { for(;;){} }
void sceSystemGestureGetPrimitiveTouchEventByPrimitiveID() { for(;;){} }
void sceSystemGestureGetPrimitiveTouchEvents() { for(;;){} }
void sceSystemGestureGetPrimitiveTouchEventsCount() { for(;;){} }
void sceSystemGestureGetTouchEventByEventID() { for(;;){} }
void sceSystemGestureGetTouchEventByIndex() { for(;;){} }
void sceSystemGestureGetTouchEvents() { for(;;){} }
void sceSystemGestureGetTouchEventsCount() { for(;;){} }
void sceSystemGestureGetTouchRecognizerInformation() { for(;;){} }
void sceSystemGestureInitializePrimitiveTouchRecognizer() { for(;;){} }
void sceSystemGestureOpen() { for(;;){} }
void sceSystemGestureRemoveTouchRecognizer() { for(;;){} }
void sceSystemGestureResetPrimitiveTouchRecognizer() { for(;;){} }
void sceSystemGestureResetTouchRecognizer() { for(;;){} }
void sceSystemGestureUpdateAllTouchRecognizer() { for(;;){} }
void sceSystemGestureUpdatePrimitiveTouchRecognizer() { for(;;){} }
void sceSystemGestureUpdateTouchRecognizer() { for(;;){} }
void sceSystemGestureUpdateTouchRecognizerRectangle() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}