/* Source generated by crazyvoids source generating tool **/
#include "libSceUserServiceForNpToolkit.h"

void sceUserServiceRegisterEventCallback() { for(;;){} }
void sceUserServiceUnregisterEventCallback() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}