/* Source generated by crazyvoids source generating tool **/
#include "libSceFiber.h"

void _sceFiberAttachContextAndRun() { for(;;){} }
void _sceFiberAttachContextAndSwitch() { for(;;){} }
void _sceFiberGetThreadFramePointerAddress() { for(;;){} }
void _sceFiberInitializeImpl() { for(;;){} }
void _sceFiberInitializeWithInternalOptionImpl() { for(;;){} }
void sceFiberFinalize() { for(;;){} }
void sceFiberGetInfo() { for(;;){} }
void sceFiberGetSelf() { for(;;){} }
void sceFiberOptParamInitialize() { for(;;){} }
void sceFiberRename() { for(;;){} }
void sceFiberReturnToThread() { for(;;){} }
void sceFiberRun() { for(;;){} }
void sceFiberStartContextSizeCheck() { for(;;){} }
void sceFiberStopContextSizeCheck() { for(;;){} }
void sceFiberSwitch() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}