/* Source generated by crazyvoids source generating tool **/
#include "libSceAudio3d.h"

void sceAudio3dAudioOutClose() { for(;;){} }
void sceAudio3dAudioOutOpen() { for(;;){} }
void sceAudio3dAudioOutOutput() { for(;;){} }
void sceAudio3dAudioOutOutputs() { for(;;){} }
void sceAudio3dBedWrite() { for(;;){} }
void sceAudio3dBedWrite2() { for(;;){} }
void sceAudio3dCreateSpeakerArray() { for(;;){} }
void sceAudio3dDeleteSpeakerArray() { for(;;){} }
void sceAudio3dGetDefaultOpenParameters() { for(;;){} }
void sceAudio3dGetSpeakerArrayMemorySize() { for(;;){} }
void sceAudio3dGetSpeakerArrayMixCoefficients() { for(;;){} }
void sceAudio3dInitialize() { for(;;){} }
void sceAudio3dObjectReserve() { for(;;){} }
void sceAudio3dObjectSetAttributes() { for(;;){} }
void sceAudio3dObjectUnreserve() { for(;;){} }
void sceAudio3dPortAdvance() { for(;;){} }
void sceAudio3dPortClose() { for(;;){} }
void sceAudio3dPortCreate() { for(;;){} }
void sceAudio3dPortDestroy() { for(;;){} }
void sceAudio3dPortFlush() { for(;;){} }
void sceAudio3dPortFreeState() { for(;;){} }
void sceAudio3dPortGetAttributesSupported() { for(;;){} }
void sceAudio3dPortGetList() { for(;;){} }
void sceAudio3dPortGetParameters() { for(;;){} }
void sceAudio3dPortGetQueueLevel() { for(;;){} }
void sceAudio3dPortGetState() { for(;;){} }
void sceAudio3dPortGetStatus() { for(;;){} }
void sceAudio3dPortOpen() { for(;;){} }
void sceAudio3dPortPush() { for(;;){} }
void sceAudio3dPortQueryDebug() { for(;;){} }
void sceAudio3dPortSetAttribute() { for(;;){} }
void sceAudio3dReportRegisterHandler() { for(;;){} }
void sceAudio3dReportUnregisterHandler() { for(;;){} }
void sceAudio3dSetGpuRenderer() { for(;;){} }
void sceAudio3dStrError() { for(;;){} }
void sceAudio3dTerminate() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}