/* Source generated by crazyvoids source generating tool **/
#include "libSceMouse.h"

void sceMouseClose() { for(;;){} }
void sceMouseConnectPort() { for(;;){} }
void sceMouseDebugGetDeviceId() { for(;;){} }
void sceMouseDeviceOpen() { for(;;){} }
void sceMouseDisconnectDevice() { for(;;){} }
void sceMouseDisconnectPort() { for(;;){} }
void sceMouseGetDeviceInfo() { for(;;){} }
void sceMouseInit() { for(;;){} }
void sceMouseMbusInit() { for(;;){} }
void sceMouseOpen() { for(;;){} }
void sceMouseRead() { for(;;){} }
void sceMouseSetHandType() { for(;;){} }
void sceMouseSetPointerSpeed() { for(;;){} }
void sceMouseSetProcessPrivilege() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}