/* Source generated by crazyvoids source generating tool **/
#include "libSceSystemServicePowerSaveLevel.h"

void sceSystemServiceSetPowerSaveLevel() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}