/* Source generated by crazyvoids source generating tool **/
#include "libSceUserServiceForShellCore.h"

void sceUserServiceInitializeForShellCore() { for(;;){} }
void sceUserServiceTerminateForShellCore() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}