/* Source generated by crazyvoids source generating tool **/
#include "libScePatchCheckerClient.h"

void scePatchCheckerCancel() { for(;;){} }
void scePatchCheckerCheckPatch() { for(;;){} }
void scePatchCheckerClearCache() { for(;;){} }
void scePatchCheckerCreateHandler() { for(;;){} }
void scePatchCheckerDestroyHandler() { for(;;){} }
void scePatchCheckerDisableAutoDownload() { for(;;){} }
void scePatchCheckerEnableAutoDownload() { for(;;){} }
void scePatchCheckerGetApplicableTick() { for(;;){} }
void scePatchCheckerGetPackageInfo() { for(;;){} }
void scePatchCheckerInitialize() { for(;;){} }
void scePatchCheckerRequestCheckPatch() { for(;;){} }
void scePatchCheckerRequestCheckPatchByType() { for(;;){} }
void scePatchCheckerSetCache() { for(;;){} }
void scePatchCheckerSetFakeCache() { for(;;){} }
void scePatchCheckerTerminate() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}