/* Source generated by crazyvoids source generating tool **/
#include "libSceSpSysCallWrapper.h"

void sceSpGetPid() { for(;;){} }
void sceSpKernelGettimeofday() { for(;;){} }
void sceSpKernelNanosleep() { for(;;){} }
void sceSpNetConnect() { for(;;){} }
void sceSpNetEpollAbort() { for(;;){} }
void sceSpNetEpollControl() { for(;;){} }
void sceSpNetEpollCreate() { for(;;){} }
void sceSpNetEpollDestroy() { for(;;){} }
void sceSpNetEpollWait() { for(;;){} }
void sceSpNetErrnoLoc() { for(;;){} }
void sceSpNetPoolCreate() { for(;;){} }
void sceSpNetPoolDestroy() { for(;;){} }
void sceSpNetRecv() { for(;;){} }
void sceSpNetResolverAbort() { for(;;){} }
void sceSpNetResolverCreate() { for(;;){} }
void sceSpNetResolverDestroy() { for(;;){} }
void sceSpNetResolverGetError() { for(;;){} }
void sceSpNetResolverStartNtoa() { for(;;){} }
void sceSpNetSend() { for(;;){} }
void sceSpNetSetsockopt() { for(;;){} }
void sceSpNetSocket() { for(;;){} }
void sceSpNetSocketClose() { for(;;){} }
void sceSpPthreadAttrDestroy() { for(;;){} }
void sceSpPthreadAttrInit() { for(;;){} }
void sceSpPthreadAttrSetinheritsched() { for(;;){} }
void sceSpPthreadAttrSetschedparam() { for(;;){} }
void sceSpPthreadAttrSetstacksize() { for(;;){} }
void sceSpPthreadCondattrDestroy() { for(;;){} }
void sceSpPthreadCondattrInit() { for(;;){} }
void sceSpPthreadCondDestroy() { for(;;){} }
void sceSpPthreadCondInit() { for(;;){} }
void sceSpPthreadCondSignal() { for(;;){} }
void sceSpPthreadCondWait() { for(;;){} }
void sceSpPthreadCreate() { for(;;){} }
void sceSpPthreadDetach() { for(;;){} }
void sceSpPthreadExit() { for(;;){} }
void sceSpPthreadJoin() { for(;;){} }
void sceSpPthreadMutexattrDestroy() { for(;;){} }
void sceSpPthreadMutexattrInit() { for(;;){} }
void sceSpPthreadMutexattrSetprioceiling() { for(;;){} }
void sceSpPthreadMutexattrSetprotocol() { for(;;){} }
void sceSpPthreadMutexattrSettype() { for(;;){} }
void sceSpPthreadMutexDestroy() { for(;;){} }
void sceSpPthreadMutexInit() { for(;;){} }
void sceSpPthreadMutexLock() { for(;;){} }
void sceSpPthreadMutexUnlock() { for(;;){} }
void sceSpPthreadSetprio() { for(;;){} }
void sceSpSelect() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}