/* Source generated by crazyvoids source generating tool **/
#include "libSceNpManagerForToolkit.h"

void sceNpCheckCallbackForLib() { for(;;){} }
void sceNpRegisterStateCallbackForToolkit() { for(;;){} }
void sceNpUnregisterStateCallbackForToolkit() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}