/* Source generated by crazyvoids source generating tool **/
#include "libSceEditMp4.h"

void sceEditMp4Abort() { for(;;){} }
void sceEditMp4Edit() { for(;;){} }
void sceEditMp4GetStatus() { for(;;){} }
void sceEditMp4Initialize() { for(;;){} }
void sceEditMp4InitializeParam() { for(;;){} }
void sceEditMp4QueryMemSize() { for(;;){} }
void sceEditMp4SetFinishCallback() { for(;;){} }
void sceEditMp4Terminate() { for(;;){} }
void sceEditMp4Unite() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}