/* Source generated by crazyvoids source generating tool **/
#include "libSceVoiceQoS.h"

void sceVoiceQoSConnect() { for(;;){} }
void sceVoiceQoSCreateLocalEndpoint() { for(;;){} }
void sceVoiceQoSCreateRemoteEndpoint() { for(;;){} }
void sceVoiceQoSDebugGetStatus() { for(;;){} }
void sceVoiceQoSDeleteLocalEndpoint() { for(;;){} }
void sceVoiceQoSDeleteRemoteEndpoint() { for(;;){} }
void sceVoiceQoSDisconnect() { for(;;){} }
void sceVoiceQoSEnd() { for(;;){} }
void sceVoiceQoSGetConnectionAttribute() { for(;;){} }
void sceVoiceQoSGetLocalEndpoint() { for(;;){} }
void sceVoiceQoSGetLocalEndpointAttribute() { for(;;){} }
void sceVoiceQoSGetRemoteEndpoint() { for(;;){} }
void sceVoiceQoSGetRemoteEndpointAttribute() { for(;;){} }
void sceVoiceQoSGetStatus() { for(;;){} }
void sceVoiceQoSInit() { for(;;){} }
void sceVoiceQoSReadPacket() { for(;;){} }
void sceVoiceQoSSetConnectionAttribute() { for(;;){} }
void sceVoiceQoSSetLocalEndpointAttribute() { for(;;){} }
void sceVoiceQoSSetRemoteEndpointAttribute() { for(;;){} }
void sceVoiceQoSWritePacket() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}