/* Source generated by crazyvoids source generating tool **/
#include "libSceInvitationDialog.h"

void sceInvitationDialogClose() { for(;;){} }
void sceInvitationDialogGetResult() { for(;;){} }
void sceInvitationDialogGetResultA() { for(;;){} }
void sceInvitationDialogGetStatus() { for(;;){} }
void sceInvitationDialogInitialize() { for(;;){} }
void sceInvitationDialogOpen() { for(;;){} }
void sceInvitationDialogOpenA() { for(;;){} }
void sceInvitationDialogTerminate() { for(;;){} }
void sceInvitationDialogUpdateStatus() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}