/* Source generated by crazyvoids source generating tool **/
#include "libSceNpMatching2Compat.h"

void sceNpMatching2CreateContext() { for(;;){} }
void sceNpMatching2CreateJoinRoom() { for(;;){} }
void sceNpMatching2GetUserInfoList() { for(;;){} }
void sceNpMatching2JoinRoom() { for(;;){} }
void sceNpMatching2SignalingGetConnectionInfo() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}