/* Source generated by crazyvoids source generating tool **/
#include "libSceVideoDecoderArbitration.h"

void sceVideoDecoderArbitrationAcceptEvent() { for(;;){} }
void sceVideoDecoderArbitrationEnable() { for(;;){} }
void sceVideoDecoderArbitrationEnableSuspendMode() { for(;;){} }
void sceVideoDecoderArbitrationInitialize() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}