/* Source generated by crazyvoids source generating tool **/
#include "libSceDbgPlayGo.h"

void sceDbgPlayGoRequestNextChunk() { for(;;){} }
void sceDbgPlayGoSnapshot() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}