/* Source generated by crazyvoids source generating tool **/
#include "libSceBluetoothHid.h"

void sceBluetoothHidDebugGetVersion() { for(;;){} }
void sceBluetoothHidDisconnectDevice() { for(;;){} }
void sceBluetoothHidGetDeviceInfo() { for(;;){} }
void sceBluetoothHidGetDeviceName() { for(;;){} }
void sceBluetoothHidGetFeatureReport() { for(;;){} }
void sceBluetoothHidGetInputReport() { for(;;){} }
void sceBluetoothHidGetReportDescriptor() { for(;;){} }
void sceBluetoothHidInit() { for(;;){} }
void sceBluetoothHidInterruptOutput() { for(;;){} }
void sceBluetoothHidParamInitialize() { for(;;){} }
void sceBluetoothHidRegisterCallback() { for(;;){} }
void sceBluetoothHidRegisterDevice() { for(;;){} }
void sceBluetoothHidSetFeatureReport() { for(;;){} }
void sceBluetoothHidSetOutputReport() { for(;;){} }
void sceBluetoothHidThreadParamInitialize() { for(;;){} }
void sceBluetoothHidUnregisterCallback() { for(;;){} }
void sceBluetoothHidUnregisterDevice() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}