/* Source generated by crazyvoids source generating tool **/
#include "libSceSystemServiceActivateHevc.h"

void sceSystemServiceActivateHevc() { for(;;){} }
void sceSystemServiceActivateHevcAbort() { for(;;){} }
void sceSystemServiceActivateHevcGetStatus() { for(;;){} }
void sceSystemServiceActivateHevcInit() { for(;;){} }
void sceSystemServiceActivateHevcIsActivated() { for(;;){} }
void sceSystemServiceActivateHevcStart() { for(;;){} }
void sceSystemServiceActivateHevcTerm() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}