/* Source generated by crazyvoids source generating tool **/
#include "libSceDtcpIp.h"

void sceDtcpIpActivateAsync() { for(;;){} }
void sceDtcpIpAddHeader() { for(;;){} }
void sceDtcpIpByteSeekAsync() { for(;;){} }
void sceDtcpIpCancelActivate() { for(;;){} }
void sceDtcpIpCheckActivationAsync() { for(;;){} }
void sceDtcpIpCloseContentAsync() { for(;;){} }
void sceDtcpIpGetErrorCode() { for(;;){} }
void sceDtcpIpGetHttpStatusCode() { for(;;){} }
void sceDtcpIpInit() { for(;;){} }
void sceDtcpIpInitAuthAsync() { for(;;){} }
void sceDtcpIpOpenContentAsync() { for(;;){} }
void sceDtcpIpPollAsync() { for(;;){} }
void sceDtcpIpReadAsync() { for(;;){} }
void sceDtcpIpRemoveHeader() { for(;;){} }
void sceDtcpIpStartAuthAsync() { for(;;){} }
void sceDtcpIpStartSeq() { for(;;){} }
void sceDtcpIpStopAuthAsync() { for(;;){} }
void sceDtcpIpStopSeq() { for(;;){} }
void sceDtcpIpTerm() { for(;;){} }
void sceDtcpIpTermAuthAsync() { for(;;){} }
void sceDtcpIpTimeSeekAsync() { for(;;){} }
void sceDtcpIpWaitAsync() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}