/* Source generated by crazyvoids source generating tool **/
#include "libScePlayGoDialog.h"

void scePlayGoDialogClose() { for(;;){} }
void scePlayGoDialogGetResult() { for(;;){} }
void scePlayGoDialogGetStatus() { for(;;){} }
void scePlayGoDialogInitialize() { for(;;){} }
void scePlayGoDialogOpen() { for(;;){} }
void scePlayGoDialogTerminate() { for(;;){} }
void scePlayGoDialogUpdateStatus() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}