/* Source generated by crazyvoids source generating tool **/
#include "libSceZlib.h"

void sceZlibFinalize() { for(;;){} }
void sceZlibGetResult() { for(;;){} }
void sceZlibInflate() { for(;;){} }
void sceZlibInitialize() { for(;;){} }
void sceZlibWaitForDone() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}