/* Source generated by crazyvoids source generating tool **/
#include "libSceVideoCoreServerInterface.h"

void sceVideoCoreAbortRequest() { for(;;){} }
void sceVideoCoreAcquireDecoderResource() { for(;;){} }
void sceVideoCoreAcquireDecoderResourceForBeWrapper() { for(;;){} }
void sceVideoCoreAddStream() { for(;;){} }
void sceVideoCoreAsyncAddStream() { for(;;){} }
void sceVideoCoreAsyncSendRequest() { for(;;){} }
void sceVideoCoreCancelThumbnail() { for(;;){} }
void sceVideoCoreChangeActiveStatus() { for(;;){} }
void sceVideoCoreChangeAudioStream() { for(;;){} }
void sceVideoCoreChangeDisplaySize() { for(;;){} }
void sceVideoCoreChangeHdcpSetting() { for(;;){} }
void sceVideoCoreChangeSubtitle() { for(;;){} }
void sceVideoCoreDeleteStream() { for(;;){} }
void sceVideoCoreGenerateThumbnail() { for(;;){} }
void sceVideoCoreGenerateThumbnail2() { for(;;){} }
void sceVideoCoreGetCanvasHandle() { for(;;){} }
void sceVideoCoreGetPlayStatus() { for(;;){} }
void sceVideoCoreGetPlayStatus2() { for(;;){} }
void sceVideoCoreGetStreamUid() { for(;;){} }
void sceVideoCoreGetThumbnail() { for(;;){} }
void sceVideoCoreGetThumbnail2() { for(;;){} }
void sceVideoCoreLaunchVideoCore() { for(;;){} }
void sceVideoCoreMediaSourceAppendData() { for(;;){} }
void sceVideoCoreMediaSourceEndOfStream() { for(;;){} }
void sceVideoCoreMediaSourceSetDuration() { for(;;){} }
void sceVideoCoreMediaSourceSetTimestampOffset() { for(;;){} }
void sceVideoCorePlayControl() { for(;;){} }
void sceVideoCoreRegistEventCallback() { for(;;){} }
void sceVideoCoreReleaseDecoderResource() { for(;;){} }
void sceVideoCoreReleaseDecoderResourceForBeWrapper() { for(;;){} }
void sceVideoCoreSetAudioMute() { for(;;){} }
void sceVideoCoreSetAudioVolume() { for(;;){} }
void sceVideoCoreSetFullScreen() { for(;;){} }
void sceVideoCoreSetInitialInfo() { for(;;){} }
void sceVideoCoreSetInitializeInfo() { for(;;){} }
void sceVideoCoreSetPlaybackRange() { for(;;){} }
void sceVideoCoreSetThumbnailInfo() { for(;;){} }
void sceVideoCoreSyncAddStream() { for(;;){} }
void sceVideoCoreSyncSendRequest() { for(;;){} }
void sceVideoCoreUnregistEventCallback() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}