/* Source generated by crazyvoids source generating tool **/
#include "libSceSystemServiceForShellCoreOnly.h"

void sceSystemServiceInitializeForShellCore() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}