/* Source generated by crazyvoids source generating tool **/
#include "libSceVideoOutBaseMode4k.h"

void sceVideoOutAddBuffer4k2kPrivilege() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}