/* Source generated by crazyvoids source generating tool **/
#include "libSceAudiodecCpuM4aac.h"

void audiodeccpuinternal_core_ops_m4aac2() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}