/* Source generated by crazyvoids source generating tool **/
#include "libSceSystemServicePowerControl.h"

void sceSystemServiceRequestPowerOff() { for(;;){} }
void sceSystemServiceRequestReboot() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}