/* Source generated by crazyvoids source generating tool **/
#include "libSceRegMgr.h"

void sceRegMgrBackupNeedMem() { for(;;){} }
void sceRegMgrBackupPullData() { for(;;){} }
void sceRegMgrBackupPushData() { for(;;){} }
void sceRegMgrCheckError() { for(;;){} }
void sceRegMgrCntlDeleteReg() { for(;;){} }
void sceRegMgrCntlGetFileName() { for(;;){} }
void sceRegMgrCntlGetFilesCount() { for(;;){} }
void sceRegMgrCntlStart() { for(;;){} }
void sceRegMgrCntlStopHdd() { for(;;){} }
void sceRegMgrCntSetInitReinst() { for(;;){} }
void sceRegMgrDrvDataCheckGet() { for(;;){} }
void sceRegMgrDrvDataClose() { for(;;){} }
void sceRegMgrDrvDataOpen() { for(;;){} }
void sceRegMgrDrvGetEntCnt() { for(;;){} }
void sceRegMgrDrvGetUpdateCnt() { for(;;){} }
void sceRegMgrEvtGetCnt() { for(;;){} }
void sceRegMgrEvtGetRegId() { for(;;){} }
void sceRegMgrGetBin() { for(;;){} }
void sceRegMgrGetBinInitVal() { for(;;){} }
void sceRegMgrGetInt() { for(;;){} }
void sceRegMgrGetIntInitVal() { for(;;){} }
void sceRegMgrGetStr() { for(;;){} }
void sceRegMgrGetStrInitVal() { for(;;){} }
void sceRegMgrGetVersion() { for(;;){} }
void sceRegMgrIsChange() { for(;;){} }
void sceRegMgrIsInitOK() { for(;;){} }
void sceRegMgrLogPull() { for(;;){} }
void sceRegMgrLogStart() { for(;;){} }
void sceRegMgrNonSysCheckError() { for(;;){} }
void sceRegMgrNonSysGetBin() { for(;;){} }
void sceRegMgrNonSysGetInt() { for(;;){} }
void sceRegMgrNonSysGetStr() { for(;;){} }
void sceRegMgrNonSysSetBin() { for(;;){} }
void sceRegMgrNonSysSetInt() { for(;;){} }
void sceRegMgrNonSysSetStr() { for(;;){} }
void sceRegMgrPrintInfo() { for(;;){} }
void sceRegMgrRecoverRegNvs() { for(;;){} }
void sceRegMgrResetVal() { for(;;){} }
void sceRegMgrSetBin() { for(;;){} }
void sceRegMgrSetInitLevel() { for(;;){} }
void sceRegMgrSetInt() { for(;;){} }
void sceRegMgrSetStr() { for(;;){} }
void sceRegMgrSrvCnvRegionInt() { for(;;){} }
void sceRegMgrSrvCnvRegionStr() { for(;;){} }
void sceRegMgrSrvGetMachineType() { for(;;){} }
void sceRegMgrSrvGetQAFforReg() { for(;;){} }
void sceRegMgrSrvGetRealMachineType() { for(;;){} }
void sceRegMgrSrvGetRegion() { for(;;){} }
void sceRegMgrSrvGetRegionStr() { for(;;){} }
void sceRegMgrToolDataCheckGet() { for(;;){} }
void sceRegMgrToolGetEntryCnt() { for(;;){} }
void sceRegMgrToolGetInfo() { for(;;){} }
void sceRegMgrToolGetUpdateCnt() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}