/* Source generated by crazyvoids source generating tool **/
#include "libSceVrTrackerFourDeviceAllowed.h"

void sceVrTrackerRegisterDevice2() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}