/* Source generated by crazyvoids source generating tool **/
#include "libSceVideoOutRawEdid.h"

void sceVideoOutGetHdmiRawEdid_() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}