/* Source generated by crazyvoids source generating tool **/
#include "libSceNpCommonCompat.h"

void sceNpCmpNpId() { for(;;){} }
void sceNpCmpNpIdInOrder() { for(;;){} }
void sceNpCmpOnlineId() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}