/* Source generated by crazyvoids source generating tool **/
#include "libSceAt9Enc.h"

void sceAt9EncClearContext() { for(;;){} }
void sceAt9EncCreateEncoder() { for(;;){} }
void sceAt9EncEncode() { for(;;){} }
void sceAt9EncFlush() { for(;;){} }
void sceAt9EncQueryMemSize() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}