/* Source generated by crazyvoids source generating tool **/
#include "libSceOpusCeltEnc.h"

void sceOpusCeltEncCreate() { for(;;){} }
void sceOpusCeltEncCtl() { for(;;){} }
void sceOpusCeltEncDestroy() { for(;;){} }
void sceOpusCeltEncEncode() { for(;;){} }
void sceOpusCeltEncEncodeFloat() { for(;;){} }
void sceOpusCeltEncEncodeFloatWithPriority() { for(;;){} }
void sceOpusCeltEncEncodeWithPriority() { for(;;){} }
void sceOpusCeltEncGetSize() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}