/* Source generated by crazyvoids source generating tool **/
#include "libScePrecompiledShaders.h"

void scePrecompiledShaderEntries() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}