/* Source generated by crazyvoids source generating tool **/
#include "libSceSharePlay.h"

void sceSharePlayCrashDaemon() { for(;;){} }
void sceSharePlayGetCurrentConnectionInfo() { for(;;){} }
void sceSharePlayGetCurrentConnectionInfoA() { for(;;){} }
void sceSharePlayGetCurrentInfo() { for(;;){} }
void sceSharePlayGetEvent() { for(;;){} }
void sceSharePlayInitialize() { for(;;){} }
void sceSharePlayNotifyForceCloseForCdlg() { for(;;){} }
void sceSharePlayResumeScreenForCdlg() { for(;;){} }
void sceSharePlayServerLock() { for(;;){} }
void sceSharePlayServerUnLock() { for(;;){} }
void sceSharePlaySetMode() { for(;;){} }
void sceSharePlaySetProhibition() { for(;;){} }
void sceSharePlaySetProhibitionModeWithAppId() { for(;;){} }
void sceSharePlayStartStandby() { for(;;){} }
void sceSharePlayStartStreaming() { for(;;){} }
void sceSharePlayStopStandby() { for(;;){} }
void sceSharePlayStopStreaming() { for(;;){} }
void sceSharePlayTerminate() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}