/* Source generated by crazyvoids source generating tool **/
#include "libSceHttp.h"

void sceHttpAbortRequest() { for(;;){} }
void sceHttpAbortRequestForce() { for(;;){} }
void sceHttpAbortWaitRequest() { for(;;){} }
void sceHttpAddCookie() { for(;;){} }
void sceHttpAddQuery() { for(;;){} }
void sceHttpAddRequestHeader() { for(;;){} }
void sceHttpAddRequestHeaderRaw() { for(;;){} }
void sceHttpAuthCacheExport() { for(;;){} }
void sceHttpAuthCacheFlush() { for(;;){} }
void sceHttpAuthCacheImport() { for(;;){} }
void sceHttpCookieExport() { for(;;){} }
void sceHttpCookieFlush() { for(;;){} }
void sceHttpCookieImport() { for(;;){} }
void sceHttpCreateConnection() { for(;;){} }
void sceHttpCreateConnectionWithURL() { for(;;){} }
void sceHttpCreateEpoll() { for(;;){} }
void sceHttpCreateRequest() { for(;;){} }
void sceHttpCreateRequest2() { for(;;){} }
void sceHttpCreateRequestWithURL() { for(;;){} }
void sceHttpCreateRequestWithURL2() { for(;;){} }
void sceHttpCreateTemplate() { for(;;){} }
void sceHttpDbgEnableProfile() { for(;;){} }
void sceHttpDbgGetConnectionStat() { for(;;){} }
void sceHttpDbgGetRequestStat() { for(;;){} }
void sceHttpDbgSetPrintf() { for(;;){} }
void sceHttpDbgShowConnectionStat() { for(;;){} }
void sceHttpDbgShowMemoryPoolStat() { for(;;){} }
void sceHttpDbgShowRequestStat() { for(;;){} }
void sceHttpDbgShowStat() { for(;;){} }
void sceHttpDeleteConnection() { for(;;){} }
void sceHttpDeleteRequest() { for(;;){} }
void sceHttpDeleteTemplate() { for(;;){} }
void sceHttpDestroyEpoll() { for(;;){} }
void sceHttpGetAcceptEncodingGZIPEnabled() { for(;;){} }
void sceHttpGetAllResponseHeaders() { for(;;){} }
void sceHttpGetAuthEnabled() { for(;;){} }
void sceHttpGetAutoRedirect() { for(;;){} }
void sceHttpGetConnectionStat() { for(;;){} }
void sceHttpGetCookie() { for(;;){} }
void sceHttpGetCookieEnabled() { for(;;){} }
void sceHttpGetCookieStats() { for(;;){} }
void sceHttpGetEpoll() { for(;;){} }
void sceHttpGetEpollId() { for(;;){} }
void sceHttpGetLastErrno() { for(;;){} }
void sceHttpGetMemoryPoolStats() { for(;;){} }
void sceHttpGetNonblock() { for(;;){} }
void sceHttpGetRegisteredCtxIds() { for(;;){} }
void sceHttpGetResponseContentLength() { for(;;){} }
void sceHttpGetStatusCode() { for(;;){} }
void sceHttpInit() { for(;;){} }
void sceHttpParseResponseHeader() { for(;;){} }
void sceHttpParseStatusLine() { for(;;){} }
void sceHttpReadData() { for(;;){} }
void sceHttpRedirectCacheFlush() { for(;;){} }
void sceHttpRemoveRequestHeader() { for(;;){} }
void sceHttpRequestGetAllHeaders() { for(;;){} }
void sceHttpsDisableOption() { for(;;){} }
void sceHttpsDisableOptionPrivate() { for(;;){} }
void sceHttpsEnableOption() { for(;;){} }
void sceHttpsEnableOptionPrivate() { for(;;){} }
void sceHttpSendRequest() { for(;;){} }
void sceHttpSetAcceptEncodingGZIPEnabled() { for(;;){} }
void sceHttpSetAuthEnabled() { for(;;){} }
void sceHttpSetAuthInfoCallback() { for(;;){} }
void sceHttpSetAutoRedirect() { for(;;){} }
void sceHttpSetChunkedTransferEnabled() { for(;;){} }
void sceHttpSetConnectTimeOut() { for(;;){} }
void sceHttpSetCookieEnabled() { for(;;){} }
void sceHttpSetCookieMaxNum() { for(;;){} }
void sceHttpSetCookieMaxNumPerDomain() { for(;;){} }
void sceHttpSetCookieMaxSize() { for(;;){} }
void sceHttpSetCookieRecvCallback() { for(;;){} }
void sceHttpSetCookieSendCallback() { for(;;){} }
void sceHttpSetCookieTotalMaxSize() { for(;;){} }
void sceHttpSetDefaultAcceptEncodingGZIPEnabled() { for(;;){} }
void sceHttpSetEpoll() { for(;;){} }
void sceHttpSetEpollId() { for(;;){} }
void sceHttpSetHttp09Enabled() { for(;;){} }
void sceHttpSetInflateGZIPEnabled() { for(;;){} }
void sceHttpSetNonblock() { for(;;){} }
void sceHttpSetPolicyOption() { for(;;){} }
void sceHttpSetPriorityOption() { for(;;){} }
void sceHttpSetProxy() { for(;;){} }
void sceHttpSetRecvBlockSize() { for(;;){} }
void sceHttpSetRecvTimeOut() { for(;;){} }
void sceHttpSetRedirectCallback() { for(;;){} }
void sceHttpSetRequestContentLength() { for(;;){} }
void sceHttpSetRequestStatusCallback() { for(;;){} }
void sceHttpSetResolveRetry() { for(;;){} }
void sceHttpSetResolveTimeOut() { for(;;){} }
void sceHttpSetResponseHeaderMaxSize() { for(;;){} }
void sceHttpSetSendTimeOut() { for(;;){} }
void sceHttpSetSocketCreationCallback() { for(;;){} }
void sceHttpsFreeCaList() { for(;;){} }
void sceHttpsGetCaList() { for(;;){} }
void sceHttpsGetSslError() { for(;;){} }
void sceHttpsLoadCert() { for(;;){} }
void sceHttpsSetMinSslVersion() { for(;;){} }
void sceHttpsSetSslCallback() { for(;;){} }
void sceHttpsSetSslVersion() { for(;;){} }
void sceHttpsUnloadCert() { for(;;){} }
void sceHttpTerm() { for(;;){} }
void sceHttpTryGetNonblock() { for(;;){} }
void sceHttpTrySetNonblock() { for(;;){} }
void sceHttpUnsetEpoll() { for(;;){} }
void sceHttpUriBuild() { for(;;){} }
void sceHttpUriCopy() { for(;;){} }
void sceHttpUriEscape() { for(;;){} }
void sceHttpUriMerge() { for(;;){} }
void sceHttpUriParse() { for(;;){} }
void sceHttpUriSweepPath() { for(;;){} }
void sceHttpUriUnescape() { for(;;){} }
void sceHttpWaitRequest() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}