/* Source generated by crazyvoids source generating tool **/
#include "libSceSocialScreen.h"

void sceSocialScreenCloseSeparateMode() { for(;;){} }
void sceSocialScreenConfigureSeparateMode() { for(;;){} }
void sceSocialScreenCrashDaemon() { for(;;){} }
void sceSocialScreenGetIgnoreSeparateMode() { for(;;){} }
void sceSocialScreenInitialize() { for(;;){} }
void sceSocialScreenInitializeSeparateModeParameter() { for(;;){} }
void sceSocialScreenOpenSeparateMode() { for(;;){} }
void sceSocialScreenReserveHighFrameRateVideoCaptureRequest() { for(;;){} }
void sceSocialScreenSetIgnoreSeparateMode() { for(;;){} }
void sceSocialScreenSetMode() { for(;;){} }
void sceSocialScreenTerminate() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}