/* Source generated by crazyvoids source generating tool **/
#include "libSceKbEmulate.h"

void sceKeyboardPadEmulateClose() { for(;;){} }
void sceKeyboardPadEmulateOpen() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}