/* Source generated by crazyvoids source generating tool **/
#include "libSceHmdDistortion.h"

void sceHmdDistortionGet2dVrCommand() { for(;;){} }
void sceHmdDistortionGetCompoundEyeCorrectionCommand() { for(;;){} }
void sceHmdDistortionGetCorrectionCommand() { for(;;){} }
void sceHmdDistortionGetWideNearCorrectionCommand() { for(;;){} }
void sceHmdDistortionGetWorkMemoryAlign() { for(;;){} }
void sceHmdDistortionGetWorkMemorySize() { for(;;){} }
void sceHmdDistortionInitialize() { for(;;){} }
void sceHmdDistortionSetOutputMinColor() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}