/* Source generated by crazyvoids source generating tool **/
#include "libSceNpSnsTwitchDialog.h"

void sceNpSnsTwitchDialogClose() { for(;;){} }
void sceNpSnsTwitchDialogGetResult() { for(;;){} }
void sceNpSnsTwitchDialogGetStatus() { for(;;){} }
void sceNpSnsTwitchDialogInitialize() { for(;;){} }
void sceNpSnsTwitchDialogOpen() { for(;;){} }
void sceNpSnsTwitchDialogTerminate() { for(;;){} }
void sceNpSnsTwitchDialogUpdateStatus() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}