/* Source generated by crazyvoids source generating tool **/
#include "libSceSystemLogger.h"

void sceSystemLoggerInitialize() { for(;;){} }
void sceSystemLoggerSetLogData() { for(;;){} }
void sceSystemLoggerTerminate() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}