/* Source generated by crazyvoids source generating tool **/
#include "libSceBgft.h"

void sceBgftServiceDownloadFindActivePatchTask() { for(;;){} }
void sceBgftServiceDownloadFindActivePupTask() { for(;;){} }
void sceBgftServiceDownloadFindTaskByContentId() { for(;;){} }
void sceBgftServiceDownloadGetProgress() { for(;;){} }
void sceBgftServiceDownloadPauseTask() { for(;;){} }
void sceBgftServiceDownloadPauseTaskAll() { for(;;){} }
void sceBgftServiceDownloadQueryTask() { for(;;){} }
void sceBgftServiceDownloadRegisterTask() { for(;;){} }
void sceBgftServiceDownloadRegisterTaskByStorage() { for(;;){} }
void sceBgftServiceDownloadResumeTask() { for(;;){} }
void sceBgftServiceDownloadResumeTaskAll() { for(;;){} }
void sceBgftServiceDownloadStartTask() { for(;;){} }
void sceBgftServiceDownloadStartTaskAll() { for(;;){} }
void sceBgftServiceDownloadStopTask() { for(;;){} }
void sceBgftServiceDownloadStopTaskAll() { for(;;){} }
void sceBgftServiceInit() { for(;;){} }
void sceBgftServiceIntAbortNotificationEvent() { for(;;){} }
void sceBgftServiceIntDebugDownloadCorruptPkg() { for(;;){} }
void sceBgftServiceIntDebugDownloadRegisterPkg() { for(;;){} }
void sceBgftServiceIntDebugDownloadRequest() { for(;;){} }
void sceBgftServiceIntDebugPlayGoIsPaused() { for(;;){} }
void sceBgftServiceIntDebugPlayGoResume() { for(;;){} }
void sceBgftServiceIntDebugPlayGoRevertToFullState() { for(;;){} }
void sceBgftServiceIntDebugPlayGoRevertToInitialState() { for(;;){} }
void sceBgftServiceIntDebugPlayGoRevertToSnapshot() { for(;;){} }
void sceBgftServiceIntDebugPlayGoSnapshotByTitleId() { for(;;){} }
void sceBgftServiceIntDebugPlayGoSuspend() { for(;;){} }
void sceBgftServiceIntDownloadCheckPatchUpdateState() { for(;;){} }
void sceBgftServiceIntDownloadDebugDeleteBgftEnvFile() { for(;;){} }
void sceBgftServiceIntDownloadDebugDownloadBgftEnvFile() { for(;;){} }
void sceBgftServiceIntDownloadDebugGetBgftEnvInfoString() { for(;;){} }
void sceBgftServiceIntDownloadFindActiveGameAndGameAcTask() { for(;;){} }
void sceBgftServiceIntDownloadFindActiveTask() { for(;;){} }
void sceBgftServiceIntDownloadGetApplicationDataSize() { for(;;){} }
void sceBgftServiceIntDownloadGetExtUsbUserStorageSize() { for(;;){} }
void sceBgftServiceIntDownloadGetGameAndGameAcProgress() { for(;;){} }
void sceBgftServiceIntDownloadGetPatchProgress() { for(;;){} }
void sceBgftServiceIntDownloadGetPlayGoProgress() { for(;;){} }
void sceBgftServiceIntDownloadGetProgress() { for(;;){} }
void sceBgftServiceIntDownloadGetTaskInfo() { for(;;){} }
void sceBgftServiceIntDownloadGetUserStorageSize() { for(;;){} }
void sceBgftServiceIntDownloadPauseTask() { for(;;){} }
void sceBgftServiceIntDownloadQueryTask() { for(;;){} }
void sceBgftServiceIntDownloadQueryTaskSection() { for(;;){} }
void sceBgftServiceIntDownloadRegisterTask() { for(;;){} }
void sceBgftServiceIntDownloadRegisterTaskByStorage() { for(;;){} }
void sceBgftServiceIntDownloadRegisterTaskByStorageEx() { for(;;){} }
void sceBgftServiceIntDownloadRegisterTaskStore() { for(;;){} }
void sceBgftServiceIntDownloadReregisterTaskPatch() { for(;;){} }
void sceBgftServiceIntDownloadResumeTask() { for(;;){} }
void sceBgftServiceIntDownloadSetHighPriority() { for(;;){} }
void sceBgftServiceIntDownloadSetResumeState() { for(;;){} }
void sceBgftServiceIntDownloadSetStartState() { for(;;){} }
void sceBgftServiceIntDownloadStartTask() { for(;;){} }
void sceBgftServiceIntDownloadStartTaskAll() { for(;;){} }
void sceBgftServiceIntDownloadStopTask() { for(;;){} }
void sceBgftServiceIntDownloadStopTaskAll() { for(;;){} }
void sceBgftServiceIntDownloadUnregisterTask() { for(;;){} }
void sceBgftServiceIntDownloadUnregisterTaskAll() { for(;;){} }
void sceBgftServiceIntExtUsbCheckActiveDownloadTasks() { for(;;){} }
void sceBgftServiceIntGetNotificationEvent() { for(;;){} }
void sceBgftServiceIntGetNotificationParam() { for(;;){} }
void sceBgftServiceIntGetTaskInfoValueInt() { for(;;){} }
void sceBgftServiceIntGetTaskInfoValueString() { for(;;){} }
void sceBgftServiceIntGetTaskInfoValueStringIndex() { for(;;){} }
void sceBgftServiceIntInit() { for(;;){} }
void sceBgftServiceIntPlayGoGetApplicationIniChunkSize() { for(;;){} }
void sceBgftServiceIntPlayGoGetDownloadTaskId() { for(;;){} }
void sceBgftServiceIntSetTaskVisible() { for(;;){} }
void sceBgftServiceIntTerm() { for(;;){} }
void sceBgftServiceIntUploadGetAvailableTaskCount() { for(;;){} }
void sceBgftServiceIntUploadGetProgress() { for(;;){} }
void sceBgftServiceIntUploadGetTaskInfo() { for(;;){} }
void sceBgftServiceIntUploadQueryTask() { for(;;){} }
void sceBgftServiceIntUploadQueryTaskSection() { for(;;){} }
void sceBgftServiceIntUploadRegisterTask() { for(;;){} }
void sceBgftServiceIntUploadSetHighPriority() { for(;;){} }
void sceBgftServiceIntUploadSetStartState() { for(;;){} }
void sceBgftServiceIntUploadStartTask() { for(;;){} }
void sceBgftServiceIntUploadStartTaskAll() { for(;;){} }
void sceBgftServiceIntUploadStopTask() { for(;;){} }
void sceBgftServiceIntUploadStopTaskAll() { for(;;){} }
void sceBgftServiceIntUploadUnregisterTask() { for(;;){} }
void sceBgftServiceIntUploadUnregisterTaskAll() { for(;;){} }
void sceBgftServiceTerm() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}