/* Source generated by crazyvoids source generating tool **/
#include "libScePsmUtil.h"

void scePsmUtilFinalize() { for(;;){} }
void scePsmUtilGetPsmIniFile() { for(;;){} }
void scePsmUtilInitialize() { for(;;){} }
void scePsmUtilRegisterCallbacks() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}