/* Source generated by crazyvoids source generating tool **/
#include "libSceAudiodecCpuDtsHdLbr.h"

void audiodeccpuinternal_core_ops_dts_hd_lbr() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}