/* Source generated by crazyvoids source generating tool **/
#include "libSceSharePlayCompat.h"

void sceSharePlayGetCurrentConnectionInfo() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}