/* Source generated by crazyvoids source generating tool **/
#include "libSceUsbStorage.h"

void sceUsbStorageGetDeviceInfo() { for(;;){} }
void sceUsbStorageGetDeviceList() { for(;;){} }
void sceUsbStorageInit() { for(;;){} }
void sceUsbStorageIsExist() { for(;;){} }
void sceUsbStorageRegisterCallback() { for(;;){} }
void sceUsbStorageRegisterCallbackForMapAvailable() { for(;;){} }
void sceUsbStorageRequestMap() { for(;;){} }
void sceUsbStorageRequestUnmap() { for(;;){} }
void sceUsbStorageTerm() { for(;;){} }
void sceUsbStorageUnregisterCallback() { for(;;){} }
void sceUsbStorageUnregisterCallbackForMapAvailable() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}