/* Source generated by crazyvoids source generating tool **/
#include "libSceCamera.h"

void sceCameraAccGetData() { for(;;){} }
void sceCameraAudioClose() { for(;;){} }
void sceCameraAudioGetData() { for(;;){} }
void sceCameraAudioGetData2() { for(;;){} }
void sceCameraAudioOpen() { for(;;){} }
void sceCameraAudioReset() { for(;;){} }
void sceCameraChangeAppModuleState() { for(;;){} }
void sceCameraClose() { for(;;){} }
void sceCameraCloseByHandle() { for(;;){} }
void sceCameraDeviceOpen() { for(;;){} }
void sceCameraGetAttribute() { for(;;){} }
void sceCameraGetAutoExposureGain() { for(;;){} }
void sceCameraGetAutoWhiteBalance() { for(;;){} }
void sceCameraGetCalibData() { for(;;){} }
void sceCameraGetCalibDataFromDevice() { for(;;){} }
void sceCameraGetCalibrationData() { for(;;){} }
void sceCameraGetConfig() { for(;;){} }
void sceCameraGetContrast() { for(;;){} }
void sceCameraGetDefectivePixelCancellation() { for(;;){} }
void sceCameraGetDeviceConfig() { for(;;){} }
void sceCameraGetDeviceConfigWithoutHandle() { for(;;){} }
void sceCameraGetDeviceID() { for(;;){} }
void sceCameraGetDeviceIDWithoutOpen() { for(;;){} }
void sceCameraGetDeviceInfo() { for(;;){} }
void sceCameraGetExposureGain() { for(;;){} }
void sceCameraGetFrameData() { for(;;){} }
void sceCameraGetGamma() { for(;;){} }
void sceCameraGetHue() { for(;;){} }
void sceCameraGetLensCorrection() { for(;;){} }
void sceCameraGetMmapConnectedCount() { for(;;){} }
void sceCameraGetProductInfo() { for(;;){} }
void sceCameraGetRegister() { for(;;){} }
void sceCameraGetRegistryInfo() { for(;;){} }
void sceCameraGetSaturation() { for(;;){} }
void sceCameraGetSharpness() { for(;;){} }
void sceCameraGetVrCaptureInfo() { for(;;){} }
void sceCameraGetWhiteBalance() { for(;;){} }
void sceCameraInitializeRegistryCalibData() { for(;;){} }
void sceCameraIsAttached() { for(;;){} }
void sceCameraIsConfigChangeDone() { for(;;){} }
void sceCameraIsValidFrameData() { for(;;){} }
void sceCameraOpen() { for(;;){} }
void sceCameraOpenByModuleId() { for(;;){} }
void sceCameraRemoveAppModuleFocus() { for(;;){} }
void sceCameraSetAppModuleFocus() { for(;;){} }
void sceCameraSetAttribute() { for(;;){} }
void sceCameraSetAttributeInternal() { for(;;){} }
void sceCameraSetAutoExposureGain() { for(;;){} }
void sceCameraSetAutoWhiteBalance() { for(;;){} }
void sceCameraSetCalibData() { for(;;){} }
void sceCameraSetConfig() { for(;;){} }
void sceCameraSetConfigInternal() { for(;;){} }
void sceCameraSetContrast() { for(;;){} }
void sceCameraSetDebugStop() { for(;;){} }
void sceCameraSetDefectivePixelCancellation() { for(;;){} }
void sceCameraSetDefectivePixelCancellationInternal() { for(;;){} }
void sceCameraSetExposureGain() { for(;;){} }
void sceCameraSetForceActivate() { for(;;){} }
void sceCameraSetGamma() { for(;;){} }
void sceCameraSetHue() { for(;;){} }
void sceCameraSetLensCorrection() { for(;;){} }
void sceCameraSetLensCorrectionInternal() { for(;;){} }
void sceCameraSetProcessFocus() { for(;;){} }
void sceCameraSetProcessFocusByHandle() { for(;;){} }
void sceCameraSetRegister() { for(;;){} }
void sceCameraSetSaturation() { for(;;){} }
void sceCameraSetSharpness() { for(;;){} }
void sceCameraSetTrackerMode() { for(;;){} }
void sceCameraSetUacModeInternal() { for(;;){} }
void sceCameraSetVideoSync() { for(;;){} }
void sceCameraSetVideoSyncInternal() { for(;;){} }
void sceCameraSetWhiteBalance() { for(;;){} }
void sceCameraStart() { for(;;){} }
void sceCameraStartByHandle() { for(;;){} }
void sceCameraStop() { for(;;){} }
void sceCameraStopByHandle() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}