/* Source generated by crazyvoids source generating tool **/
#include "libSceUlt.h"

void _sceUltConditionVariableCreate() { for(;;){} }
void _sceUltConditionVariableOptParamInitialize() { for(;;){} }
void _sceUltMutexCreate() { for(;;){} }
void _sceUltMutexOptParamInitialize() { for(;;){} }
void _sceUltQueueCreate() { for(;;){} }
void _sceUltQueueDataResourcePoolCreate() { for(;;){} }
void _sceUltQueueDataResourcePoolOptParamInitialize() { for(;;){} }
void _sceUltQueueOptParamInitialize() { for(;;){} }
void _sceUltReaderWriterLockCreate() { for(;;){} }
void _sceUltReaderWriterLockOptParamInitialize() { for(;;){} }
void _sceUltSemaphoreCreate() { for(;;){} }
void _sceUltSemaphoreOptParamInitialize() { for(;;){} }
void _sceUltUlthreadCreate() { for(;;){} }
void _sceUltUlthreadOptParamInitialize() { for(;;){} }
void _sceUltUlthreadRuntimeCreate() { for(;;){} }
void _sceUltUlthreadRuntimeOptParamInitialize() { for(;;){} }
void _sceUltWaitingQueueResourcePoolCreate() { for(;;){} }
void _sceUltWaitingQueueResourcePoolOptParamInitialize() { for(;;){} }
void sceUltConditionVariableDestroy() { for(;;){} }
void sceUltConditionVariableSignal() { for(;;){} }
void sceUltConditionVariableSignalAll() { for(;;){} }
void sceUltConditionVariableWait() { for(;;){} }
void sceUltFinalize() { for(;;){} }
void sceUltGetConditionVariableInfo() { for(;;){} }
void sceUltGetMutexInfo() { for(;;){} }
void sceUltGetQueueDataResourcePoolInfo() { for(;;){} }
void sceUltGetQueueInfo() { for(;;){} }
void sceUltGetReaderWriterLockInfo() { for(;;){} }
void sceUltGetSemaphoreInfo() { for(;;){} }
void sceUltGetUlthreadInfo() { for(;;){} }
void sceUltGetUlthreadRuntimeInfo() { for(;;){} }
void sceUltGetWaitingQueueResourcePoolInfo() { for(;;){} }
void sceUltInitialize() { for(;;){} }
void sceUltMutexDestroy() { for(;;){} }
void sceUltMutexLock() { for(;;){} }
void sceUltMutexTryLock() { for(;;){} }
void sceUltMutexUnlock() { for(;;){} }
void sceUltQueueDataResourcePoolDestroy() { for(;;){} }
void sceUltQueueDataResourcePoolGetWorkAreaSize() { for(;;){} }
void sceUltQueueDestroy() { for(;;){} }
void sceUltQueuePop() { for(;;){} }
void sceUltQueuePush() { for(;;){} }
void sceUltQueueTryPop() { for(;;){} }
void sceUltQueueTryPush() { for(;;){} }
void sceUltReaderWriterLockDestroy() { for(;;){} }
void sceUltReaderWriterLockLockRead() { for(;;){} }
void sceUltReaderWriterLockLockWrite() { for(;;){} }
void sceUltReaderWriterLockTryLockRead() { for(;;){} }
void sceUltReaderWriterLockTryLockWrite() { for(;;){} }
void sceUltReaderWriterLockUnlockRead() { for(;;){} }
void sceUltReaderWriterLockUnlockWrite() { for(;;){} }
void sceUltSemaphoreAcquire() { for(;;){} }
void sceUltSemaphoreDestroy() { for(;;){} }
void sceUltSemaphoreRelease() { for(;;){} }
void sceUltSemaphoreTryAcquire() { for(;;){} }
void sceUltUlthreadExit() { for(;;){} }
void sceUltUlthreadGetSelf() { for(;;){} }
void sceUltUlthreadJoin() { for(;;){} }
void sceUltUlthreadRuntimeDestroy() { for(;;){} }
void sceUltUlthreadRuntimeGetWorkAreaSize() { for(;;){} }
void sceUltUlthreadTryJoin() { for(;;){} }
void sceUltUlthreadYield() { for(;;){} }
void sceUltWaitingQueueResourcePoolDestroy() { for(;;){} }
void sceUltWaitingQueueResourcePoolGetWorkAreaSize() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}