/* Source generated by crazyvoids source generating tool **/
#include "libScePngDec.h"

void scePngDecCreate() { for(;;){} }
void scePngDecDecode() { for(;;){} }
void scePngDecDecodeWithInputControl() { for(;;){} }
void scePngDecDelete() { for(;;){} }
void scePngDecParseHeader() { for(;;){} }
void scePngDecQueryMemorySize() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}