/* Source generated by crazyvoids source generating tool **/
#include "libSceNpManagerCompat.h"

void sceNpCheckNpAvailability() { for(;;){} }
void sceNpGetAccountCountry() { for(;;){} }
void sceNpGetAccountDateOfBirth() { for(;;){} }
void sceNpGetAccountId() { for(;;){} }
void sceNpGetAccountLanguage() { for(;;){} }
void sceNpGetGamePresenceStatus() { for(;;){} }
void sceNpGetParentalControlInfo() { for(;;){} }
void sceNpGetUserIdByOnlineId() { for(;;){} }
void sceNpInGameMessagePrepare() { for(;;){} }
void sceNpInGameMessageSendData() { for(;;){} }
void sceNpRegisterGamePresenceCallback() { for(;;){} }
void sceNpRegisterStateCallback() { for(;;){} }
void sceNpSetGamePresenceOnline() { for(;;){} }
void sceNpUnregisterStateCallback() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}