/* Source generated by crazyvoids source generating tool **/
#include "libSceAppInstUtil.h"

void sceAppInstUtilAppAllowDownloadInstall() { for(;;){} }
void sceAppInstUtilAppCancelableUnInstall() { for(;;){} }
void sceAppInstUtilAppCancelableUnInstallByUser() { for(;;){} }
void sceAppInstUtilAppCancelGetAllAppSize() { for(;;){} }
void sceAppInstUtilAppCancelMoveApps() { for(;;){} }
void sceAppInstUtilAppCancelUnInstall() { for(;;){} }
void sceAppInstUtilAppConvertAppDiscToDownload() { for(;;){} }
void sceAppInstUtilAppConvertAppDownloadToDisc() { for(;;){} }
void sceAppInstUtilAppDestroyMetadata() { for(;;){} }
void sceAppInstUtilAppDestroyPkg() { for(;;){} }
void sceAppInstUtilAppExists() { for(;;){} }
void sceAppInstUtilAppGetAddcontInfo() { for(;;){} }
void sceAppInstUtilAppGetAddcontInfoByContentId() { for(;;){} }
void sceAppInstUtilAppGetAddcontListTotalSize() { for(;;){} }
void sceAppInstUtilAppGetAddcontNum() { for(;;){} }
void sceAppInstUtilAppGetAllAppSize() { for(;;){} }
void sceAppInstUtilAppGetAppInstallStatus() { for(;;){} }
void sceAppInstUtilAppGetAppInstallStatusByAppInfo() { for(;;){} }
void sceAppInstUtilAppGetAppOtherSize() { for(;;){} }
void sceAppInstUtilAppGetCompilationDiscInfo() { for(;;){} }
void sceAppInstUtilAppGetCustomThemeInfo() { for(;;){} }
void sceAppInstUtilAppGetInsertedDiscMasterDataId() { for(;;){} }
void sceAppInstUtilAppGetInsertedDiscTitleId() { for(;;){} }
void sceAppInstUtilAppGetInsertedDiscTitleIdList() { for(;;){} }
void sceAppInstUtilAppGetInstallAddcontFromDiscStatus() { for(;;){} }
void sceAppInstUtilAppGetIrremovableAppList() { for(;;){} }
void sceAppInstUtilAppGetMoveErrorAppList() { for(;;){} }
void sceAppInstUtilAppGetNoRelatedAddcontTitleList() { for(;;){} }
void sceAppInstUtilAppGetSize() { for(;;){} }
void sceAppInstUtilAppGetStoreCompilationDiscInfo() { for(;;){} }
void sceAppInstUtilAppInstallAll() { for(;;){} }
void sceAppInstUtilAppInstallCloudGame() { for(;;){} }
void sceAppInstUtilAppInstallGetLinkState() { for(;;){} }
void sceAppInstUtilAppInstallMediaPlayer() { for(;;){} }
void sceAppInstUtilAppInstallPkg() { for(;;){} }
void sceAppInstUtilAppInstallPs4CloudGame() { for(;;){} }
void sceAppInstUtilAppInstallRequestAddcontFromDisc() { for(;;){} }
void sceAppInstUtilAppInstallRequestCompilationDiscApp() { for(;;){} }
void sceAppInstUtilAppInstallSharePlayLink() { for(;;){} }
void sceAppInstUtilAppInstallSharePlayLinkByUser() { for(;;){} }
void sceAppInstUtilAppInstallTitleDir() { for(;;){} }
void sceAppInstUtilAppIsInInstalling() { for(;;){} }
void sceAppInstUtilAppIsInUpdating() { for(;;){} }
void sceAppInstUtilAppPrepareOverwritePkg() { for(;;){} }
void sceAppInstUtilAppProhibitDownloadInstall() { for(;;){} }
void sceAppInstUtilAppRecoverApp() { for(;;){} }
void sceAppInstUtilAppRequestMoveApps() { for(;;){} }
void sceAppInstUtilAppSetSavedataUploadStatus() { for(;;){} }
void sceAppInstUtilAppStoreCompilationDiscInfo() { for(;;){} }
void sceAppInstUtilAppUnInstall() { for(;;){} }
void sceAppInstUtilAppUnInstallAddcont() { for(;;){} }
void sceAppInstUtilAppUnInstallByUser() { for(;;){} }
void sceAppInstUtilAppUnInstallForMultiInstall() { for(;;){} }
void sceAppInstUtilAppUnInstallPat() { for(;;){} }
void sceAppInstUtilAppUnInstallTheme() { for(;;){} }
void sceAppInstUtilAppUnInstallTypes() { for(;;){} }
void sceAppInstUtilAppUpdateStartTime() { for(;;){} }
void sceAppInstUtilCancelDataDiscCopy() { for(;;){} }
void sceAppInstUtilCheckAppSystemVer() { for(;;){} }
void sceAppInstUtilGetAddcontInstalledStatus() { for(;;){} }
void sceAppInstUtilGetAppEmptySlot() { for(;;){} }
void sceAppInstUtilGetAppMoveProgressInfo() { for(;;){} }
void sceAppInstUtilGetAppSlotInfoList() { for(;;){} }
void sceAppInstUtilGetDataDiscCopyProgress() { for(;;){} }
void sceAppInstUtilGetInsertedDiscRoleType() { for(;;){} }
void sceAppInstUtilGetInstallProgress() { for(;;){} }
void sceAppInstUtilGetInstallProgressInfo() { for(;;){} }
void sceAppInstUtilGetMainAppTitleIdForSP() { for(;;){} }
void sceAppInstUtilGetPrimaryAppSlot() { for(;;){} }
void sceAppInstUtilGetSubAppTitleIdForSP() { for(;;){} }
void sceAppInstUtilGetTitleIdFromPkg() { for(;;){} }
void sceAppInstUtilInitialize() { for(;;){} }
void sceAppInstUtilJson() { for(;;){} }
void sceAppInstUtilRequestDataDiscCopy() { for(;;){} }
void sceAppInstUtilRequestInstallDiscGame() { for(;;){} }
void sceAppInstUtilSetPrimaryAppSlot() { for(;;){} }
void sceAppInstUtilTerminate() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}