/* Source generated by crazyvoids source generating tool **/
#include "libSceRudp.h"

void sceRudpAccept() { for(;;){} }
void sceRudpActivate() { for(;;){} }
void sceRudpBind() { for(;;){} }
void sceRudpCreateContext() { for(;;){} }
void sceRudpEnableInternalIOThread() { for(;;){} }
void sceRudpEnableInternalIOThread2() { for(;;){} }
void sceRudpEnd() { for(;;){} }
void sceRudpFlush() { for(;;){} }
void sceRudpGetContextStatus() { for(;;){} }
void sceRudpGetLocalInfo() { for(;;){} }
void sceRudpGetMaxSegmentSize() { for(;;){} }
void sceRudpGetNumberOfPacketsToRead() { for(;;){} }
void sceRudpGetOption() { for(;;){} }
void sceRudpGetRemoteInfo() { for(;;){} }
void sceRudpGetSizeReadable() { for(;;){} }
void sceRudpGetSizeWritable() { for(;;){} }
void sceRudpGetStatus() { for(;;){} }
void sceRudpInit() { for(;;){} }
void sceRudpInitiate() { for(;;){} }
void sceRudpListen() { for(;;){} }
void sceRudpNetFlush() { for(;;){} }
void sceRudpNetReceived() { for(;;){} }
void sceRudpPollCancel() { for(;;){} }
void sceRudpPollControl() { for(;;){} }
void sceRudpPollCreate() { for(;;){} }
void sceRudpPollDestroy() { for(;;){} }
void sceRudpPollWait() { for(;;){} }
void sceRudpProcessEvents() { for(;;){} }
void sceRudpRead() { for(;;){} }
void sceRudpSetEventHandler() { for(;;){} }
void sceRudpSetMaxSegmentSize() { for(;;){} }
void sceRudpSetOption() { for(;;){} }
void sceRudpTerminate() { for(;;){} }
void sceRudpWrite() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}