/* Source generated by crazyvoids source generating tool **/
#include "libSceRandom.h"

void sceRandomGetRandomNumber() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}