/* Source generated by crazyvoids source generating tool **/
#include "libSceSystemServiceEyeToEyeDistance.h"

void sceSystemServiceDisablePersonalEyeToEyeDistanceSetting() { for(;;){} }
void sceSystemServiceEnablePersonalEyeToEyeDistanceSetting() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}