/* Source generated by crazyvoids source generating tool **/
#include "MicrosoftCSharp.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Microsoft_CSharpjit_code_end() { for(;;){} }
void mono_aot_Microsoft_CSharpjit_code_start() { for(;;){} }
void mono_aot_Microsoft_CSharpjit_got() { for(;;){} }
void mono_aot_Microsoft_CSharpmethod_addresses() { for(;;){} }
void mono_aot_Microsoft_CSharpplt() { for(;;){} }
void mono_aot_Microsoft_CSharpplt_end() { for(;;){} }
void mono_aot_Microsoft_CSharpunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Microsoft_CSharpunbox_trampolines() { for(;;){} }
void mono_aot_Microsoft_CSharpunbox_trampolines_end() { for(;;){} }
void mono_aot_Microsoft_CSharpunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}