/* Source generated by crazyvoids source generating tool **/
#include "MonoDynamicInterpreter.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Mono_Dynamic_Interpreterjit_code_end() { for(;;){} }
void mono_aot_Mono_Dynamic_Interpreterjit_code_start() { for(;;){} }
void mono_aot_Mono_Dynamic_Interpreterjit_got() { for(;;){} }
void mono_aot_Mono_Dynamic_Interpretermethod_addresses() { for(;;){} }
void mono_aot_Mono_Dynamic_Interpreterplt() { for(;;){} }
void mono_aot_Mono_Dynamic_Interpreterplt_end() { for(;;){} }
void mono_aot_Mono_Dynamic_Interpreterunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Mono_Dynamic_Interpreterunbox_trampolines() { for(;;){} }
void mono_aot_Mono_Dynamic_Interpreterunbox_trampolines_end() { for(;;){} }
void mono_aot_Mono_Dynamic_Interpreterunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}