/* Source generated by crazyvoids source generating tool **/
#include "MonoSecurity.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Mono_Securityjit_code_end() { for(;;){} }
void mono_aot_Mono_Securityjit_code_start() { for(;;){} }
void mono_aot_Mono_Securityjit_got() { for(;;){} }
void mono_aot_Mono_Securitymethod_addresses() { for(;;){} }
void mono_aot_Mono_Securityplt() { for(;;){} }
void mono_aot_Mono_Securityplt_end() { for(;;){} }
void mono_aot_Mono_Securityunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Mono_Securityunbox_trampolines() { for(;;){} }
void mono_aot_Mono_Securityunbox_trampolines_end() { for(;;){} }
void mono_aot_Mono_Securityunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}