/* Source generated by crazyvoids source generating tool **/
#include "MonoCairo.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Mono_Cairojit_code_end() { for(;;){} }
void mono_aot_Mono_Cairojit_code_start() { for(;;){} }
void mono_aot_Mono_Cairojit_got() { for(;;){} }
void mono_aot_Mono_Cairomethod_addresses() { for(;;){} }
void mono_aot_Mono_Cairoplt() { for(;;){} }
void mono_aot_Mono_Cairoplt_end() { for(;;){} }
void mono_aot_Mono_Cairounbox_trampoline_addresses() { for(;;){} }
void mono_aot_Mono_Cairounbox_trampolines() { for(;;){} }
void mono_aot_Mono_Cairounbox_trampolines_end() { for(;;){} }
void mono_aot_Mono_Cairounwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}