/* Source generated by crazyvoids source generating tool **/
#include "MonoDataSqlite.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Mono_Data_Sqlitejit_code_end() { for(;;){} }
void mono_aot_Mono_Data_Sqlitejit_code_start() { for(;;){} }
void mono_aot_Mono_Data_Sqlitejit_got() { for(;;){} }
void mono_aot_Mono_Data_Sqlitemethod_addresses() { for(;;){} }
void mono_aot_Mono_Data_Sqliteplt() { for(;;){} }
void mono_aot_Mono_Data_Sqliteplt_end() { for(;;){} }
void mono_aot_Mono_Data_Sqliteunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Mono_Data_Sqliteunbox_trampolines() { for(;;){} }
void mono_aot_Mono_Data_Sqliteunbox_trampolines_end() { for(;;){} }
void mono_aot_Mono_Data_Sqliteunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}