/* Source generated by crazyvoids source generating tool **/
#include "ScePlayStationIme.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_PlayStation_Imejit_code_end() { for(;;){} }
void mono_aot_Sce_PlayStation_Imejit_code_start() { for(;;){} }
void mono_aot_Sce_PlayStation_Imejit_got() { for(;;){} }
void mono_aot_Sce_PlayStation_Imemethod_addresses() { for(;;){} }
void mono_aot_Sce_PlayStation_Imeplt() { for(;;){} }
void mono_aot_Sce_PlayStation_Imeplt_end() { for(;;){} }
void mono_aot_Sce_PlayStation_Imeunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_PlayStation_Imeunbox_trampolines() { for(;;){} }
void mono_aot_Sce_PlayStation_Imeunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_PlayStation_Imeunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}