/* Source generated by crazyvoids source generating tool **/
#include "ScePlayStationOrbisSpeech.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_PlayStation_Orbis_Speechjit_code_end() { for(;;){} }
void mono_aot_Sce_PlayStation_Orbis_Speechjit_code_start() { for(;;){} }
void mono_aot_Sce_PlayStation_Orbis_Speechjit_got() { for(;;){} }
void mono_aot_Sce_PlayStation_Orbis_Speechmethod_addresses() { for(;;){} }
void mono_aot_Sce_PlayStation_Orbis_Speechplt() { for(;;){} }
void mono_aot_Sce_PlayStation_Orbis_Speechplt_end() { for(;;){} }
void mono_aot_Sce_PlayStation_Orbis_Speechunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_PlayStation_Orbis_Speechunbox_trampolines() { for(;;){} }
void mono_aot_Sce_PlayStation_Orbis_Speechunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_PlayStation_Orbis_Speechunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}