/* Source generated by crazyvoids source generating tool **/
#include "ScePlayStationHighLevelUI2.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_PlayStation_HighLevel_UI2jit_code_end() { for(;;){} }
void mono_aot_Sce_PlayStation_HighLevel_UI2jit_code_start() { for(;;){} }
void mono_aot_Sce_PlayStation_HighLevel_UI2jit_got() { for(;;){} }
void mono_aot_Sce_PlayStation_HighLevel_UI2method_addresses() { for(;;){} }
void mono_aot_Sce_PlayStation_HighLevel_UI2plt() { for(;;){} }
void mono_aot_Sce_PlayStation_HighLevel_UI2plt_end() { for(;;){} }
void mono_aot_Sce_PlayStation_HighLevel_UI2unbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_PlayStation_HighLevel_UI2unbox_trampolines() { for(;;){} }
void mono_aot_Sce_PlayStation_HighLevel_UI2unbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_PlayStation_HighLevel_UI2unwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}