/* Source generated by crazyvoids source generating tool **/
#include "ScePlayStationOrbis.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_PlayStation_Orbisjit_code_end() { for(;;){} }
void mono_aot_Sce_PlayStation_Orbisjit_code_start() { for(;;){} }
void mono_aot_Sce_PlayStation_Orbisjit_got() { for(;;){} }
void mono_aot_Sce_PlayStation_Orbismethod_addresses() { for(;;){} }
void mono_aot_Sce_PlayStation_Orbisplt() { for(;;){} }
void mono_aot_Sce_PlayStation_Orbisplt_end() { for(;;){} }
void mono_aot_Sce_PlayStation_Orbisunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_PlayStation_Orbisunbox_trampolines() { for(;;){} }
void mono_aot_Sce_PlayStation_Orbisunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_PlayStation_Orbisunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}