/* Source generated by crazyvoids source generating tool **/
#include "ScePlayStationCore.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_PlayStation_Corejit_code_end() { for(;;){} }
void mono_aot_Sce_PlayStation_Corejit_code_start() { for(;;){} }
void mono_aot_Sce_PlayStation_Corejit_got() { for(;;){} }
void mono_aot_Sce_PlayStation_Coremethod_addresses() { for(;;){} }
void mono_aot_Sce_PlayStation_Coreplt() { for(;;){} }
void mono_aot_Sce_PlayStation_Coreplt_end() { for(;;){} }
void mono_aot_Sce_PlayStation_Coreunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_PlayStation_Coreunbox_trampolines() { for(;;){} }
void mono_aot_Sce_PlayStation_Coreunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_PlayStation_Coreunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}