/* Source generated by crazyvoids source generating tool **/
#include "ScePlayStationHighLevelUI2Platform.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_PlayStation_HighLevel_UI2Platformjit_code_end() { for(;;){} }
void mono_aot_Sce_PlayStation_HighLevel_UI2Platformjit_code_start() { for(;;){} }
void mono_aot_Sce_PlayStation_HighLevel_UI2Platformjit_got() { for(;;){} }
void mono_aot_Sce_PlayStation_HighLevel_UI2Platformmethod_addresses() { for(;;){} }
void mono_aot_Sce_PlayStation_HighLevel_UI2Platformplt() { for(;;){} }
void mono_aot_Sce_PlayStation_HighLevel_UI2Platformplt_end() { for(;;){} }
void mono_aot_Sce_PlayStation_HighLevel_UI2Platformunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_PlayStation_HighLevel_UI2Platformunbox_trampolines() { for(;;){} }
void mono_aot_Sce_PlayStation_HighLevel_UI2Platformunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_PlayStation_HighLevel_UI2Platformunwind_info() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}