/* Source generated by crazyvoids source generating tool **/
#include "ScePlayStationJson.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_PlayStation_Jsonjit_code_end() { for(;;){} }
void mono_aot_Sce_PlayStation_Jsonjit_code_start() { for(;;){} }
void mono_aot_Sce_PlayStation_Jsonjit_got() { for(;;){} }
void mono_aot_Sce_PlayStation_Jsonmethod_addresses() { for(;;){} }
void mono_aot_Sce_PlayStation_Jsonplt() { for(;;){} }
void mono_aot_Sce_PlayStation_Jsonplt_end() { for(;;){} }
void mono_aot_Sce_PlayStation_Jsonunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_PlayStation_Jsonunbox_trampolines() { for(;;){} }
void mono_aot_Sce_PlayStation_Jsonunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_PlayStation_Jsonunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}