/* Source generated by crazyvoids source generating tool **/
#include "SceVsh.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vshjit_code_end() { for(;;){} }
void mono_aot_Sce_Vshjit_code_start() { for(;;){} }
void mono_aot_Sce_Vshjit_got() { for(;;){} }
void mono_aot_Sce_Vshmethod_addresses() { for(;;){} }
void mono_aot_Sce_Vshplt() { for(;;){} }
void mono_aot_Sce_Vshplt_end() { for(;;){} }
void mono_aot_Sce_Vshunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vshunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vshunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vshunwind_info() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}