/* Source generated by crazyvoids source generating tool **/
#include "SceVshUpdateServiceWrapper.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_UpdateServiceWrapperjit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_UpdateServiceWrapperjit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_UpdateServiceWrapperjit_got() { for(;;){} }
void mono_aot_Sce_Vsh_UpdateServiceWrappermethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_UpdateServiceWrapperplt() { for(;;){} }
void mono_aot_Sce_Vsh_UpdateServiceWrapperplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_UpdateServiceWrapperunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_UpdateServiceWrapperunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_UpdateServiceWrapperunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_UpdateServiceWrapperunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}