/* Source generated by crazyvoids source generating tool **/
#include "SceVshWebViewDialog.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_WebViewDialogjit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_WebViewDialogjit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_WebViewDialogjit_got() { for(;;){} }
void mono_aot_Sce_Vsh_WebViewDialogmethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_WebViewDialogplt() { for(;;){} }
void mono_aot_Sce_Vsh_WebViewDialogplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_WebViewDialogunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_WebViewDialogunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_WebViewDialogunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_WebViewDialogunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}