/* Source generated by crazyvoids source generating tool **/
#include "SceVshGriefReportStorage.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_GriefReportStoragejit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_GriefReportStoragejit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_GriefReportStoragejit_got() { for(;;){} }
void mono_aot_Sce_Vsh_GriefReportStoragemethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_GriefReportStorageplt() { for(;;){} }
void mono_aot_Sce_Vsh_GriefReportStorageplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_GriefReportStorageunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_GriefReportStorageunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_GriefReportStorageunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_GriefReportStorageunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}