/* Source generated by crazyvoids source generating tool **/
#include "SceVshWebbrowserXdbWrapper.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_Webbrowser_XdbWrapperjit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_Webbrowser_XdbWrapperjit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_Webbrowser_XdbWrapperjit_got() { for(;;){} }
void mono_aot_Sce_Vsh_Webbrowser_XdbWrappermethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_Webbrowser_XdbWrapperplt() { for(;;){} }
void mono_aot_Sce_Vsh_Webbrowser_XdbWrapperplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_Webbrowser_XdbWrapperunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_Webbrowser_XdbWrapperunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_Webbrowser_XdbWrapperunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_Webbrowser_XdbWrapperunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}