/* Source generated by crazyvoids source generating tool **/
#include "SceVshPsnUtil.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_PsnUtiljit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_PsnUtiljit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_PsnUtiljit_got() { for(;;){} }
void mono_aot_Sce_Vsh_PsnUtilmethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_PsnUtilplt() { for(;;){} }
void mono_aot_Sce_Vsh_PsnUtilplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_PsnUtilunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_PsnUtilunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_PsnUtilunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_PsnUtilunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}