/* Source generated by crazyvoids source generating tool **/
#include "SceVshAccessor.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_Accessorjit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_Accessorjit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_Accessorjit_got() { for(;;){} }
void mono_aot_Sce_Vsh_Accessormethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_Accessorplt() { for(;;){} }
void mono_aot_Sce_Vsh_Accessorplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_Accessorunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_Accessorunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_Accessorunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_Accessorunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}