/* Source generated by crazyvoids source generating tool **/
#include "SceVshVrEnvironment.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_VrEnvironmentjit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_VrEnvironmentjit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_VrEnvironmentjit_got() { for(;;){} }
void mono_aot_Sce_Vsh_VrEnvironmentmethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_VrEnvironmentplt() { for(;;){} }
void mono_aot_Sce_Vsh_VrEnvironmentplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_VrEnvironmentunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_VrEnvironmentunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_VrEnvironmentunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_VrEnvironmentunwind_info() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}