/* Source generated by crazyvoids source generating tool **/
#include "SceVshGlsNativeCall.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_Gls_NativeCalljit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_Gls_NativeCalljit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_Gls_NativeCalljit_got() { for(;;){} }
void mono_aot_Sce_Vsh_Gls_NativeCallmethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_Gls_NativeCallplt() { for(;;){} }
void mono_aot_Sce_Vsh_Gls_NativeCallplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_Gls_NativeCallunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_Gls_NativeCallunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_Gls_NativeCallunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_Gls_NativeCallunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}