/* Source generated by crazyvoids source generating tool **/
#include "SceVshRequestShareScreen.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_RequestShareScreenjit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_RequestShareScreenjit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_RequestShareScreenjit_got() { for(;;){} }
void mono_aot_Sce_Vsh_RequestShareScreenmethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_RequestShareScreenplt() { for(;;){} }
void mono_aot_Sce_Vsh_RequestShareScreenplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_RequestShareScreenunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_RequestShareScreenunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_RequestShareScreenunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_RequestShareScreenunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}