/* Source generated by crazyvoids source generating tool **/
#include "SceVshAccessorDbNotify.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_Accessor_Db_Notifyjit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_Accessor_Db_Notifyjit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_Accessor_Db_Notifyjit_got() { for(;;){} }
void mono_aot_Sce_Vsh_Accessor_Db_Notifymethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_Accessor_Db_Notifyplt() { for(;;){} }
void mono_aot_Sce_Vsh_Accessor_Db_Notifyplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_Accessor_Db_Notifyunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_Accessor_Db_Notifyunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_Accessor_Db_Notifyunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_Accessor_Db_Notifyunwind_info() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}