/* Source generated by crazyvoids source generating tool **/
#include "SceVshNpAsm.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Asmjit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Asmjit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Asmjit_got() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Asmmethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Asmplt() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Asmplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Asmunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Asmunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Asmunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Asmunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}