/* Source generated by crazyvoids source generating tool **/
#include "SceVshMimeType.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_MimeTypejit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_MimeTypejit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_MimeTypejit_got() { for(;;){} }
void mono_aot_Sce_Vsh_MimeTypemethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_MimeTypeplt() { for(;;){} }
void mono_aot_Sce_Vsh_MimeTypeplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_MimeTypeunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_MimeTypeunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_MimeTypeunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_MimeTypeunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}