/* Source generated by crazyvoids source generating tool **/
#include "SceVshNpIdMapper.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_Np_IdMapperjit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_Np_IdMapperjit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_Np_IdMapperjit_got() { for(;;){} }
void mono_aot_Sce_Vsh_Np_IdMappermethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_Np_IdMapperplt() { for(;;){} }
void mono_aot_Sce_Vsh_Np_IdMapperplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_Np_IdMapperunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_Np_IdMapperunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_Np_IdMapperunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_Np_IdMapperunwind_info() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}