/* Source generated by crazyvoids source generating tool **/
#include "SceVshNpSns.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Snsjit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Snsjit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Snsjit_got() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Snsmethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Snsplt() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Snsplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Snsunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Snsunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Snsunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Snsunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}