/* Source generated by crazyvoids source generating tool **/
#include "SceVshMyGameList.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_MyGameListjit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_MyGameListjit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_MyGameListjit_got() { for(;;){} }
void mono_aot_Sce_Vsh_MyGameListmethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_MyGameListplt() { for(;;){} }
void mono_aot_Sce_Vsh_MyGameListplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_MyGameListunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_MyGameListunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_MyGameListunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_MyGameListunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}