/* Source generated by crazyvoids source generating tool **/
#include "SceVshMarlinDownloaderWrapper.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_MarlinDownloaderWrapperjit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_MarlinDownloaderWrapperjit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_MarlinDownloaderWrapperjit_got() { for(;;){} }
void mono_aot_Sce_Vsh_MarlinDownloaderWrappermethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_MarlinDownloaderWrapperplt() { for(;;){} }
void mono_aot_Sce_Vsh_MarlinDownloaderWrapperplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_MarlinDownloaderWrapperunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_MarlinDownloaderWrapperunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_MarlinDownloaderWrapperunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_MarlinDownloaderWrapperunwind_info() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}