/* Source generated by crazyvoids source generating tool **/
#include "SceVshNpUds.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Udsjit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Udsjit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Udsjit_got() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Udsmethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Udsplt() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Udsplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Udsunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Udsunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Udsunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Udsunwind_info() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}