/* Source generated by crazyvoids source generating tool **/
#include "SceVshEventServiceWrapper.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_EventServiceWrapperjit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_EventServiceWrapperjit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_EventServiceWrapperjit_got() { for(;;){} }
void mono_aot_Sce_Vsh_EventServiceWrappermethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_EventServiceWrapperplt() { for(;;){} }
void mono_aot_Sce_Vsh_EventServiceWrapperplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_EventServiceWrapperunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_EventServiceWrapperunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_EventServiceWrapperunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_EventServiceWrapperunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}