/* Source generated by crazyvoids source generating tool **/
#include "SceVshAppDbWrapper.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_AppDbWrapperjit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_AppDbWrapperjit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_AppDbWrapperjit_got() { for(;;){} }
void mono_aot_Sce_Vsh_AppDbWrappermethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_AppDbWrapperplt() { for(;;){} }
void mono_aot_Sce_Vsh_AppDbWrapperplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_AppDbWrapperunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_AppDbWrapperunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_AppDbWrapperunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_AppDbWrapperunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}