/* Source generated by crazyvoids source generating tool **/
#include "SceVshBackupRestoreUtil.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_BackupRestoreUtiljit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_BackupRestoreUtiljit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_BackupRestoreUtiljit_got() { for(;;){} }
void mono_aot_Sce_Vsh_BackupRestoreUtilmethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_BackupRestoreUtilplt() { for(;;){} }
void mono_aot_Sce_Vsh_BackupRestoreUtilplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_BackupRestoreUtilunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_BackupRestoreUtilunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_BackupRestoreUtilunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_BackupRestoreUtilunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}