/* Source generated by crazyvoids source generating tool **/
#include "SceVshVideoServiceWrapper.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_VideoServiceWrapperjit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_VideoServiceWrapperjit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_VideoServiceWrapperjit_got() { for(;;){} }
void mono_aot_Sce_Vsh_VideoServiceWrappermethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_VideoServiceWrapperplt() { for(;;){} }
void mono_aot_Sce_Vsh_VideoServiceWrapperplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_VideoServiceWrapperunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_VideoServiceWrapperunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_VideoServiceWrapperunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_VideoServiceWrapperunwind_info() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}