/* Source generated by crazyvoids source generating tool **/
#include "SceVshSysfileUtilWrapper.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_SysfileUtilWrapperjit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_SysfileUtilWrapperjit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_SysfileUtilWrapperjit_got() { for(;;){} }
void mono_aot_Sce_Vsh_SysfileUtilWrappermethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_SysfileUtilWrapperplt() { for(;;){} }
void mono_aot_Sce_Vsh_SysfileUtilWrapperplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_SysfileUtilWrapperunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_SysfileUtilWrapperunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_SysfileUtilWrapperunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_SysfileUtilWrapperunwind_info() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}