/* Source generated by crazyvoids source generating tool **/
#include "SceVshSQLite.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_SQLitejit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_SQLitejit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_SQLitejit_got() { for(;;){} }
void mono_aot_Sce_Vsh_SQLitemethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_SQLiteplt() { for(;;){} }
void mono_aot_Sce_Vsh_SQLiteplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_SQLiteunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_SQLiteunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_SQLiteunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_SQLiteunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}