/* Source generated by crazyvoids source generating tool **/
#include "SceVshShellCoreUtilWrapper.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_ShellCoreUtilWrapperjit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_ShellCoreUtilWrapperjit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_ShellCoreUtilWrapperjit_got() { for(;;){} }
void mono_aot_Sce_Vsh_ShellCoreUtilWrappermethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_ShellCoreUtilWrapperplt() { for(;;){} }
void mono_aot_Sce_Vsh_ShellCoreUtilWrapperplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_ShellCoreUtilWrapperunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_ShellCoreUtilWrapperunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_ShellCoreUtilWrapperunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_ShellCoreUtilWrapperunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}