/* Source generated by crazyvoids source generating tool **/
#include "SceVshAutoMounterWrapper.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_AutoMounterWrapperjit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_AutoMounterWrapperjit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_AutoMounterWrapperjit_got() { for(;;){} }
void mono_aot_Sce_Vsh_AutoMounterWrappermethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_AutoMounterWrapperplt() { for(;;){} }
void mono_aot_Sce_Vsh_AutoMounterWrapperplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_AutoMounterWrapperunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_AutoMounterWrapperunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_AutoMounterWrapperunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_AutoMounterWrapperunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}