/* Source generated by crazyvoids source generating tool **/
#include "SceVshSysUtilWrapper.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_SysUtilWrapperjit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_SysUtilWrapperjit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_SysUtilWrapperjit_got() { for(;;){} }
void mono_aot_Sce_Vsh_SysUtilWrappermethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_SysUtilWrapperplt() { for(;;){} }
void mono_aot_Sce_Vsh_SysUtilWrapperplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_SysUtilWrapperunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_SysUtilWrapperunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_SysUtilWrapperunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_SysUtilWrapperunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}