/* Source generated by crazyvoids source generating tool **/
#include "SceVshNpAuCheck.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_Np_AuCheckjit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_Np_AuCheckjit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_Np_AuCheckjit_got() { for(;;){} }
void mono_aot_Sce_Vsh_Np_AuCheckmethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_Np_AuCheckplt() { for(;;){} }
void mono_aot_Sce_Vsh_Np_AuCheckplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_Np_AuCheckunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_Np_AuCheckunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_Np_AuCheckunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_Np_AuCheckunwind_info() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}