/* Source generated by crazyvoids source generating tool **/
#include "SceVshShareServerPostWrapper.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_ShareServerPostWrapperjit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_ShareServerPostWrapperjit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_ShareServerPostWrapperjit_got() { for(;;){} }
void mono_aot_Sce_Vsh_ShareServerPostWrappermethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_ShareServerPostWrapperplt() { for(;;){} }
void mono_aot_Sce_Vsh_ShareServerPostWrapperplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_ShareServerPostWrapperunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_ShareServerPostWrapperunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_ShareServerPostWrapperunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_ShareServerPostWrapperunwind_info() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}