/* Source generated by crazyvoids source generating tool **/
#include "SceVshNpServiceChecker.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_Np_ServiceCheckerjit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_Np_ServiceCheckerjit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_Np_ServiceCheckerjit_got() { for(;;){} }
void mono_aot_Sce_Vsh_Np_ServiceCheckermethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_Np_ServiceCheckerplt() { for(;;){} }
void mono_aot_Sce_Vsh_Np_ServiceCheckerplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_Np_ServiceCheckerunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_Np_ServiceCheckerunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_Np_ServiceCheckerunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_Np_ServiceCheckerunwind_info() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}