/* Source generated by crazyvoids source generating tool **/
#include "SceVshNpTrophy.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Trophyjit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Trophyjit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Trophyjit_got() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Trophymethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Trophyplt() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Trophyplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Trophyunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Trophyunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Trophyunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Trophyunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}