/* Source generated by crazyvoids source generating tool **/
#include "SceVshNpTmdb.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Tmdbjit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Tmdbjit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Tmdbjit_got() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Tmdbmethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Tmdbplt() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Tmdbplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Tmdbunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Tmdbunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Tmdbunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Tmdbunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}