/* Source generated by crazyvoids source generating tool **/
#include "SceVshJsExtension.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_JsExtensionjit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_JsExtensionjit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_JsExtensionjit_got() { for(;;){} }
void mono_aot_Sce_Vsh_JsExtensionmethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_JsExtensionplt() { for(;;){} }
void mono_aot_Sce_Vsh_JsExtensionplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_JsExtensionunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_JsExtensionunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_JsExtensionunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_JsExtensionunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}