/* Source generated by crazyvoids source generating tool **/
#include "SceVshMorpheusUpdWrapper.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_MorpheusUpdWrapperjit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_MorpheusUpdWrapperjit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_MorpheusUpdWrapperjit_got() { for(;;){} }
void mono_aot_Sce_Vsh_MorpheusUpdWrappermethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_MorpheusUpdWrapperplt() { for(;;){} }
void mono_aot_Sce_Vsh_MorpheusUpdWrapperplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_MorpheusUpdWrapperunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_MorpheusUpdWrapperunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_MorpheusUpdWrapperunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_MorpheusUpdWrapperunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}