/* Source generated by crazyvoids source generating tool **/
#include "SceVshFileSelector.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_FileSelectorjit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_FileSelectorjit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_FileSelectorjit_got() { for(;;){} }
void mono_aot_Sce_Vsh_FileSelectormethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_FileSelectorplt() { for(;;){} }
void mono_aot_Sce_Vsh_FileSelectorplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_FileSelectorunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_FileSelectorunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_FileSelectorunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_FileSelectorunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}