/* Source generated by crazyvoids source generating tool **/
#include "SceVshDbPreparationWrapper.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_DbPreparationWrapperjit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_DbPreparationWrapperjit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_DbPreparationWrapperjit_got() { for(;;){} }
void mono_aot_Sce_Vsh_DbPreparationWrappermethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_DbPreparationWrapperplt() { for(;;){} }
void mono_aot_Sce_Vsh_DbPreparationWrapperplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_DbPreparationWrapperunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_DbPreparationWrapperunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_DbPreparationWrapperunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_DbPreparationWrapperunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}