/* Source generated by crazyvoids source generating tool **/
#include "SceVshGlsGlsSharedMediaView.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_Gls_GlsSharedMediaViewjit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_Gls_GlsSharedMediaViewjit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_Gls_GlsSharedMediaViewjit_got() { for(;;){} }
void mono_aot_Sce_Vsh_Gls_GlsSharedMediaViewmethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_Gls_GlsSharedMediaViewplt() { for(;;){} }
void mono_aot_Sce_Vsh_Gls_GlsSharedMediaViewplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_Gls_GlsSharedMediaViewunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_Gls_GlsSharedMediaViewunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_Gls_GlsSharedMediaViewunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_Gls_GlsSharedMediaViewunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}