/* Source generated by crazyvoids source generating tool **/
#include "SceVshSessionInvitation.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_SessionInvitationjit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_SessionInvitationjit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_SessionInvitationjit_got() { for(;;){} }
void mono_aot_Sce_Vsh_SessionInvitationmethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_SessionInvitationplt() { for(;;){} }
void mono_aot_Sce_Vsh_SessionInvitationplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_SessionInvitationunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_SessionInvitationunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_SessionInvitationunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_SessionInvitationunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}