/* Source generated by crazyvoids source generating tool **/
#include "SceVshVideoPlayer.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_VideoPlayerjit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_VideoPlayerjit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_VideoPlayerjit_got() { for(;;){} }
void mono_aot_Sce_Vsh_VideoPlayermethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_VideoPlayerplt() { for(;;){} }
void mono_aot_Sce_Vsh_VideoPlayerplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_VideoPlayerunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_VideoPlayerunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_VideoPlayerunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_VideoPlayerunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}