/* Source generated by crazyvoids source generating tool **/
#include "SceVshPsnMessageUtil.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_PsnMessageUtiljit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_PsnMessageUtiljit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_PsnMessageUtiljit_got() { for(;;){} }
void mono_aot_Sce_Vsh_PsnMessageUtilmethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_PsnMessageUtilplt() { for(;;){} }
void mono_aot_Sce_Vsh_PsnMessageUtilplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_PsnMessageUtilunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_PsnMessageUtilunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_PsnMessageUtilunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_PsnMessageUtilunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}