/* Source generated by crazyvoids source generating tool **/
#include "SceVshStickerStickerLibAccessor.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_Sticker_StickerLibAccessorjit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_Sticker_StickerLibAccessorjit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_Sticker_StickerLibAccessorjit_got() { for(;;){} }
void mono_aot_Sce_Vsh_Sticker_StickerLibAccessormethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_Sticker_StickerLibAccessorplt() { for(;;){} }
void mono_aot_Sce_Vsh_Sticker_StickerLibAccessorplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_Sticker_StickerLibAccessorunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_Sticker_StickerLibAccessorunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_Sticker_StickerLibAccessorunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_Sticker_StickerLibAccessorunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}