/* Source generated by crazyvoids source generating tool **/
#include "SceVshPartyCommon.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_PartyCommonjit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_PartyCommonjit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_PartyCommonjit_got() { for(;;){} }
void mono_aot_Sce_Vsh_PartyCommonmethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_PartyCommonplt() { for(;;){} }
void mono_aot_Sce_Vsh_PartyCommonplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_PartyCommonunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_PartyCommonunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_PartyCommonunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_PartyCommonunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}