/* Source generated by crazyvoids source generating tool **/
#include "SceVshWebbrowserXutilWrapper.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_Webbrowser_XutilWrapperjit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_Webbrowser_XutilWrapperjit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_Webbrowser_XutilWrapperjit_got() { for(;;){} }
void mono_aot_Sce_Vsh_Webbrowser_XutilWrappermethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_Webbrowser_XutilWrapperplt() { for(;;){} }
void mono_aot_Sce_Vsh_Webbrowser_XutilWrapperplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_Webbrowser_XutilWrapperunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_Webbrowser_XutilWrapperunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_Webbrowser_XutilWrapperunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_Webbrowser_XutilWrapperunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}