/* Source generated by crazyvoids source generating tool **/
#include "SceVshWebBrowser.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_WebBrowserjit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_WebBrowserjit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_WebBrowserjit_got() { for(;;){} }
void mono_aot_Sce_Vsh_WebBrowsermethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_WebBrowserplt() { for(;;){} }
void mono_aot_Sce_Vsh_WebBrowserplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_WebBrowserunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_WebBrowserunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_WebBrowserunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_WebBrowserunwind_info() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}