/* Source generated by crazyvoids source generating tool **/
#include "SceVshSQLiteAux.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_SQLiteAuxjit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_SQLiteAuxjit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_SQLiteAuxjit_got() { for(;;){} }
void mono_aot_Sce_Vsh_SQLiteAuxmethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_SQLiteAuxplt() { for(;;){} }
void mono_aot_Sce_Vsh_SQLiteAuxplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_SQLiteAuxunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_SQLiteAuxunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_SQLiteAuxunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_SQLiteAuxunwind_info() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}