/* Source generated by crazyvoids source generating tool **/
#include "SceVshNpPapc.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Papcjit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Papcjit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Papcjit_got() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Papcmethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Papcplt() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Papcplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Papcunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Papcunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Papcunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Papcunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}