/* Source generated by crazyvoids source generating tool **/
#include "SceVshDataTransfer.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_DataTransferjit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_DataTransferjit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_DataTransferjit_got() { for(;;){} }
void mono_aot_Sce_Vsh_DataTransfermethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_DataTransferplt() { for(;;){} }
void mono_aot_Sce_Vsh_DataTransferplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_DataTransferunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_DataTransferunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_DataTransferunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_DataTransferunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}