/* Source generated by crazyvoids source generating tool **/
#include "SceVshUserServiceWrapper.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_UserServiceWrapperjit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_UserServiceWrapperjit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_UserServiceWrapperjit_got() { for(;;){} }
void mono_aot_Sce_Vsh_UserServiceWrappermethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_UserServiceWrapperplt() { for(;;){} }
void mono_aot_Sce_Vsh_UserServiceWrapperplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_UserServiceWrapperunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_UserServiceWrapperunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_UserServiceWrapperunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_UserServiceWrapperunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}