/* Source generated by crazyvoids source generating tool **/
#include "SceVshNpWebapi.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Webapijit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Webapijit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Webapijit_got() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Webapimethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Webapiplt() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Webapiplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Webapiunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Webapiunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Webapiunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Webapiunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}