/* Source generated by crazyvoids source generating tool **/
#include "SceVshVoiceMsgVoiceMsgWrapper.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_VoiceMsg_VoiceMsgWrapperjit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_VoiceMsg_VoiceMsgWrapperjit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_VoiceMsg_VoiceMsgWrapperjit_got() { for(;;){} }
void mono_aot_Sce_Vsh_VoiceMsg_VoiceMsgWrappermethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_VoiceMsg_VoiceMsgWrapperplt() { for(;;){} }
void mono_aot_Sce_Vsh_VoiceMsg_VoiceMsgWrapperplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_VoiceMsg_VoiceMsgWrapperunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_VoiceMsg_VoiceMsgWrapperunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_VoiceMsg_VoiceMsgWrapperunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_VoiceMsg_VoiceMsgWrapperunwind_info() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}