/* Source generated by crazyvoids source generating tool **/
#include "SceVshSystemLoggerWrapper.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_SystemLoggerWrapperjit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_SystemLoggerWrapperjit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_SystemLoggerWrapperjit_got() { for(;;){} }
void mono_aot_Sce_Vsh_SystemLoggerWrappermethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_SystemLoggerWrapperplt() { for(;;){} }
void mono_aot_Sce_Vsh_SystemLoggerWrapperplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_SystemLoggerWrapperunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_SystemLoggerWrapperunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_SystemLoggerWrapperunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_SystemLoggerWrapperunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}