/* Source generated by crazyvoids source generating tool **/
#include "SceVshAppInstUtilWrapper.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_AppInstUtilWrapperjit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_AppInstUtilWrapperjit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_AppInstUtilWrapperjit_got() { for(;;){} }
void mono_aot_Sce_Vsh_AppInstUtilWrappermethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_AppInstUtilWrapperplt() { for(;;){} }
void mono_aot_Sce_Vsh_AppInstUtilWrapperplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_AppInstUtilWrapperunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_AppInstUtilWrapperunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_AppInstUtilWrapperunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_AppInstUtilWrapperunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}