/* Source generated by crazyvoids source generating tool **/
#include "SceVshKernelSysWrapper.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_KernelSysWrapperjit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_KernelSysWrapperjit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_KernelSysWrapperjit_got() { for(;;){} }
void mono_aot_Sce_Vsh_KernelSysWrappermethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_KernelSysWrapperplt() { for(;;){} }
void mono_aot_Sce_Vsh_KernelSysWrapperplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_KernelSysWrapperunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_KernelSysWrapperunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_KernelSysWrapperunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_KernelSysWrapperunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}