/* Source generated by crazyvoids source generating tool **/
#include "SceVshPasscode.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_Passcodejit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_Passcodejit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_Passcodejit_got() { for(;;){} }
void mono_aot_Sce_Vsh_Passcodemethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_Passcodeplt() { for(;;){} }
void mono_aot_Sce_Vsh_Passcodeplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_Passcodeunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_Passcodeunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_Passcodeunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_Passcodeunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}