/* Source generated by crazyvoids source generating tool **/
#include "SceVshDbRecoveryUtilityWrapper.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_DbRecoveryUtilityWrapperjit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_DbRecoveryUtilityWrapperjit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_DbRecoveryUtilityWrapperjit_got() { for(;;){} }
void mono_aot_Sce_Vsh_DbRecoveryUtilityWrappermethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_DbRecoveryUtilityWrapperplt() { for(;;){} }
void mono_aot_Sce_Vsh_DbRecoveryUtilityWrapperplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_DbRecoveryUtilityWrapperunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_DbRecoveryUtilityWrapperunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_DbRecoveryUtilityWrapperunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_DbRecoveryUtilityWrapperunwind_info() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}