/* Source generated by crazyvoids source generating tool **/
#include "SceVshLx.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_Lxjit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_Lxjit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_Lxjit_got() { for(;;){} }
void mono_aot_Sce_Vsh_Lxmethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_Lxplt() { for(;;){} }
void mono_aot_Sce_Vsh_Lxplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_Lxunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_Lxunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_Lxunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_Lxunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}