/* Source generated by crazyvoids source generating tool **/
#include "SceVshProfileCache.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_ProfileCachejit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_ProfileCachejit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_ProfileCachejit_got() { for(;;){} }
void mono_aot_Sce_Vsh_ProfileCachemethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_ProfileCacheplt() { for(;;){} }
void mono_aot_Sce_Vsh_ProfileCacheplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_ProfileCacheunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_ProfileCacheunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_ProfileCacheunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_ProfileCacheunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}