/* Source generated by crazyvoids source generating tool **/
#include "SceVshMessagesDbAccessLib.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_Messages_DbAccessLibjit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_Messages_DbAccessLibjit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_Messages_DbAccessLibjit_got() { for(;;){} }
void mono_aot_Sce_Vsh_Messages_DbAccessLibmethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_Messages_DbAccessLibplt() { for(;;){} }
void mono_aot_Sce_Vsh_Messages_DbAccessLibplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_Messages_DbAccessLibunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_Messages_DbAccessLibunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_Messages_DbAccessLibunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_Messages_DbAccessLibunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}