/* Source generated by crazyvoids source generating tool **/
#include "SceVshGameListRetrieverWrapper.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_GameListRetrieverWrapperjit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_GameListRetrieverWrapperjit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_GameListRetrieverWrapperjit_got() { for(;;){} }
void mono_aot_Sce_Vsh_GameListRetrieverWrappermethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_GameListRetrieverWrapperplt() { for(;;){} }
void mono_aot_Sce_Vsh_GameListRetrieverWrapperplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_GameListRetrieverWrapperunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_GameListRetrieverWrapperunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_GameListRetrieverWrapperunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_GameListRetrieverWrapperunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}