/* Source generated by crazyvoids source generating tool **/
#include "SceVshRegistry.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_Registryjit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_Registryjit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_Registryjit_got() { for(;;){} }
void mono_aot_Sce_Vsh_Registrymethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_Registryplt() { for(;;){} }
void mono_aot_Sce_Vsh_Registryplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_Registryunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_Registryunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_Registryunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_Registryunwind_info() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}