/* Source generated by crazyvoids source generating tool **/
#include "SceVshOrbisContentManager.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_Orbis_ContentManagerjit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_Orbis_ContentManagerjit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_Orbis_ContentManagerjit_got() { for(;;){} }
void mono_aot_Sce_Vsh_Orbis_ContentManagermethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_Orbis_ContentManagerplt() { for(;;){} }
void mono_aot_Sce_Vsh_Orbis_ContentManagerplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_Orbis_ContentManagerunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_Orbis_ContentManagerunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_Orbis_ContentManagerunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_Orbis_ContentManagerunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}