/* Source generated by crazyvoids source generating tool **/
#include "SceVshNpManager.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Managerjit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Managerjit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Managerjit_got() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Managermethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Managerplt() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Managerplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Managerunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Managerunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Managerunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_Np_Managerunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}