/* Source generated by crazyvoids source generating tool **/
#include "SceVshDbShared.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_Db_Sharedjit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_Db_Sharedjit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_Db_Sharedjit_got() { for(;;){} }
void mono_aot_Sce_Vsh_Db_Sharedmethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_Db_Sharedplt() { for(;;){} }
void mono_aot_Sce_Vsh_Db_Sharedplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_Db_Sharedunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_Db_Sharedunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_Db_Sharedunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_Db_Sharedunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}