/* Source generated by crazyvoids source generating tool **/
#include "SceVshRequestShareStorageWrapper.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_RequestShareStorageWrapperjit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_RequestShareStorageWrapperjit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_RequestShareStorageWrapperjit_got() { for(;;){} }
void mono_aot_Sce_Vsh_RequestShareStorageWrappermethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_RequestShareStorageWrapperplt() { for(;;){} }
void mono_aot_Sce_Vsh_RequestShareStorageWrapperplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_RequestShareStorageWrapperunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_RequestShareStorageWrapperunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_RequestShareStorageWrapperunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_RequestShareStorageWrapperunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}