/* Source generated by crazyvoids source generating tool **/
#include "SceVshOrbisAbstractStorage.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_Orbis_AbstractStoragejit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_Orbis_AbstractStoragejit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_Orbis_AbstractStoragejit_got() { for(;;){} }
void mono_aot_Sce_Vsh_Orbis_AbstractStoragemethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_Orbis_AbstractStorageplt() { for(;;){} }
void mono_aot_Sce_Vsh_Orbis_AbstractStorageplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_Orbis_AbstractStorageunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_Orbis_AbstractStorageunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_Orbis_AbstractStorageunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_Orbis_AbstractStorageunwind_info() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}