/* Source generated by crazyvoids source generating tool **/
#include "SceVshSystemLoggerUtilWrapper.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_SystemLoggerUtilWrapperjit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_SystemLoggerUtilWrapperjit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_SystemLoggerUtilWrapperjit_got() { for(;;){} }
void mono_aot_Sce_Vsh_SystemLoggerUtilWrappermethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_SystemLoggerUtilWrapperplt() { for(;;){} }
void mono_aot_Sce_Vsh_SystemLoggerUtilWrapperplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_SystemLoggerUtilWrapperunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_SystemLoggerUtilWrapperunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_SystemLoggerUtilWrapperunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_SystemLoggerUtilWrapperunwind_info() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}