/* Source generated by crazyvoids source generating tool **/
#include "SceVshNpAppInfo.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_Np_AppInfojit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_Np_AppInfojit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_Np_AppInfojit_got() { for(;;){} }
void mono_aot_Sce_Vsh_Np_AppInfomethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_Np_AppInfoplt() { for(;;){} }
void mono_aot_Sce_Vsh_Np_AppInfoplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_Np_AppInfounbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_Np_AppInfounbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_Np_AppInfounbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_Np_AppInfounwind_info() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}