/* Source generated by crazyvoids source generating tool **/
#include "SceVshTheme.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_Themejit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_Themejit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_Themejit_got() { for(;;){} }
void mono_aot_Sce_Vsh_Thememethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_Themeplt() { for(;;){} }
void mono_aot_Sce_Vsh_Themeplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_Themeunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_Themeunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_Themeunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_Themeunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}