/* Source generated by crazyvoids source generating tool **/
#include "SceVshPatchCheckerClientWrapper.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_PatchCheckerClientWrapperjit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_PatchCheckerClientWrapperjit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_PatchCheckerClientWrapperjit_got() { for(;;){} }
void mono_aot_Sce_Vsh_PatchCheckerClientWrappermethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_PatchCheckerClientWrapperplt() { for(;;){} }
void mono_aot_Sce_Vsh_PatchCheckerClientWrapperplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_PatchCheckerClientWrapperunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_PatchCheckerClientWrapperunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_PatchCheckerClientWrapperunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_PatchCheckerClientWrapperunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}