/* Source generated by crazyvoids source generating tool **/
#include "SceVshShareGuideScene.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_ShareGuideScenejit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_ShareGuideScenejit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_ShareGuideScenejit_got() { for(;;){} }
void mono_aot_Sce_Vsh_ShareGuideScenemethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_ShareGuideSceneplt() { for(;;){} }
void mono_aot_Sce_Vsh_ShareGuideSceneplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_ShareGuideSceneunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_ShareGuideSceneunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_ShareGuideSceneunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_ShareGuideSceneunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}