/* Source generated by crazyvoids source generating tool **/
#include "SceVshSyscallWrapper.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_Sce_Vsh_SyscallWrapperjit_code_end() { for(;;){} }
void mono_aot_Sce_Vsh_SyscallWrapperjit_code_start() { for(;;){} }
void mono_aot_Sce_Vsh_SyscallWrapperjit_got() { for(;;){} }
void mono_aot_Sce_Vsh_SyscallWrappermethod_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_SyscallWrapperplt() { for(;;){} }
void mono_aot_Sce_Vsh_SyscallWrapperplt_end() { for(;;){} }
void mono_aot_Sce_Vsh_SyscallWrapperunbox_trampoline_addresses() { for(;;){} }
void mono_aot_Sce_Vsh_SyscallWrapperunbox_trampolines() { for(;;){} }
void mono_aot_Sce_Vsh_SyscallWrapperunbox_trampolines_end() { for(;;){} }
void mono_aot_Sce_Vsh_SyscallWrapperunwind_info() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}