/* Source generated by crazyvoids source generating tool **/
#include "SMDiagnostics.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_SMDiagnosticsjit_code_end() { for(;;){} }
void mono_aot_SMDiagnosticsjit_code_start() { for(;;){} }
void mono_aot_SMDiagnosticsjit_got() { for(;;){} }
void mono_aot_SMDiagnosticsmethod_addresses() { for(;;){} }
void mono_aot_SMDiagnosticsplt() { for(;;){} }
void mono_aot_SMDiagnosticsplt_end() { for(;;){} }
void mono_aot_SMDiagnosticsunbox_trampoline_addresses() { for(;;){} }
void mono_aot_SMDiagnosticsunbox_trampolines() { for(;;){} }
void mono_aot_SMDiagnosticsunbox_trampolines_end() { for(;;){} }
void mono_aot_SMDiagnosticsunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}