/* Source generated by crazyvoids source generating tool **/
#include "SystemComponentModelComposition.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_System_ComponentModel_Compositionjit_code_end() { for(;;){} }
void mono_aot_System_ComponentModel_Compositionjit_code_start() { for(;;){} }
void mono_aot_System_ComponentModel_Compositionjit_got() { for(;;){} }
void mono_aot_System_ComponentModel_Compositionmethod_addresses() { for(;;){} }
void mono_aot_System_ComponentModel_Compositionplt() { for(;;){} }
void mono_aot_System_ComponentModel_Compositionplt_end() { for(;;){} }
void mono_aot_System_ComponentModel_Compositionunbox_trampoline_addresses() { for(;;){} }
void mono_aot_System_ComponentModel_Compositionunbox_trampolines() { for(;;){} }
void mono_aot_System_ComponentModel_Compositionunbox_trampolines_end() { for(;;){} }
void mono_aot_System_ComponentModel_Compositionunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}