/* Source generated by crazyvoids source generating tool **/
#include "SystemServiceModelInternals.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_System_ServiceModel_Internalsjit_code_end() { for(;;){} }
void mono_aot_System_ServiceModel_Internalsjit_code_start() { for(;;){} }
void mono_aot_System_ServiceModel_Internalsjit_got() { for(;;){} }
void mono_aot_System_ServiceModel_Internalsmethod_addresses() { for(;;){} }
void mono_aot_System_ServiceModel_Internalsplt() { for(;;){} }
void mono_aot_System_ServiceModel_Internalsplt_end() { for(;;){} }
void mono_aot_System_ServiceModel_Internalsunbox_trampoline_addresses() { for(;;){} }
void mono_aot_System_ServiceModel_Internalsunbox_trampolines() { for(;;){} }
void mono_aot_System_ServiceModel_Internalsunbox_trampolines_end() { for(;;){} }
void mono_aot_System_ServiceModel_Internalsunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}