/* Source generated by crazyvoids source generating tool **/
#include "SystemXml.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_System_Xmljit_code_end() { for(;;){} }
void mono_aot_System_Xmljit_code_start() { for(;;){} }
void mono_aot_System_Xmljit_got() { for(;;){} }
void mono_aot_System_Xmlmethod_addresses() { for(;;){} }
void mono_aot_System_Xmlplt() { for(;;){} }
void mono_aot_System_Xmlplt_end() { for(;;){} }
void mono_aot_System_Xmlunbox_trampoline_addresses() { for(;;){} }
void mono_aot_System_Xmlunbox_trampolines() { for(;;){} }
void mono_aot_System_Xmlunbox_trampolines_end() { for(;;){} }
void mono_aot_System_Xmlunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}