/* Source generated by crazyvoids source generating tool **/
#include "SystemIOCompression.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_System_IO_Compressionjit_code_end() { for(;;){} }
void mono_aot_System_IO_Compressionjit_code_start() { for(;;){} }
void mono_aot_System_IO_Compressionjit_got() { for(;;){} }
void mono_aot_System_IO_Compressionmethod_addresses() { for(;;){} }
void mono_aot_System_IO_Compressionplt() { for(;;){} }
void mono_aot_System_IO_Compressionplt_end() { for(;;){} }
void mono_aot_System_IO_Compressionunbox_trampoline_addresses() { for(;;){} }
void mono_aot_System_IO_Compressionunbox_trampolines() { for(;;){} }
void mono_aot_System_IO_Compressionunbox_trampolines_end() { for(;;){} }
void mono_aot_System_IO_Compressionunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}