/* Source generated by crazyvoids source generating tool **/
#include "SystemWindows.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_System_Windowsjit_code_end() { for(;;){} }
void mono_aot_System_Windowsjit_code_start() { for(;;){} }
void mono_aot_System_Windowsjit_got() { for(;;){} }
void mono_aot_System_Windowsmethod_addresses() { for(;;){} }
void mono_aot_System_Windowsplt() { for(;;){} }
void mono_aot_System_Windowsplt_end() { for(;;){} }
void mono_aot_System_Windowsunbox_trampoline_addresses() { for(;;){} }
void mono_aot_System_Windowsunbox_trampolines() { for(;;){} }
void mono_aot_System_Windowsunbox_trampolines_end() { for(;;){} }
void mono_aot_System_Windowsunwind_info() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}