/* Source generated by crazyvoids source generating tool **/
#include "SystemNetHttp.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_System_Net_Httpjit_code_end() { for(;;){} }
void mono_aot_System_Net_Httpjit_code_start() { for(;;){} }
void mono_aot_System_Net_Httpjit_got() { for(;;){} }
void mono_aot_System_Net_Httpmethod_addresses() { for(;;){} }
void mono_aot_System_Net_Httpplt() { for(;;){} }
void mono_aot_System_Net_Httpplt_end() { for(;;){} }
void mono_aot_System_Net_Httpunbox_trampoline_addresses() { for(;;){} }
void mono_aot_System_Net_Httpunbox_trampolines() { for(;;){} }
void mono_aot_System_Net_Httpunbox_trampolines_end() { for(;;){} }
void mono_aot_System_Net_Httpunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}