/* Source generated by crazyvoids source generating tool **/
#include "SystemIOCompressionFileSystem.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_System_IO_Compression_FileSystemjit_code_end() { for(;;){} }
void mono_aot_System_IO_Compression_FileSystemjit_code_start() { for(;;){} }
void mono_aot_System_IO_Compression_FileSystemjit_got() { for(;;){} }
void mono_aot_System_IO_Compression_FileSystemmethod_addresses() { for(;;){} }
void mono_aot_System_IO_Compression_FileSystemplt() { for(;;){} }
void mono_aot_System_IO_Compression_FileSystemplt_end() { for(;;){} }
void mono_aot_System_IO_Compression_FileSystemunbox_trampoline_addresses() { for(;;){} }
void mono_aot_System_IO_Compression_FileSystemunbox_trampolines() { for(;;){} }
void mono_aot_System_IO_Compression_FileSystemunbox_trampolines_end() { for(;;){} }
void mono_aot_System_IO_Compression_FileSystemunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}