/* Source generated by crazyvoids source generating tool **/
#include "SystemServiceModel.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_System_ServiceModeljit_code_end() { for(;;){} }
void mono_aot_System_ServiceModeljit_code_start() { for(;;){} }
void mono_aot_System_ServiceModeljit_got() { for(;;){} }
void mono_aot_System_ServiceModelmethod_addresses() { for(;;){} }
void mono_aot_System_ServiceModelplt() { for(;;){} }
void mono_aot_System_ServiceModelplt_end() { for(;;){} }
void mono_aot_System_ServiceModelunbox_trampoline_addresses() { for(;;){} }
void mono_aot_System_ServiceModelunbox_trampolines() { for(;;){} }
void mono_aot_System_ServiceModelunbox_trampolines_end() { for(;;){} }
void mono_aot_System_ServiceModelunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}