/* Source generated by crazyvoids source generating tool **/
#include "SystemDataServicesClient.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_System_Data_Services_Clientjit_code_end() { for(;;){} }
void mono_aot_System_Data_Services_Clientjit_code_start() { for(;;){} }
void mono_aot_System_Data_Services_Clientjit_got() { for(;;){} }
void mono_aot_System_Data_Services_Clientmethod_addresses() { for(;;){} }
void mono_aot_System_Data_Services_Clientplt() { for(;;){} }
void mono_aot_System_Data_Services_Clientplt_end() { for(;;){} }
void mono_aot_System_Data_Services_Clientunbox_trampoline_addresses() { for(;;){} }
void mono_aot_System_Data_Services_Clientunbox_trampolines() { for(;;){} }
void mono_aot_System_Data_Services_Clientunbox_trampolines_end() { for(;;){} }
void mono_aot_System_Data_Services_Clientunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}