/* Source generated by crazyvoids source generating tool **/
#include "SystemWebServices.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_System_Web_Servicesjit_code_end() { for(;;){} }
void mono_aot_System_Web_Servicesjit_code_start() { for(;;){} }
void mono_aot_System_Web_Servicesjit_got() { for(;;){} }
void mono_aot_System_Web_Servicesmethod_addresses() { for(;;){} }
void mono_aot_System_Web_Servicesplt() { for(;;){} }
void mono_aot_System_Web_Servicesplt_end() { for(;;){} }
void mono_aot_System_Web_Servicesunbox_trampoline_addresses() { for(;;){} }
void mono_aot_System_Web_Servicesunbox_trampolines() { for(;;){} }
void mono_aot_System_Web_Servicesunbox_trampolines_end() { for(;;){} }
void mono_aot_System_Web_Servicesunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}