/* Source generated by crazyvoids source generating tool **/
#include "SystemXmlSerialization.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_System_Xml_Serializationjit_code_end() { for(;;){} }
void mono_aot_System_Xml_Serializationjit_code_start() { for(;;){} }
void mono_aot_System_Xml_Serializationjit_got() { for(;;){} }
void mono_aot_System_Xml_Serializationmethod_addresses() { for(;;){} }
void mono_aot_System_Xml_Serializationplt() { for(;;){} }
void mono_aot_System_Xml_Serializationplt_end() { for(;;){} }
void mono_aot_System_Xml_Serializationunbox_trampoline_addresses() { for(;;){} }
void mono_aot_System_Xml_Serializationunbox_trampolines() { for(;;){} }
void mono_aot_System_Xml_Serializationunbox_trampolines_end() { for(;;){} }
void mono_aot_System_Xml_Serializationunwind_info() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}