/* Source generated by crazyvoids source generating tool **/
#include "SystemComponentModelDataAnnotations.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_System_ComponentModel_DataAnnotationsjit_code_end() { for(;;){} }
void mono_aot_System_ComponentModel_DataAnnotationsjit_code_start() { for(;;){} }
void mono_aot_System_ComponentModel_DataAnnotationsjit_got() { for(;;){} }
void mono_aot_System_ComponentModel_DataAnnotationsmethod_addresses() { for(;;){} }
void mono_aot_System_ComponentModel_DataAnnotationsplt() { for(;;){} }
void mono_aot_System_ComponentModel_DataAnnotationsplt_end() { for(;;){} }
void mono_aot_System_ComponentModel_DataAnnotationsunbox_trampoline_addresses() { for(;;){} }
void mono_aot_System_ComponentModel_DataAnnotationsunbox_trampolines() { for(;;){} }
void mono_aot_System_ComponentModel_DataAnnotationsunbox_trampolines_end() { for(;;){} }
void mono_aot_System_ComponentModel_DataAnnotationsunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}