/* Source generated by crazyvoids source generating tool **/
#include "SystemNetHttpWebRequest.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_System_Net_Http_WebRequestjit_code_end() { for(;;){} }
void mono_aot_System_Net_Http_WebRequestjit_code_start() { for(;;){} }
void mono_aot_System_Net_Http_WebRequestjit_got() { for(;;){} }
void mono_aot_System_Net_Http_WebRequestmethod_addresses() { for(;;){} }
void mono_aot_System_Net_Http_WebRequestplt() { for(;;){} }
void mono_aot_System_Net_Http_WebRequestplt_end() { for(;;){} }
void mono_aot_System_Net_Http_WebRequestunbox_trampoline_addresses() { for(;;){} }
void mono_aot_System_Net_Http_WebRequestunbox_trampolines() { for(;;){} }
void mono_aot_System_Net_Http_WebRequestunbox_trampolines_end() { for(;;){} }
void mono_aot_System_Net_Http_WebRequestunwind_info() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}