/* Source generated by crazyvoids source generating tool **/
#include "SystemXmlLinq.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_System_Xml_Linqjit_code_end() { for(;;){} }
void mono_aot_System_Xml_Linqjit_code_start() { for(;;){} }
void mono_aot_System_Xml_Linqjit_got() { for(;;){} }
void mono_aot_System_Xml_Linqmethod_addresses() { for(;;){} }
void mono_aot_System_Xml_Linqplt() { for(;;){} }
void mono_aot_System_Xml_Linqplt_end() { for(;;){} }
void mono_aot_System_Xml_Linqunbox_trampoline_addresses() { for(;;){} }
void mono_aot_System_Xml_Linqunbox_trampolines() { for(;;){} }
void mono_aot_System_Xml_Linqunbox_trampolines_end() { for(;;){} }
void mono_aot_System_Xml_Linqunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}