/* Source generated by crazyvoids source generating tool **/
#include "SystemServiceModelWeb.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_System_ServiceModel_Webjit_code_end() { for(;;){} }
void mono_aot_System_ServiceModel_Webjit_code_start() { for(;;){} }
void mono_aot_System_ServiceModel_Webjit_got() { for(;;){} }
void mono_aot_System_ServiceModel_Webmethod_addresses() { for(;;){} }
void mono_aot_System_ServiceModel_Webplt() { for(;;){} }
void mono_aot_System_ServiceModel_Webplt_end() { for(;;){} }
void mono_aot_System_ServiceModel_Webunbox_trampoline_addresses() { for(;;){} }
void mono_aot_System_ServiceModel_Webunbox_trampolines() { for(;;){} }
void mono_aot_System_ServiceModel_Webunbox_trampolines_end() { for(;;){} }
void mono_aot_System_ServiceModel_Webunwind_info() { for(;;){} }
void unbox_trampoline_p() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}