/* Source generated by crazyvoids source generating tool **/
#include "SystemNet.h"

void dll_end() { for(;;){} }
void dll_size() { for(;;){} }
void dll_start() { for(;;){} }
void mono_aot_file_info() { for(;;){} }
void mono_aot_System_Netjit_code_end() { for(;;){} }
void mono_aot_System_Netjit_code_start() { for(;;){} }
void mono_aot_System_Netjit_got() { for(;;){} }
void mono_aot_System_Netmethod_addresses() { for(;;){} }
void mono_aot_System_Netplt() { for(;;){} }
void mono_aot_System_Netplt_end() { for(;;){} }
void mono_aot_System_Netunbox_trampoline_addresses() { for(;;){} }
void mono_aot_System_Netunbox_trampolines() { for(;;){} }
void mono_aot_System_Netunbox_trampolines_end() { for(;;){} }
void mono_aot_System_Netunwind_info() { for(;;){} }


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}