#define	FREAD                 0x0001
#define FWRITE                0x0002
#define	O_NONBLOCK            0x0004
#define O_APPEND              0x0008
#define O_SHLOCK              0x0010
#define O_EXLOCK              0x0020
#define O_ASYNC               0x0040
#define O_FSYNC               0x0080
#define O_NOFOLLOW            0x0100
#define	O_CREAT               0x0200
#define	O_TRUNC               0x0400
#define	O_EXCL                0x0800
#define O_NOCTTY              0x8000

#define O_DIRECT          0x00010000
#define O_DIRECTORY       0x00020000
#define O_EXEC            0x00040000

#define	FAPPEND             O_APPEND
#define	FASYNC               O_ASYNC
#define	FFSYNC               O_FSYNC
#define	FNONBLOCK         O_NONBLOCK
#define	FNDELAY           O_NONBLOCK
#define	O_NDELAY          O_NONBLOCK

#define	AT_FDCWD                -100
#define	AT_EACCESS             0x100
#define	AT_SYMLINK_NOFOLLOW	   0x200
#define	AT_SYMLINK_FOLLOW	   0x400
#define	AT_REMOVEDIR		   0x800

#define F_DUPFD                    0
#define F_GETFD                    1
#define F_SETFD                    2
#define F_GETFL                    3
#define F_SETFL                    4
#define F_GETOWN                   5
#define F_SETOWN                   6
#define F_OGETLK                   7
#define F_OSETLK                   8
#define F_OSETLKW                  9
#define F_DUP2FD                  10
#define F_GETLK                   11
#define F_SETLK                   12
#define F_SETLKW                  13
#define F_SETLK_REMOTE            14
#define F_READAHEAD               15
#define F_RDAHEAD                 16
#define F_DUP2FD_CLOEXEC          18
