#define	__NR_syscall	0
#define	__NR_exit	1
#define	__NR_fork	2
#define	__NR_read	3
#define	__NR_write	4
#define	__NR_open	5
#define	__NR_close	6
#define	__NR_wait4	7
#define	__NR_link	9
#define	__NR_unlink	10
#define	__NR_chdir	12
#define	__NR_fchdir	13
#define	__NR_mknod	14
#define	__NR_chmod	15
#define	__NR_chown	16
#define	__NR_break	17
#define	__NR_freebsd4_getfsstat	18
#define	__NR_getpid	20
#define	__NR_mount	21
#define	__NR_unmount	22
#define	__NR_setuid	23
#define	__NR_getuid	24
#define	__NR_geteuid	25
#define	__NR_ptrace	26
#define	__NR_recvmsg	27
#define	__NR_sendmsg	28
#define	__NR_recvfrom	29
#define	__NR_accept	30
#define	__NR_getpeername	31
#define	__NR_getsockname	32
#define	__NR_access	33
#define	__NR_chflags	34
#define	__NR_fchflags	35
#define	__NR_sync	36
#define	__NR_kill	37
#define	__NR_getppid	39
#define	__NR_dup	41
#define	__NR_pipe	42
#define	__NR_getegid	43
#define	__NR_profil	44
#define	__NR_ktrace	45
#define	__NR_getgid	47
#define	__NR_getlogin	49
#define	__NR_setlogin	50
#define	__NR_acct	51
#define	__NR_sigaltstack	53
#define	__NR_ioctl	54
#define	__NR_reboot	55
#define	__NR_revoke	56
#define	__NR_symlink	57
#define	__NR_readlink	58
#define	__NR_execve	59
#define	__NR_umask	60
#define	__NR_chroot	61
#define	__NR_msync	65
#define	__NR_vfork	66
#define	__NR_sbrk	69
#define	__NR_sstk	70
#define	__NR_vadvise	72
#define	__NR_munmap	73
#define	__NR_mprotect	74
#define	__NR_madvise	75
#define	__NR_mincore	78
#define	__NR_getgroups	79
#define	__NR_setgroups	80
#define	__NR_getpgrp	81
#define	__NR_setpgid	82
#define	__NR_setitimer	83
#define	__NR_swapon	85
#define	__NR_getitimer	86
#define	__NR_getdtablesize	89
#define	__NR_dup2	90
#define	__NR_fcntl	92
#define	__NR_select	93
#define	__NR_fsync	95
#define	__NR_setpriority	96
#define	__NR_socket	97
#define	__NR_connect	98
#define	__NR_getpriority	100
#define	__NR_bind	104
#define	__NR_setsockopt	105
#define	__NR_listen	106
#define	__NR_gettimeofday	116
#define	__NR_getrusage	117
#define	__NR_getsockopt	118
#define	__NR_readv	120
#define	__NR_writev	121
#define	__NR_settimeofday	122
#define	__NR_fchown	123
#define	__NR_fchmod	124
#define	__NR_setreuid	126
#define	__NR_setregid	127
#define	__NR_rename	128
#define	__NR_flock	131
#define	__NR_mkfifo	132
#define	__NR_sendto	133
#define	__NR_shutdown	134
#define	__NR_socketpair	135
#define	__NR_mkdir	136
#define	__NR_rmdir	137
#define	__NR_utimes	138
#define	__NR_adjtime	140
#define	__NR_setsid	147
#define	__NR_quotactl	148
#define	__NR_nlm_syscall	154
#define	__NR_nfssvc	155
#define	__NR_freebsd4_statfs	157
#define	__NR_freebsd4_fstatfs	158
#define	__NR_lgetfh	160
#define	__NR_getfh	161
#define	__NR_freebsd4_getdomainname	162
#define	__NR_freebsd4_setdomainname	163
#define	__NR_freebsd4_uname	164
#define	__NR_sysarch	165
#define	__NR_rtprio	166
#define	__NR_semsys	169
#define	__NR_msgsys	170
#define	__NR_shmsys	171
#define	__NR_freebsd6_pread	173
#define	__NR_freebsd6_pwrite	174
#define	__NR_setfib	175
#define	__NR_ntp_adjtime	176
#define	__NR_setgid	181
#define	__NR_setegid	182
#define	__NR_seteuid	183
#define	__NR_stat	188
#define	__NR_fstat	189
#define	__NR_lstat	190
#define	__NR_pathconf	191
#define	__NR_fpathconf	192
#define	__NR_getrlimit	194
#define	__NR_setrlimit	195
#define	__NR_getdirentries	196
#define	__NR_freebsd6_mmap	197
#define	__NR___syscall	198
#define	__NR_freebsd6_lseek	199
#define	__NR_freebsd6_truncate	200
#define	__NR_freebsd6_ftruncate	201
#define	__NR___sysctl	202
#define	__NR_mlock	203
#define	__NR_munlock	204
#define	__NR_undelete	205
#define	__NR_futimes	206
#define	__NR_getpgid	207
#define	__NR_poll	209
#define	__NR_freebsd7___semctl	220
#define	__NR_semget	221
#define	__NR_semop	222
#define	__NR_freebsd7_msgctl	224
#define	__NR_msgget	225
#define	__NR_msgsnd	226
#define	__NR_msgrcv	227
#define	__NR_shmat	228
#define	__NR_freebsd7_shmctl	229
#define	__NR_shmdt	230
#define	__NR_shmget	231
#define	__NR_clock_gettime	232
#define	__NR_clock_settime	233
#define	__NR_clock_getres	234
#define	__NR_ktimer_create	235
#define	__NR_ktimer_delete	236
#define	__NR_ktimer_settime	237
#define	__NR_ktimer_gettime	238
#define	__NR_ktimer_getoverrun	239
#define	__NR_nanosleep	240
#define	__NR_ntp_gettime	248
#define	__NR_minherit	250
#define	__NR_rfork	251
#define	__NR_openbsd_poll	252
#define	__NR_issetugid	253
#define	__NR_lchown	254
#define	__NR_aio_read	255
#define	__NR_aio_write	256
#define	__NR_lio_listio	257
#define	__NR_getdents	272
#define	__NR_lchmod	274
#define	__NR_netbsd_lchown	275
#define	__NR_lutimes	276
#define	__NR_netbsd_msync	277
#define	__NR_nstat	278
#define	__NR_nfstat	279
#define	__NR_nlstat	280
#define	__NR_preadv	289
#define	__NR_pwritev	290
#define	__NR_freebsd4_fhstatfs	297
#define	__NR_fhopen	298
#define	__NR_fhstat	299
#define	__NR_modnext	300
#define	__NR_modstat	301
#define	__NR_modfnext	302
#define	__NR_modfind	303
#define	__NR_kldload	304
#define	__NR_kldunload	305
#define	__NR_kldfind	306
#define	__NR_kldnext	307
#define	__NR_kldstat	308
#define	__NR_kldfirstmod	309
#define	__NR_getsid	310
#define	__NR_setresuid	311
#define	__NR_setresgid	312
#define	__NR_aio_return	314
#define	__NR_aio_suspend	315
#define	__NR_aio_cancel	316
#define	__NR_aio_error	317
#define	__NR_oaio_read	318
#define	__NR_oaio_write	319
#define	__NR_olio_listio	320
#define	__NR_yield	321
#define	__NR_mlockall	324
#define	__NR_munlockall	325
#define	__NR___getcwd	326
#define	__NR_sched_setparam	327
#define	__NR_sched_getparam	328
#define	__NR_sched_setscheduler	329
#define	__NR_sched_getscheduler	330
#define	__NR_sched_yield	331
#define	__NR_sched_get_priority_max	332
#define	__NR_sched_get_priority_min	333
#define	__NR_sched_rr_get_interval	334
#define	__NR_utrace	335
#define	__NR_freebsd4_sendfile	336
#define	__NR_kldsym	337
#define	__NR_jail	338
#define	__NR_nnpfs_syscall	339
#define	__NR_sigprocmask	340
#define	__NR_sigsuspend	341
#define	__NR_freebsd4_sigaction	342
#define	__NR_sigpending	343
#define	__NR_freebsd4_sigreturn	344
#define	__NR_sigtimedwait	345
#define	__NR_sigwaitinfo	346
#define	__NR___acl_get_file	347
#define	__NR___acl_set_file	348
#define	__NR___acl_get_fd	349
#define	__NR___acl_set_fd	350
#define	__NR___acl_delete_file	351
#define	__NR___acl_delete_fd	352
#define	__NR___acl_aclcheck_file	353
#define	__NR___acl_aclcheck_fd	354
#define	__NR_extattrctl	355
#define	__NR_extattr_set_file	356
#define	__NR_extattr_get_file	357
#define	__NR_extattr_delete_file	358
#define	__NR_aio_waitcomplete	359
#define	__NR_getresuid	360
#define	__NR_getresgid	361
#define	__NR_kqueue	362
#define	__NR_kevent	363
#define	__NR_extattr_set_fd	371
#define	__NR_extattr_get_fd	372
#define	__NR_extattr_delete_fd	373
#define	__NR___setugid	374
#define	__NR_eaccess	376
#define	__NR_afs3_syscall	377
#define	__NR_nmount	378
#define	__NR___mac_get_proc	384
#define	__NR___mac_set_proc	385
#define	__NR___mac_get_fd	386
#define	__NR___mac_get_file	387
#define	__NR___mac_set_fd	388
#define	__NR___mac_set_file	389
#define	__NR_kenv	390
#define	__NR_lchflags	391
#define	__NR_uuidgen	392
#define	__NR_sendfile	393
#define	__NR_mac_syscall	394
#define	__NR_getfsstat	395
#define	__NR_statfs	396
#define	__NR_fstatfs	397
#define	__NR_fhstatfs	398
#define	__NR_ksem_close	400
#define	__NR_ksem_post	401
#define	__NR_ksem_wait	402
#define	__NR_ksem_trywait	403
#define	__NR_ksem_init	404
#define	__NR_ksem_open	405
#define	__NR_ksem_unlink	406
#define	__NR_ksem_getvalue	407
#define	__NR_ksem_destroy	408
#define	__NR___mac_get_pid	409
#define	__NR___mac_get_link	410
#define	__NR___mac_set_link	411
#define	__NR_extattr_set_link	412
#define	__NR_extattr_get_link	413
#define	__NR_extattr_delete_link	414
#define	__NR___mac_execve	415
#define	__NR_sigaction	416
#define	__NR_sigreturn	417
#define	__NR_getcontext	421
#define	__NR_setcontext	422
#define	__NR_swapcontext	423
#define	__NR_swapoff	424
#define	__NR___acl_get_link	425
#define	__NR___acl_set_link	426
#define	__NR___acl_delete_link	427
#define	__NR___acl_aclcheck_link	428
#define	__NR_sigwait	429
#define	__NR_thr_create	430
#define	__NR_thr_exit	431
#define	__NR_thr_self	432
#define	__NR_thr_kill	433
#define	__NR__umtx_lock	434
#define	__NR__umtx_unlock	435
#define	__NR_jail_attach	436
#define	__NR_extattr_list_fd	437
#define	__NR_extattr_list_file	438
#define	__NR_extattr_list_link	439
#define	__NR_ksem_timedwait	441
#define	__NR_thr_suspend	442
#define	__NR_thr_wake	443
#define	__NR_kldunloadf	444
#define	__NR_audit	445
#define	__NR_auditon	446
#define	__NR_getauid	447
#define	__NR_setauid	448
#define	__NR_getaudit	449
#define	__NR_setaudit	450
#define	__NR_getaudit_addr	451
#define	__NR_setaudit_addr	452
#define	__NR_auditctl	453
#define	__NR__umtx_op	454
#define	__NR_thr_new	455
#define	__NR_sigqueue	456
#define	__NR_kmq_open	457
#define	__NR_kmq_setattr	458
#define	__NR_kmq_timedreceive	459
#define	__NR_kmq_timedsend	460
#define	__NR_kmq_notify	461
#define	__NR_kmq_unlink	462
#define	__NR_abort2	463
#define	__NR_thr_set_name	464
#define	__NR_aio_fsync	465
#define	__NR_rtprio_thread	466
#define	__NR_sctp_peeloff	471
#define	__NR_sctp_generic_sendmsg	472
#define	__NR_sctp_generic_sendmsg_iov	473
#define	__NR_sctp_generic_recvmsg	474
#define	__NR_pread	475
#define	__NR_pwrite	476
#define	__NR_mmap	477
#define	__NR_lseek	478
#define	__NR_truncate	479
#define	__NR_ftruncate	480
#define	__NR_thr_kill2	481
#define	__NR_shm_open	482
#define	__NR_shm_unlink	483
#define	__NR_cpuset	484
#define	__NR_cpuset_setid	485
#define	__NR_cpuset_getid	486
#define	__NR_cpuset_getaffinity	487
#define	__NR_cpuset_setaffinity	488
#define	__NR_faccessat	489
#define	__NR_fchmodat	490
#define	__NR_fchownat	491
#define	__NR_fexecve	492
#define	__NR_fstatat	493
#define	__NR_futimesat	494
#define	__NR_linkat	495
#define	__NR_mkdirat	496
#define	__NR_mkfifoat	497
#define	__NR_mknodat	498
#define	__NR_openat	499
#define	__NR_readlinkat	500
#define	__NR_renameat	501
#define	__NR_symlinkat	502
#define	__NR_unlinkat	503
#define	__NR_posix_openpt	504
#define	__NR_gssd_syscall	505
#define	__NR_jail_get	506
#define	__NR_jail_set	507
#define	__NR_jail_remove	508
#define	__NR_closefrom	509
#define	__NR___semctl	510
#define	__NR_msgctl	511
#define	__NR_shmctl	512
#define	__NR_lpathconf	513
#define	__NR_cap_new	514
#define	__NR_cap_getrights	515
#define	__NR_cap_enter	516
#define	__NR_cap_getmode	517
#define	__NR_pdfork	518
#define	__NR_pdkill	519
#define	__NR_pdgetpid	520
#define	__NR_pselect	522
#define	__NR_getloginclass	523
#define	__NR_setloginclass	524
#define	__NR_rctl_get_racct	525
#define	__NR_rctl_get_rules	526
#define	__NR_rctl_get_limits	527
#define	__NR_rctl_add_rule	528
#define	__NR_rctl_remove_rule	529
#define	__NR_posix_fallocate	530

// Aliases for linux -> BSD
#define __NR_rt_sigqueueinfo	__NR_sigqueue
#define __NR_rt_sigaction	__NR_sigaction
#define __NR_rt_sigpending	__NR_sigpending
#define __NR_rt_sigsuspend	__NR_sigsuspend
#define __NR_rt_sigprocmask	__NR_sigprocmask
#define __NR_rt_sigtimedwait 	__NR_sigtimedwait
#define __NR_set_tid_address	__NR_getpid
#define __NR_fallocate	__NR_posix_fallocate
#define __NR_brk	__NR_sbrk
#define __NR_mq_notify	__NR_kmq_notify
#define __NR_mq_open	__NR_kmq_open
#define __NR_mq_getsetattr	__NR_kmq_setattr
#define __NR_mq_timedreceive	__NR_kmq_timedreceive
#define __NR_mq_timedsend	__NR_kmq_timedsend
#define __NR_mq_unlink	__NR_kmq_unlink
#define __NR_gettid	__NR_getpid
#define __NR_tkill	__NR_thr_kill
#define __NR_timer_delete	__NR_ktimer_delete
#define __NR_timer_create	__NR_ktimer_create
#define __NR_timer_getoverrun	__NR_ktimer_getoverrun
#define __NR_timer_gettime	__NR_ktimer_gettime
#define __NR_timer_settime	__NR_ktimer_settime
#define __NR_times	__NR_lutimes
#define __NR_getcwd	__NR___getcwd
#define __NR_exit_group __NR_exit
#define	SYS_syscall	0
#define	SYS_exit	1
#define	SYS_fork	2
#define	SYS_read	3
#define	SYS_write	4
#define	SYS_open	5
#define	SYS_close	6
#define	SYS_wait4	7
#define	SYS_link	9
#define	SYS_unlink	10
#define	SYS_chdir	12
#define	SYS_fchdir	13
#define	SYS_mknod	14
#define	SYS_chmod	15
#define	SYS_chown	16
#define	SYS_break	17
#define	SYS_freebsd4_getfsstat	18
#define	SYS_getpid	20
#define	SYS_mount	21
#define	SYS_unmount	22
#define	SYS_setuid	23
#define	SYS_getuid	24
#define	SYS_geteuid	25
#define	SYS_ptrace	26
#define	SYS_recvmsg	27
#define	SYS_sendmsg	28
#define	SYS_recvfrom	29
#define	SYS_accept	30
#define	SYS_getpeername	31
#define	SYS_getsockname	32
#define	SYS_access	33
#define	SYS_chflags	34
#define	SYS_fchflags	35
#define	SYS_sync	36
#define	SYS_kill	37
#define	SYS_getppid	39
#define	SYS_dup	41
#define	SYS_pipe	42
#define	SYS_getegid	43
#define	SYS_profil	44
#define	SYS_ktrace	45
#define	SYS_getgid	47
#define	SYS_getlogin	49
#define	SYS_setlogin	50
#define	SYS_acct	51
#define	SYS_sigaltstack	53
#define	SYS_ioctl	54
#define	SYS_reboot	55
#define	SYS_revoke	56
#define	SYS_symlink	57
#define	SYS_readlink	58
#define	SYS_execve	59
#define	SYS_umask	60
#define	SYS_chroot	61
#define	SYS_msync	65
#define	SYS_vfork	66
#define	SYS_sbrk	69
#define	SYS_sstk	70
#define	SYS_vadvise	72
#define	SYS_munmap	73
#define	SYS_mprotect	74
#define	SYS_madvise	75
#define	SYS_mincore	78
#define	SYS_getgroups	79
#define	SYS_setgroups	80
#define	SYS_getpgrp	81
#define	SYS_setpgid	82
#define	SYS_setitimer	83
#define	SYS_swapon	85
#define	SYS_getitimer	86
#define	SYS_getdtablesize	89
#define	SYS_dup2	90
#define	SYS_fcntl	92
#define	SYS_select	93
#define	SYS_fsync	95
#define	SYS_setpriority	96
#define	SYS_socket	97
#define	SYS_connect	98
#define	SYS_getpriority	100
#define	SYS_bind	104
#define	SYS_setsockopt	105
#define	SYS_listen	106
#define	SYS_gettimeofday	116
#define	SYS_getrusage	117
#define	SYS_getsockopt	118
#define	SYS_readv	120
#define	SYS_writev	121
#define	SYS_settimeofday	122
#define	SYS_fchown	123
#define	SYS_fchmod	124
#define	SYS_setreuid	126
#define	SYS_setregid	127
#define	SYS_rename	128
#define	SYS_flock	131
#define	SYS_mkfifo	132
#define	SYS_sendto	133
#define	SYS_shutdown	134
#define	SYS_socketpair	135
#define	SYS_mkdir	136
#define	SYS_rmdir	137
#define	SYS_utimes	138
#define	SYS_adjtime	140
#define	SYS_setsid	147
#define	SYS_quotactl	148
#define	SYS_nlm_syscall	154
#define	SYS_nfssvc	155
#define	SYS_freebsd4_statfs	157
#define	SYS_freebsd4_fstatfs	158
#define	SYS_lgetfh	160
#define	SYS_getfh	161
#define	SYS_freebsd4_getdomainname	162
#define	SYS_freebsd4_setdomainname	163
#define	SYS_freebsd4_uname	164
#define	SYS_sysarch	165
#define	SYS_rtprio	166
#define	SYS_semsys	169
#define	SYS_msgsys	170
#define	SYS_shmsys	171
#define	SYS_freebsd6_pread	173
#define	SYS_freebsd6_pwrite	174
#define	SYS_setfib	175
#define	SYS_ntp_adjtime	176
#define	SYS_setgid	181
#define	SYS_setegid	182
#define	SYS_seteuid	183
#define	SYS_stat	188
#define	SYS_fstat	189
#define	SYS_lstat	190
#define	SYS_pathconf	191
#define	SYS_fpathconf	192
#define	SYS_getrlimit	194
#define	SYS_setrlimit	195
#define	SYS_getdirentries	196
#define	SYS_freebsd6_mmap	197
#define	SYS___syscall	198
#define	SYS_freebsd6_lseek	199
#define	SYS_freebsd6_truncate	200
#define	SYS_freebsd6_ftruncate	201
#define	SYS___sysctl	202
#define	SYS_mlock	203
#define	SYS_munlock	204
#define	SYS_undelete	205
#define	SYS_futimes	206
#define	SYS_getpgid	207
#define	SYS_poll	209
#define	SYS_freebsd7___semctl	220
#define	SYS_semget	221
#define	SYS_semop	222
#define	SYS_freebsd7_msgctl	224
#define	SYS_msgget	225
#define	SYS_msgsnd	226
#define	SYS_msgrcv	227
#define	SYS_shmat	228
#define	SYS_freebsd7_shmctl	229
#define	SYS_shmdt	230
#define	SYS_shmget	231
#define	SYS_clock_gettime	232
#define	SYS_clock_settime	233
#define	SYS_clock_getres	234
#define	SYS_ktimer_create	235
#define	SYS_ktimer_delete	236
#define	SYS_ktimer_settime	237
#define	SYS_ktimer_gettime	238
#define	SYS_ktimer_getoverrun	239
#define	SYS_nanosleep	240
#define	SYS_ntp_gettime	248
#define	SYS_minherit	250
#define	SYS_rfork	251
#define	SYS_openbsd_poll	252
#define	SYS_issetugid	253
#define	SYS_lchown	254
#define	SYS_aio_read	255
#define	SYS_aio_write	256
#define	SYS_lio_listio	257
#define	SYS_getdents	272
#define	SYS_lchmod	274
#define	SYS_netbsd_lchown	275
#define	SYS_lutimes	276
#define	SYS_netbsd_msync	277
#define	SYS_nstat	278
#define	SYS_nfstat	279
#define	SYS_nlstat	280
#define	SYS_preadv	289
#define	SYS_pwritev	290
#define	SYS_freebsd4_fhstatfs	297
#define	SYS_fhopen	298
#define	SYS_fhstat	299
#define	SYS_modnext	300
#define	SYS_modstat	301
#define	SYS_modfnext	302
#define	SYS_modfind	303
#define	SYS_kldload	304
#define	SYS_kldunload	305
#define	SYS_kldfind	306
#define	SYS_kldnext	307
#define	SYS_kldstat	308
#define	SYS_kldfirstmod	309
#define	SYS_getsid	310
#define	SYS_setresuid	311
#define	SYS_setresgid	312
#define	SYS_aio_return	314
#define	SYS_aio_suspend	315
#define	SYS_aio_cancel	316
#define	SYS_aio_error	317
#define	SYS_oaio_read	318
#define	SYS_oaio_write	319
#define	SYS_olio_listio	320
#define	SYS_yield	321
#define	SYS_mlockall	324
#define	SYS_munlockall	325
#define	SYS___getcwd	326
#define	SYS_sched_setparam	327
#define	SYS_sched_getparam	328
#define	SYS_sched_setscheduler	329
#define	SYS_sched_getscheduler	330
#define	SYS_sched_yield	331
#define	SYS_sched_get_priority_max	332
#define	SYS_sched_get_priority_min	333
#define	SYS_sched_rr_get_interval	334
#define	SYS_utrace	335
#define	SYS_freebsd4_sendfile	336
#define	SYS_kldsym	337
#define	SYS_jail	338
#define	SYS_nnpfs_syscall	339
#define	SYS_sigprocmask	340
#define	SYS_sigsuspend	341
#define	SYS_freebsd4_sigaction	342
#define	SYS_sigpending	343
#define	SYS_freebsd4_sigreturn	344
#define	SYS_sigtimedwait	345
#define	SYS_sigwaitinfo	346
#define	SYS___acl_get_file	347
#define	SYS___acl_set_file	348
#define	SYS___acl_get_fd	349
#define	SYS___acl_set_fd	350
#define	SYS___acl_delete_file	351
#define	SYS___acl_delete_fd	352
#define	SYS___acl_aclcheck_file	353
#define	SYS___acl_aclcheck_fd	354
#define	SYS_extattrctl	355
#define	SYS_extattr_set_file	356
#define	SYS_extattr_get_file	357
#define	SYS_extattr_delete_file	358
#define	SYS_aio_waitcomplete	359
#define	SYS_getresuid	360
#define	SYS_getresgid	361
#define	SYS_kqueue	362
#define	SYS_kevent	363
#define	SYS_extattr_set_fd	371
#define	SYS_extattr_get_fd	372
#define	SYS_extattr_delete_fd	373
#define	SYS___setugid	374
#define	SYS_eaccess	376
#define	SYS_afs3_syscall	377
#define	SYS_nmount	378
#define	SYS___mac_get_proc	384
#define	SYS___mac_set_proc	385
#define	SYS___mac_get_fd	386
#define	SYS___mac_get_file	387
#define	SYS___mac_set_fd	388
#define	SYS___mac_set_file	389
#define	SYS_kenv	390
#define	SYS_lchflags	391
#define	SYS_uuidgen	392
#define	SYS_sendfile	393
#define	SYS_mac_syscall	394
#define	SYS_getfsstat	395
#define	SYS_statfs	396
#define	SYS_fstatfs	397
#define	SYS_fhstatfs	398
#define	SYS_ksem_close	400
#define	SYS_ksem_post	401
#define	SYS_ksem_wait	402
#define	SYS_ksem_trywait	403
#define	SYS_ksem_init	404
#define	SYS_ksem_open	405
#define	SYS_ksem_unlink	406
#define	SYS_ksem_getvalue	407
#define	SYS_ksem_destroy	408
#define	SYS___mac_get_pid	409
#define	SYS___mac_get_link	410
#define	SYS___mac_set_link	411
#define	SYS_extattr_set_link	412
#define	SYS_extattr_get_link	413
#define	SYS_extattr_delete_link	414
#define	SYS___mac_execve	415
#define	SYS_sigaction	416
#define	SYS_sigreturn	417
#define	SYS_getcontext	421
#define	SYS_setcontext	422
#define	SYS_swapcontext	423
#define	SYS_swapoff	424
#define	SYS___acl_get_link	425
#define	SYS___acl_set_link	426
#define	SYS___acl_delete_link	427
#define	SYS___acl_aclcheck_link	428
#define	SYS_sigwait	429
#define	SYS_thr_create	430
#define	SYS_thr_exit	431
#define	SYS_thr_self	432
#define	SYS_thr_kill	433
#define	SYS__umtx_lock	434
#define	SYS__umtx_unlock	435
#define	SYS_jail_attach	436
#define	SYS_extattr_list_fd	437
#define	SYS_extattr_list_file	438
#define	SYS_extattr_list_link	439
#define	SYS_ksem_timedwait	441
#define	SYS_thr_suspend	442
#define	SYS_thr_wake	443
#define	SYS_kldunloadf	444
#define	SYS_audit	445
#define	SYS_auditon	446
#define	SYS_getauid	447
#define	SYS_setauid	448
#define	SYS_getaudit	449
#define	SYS_setaudit	450
#define	SYS_getaudit_addr	451
#define	SYS_setaudit_addr	452
#define	SYS_auditctl	453
#define	SYS__umtx_op	454
#define	SYS_thr_new	455
#define	SYS_sigqueue	456
#define	SYS_kmq_open	457
#define	SYS_kmq_setattr	458
#define	SYS_kmq_timedreceive	459
#define	SYS_kmq_timedsend	460
#define	SYS_kmq_notify	461
#define	SYS_kmq_unlink	462
#define	SYS_abort2	463
#define	SYS_thr_set_name	464
#define	SYS_aio_fsync	465
#define	SYS_rtprio_thread	466
#define	SYS_sctp_peeloff	471
#define	SYS_sctp_generic_sendmsg	472
#define	SYS_sctp_generic_sendmsg_iov	473
#define	SYS_sctp_generic_recvmsg	474
#define	SYS_pread	475
#define	SYS_pwrite	476
#define	SYS_mmap	477
#define	SYS_lseek	478
#define	SYS_truncate	479
#define	SYS_ftruncate	480
#define	SYS_thr_kill2	481
#define	SYS_shm_open	482
#define	SYS_shm_unlink	483
#define	SYS_cpuset	484
#define	SYS_cpuset_setid	485
#define	SYS_cpuset_getid	486
#define	SYS_cpuset_getaffinity	487
#define	SYS_cpuset_setaffinity	488
#define	SYS_faccessat	489
#define	SYS_fchmodat	490
#define	SYS_fchownat	491
#define	SYS_fexecve	492
#define	SYS_fstatat	493
#define	SYS_futimesat	494
#define	SYS_linkat	495
#define	SYS_mkdirat	496
#define	SYS_mkfifoat	497
#define	SYS_mknodat	498
#define	SYS_openat	499
#define	SYS_readlinkat	500
#define	SYS_renameat	501
#define	SYS_symlinkat	502
#define	SYS_unlinkat	503
#define	SYS_posix_openpt	504
#define	SYS_gssd_syscall	505
#define	SYS_jail_get	506
#define	SYS_jail_set	507
#define	SYS_jail_remove	508
#define	SYS_closefrom	509
#define	SYS___semctl	510
#define	SYS_msgctl	511
#define	SYS_shmctl	512
#define	SYS_lpathconf	513
#define	SYS_cap_new	514
#define	SYS_cap_getrights	515
#define	SYS_cap_enter	516
#define	SYS_cap_getmode	517
#define	SYS_pdfork	518
#define	SYS_pdkill	519
#define	SYS_pdgetpid	520
#define	SYS_pselect	522
#define	SYS_getloginclass	523
#define	SYS_setloginclass	524
#define	SYS_rctl_get_racct	525
#define	SYS_rctl_get_rules	526
#define	SYS_rctl_get_limits	527
#define	SYS_rctl_add_rule	528
#define	SYS_rctl_remove_rule	529
#define	SYS_posix_fallocate	530
#define SYS_rt_sigqueueinfo	__NR_sigqueue
#define SYS_rt_sigaction	__NR_sigaction
#define SYS_rt_sigpending	__NR_sigpending
#define SYS_rt_sigsuspend	__NR_sigsuspend
#define SYS_rt_sigprocmask	__NR_sigprocmask
#define SYS_rt_sigtimedwait 	__NR_sigtimedwait
#define SYS_set_tid_address	__NR_getpid
#define SYS_fallocate	__NR_posix_fallocate
#define SYS_brk	__NR_sbrk
#define SYS_mq_notify	__NR_kmq_notify
#define SYS_mq_open	__NR_kmq_open
#define SYS_mq_getsetattr	__NR_kmq_setattr
#define SYS_mq_timedreceive	__NR_kmq_timedreceive
#define SYS_mq_timedsend	__NR_kmq_timedsend
#define SYS_mq_unlink	__NR_kmq_unlink
#define SYS_gettid	__NR_getpid
#define SYS_tkill	__NR_thr_kill
#define SYS_timer_delete	__NR_ktimer_delete
#define SYS_timer_create	__NR_ktimer_create
#define SYS_timer_getoverrun	__NR_ktimer_getoverrun
#define SYS_timer_gettime	__NR_ktimer_gettime
#define SYS_timer_settime	__NR_ktimer_settime
#define SYS_times	__NR_lutimes
#define SYS_getcwd	__NR___getcwd
#define SYS_exit_group __NR_exit
